alphagov/content-publisher

bin/setup, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/backtrace_silencers.rb, config/initializers/content_security_policy.rb, config/initializers/inflections.rb, config/initializers/mime_types.rb, config/initializers/new_framework_defaults_5_2.rb, config/spring.rb, config/storage.yml
=> Make app more idempotent to rails app:update

Procfile, app.json
=> Add config for Heroku

app.json
=> Add missing env variable for Heroku

Jenkinsfile
The Brakeman gem detects security issues.
=> Run Brakeman on CI

README.md
=> Make a minimal README

Gemfile.lock, app.json, app/controllers/tmp_controller.rb, config/routes.rb, db/schema.rb, db/seeds.rb
We needed to add a controller using the ApplicatonController to check our Signon
integration is working.
=> Create TmpController to test Signon in integration

config/routes.rb
This should allow us to test Signon integration.
=> Put the temp controller at root /

config/database.yml
This approach is now preferred as it makes the origin of the url for the
test database clearer.
=> Use TEST_DATABASE_URL in db config

docs/adr/0003-initial-domain-modelling.md
Trello: https://trello.com/c/aMiw1bk2/28-start-to-build-up-information-for-domain-modelling
[View rendered version](https://github.com/alphagov/content-publisher/blob/9bfc33a1d22f00fcaa7fab4791a7f11fa99dfc3b/docs/adr/0003-initial-domain-modelling.md)
This could probably be 3 ADR's but I think it's all ok as one.
=> ADR 3: Initial Domain Modelling

spec/spec_helper.rb
https://trello.com/c/Vbwd7cye/68-allow-sending-news-to-publishing-api-m
=> Run specs in transactions to keep DB clean

app/formats/document_types.yml, app/services/document_publishing_service.rb, app/services/document_type_schema.rb
=> Replace hard-coded payload fields with config

app/views/documents/show.html.erb, spec/integration/edit_a_document_spec.rb
=> Add edit button on show page

app/formats/document_types.yml, app/services/document_publishing_service.rb, app/services/document_type_schema.rb
=> Fix news story document type

app/views/documents/edit.html.erb
Update the edit page layout to use a 2/3-1/3 layout.
As part of [Trello card](https://trello.com/c/egKyMGRP)
=> Update edit page layout to use a 2/3-1/3 layout

app/views/documents/edit.html.erb, app/views/documents/fields/_govspeak.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/documents/index.html.erb, app/views/documents/show.html.erb, spec/integration/edit_a_document_spec.rb, spec/integration/publish_a_document_api_down_spec.rb, spec/integration/publish_a_document_spec.rb
There are a couple of kinks to fix later: abuse of the label component
on the show page, as well as a few CSS issues with the fonts and
document text. Probably loads of other stuff I'm not considering too :-)
=> Beautify the pages quickly for the show/tell

app/views/documents/edit.html.erb, app/views/documents/fields/_govspeak.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/documents/index.html.erb, app/views/documents/show.html.erb, spec/integration/edit_a_document_spec.rb, spec/integration/publish_a_document_api_down_spec.rb, spec/integration/publish_a_document_spec.rb
Reverts alphagov/content-publisher#58
We should fix Brakeman failing before we use this.
=> Revert "Beautify the pages quickly for the show/tell"

spec/features/create_a_document_api_down_spec.rb, spec/features/create_a_document_elsewhere_spec.rb, spec/features/create_a_document_not_sure_spec.rb, spec/features/create_a_document_spec.rb, spec/features/edit_a_document_spec.rb, spec/features/publish_a_document_api_down_spec.rb, spec/features/publish_a_document_spec.rb, spec/features/publishing_validations_spec.rb, spec/features/show_a_document_spec.rb
Also change RSpec.describe to RSpec.feature to be consistent with the
then use of 'scenario' in the feature specs.
=> Move feature tests into a features folder

.gitignore, Jenkinsfile, README.md, app/assets/javascripts/documents/edit.js, lib/tasks/lint.rake, package-lock.json, package.json
Reverts alphagov/content-publisher#100
=> Revert "Revert "Lint Javascript with StandardJS""

app/assets/javascripts/application.js, app/assets/javascripts/components/markdown-editor.js, app/assets/javascripts/vendor/@github/markdown-toolbar-element/dist/index.umd.js, app/assets/javascripts/vendor/@webcomponents/webcomponentsjs/webcomponents-loader.js, app/assets/javascripts/vendor/nodelist-foreach-polyfill/index.js, package-lock.json, package.json, startup.sh
This PR
- vendors all npm JavaScript files to allow deployment and ignores them when linting
- reverts configuration changes to 6ecd117
=> Vendor npm assets

Jenkinsfile
(We're already doing this as part of the default Rake task locally.)
=> Make Jenkins perform rails-specific linting checks

Gemfile, Gemfile.lock, Jenkinsfile, Rakefile, lib/tasks/brakeman.rake
As per https://github.com/alphagov/govuk-jenkinslib/pull/19
=> Brakeman now runs automatically for Rails apps

app/assets/stylesheets/components/_contextual-guidance.scss, app/views/components/docs/contextual-guidance.yml
This PR:
- defines typography styles for the component instead of relying on the defaults
- defines a default example for the component
=> Update contextual guidance component

startup.sh
Seems to make sense that we have this since we have bundle install
=> Add yarn install to the startup.sh file

config/locales/en/documents/show.yml
https://trello.com/c/7XfrouK7/90-allow-content-designers-to-edit-the-application-microcopy-m
=> Update summary label to capitalisation

app/formats/document_types.yml
https://trello.com/c/7XfrouK7/90-allow-content-designers-to-edit-the-application-microcopy-m
=> Correction of missed contractions

app/formats/document_types.yml
https://trello.com/c/Gm1BOO1O/151-review-pages-with-updated-content-in-content-publisher-s
=> Update label for primary organisation

config/locales/en/document_associations/edit.yml
https://trello.com/c/Gm1BOO1O/151-review-pages-with-updated-content-in-content-publisher-s
=> Changing title of associations page to 'tags'

README.md
Preview URL: https://github.com/alphagov/content-publisher/blob/fix-postgresql-link/README.md
=> Fix postgresql link

README.md, spec/services/uploaded_image_service/image_normaliser_spec.rb
Also fixup one of the tests to indicate the code is normalising the
image orientation as part of getting the dimensions.
=> Reference ImageMagick in the README

config/environments/development.rb
This was changed accidentally.
=> Make sure we get error reports in development

app/assets/images/components/preview-mobile.svg, app/assets/stylesheets/components/_page_preview.scss, app/views/components/_page_preview.html.erb
This implements the mobile preview in the component.
https://trello.com/c/i2Fi5qNQ
=> Add mobile preview

spec/spec_helper.rb
This fixes an issue where we forget to seed a fresh test database.
=> Auto seed the test database

app/views/new_document/choose_document_type.html.erb, app/views/new_document/choose_supertype.html.erb
This was fixed in https://github.com/alphagov/content-publisher/pull/224.
=> Remove temporary bugfix for radio component

app/views/documents/show/_actions.html.erb
As designed in https://trello.com/c/i2Fi5qNQ.
=> Open preview link in a new window

app/views/components/_page_preview.html.erb, app/views/publish_document/published.html.erb, config/locales/en/global.yml, config/locales/en/publish_document/published.yml
See commits for details.
https://trello.com/c/hAfZNnxt
=> Use the copy to clipboard component

docs/adr/0004-editing-microcopy.md
https://trello.com/c/J55uTleS/242-adr-for-application-microcopy
Whitehall also has a concept of translations, so let's avoid this word.
=> Rename ADR to avoid confusion with Whitehall

app/controllers/documents_controller.rb, app/services/document_filter.rb, app/views/documents/index/_filters.html.erb, config/locales/en/documents/index.yml, spec/features/index_filtering_spec.rb, spec/services/document_filter_spec.rb, spec/spec_helper.rb
https://trello.com/c/GsK9GgOu/241-filter-index-page-by-organisation
=> Organisation filtering

app/views/document_lead_image/index.html.erb, config/locales/en/document_lead_image/index.yml
Use the file upload component
Update the content and add link ot guidance
[Trello card](https://trello.com/c/RCoMnQcK)
=> Use file upload component

app/views/documents/index/_filters.html.erb, spec/features/index_filtering_api_down_spec.rb
https://trello.com/c/GsK9GgOu/241-filter-index-page-by-organisation
=> Handle no Publishing API for organisation filters

app/assets/stylesheets/application.scss, app/assets/stylesheets/objects/_history.scss, app/views/documents/show/_history_tab.html.erb, spec/features/document_timeline_spec.rb, spec/features/edit_lead_image_spec.rb
As designed by @soniaturcotte, helped by @alex-ju.
https://trello.com/c/TVcThaKi
=> Implement styling for history

app/assets/javascripts/application.js, app/assets/javascripts/components/image_cropper.js, app/assets/javascripts/vendor/cropperjs/dist/cropper.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_image_cropper.scss, app/assets/stylesheets/vendor/cropperjs/dist/cropper.scss, app/controllers/document_lead_image_controller.rb, app/views/components/_image_cropper.html.erb, app/views/components/_image_meta.html.erb, app/views/components/docs/image_cropper.yml, app/views/document_lead_image/_image_list.html.erb, app/views/document_lead_image/crop.html.erb, config/locales/en/document_lead_image/crop.yml, config/locales/en/documents/history.yml, config/routes.rb, db/schema.rb, spec/features/edit_lead_image_crop_spec.rb, spec/features/editing_images/edit_lead_image_crop_spec.rb, spec/features/editing_images/upload_lead_image_publishing_api_down_spec.rb, spec/features/editing_images/upload_lead_image_spec.rb
This PR:
[Trello card](https://trello.com/c/3vS8DPkB)
[Trello card](https://trello.com/c/Yavdtg4i)
We ended up attaching the cropper instance to `window.onload` as `image.load` in unreliable because of caching.
When the uploaded image has an aspect ratio bigger than 3:2
When the uploaded image has an aspect ratio smaller than 3:2
=> Add cropper component

app/assets/stylesheets/components/_image_cropper.scss
This PR fixed the import of the vendored cropper scss
=> Fix vendored css import

app/views/documents/show/_delete_draft.html.erb
https://trello.com/c/QAEhhJdf/244-build-workflow-for-delete-draft-remove-and-retire-document-m
=> Color the 'Yes, delete draft' button red

app/services/linkables_service.rb, spec/services/linkables_service_spec.rb
https://trello.com/c/aAzgU7vc/185-tags-associations
=> Sort linkables alphabetically (case insensitive)

app/views/documents/edit/_change_notes.html.erb
https://trello.com/c/GWR4WwMR/165-document-create-page
=> Make change note labels bold

spec/features/editing_content/previews_a_url_when_editing_title_spec.rb, spec/formats/consultation_spec.rb, spec/formats/detailed_guide_spec.rb, spec/formats/news_story_spec.rb, spec/formats/not_sure_spec.rb, spec/formats/press_release_spec.rb
As per https://github.com/alphagov/content-publisher/pull/354.
But fix the accidental deletion for the one feature that has multiple
scenarios.
=> Remove even more repetitive scenario text

app/assets/stylesheets/utilities/_overwrites.scss, app/views/layouts/application.html.erb
Update footer to add support and feedback links
=> Update footer links

app/assets/stylesheets/components/_image_meta.scss, app/views/document_images/_image_list.html.erb
https://trello.com/c/8D48qG5D/280-minor-iterations-for-lead-image-workflow
=> Remove last image border and fix bottom padding

config/locales/en/documents/index.yml
=> Update label to match content summary

app/services/drafting_requirements.rb, spec/features/workflow/drafting_requirements_spec.rb
https://trello.com/c/sAXUVPxo/275-replace-trimming-document-contents-with-drafting-requirements
=> Check for blank titles (not just empty ones)

app/views/layouts/application.html.erb
=> Fix dataLayer value to be string

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_image-meta.scss, app/assets/stylesheets/objects/_pane.scss, app/views/components/_image_meta.html.erb, app/views/document_images/_image_list.html.erb, app/views/document_images/_lead_image.html.erb, app/views/document_images/index.html.erb, config/locales/en/document_images/index.yml, spec/features/editing_images/choose_lead_image_publishing_api_down_spec.rb, spec/features/editing_images/choose_lead_image_spec.rb, spec/features/editing_images/remove_lead_image_publishing_api_down_spec.rb, spec/features/editing_images/remove_lead_image_spec.rb, spec/features/editing_images/upload_lead_image_publishing_api_down_spec.rb
This PR updates the lead image with the changes resulted from user research analysis.
[Trello card](https://trello.com/c/Yu5DjMk3)
=> Update lead image

app/formats/document_types.yml
=> Update Summary hint text

config/locales/en/documents/edit.yml
Made it consistent with the summary page
=> Updated "Page address path" label

app/views/documents/show/_contents.html.erb, config/locales/en/documents/show.yml
https://trello.com/c/AiMKvMd2/424-update-naming-of-html-and-govspeak-fields-in-locale-and-config-files
(Referenced in the guidance linked on the card above.)
=> Remove base path from summary screen

app/assets/stylesheets/utilities/_overwrites.scss, app/views/documents/index.html.erb, app/views/documents/index/_results.html.erb, config/locales/en/documents/index.yml, spec/features/creating_documents/choose_format_spec.rb, spec/features/creating_documents/create_document_spec.rb, spec/features/finding/index_results_spec.rb, spec/features/workflow/show_with_creator_spec.rb, spec/formats/consultation_spec.rb, spec/formats/detailed_guide_spec.rb, spec/formats/news_story_spec.rb, spec/formats/not_sure_spec.rb, spec/formats/press_release_spec.rb
- Adds additional column for status
- make index page layout changes (filters now 1/4, results now 3/4)
- changes font size to 16 for table row text
https://trello.com/c/jok0QIR6/286-index-page-design
https://trello.com/c/cJmGlDh9/374-update-design-for-index-page-in-content-publisher
=> Index page design updated

app/assets/stylesheets/utilities/_overwrites.scss, app/views/layouts/_phase_banner_elements.html.erb, app/views/layouts/application.html.erb, config/locales/en/application.yml
Ticket: https://trello.com/c/6hvQZTVK/259-update-navigation-header
=> Update navigation header to include phase banner

config/locales/en/documents/edit.yml
Reverts alphagov/content-publisher#466
=> Revert "Updated "Page address path" label"

app/views/layouts/_phase_banner_elements.html.erb
=> Fix ugly links

app/formats/document_types.yml, spec/services/document_unpublishing_service_spec.rb
https://trello.com/c/vqd2BLa0/449-we-dont-publish-urls-the-same-as-whitehall-does
=> Use whitehall prefixes

app/formats/document_types.yml, app/formats/supertypes.yml
https://trello.com/c/ZBE2ikSq/489-in-the-create-new-doc-flow-transparency-and-statistics-statistics-users-are-redirected-to-case-study
=> Fix statistics redirect -> statistical data sets

app/views/publisher_information/how_to_use_publisher.govspeak.md
=> Corrections, added links, and various bits

app/helpers/application_helper.rb, app/views/document_contacts/search.html.erb, app/views/document_contacts/search_api_down.html.erb, app/views/document_images/crop.html.erb, app/views/document_images/edit.html.erb, app/views/document_images/index.html.erb, app/views/document_tags/edit.html.erb, app/views/document_tags/edit_api_down.html.erb, app/views/document_topics/edit.html.erb, app/views/document_topics/edit_api_down.html.erb, app/views/documents/debug.html.erb, app/views/documents/edit.html.erb, app/views/documents/show.html.erb, app/views/layouts/application.html.erb, app/views/new_document/choose_document_type.html.erb, app/views/new_document/choose_supertype.html.erb, app/views/new_document/guidance.html.erb, app/views/preview/show.html.erb, app/views/publish_document/confirmation.html.erb, app/views/publish_document/published.html.erb, app/views/remove_document/remove.html.erb, app/views/retire_document/retire.html.erb
Ticket: https://trello.com/c/JsrpqR3h/419-iterate-design-of-content-has-been-published-confirmation-screen
We need to display a back link button with custom text in a specific view.
=> Change back link

app/views/documents/index/_filters.html.erb, app/views/layouts/application.html.erb, config/locales/en/document_images/index.yml, spec/features/finding/index_filtering_spec.rb
A few content-related updates from @paola-roccuzzo.
https://trello.com/c/QEt5Nuye
=> Content fixes

docs/adr/0004-editing-microcopy.md, docs/adr/0005-avoiding-initialisation-flickers.md
Trello: https://trello.com/c/H1TqpkiC/491-strategy-for-avoiding-flickering-of-content-as-js-initialises
Rendered View 👉 https://github.com/alphagov/content-publisher/blob/js-enabled-adr/docs/adr/0005-avoiding-initialisation-flickers.md
=> ADR on Javascript initialisation flickering

app/assets/stylesheets/components/_miller-columns.scss
Hide the nested lists only if JavaScript is enabled.
Reposition the remove topics button as per design.
[Trello card](https://trello.com/c/qPhY7IHR)
=> Update miller columns

app/assets/stylesheets/components/_markdown-editor.scss, app/views/components/_markdown_editor.html.erb, app/views/documents/fields/_govspeak_input.html.erb
[Trello card](https://trello.com/c/05U8l7DF)
=> Move insert contact button within markdown toolbar

config/locales/en/document_images/index.yml
Updated double quotes to single quotes in the flashes
=> Double quotes to single quotes

app/formats/document_types.yml
=> Updated suggested limit for summary

app/views/components/docs/image_meta.yml
This PR updates the examples for image-meta component to reflect the current code.
=> Update examples for the image-meta component

spec/features/workflow/publish_requirements_publishing_api_down_spec.rb, spec/features/workflow/publish_requirements_spec.rb, spec/features/workflow/publish_without_review_spec.rb
* Use 'publish' instead of 'publishing' for consistency
* Avoid the term 'force publish' as it's not an app concept
=> A few minor tweaks left over from my image PRs

app/helpers/application_helper.rb, app/views/documents/edit/_change_notes.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/documents/show/_actions.html.erb, app/views/images/edit.html.erb, app/views/images/index.html.erb, app/views/new_document/guidance.html.erb, app/views/publisher_information/beta_capabilities.html.erb, app/views/publisher_information/how_to_use_publisher.html.erb, app/views/publisher_information/publisher_updates.html.erb, app/views/unpublish/remove.html.erb, app/views/unpublish/retire.html.erb
https://trello.com/c/SK813uOn/545-create-and-use-helper-for-rendering-govspeak-in-govspeak-component
=> Govspeak helper

app/models/concerns/initialize_with_hash.rb, app/services/document_type.rb, app/services/supertype.rb, spec/factories/document_type_factory.rb, spec/factories/field_factory.rb, spec/factories/tag_field_factory.rb, spec/features/editing_tags/edit_tags_publishing_api_down_spec.rb, spec/features/editing_tags/edit_tags_spec.rb, spec/features/editing_tags/show_tags_publishing_api_down_spec.rb
https://trello.com/c/qYHMcyDZ/550-revisit-our-approach-to-models
Another attempt to improve our format-related models and the way we use them in tests. I'm pretty happy with the overall result here: the models are more DRY and the factories consistent.
=> Revamp models

docs/adr/0007-minimal-model.md
https://trello.com/c/EabnADEo/685-adr-for-the-minimal-model
=> Add ADR to describe our minimal policy for models

spec/features/editing_content/insert_contact_spec.rb, spec/features/editing_tags/edit_tags_spec.rb, spec/features/editing_topics/edit_topics_conflict_spec.rb, spec/features/editing_topics/edit_topics_spec.rb, spec/features/editing_topics/save_topics_publishing_api_down_spec.rb, spec/features/editing_topics/show_topics_spec.rb, spec/features/finding/index_filtering_spec.rb, spec/formats/news_story_spec.rb, spec/formats/press_release_spec.rb, spec/models/document_topics_spec.rb, spec/services/contacts_service_spec.rb, spec/services/delete_draft_service_spec.rb, spec/services/govspeak_document_spec.rb, spec/services/linkables_service_spec.rb, spec/services/path_generator_service_spec.rb, spec/services/publishing_api_payload_spec.rb, spec/services/requirements/path_checker_spec.rb, spec/services/requirements/topic_checker_spec.rb, spec/spec_helper.rb, spec/support/topics_helper.rb
https://trello.com/c/5JMGsuBj/581-follow-up-work-from-versioning-review
=> Use new stub_ prefix for Publishing API helpers

app/controllers/editions_controller.rb, app/controllers/review_controller.rb, app/models/revision.rb, app/views/documents/show/_lead_image.html.erb, db/migrate/20190111104120_update_foreign_key_delete_behaviour.rb, spec/factories/document_factory.rb, spec/features/editing_images/choose_lead_image_spec.rb, spec/models/document_spec.rb, spec/models/edition_spec.rb, spec/models/revision_spec.rb, spec/services/delete_draft_service_spec.rb
This PR comprises a bunch of follow ups from review comments raised by @benthorner that could be resolved post merge. 
Most of these seemed small enough that they didn't warrant their own PR, hopefully none are divisive.
=> Miscellaneous post versioning changes

app/models/content_revision.rb, app/models/document.rb, app/models/edition.rb, app/models/image.rb, app/models/removal.rb, app/models/revision.rb, app/models/tags_revision.rb, app/models/withdrawal.rb, app/services/asset_cleanup_service.rb
This aims to make these a little better and clearer. Hopefully they add
some value.
=> Update model comments

docs/adr/000x-restricted-deletion.md
https://trello.com/c/5JMGsuBj/581-follow-up-work-from-versioning-review
=> Add ADR to describe our DB deletion policy

spec/features/editing_images/upload_lead_image_spec.rb
This enhances the upload_lead_image_spec to also check that files are
uploaded to Asset Manager.
This is to fill a gap that we didn't have feature tests that tested
whether assets made it to Asset Manager. This test was chosen as it was
the point images would be uploaded to Asset Manager for the first time.
=> Test Asset Manager receives lead image

spec/services/publish_service_spec.rb
This test didn't make much sense.
=> Fix missing words in test "it"

app/views/publisher_information/beta_capabilities.govspeak.md, app/views/publisher_information/how_to_use_publisher.govspeak.md
Updated to help beta users feature docs on dept homepages.
Relates to feedback: https://trello.com/c/Lbkxb8PV/47-not-sure-how-to-feature-content-on-org-homepage
=> Bh featured docs guidance

app/formats/document_types.yml, app/views/components/_image_cropper.html.erb
Update based on GOV.UK style guidance
=> Bh negative contractions

app/assets/stylesheets/components/_image-meta.scss
(By request from @soniaturcotte.)
=> Image action line spacing

spec/javascripts/components/modal-dialogue-spec.js
https://trello.com/c/HqVa7cnk/556-build-modal-component
That focus thing again...
=> Fix and extend modal tests to cover interface

app/assets/javascripts/components/modal-dialogue.js, app/views/components/docs/modal_dialogue.yml, spec/javascripts/components/modal-dialogue-spec.js
=> Remove redundant # in modal data-target

app/views/components/docs/contextual_guidance.yml
Update contextual-guidance component examples to put them in the current context and expose the `relative` attribute.
=> Update contextual_guidance examples

README.md
In case other members of the team find this useful as a reference.
=> Add rake jasmine tasks in docs

app/views/publisher_information/beta_capabilities.govspeak.md, app/views/publisher_information/how_to_use_publisher.govspeak.md
Corrections and improvements to guidance
=> Correction to guidance

app/views/publisher_information/publisher_updates.govspeak.md
https://trello.com/c/kblJ4Alf/702-feature-release-master-card
=> BH release note 21 march

app/controllers/documents_controller.rb
https://trello.com/c/kblJ4Alf/702-feature-release-master-card
=> Remove feature flag for auto-org redirect

app/views/publish_mailer/publish_email.text.erb
https://trello.com/c/CJSGxDmN/717-notify-editors-when-content-has-been-published
=> Add tracking attribute to publish email link

app/assets/javascripts/modules/inline-image-modal.js, app/assets/javascripts/modules/video-embed-modal.js
https://trello.com/c/4kQa7EZO/762-allow-users-embed-videos
=> Show images wide, video embed narrow

app/views/documents/show/_actions.html.erb
For https://trello.com/c/y1CtmFT9/763-link-from-our-app-to-content-data-page
=> Remove feature flag for Content Data link

docs/adr/0010-sending-email-notifications.md
This got missed at the merge stage
=> Add missing ADR number

app/views/documents/fields/_govspeak_input.html.erb, app/views/publisher_information/how_to_use_publisher.govspeak.md, app/views/publisher_information/publisher_updates.govspeak.md
For https://trello.com/c/3JX1Pc9f/770-embed-paste-html-to-govspeak-functionality
=> Remove feature flag from paste-html-to-govspeak

app/views/components/docs/contextual_guidance.yml, app/views/components/docs/image_cropper.yml, app/views/components/docs/image_meta.yml, app/views/components/docs/input_length_suggester.yml, app/views/components/docs/loading_spinner.yml, app/views/components/docs/markdown_editor.yml, app/views/components/docs/metadata.yml, app/views/components/docs/multi_section_viewer.yml, app/views/components/docs/page_preview.yml, app/views/components/docs/side_navigation.yml, app/views/components/docs/summary.yml, app/views/components/docs/toolbar_dropdown.yml, app/views/components/docs/url_preview.yml, app/views/components/docs/warning_summary.yml
A small PR to align the way to write acceptance criteria and add criteria where missing.
=> Align accessibility acceptance criteria

app/models/file_attachment.rb, app/models/file_attachment/asset.rb, app/models/file_attachment/file_revision.rb, app/models/file_attachment/metadata_revision.rb, app/models/file_attachment/revision.rb, app/models/revision.rb, db/migrate/20190415124810_create_file_attachment.rb, db/migrate/20190415125457_create_file_attachment_revisions.rb, db/migrate/20190415135406_add_attachment_file_metadata_revision.rb, db/migrate/20190415141144_add_file_attachment_file_revision.rb, db/migrate/20190415144101_add_revision_references_to_file_attachment_revision.rb, db/migrate/20190415144526_create_revisions_file_attachment_revisions.rb, db/migrate/20190416075600_create_file_attachment_asset.rb, db/migrate/20190417133100_add_size_to_file_attachment_file_revision.rb, db/schema.rb
For https://trello.com/c/3c6nomPo/782-mvp-of-inline-attachment-flow-add-and-insert
In this PR we create the various models needed to store File Attachments.  This is based strongly on the current modelling for Images.
=> Create File Attachment models

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_attachment-meta.scss, app/views/components/_attachment_meta.html.erb, app/views/components/docs/attachment_meta.yml
Add an ["attachment meta" component](https://content-publisher-revie-pr-968.herokuapp.com/component-guide/attachment_meta) in a similar fashion with the ["image meta" component](https://content-publisher-revie-pr-968.herokuapp.com/component-guide/image_meta)
[Trello card](https://trello.com/c/z1aiStcD)
=> Add attachment meta component

app/models/file_attachment/asset.rb, app/models/file_attachment/blob_revision.rb, app/models/file_attachment/revision.rb, app/models/image/asset.rb, app/models/image/blob_revision.rb, app/models/image/revision.rb, db/migrate/20190424145213_rename_file_revision_to_blob_revision.rb, db/schema.rb
https://trello.com/c/pd6fOgwf/800-follow-up-steps-on-minimal-workflow-for-inline-attachments
=> Rename 'file revision' to 'blob revision' in DB

app/services/delete_draft_service.rb, spec/services/delete_draft_service_spec.rb
Previously we used to modify the revision_synced flag of the previously
current edition if discarding its path reservations failed. This changes
the exception handling to preserve the state of the flag if discarding
a path fails, as this does not impact on the sync status of the edition.
=> Preserve revision synced when discarding paths

app/controllers/file_attachments_controller.rb, app/interactors/file_attachments/create_interactor.rb
https://trello.com/c/vf6xQW7w/739-prototype-controllers-with-interactors-pattern
=> Move create attachment code into interactor

app/views/layouts/application.html.erb
https://trello.com/c/NJajzaXL/925-tidy-up-our-gtm-config
https://github.com/alphagov/content-data-admin/blob/master/app/views/layouts/application.html.erb#L9
=> Rename GTM vars to be consistent with Content Data

app/assets/stylesheets/components/_markdown-editor.scss
[Preview on this page](https://content-publisher-revi-pr-1009.herokuapp.com/documents/438b352d-27a1-4adf-927e-d412077bf228:en/edit)
[Trello card](https://trello.com/c/ieu6TCxv/813-improve-visual-difference-between-edit-and-preview-tabs-on-the-edit-page)
=> Update preview style

config/locales/en/application.yml, config/locales/en/documents/index.yml, config/locales/en/documents/show.yml, config/locales/en/unpublish/withdraw.yml
I found one of these manually, and the rest with the help of the
i18n-tasks gem, which unfortunately isn't quite good enough to have on a
permanent basis yet.
=> Remove redundant locales

app/formats/document_types.yml, app/views/components/_image_cropper.html.erb, app/views/components/_markdown_guidance.html.erb, app/views/images/crop.html.erb, config/locales/en/documents/show.yml, config/locales/en/images/crop.yml, config/locales/en/images/edit.yml
Content updates based on last round of user research.
[Trello card](https://trello.com/c/DaLtJhyA)
=> Content updates

config/locales/en/file_attachments/preview_pending.yml
https://trello.com/c/TI9uPeMu/855-design-and-copy-review-of-attachments-flow
This change is based on a review of content for the attachments
workflow.
=> Update copy for preview pending page

app/controllers/file_attachments_controller.rb, app/interactors/file_attachments/update_interactor.rb
https://trello.com/c/WvCPILCl/817-provide-means-to-edit-replace-an-attachment
=> Don't show attachment update flash when unchanged

app/views/components/_markdown_editor.html.erb, app/views/file_attachments/_file_attachment.html.erb, app/views/file_attachments/edit.html.erb, app/views/file_attachments/index.html.erb
https://trello.com/c/1mY4fPN1/857-analytics-for-attachments
=> Add data-gtm attributes for attachments

app/views/components/_attachment_meta.html.erb, app/views/file_attachments/_file_attachment.html.erb, app/views/file_attachments/show.html.erb
https://trello.com/c/1mY4fPN1/857-analytics-for-attachments
=> Add remaining GTM tags for attachments

app/views/file_attachments/index.html.erb
https://trello.com/c/1mY4fPN1/857-analytics-for-attachments
=> Move attachment upload GTM attr to form

app/views/publisher_information/beta_capabilities.govspeak.md, app/views/publisher_information/how_to_use_publisher.govspeak.md, app/views/publisher_information/publisher_updates.govspeak.md
Guidance content updates to be released alongside the launch of the attachments features.
Date may need amending.
=> BH attachments comms

app/views/components/_markdown_editor.html.erb
https://trello.com/c/NwWjLtlX/724-user-can-embed-attachment-links-inline-attachment
=> Remove beta flag for inline attachments

app/views/documents/show/_actions.html.erb
https://trello.com/c/rGjDviSL/848-adapt-scheduling-implementation-for-iterated-workflow
=> Fix positioning of 'Delete draft' link after 2i

app/views/components/_page_preview.html.erb
=> Use different data-gtm values for tab list

app/services/requirements/schedule_datetime_checker.rb, spec/services/requirements/schedule_datetime_checker_spec.rb
This was having problems with times around the hour of 12 in both am and
pm. This was due to the previous code (which I wrote 😭) being a bit too
simplistic with time handling and handling every hour but 12. There are
now extra tests to catch this.
I've also added some extra tests to make clear some of the time
scenarios that should be rejected, these are mostly types of parsing
that are more complex than this time should accept but `Time.parse`
would.
@benthorner I imagine there is a crossover with this and what you've been working on so I guess we may need to co-ordinate somewhat.
=> Fix parsing of time

app/jobs/scheduled_publishing_job.rb, app/models/timeline_entry.rb, app/services/scheduled_publishing_failed_service.rb, config/locales/en/documents/history.yml, spec/integration/failed_scheduled_publishing_spec.rb, spec/integration/successful_scheduled_publishing_spec.rb, spec/jobs/scheduled_publishing_job_spec.rb
Trello: https://trello.com/c/rBYaERp4/708-handle-scheduled-publishing-errors
These had got missed last time around
=> Missing scheduling timeline entries

app/views/documents/show/_requirements.html.erb
=> Add missing requiremnts tracking on summary page

app/views/publisher_information/publisher_updates.govspeak.md, app/views/topics/edit.html.erb
[Trello card](https://trello.com/c/RFcetKNF)
=> Add release note for topic search

app/views/documents/edit/_change_notes.html.erb
This one got missed out of the original radio buttons audit.
=> Add missing gtm-value for change note radios

app/views/components/_markdown_guidance.html.erb
This removes some redundant data-gtm attributes used for an old approach
for monitoring the use of individual pieces of guidance.
=> Remove redundant data-gtm attributes

app/views/documents/index/_filters.html.erb, app/views/documents/show/_actions.html.erb, app/views/publisher_information/beta_capabilities.govspeak.md, app/views/publisher_information/how_to_use_publisher.govspeak.md, app/views/publisher_information/publisher_updates.govspeak.md
Updates to guidance for Scheduling release.
=> BH scheduling release comms

docs/adr/0012-file-attachment-rendering.md, docs/adr/00xx-file-attachment-rendering.md
Trello: https://trello.com/c/R1Erlbpa/878-write-an-adr-about-how-we-render-attachments-with-govspeak
[View Rendered 👀](https://github.com/alphagov/content-publisher/blob/file-attachment-rendering-adr/docs/adr/00xx-file-attachment-rendering.md)
=> ADR for rendering file attachments

config/locales/en/requirements.yml
=> updated scheduling date warning

app/views/components/_markdown_editor.html.erb, app/views/components/_toolbar_dropdown.html.erb, app/views/layouts/application.html.erb
This fixes a couple of bugs with the recent analytics uplift PR: https://github.com/alphagov/content-publisher/pull/1194
=> Fix gtm bugs roundup

app/assets/javascripts/modules/gtm-copy-paste-listener.js, app/helpers/actions_helper.rb, app/views/components/_page_preview.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/documents/show/_submitted_for_review.html.erb, app/views/publish/published.html.erb, spec/javascripts/modules/gtm-copy-paste-listener-spec.js
A few tweaks here in a final tidy-up bid. Please see the commits for more details.
=> Analytics tweaks for docs

app/views/components/docs/side_navigation.yml, app/views/layouts/application.html.erb, app/views/publisher_information/_publication_info_nav.html.erb, config/locales/en/application.yml, spec/features/publisher_information/visit_publisher_information_pages_spec.rb
=> Update wrong apostrophe

app/views/layouts/application.html.erb
This was seen by the IE developer tools
=> Fix incorrect HTML meta element

package.json, yarn.lock
https://github.com/alphagov/miller-columns-element/blob/master/CHANGELOG.md#011
[Trello card](https://trello.com/c/xZ476iSf)
=> Update miller-columns-element to 0.1.1

config/locales/en/publisher_information/publisher_updates.yml
Sorry, I missed one in the original pull request
=> Update straight to curly apostrophe

app/views/images/edit.html.erb, app/views/topics/edit.html.erb, package.json, yarn.lock
https://trello.com/c/tAXP6pf1/948-analytics-for-topics
This adds standard data-gtm and data-gtm-value attributes for all
checkboxes, pending an update to miller-columns to forward all click
events from the containing divs, which currently intercept them.
=> Add tracking attributes for checkboxes

app/controllers/new_document_controller.rb, app/interactors/new_document/choose_supertype_interactor.rb, app/interactors/new_document/create_interactor.rb, app/views/new_document/choose_supertype.html.erb
This got missed during the original refactoring.
=> Move new document actions into interactors

app/controllers/publish_controller.rb, app/interactors/publish/confirmation_interactor.rb
This action was getting a bit too complex and merits an interactor.
=> Add interactor for publish#confirmation

app/views/backdate/edit.html.erb, app/views/documents/edit.html.erb, app/views/documents/edit/_change_notes.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/images/edit.html.erb, app/views/tags/edit.html.erb, app/views/withdraw/new.html.erb
This removes a few bits of redundant HTML. See the commits for more info...
=> Fix row column inconsistency

app/views/documents/edit.html.erb, app/views/documents/edit/_change_notes.html.erb, app/views/documents/fields/_govspeak_input.html.erb, app/views/images/edit.html.erb, app/views/tags/edit.html.erb
This reverts commit 82405a760da05d70efa318856c3deabb089d5c58.
=> Revert "Remove redundant id attributes"

app/services/requirements/tag_checker.rb, spec/factories/revision_factory.rb, spec/features/scheduling/schedule_review_status_not_selected.rb, spec/services/requirements/tag_checker_spec.rb
This fixes a few small things I spotted while doing https://github.com/alphagov/content-publisher/pull/1286. Please see the commits for more details.
=> Fix small things

config/locales/en/contacts/index.yml
Update copy for contacts page as per [trello comment](https://trello.com/c/8NN6jQiI/1025-modal-experience-for-contacts-new-design#comment-5d3ae50aab4e0236dfb2a7f3).
=> Update copy for contacts page

db/scrub_access_limited.sql
Trello: https://trello.com/c/X8hmEQKk/990-data-syncing-access-limited-content-to-integration
All the sadness for another fail...
=> Add missing semi colon to access limited SQL

package.json, yarn.lock
Use the component from a fork of the accessible-autocomplete component which will allow us to raise PRs and review further changes/updates.
[Trello card](https://trello.com/c/1yWVlb42)
=> Use autocomplete from fork

app/controllers/video_embed_controller.rb, app/interactors/video_embed/create_interactor.rb
https://trello.com/c/8NN6jQiI/1025-modal-experience-for-contacts
This one escaped the interactor campaign somehow...
=> Use interactor for creating a video embed snippet

app/views/documents/show/_content_settings.html.erb, app/views/publisher_information/beta_capabilities.govspeak.md, app/views/publisher_information/how_to_use_publisher.govspeak.md, app/views/publisher_information/publisher_updates.govspeak.md, spec/features/editing_content_settings/enforce_access_limit_spec.rb, spec/features/editing_content_settings/remove_access_limit_spec.rb
Review for clear language and check dates please.
Hold till feature released
=> Access limiting release notes

config/application.rb
Note this only applies in dev.
=> Ensure lib classes are reloaded when they change

app/controllers/contact_embed_controller.rb, app/interactors/contact_embed/create_interactor.rb, app/views/contact_embed/new.html.erb, config/locales/en/requirements.yml, spec/features/editing_content/insert_contact_embed_requirements_spec.rb
https://trello.com/c/8NN6jQiI/1025-modal-experience-for-contacts
=> Add requirements check for contact selection

app/helpers/edition_url_helper.rb, app/helpers/file_attachment_helper.rb, app/services/preview_asset_service/payload.rb, app/services/publishing_api_payload.rb, lib/preview_auth_bypass.rb, spec/helpers/edition_url_helper_spec.rb, spec/lib/preview_auth_bypass_spec.rb, spec/services/preview_asset_service/payload_spec.rb, spec/services/publishing_api_payload_spec.rb
=> Move PreviewAuthBypass (non-service) to 'lib/'

app/views/images/_image.html.erb
This is part of the new images workflow design.
https://trello.com/c/TL1An3FR/1077-iterate-crop-edit-workflow-for-lead-and-inline-images
=> Move delete link to the last link

app/interactors/images/update_crop_interactor.rb, app/interactors/images/update_interactor.rb, lib/versioning/revision_updater/image.rb, spec/features/editing_images/edit_image_spec.rb, spec/lib/versioning/revision_updater/image_spec.rb
See commits for further information.
=> Fix lead image bug

app/views/publisher_information/beta_capabilities.govspeak.md
I'm having a bad day for these
=> Fix another updated date

docs/history-mode.md
Trello: https://trello.com/c/HNIipHfC
What's changed and why?
Documents what history mode is and the rules that determine if a document is in history mode.
Source document:
https://docs.google.com/document/d/1B2n4DU5YcpxC1a8bsuty1q9lLAroqjBapBOKrhHFAWo/edit#
[Rendered version](https://github.com/alphagov/content-publisher/blob/cdcc03230632b4306b8accba7fbdc5d4620e6c0c/docs/history-mode.md)
=> History mode documentation

app/controllers/political_controller.rb, app/views/documents/index/_filters.html.erb, app/views/documents/show/_content_settings.html.erb, app/views/documents/show/_summary_tab.html.erb
Trello: https://trello.com/c/LHR7GodT
=> Remove feature flag for history mode

package.json, yarn.lock
This includes improvements on the remove action for screen readers.
[Trello card](https://trello.com/c/RbhZMiEB)
=> Update miller-columns-element to 1.2.1

docs/adr/0015-bulk-data-loading.md
Trello: https://trello.com/c/TQ6GPOHU/1228-spike-into-loading-governments-from-publishing-api
[Rendered version](https://github.com/alphagov/content-publisher/blob/bulk-data-adr/docs/adr/00XX-bulk-data-loading.md)
=> Add ADR for bulk data loading

app/helpers/actions_helper.rb, app/views/access_limit/edit.html.erb, app/views/backdate/edit.html.erb, app/views/documents/show/_requirements.html.erb, app/views/file_attachments/_file_attachment.html.erb, app/views/file_attachments/edit.html.erb, app/views/file_attachments/index.html.erb, app/views/history_mode/edit.html.erb, app/views/images/edit.html.erb, app/views/images/index.html.erb, app/views/schedule/edit.html.erb, app/views/schedule/new.html.erb, app/views/tags/edit.html.erb, app/views/topics/edit.html.erb, config/routes.rb, spec/requests/history_mode_spec.rb
This brings consistency to a number of areas of the config/routes.rb file that had become inconsistent. See commits for details of each change.
=> More consistency in application routes

spec/lib/bulk_data/government_repository_spec.rb
Talking through this file with Ben there was a few things he wanted more consistent with the testing strategy: https://github.com/alphagov/content-publisher/pull/1590
=> Small amends to Bulk Data tests

docs/testing-strategy.md
https://trello.com/c/wgkfOJsE/1283-improve-consistency-in-content-publisher-tests
We've struggled over time with a consistent approach to testing with
different understandings of our approaches. This document serves as an
attempt to put down our current thinkings. It's unlikely to be fully
exhaustive and I'm hoping it will be amended and improved over time.
I intend to follow this with a bunch of changes to our tests to increase
consistency.
[View rendered](https://github.com/alphagov/content-publisher/blob/test-strategy/docs/testing-strategy.md)
=> Write up testing strategy

app/services/resync_document_service.rb
https://trello.com/c/f1QaCH7x/231-our-services-directory-is-a-mess
This is consistent with all the other files in 'app/services'.
We are looking to DRY-up common properties of services as part
of the work to better define them.
=> Make attributes private for services

lib/whitehall_importer/create_revision.rb, spec/lib/whitehall_importer/create_revision_spec.rb
In some Whitehall documents, the image metadata (e.g. alt_text and caption) has changed between editions.  This affects 8 news articles from NDA.
An example is https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/export/document/404026 where the suffix "OBE" has been removed from the name in the caption and alt_text values.
We were only storing this data from the first edition, which led to the integrity check failing in cases where these values had been updated in a later edition (in the example above, we were proposing to publish the name with OBE, that had been removed in the second edition)
This change creates a new revision for an existing image where either the alt_text or caption has changed between editions.  The correct values for alt_text and caption …
=> Create new revision for images where metadata has changed

spec/features/editing_content/url_preview_spec.rb, spec/services/generate_base_path_service_spec.rb
=> Move edge case scenario into unit test

config/locales/en/documents/show.yml, spec/views/new_document/guidance.html.erb_spec.rb
https://trello.com/c/ihcpYeWf/1320-iterate-how-we-test-formats
=> Increase I18n coverage in a few places

app/controllers/application_controller.rb, app/controllers/contact_embed_controller.rb, app/controllers/file_attachments_controller.rb, app/controllers/images_controller.rb, spec/features/editing_content/insert_contact_embed_spec.rb, spec/features/editing_content/insert_inline_file_attachment_spec.rb, spec/features/editing_content/insert_inline_image_spec.rb, spec/features/editing_file_attachments/delete_file_attachment_spec.rb, spec/features/editing_images/delete_image_spec.rb
=> A few misc tweaks for JS features

app/interactors/images/update_interactor.rb, app/views/file_attachments/edit.html.erb, app/views/images/edit.html.erb, lib/requirements/image_revision_checker.rb, spec/lib/requirements/image_revision_checker_spec.rb
This is a continuation of https://github.com/alphagov/content-publisher/pull/1753.
=> Check for issues before updating images

app/views/content/edit/_change_notes.html.erb, spec/lib/requirements/backdate_checker_spec.rb, spec/lib/requirements/publish_time_checker_spec.rb, spec/lib/requirements/withdrawal_checker_spec.rb, spec/models/document_type/body_field_spec.rb, spec/models/document_type/summary_field_spec.rb, spec/models/document_type/title_and_base_path_field_spec.rb
=> Follow-up tweaks for #1753

config/document_types.yml, spec/support/schemas/document_type.json
This got missed somehow in https://github.com/alphagov/content-publisher/pull/1705
=> Remove 'check_path_conflict' attribute

config/locales/en/featured_attachments/index.yml
Trello: https://trello.com/c/gN1BuGKB
=> Update guidance on featured attachments index page

spec/lib/whitehall_importer/change_history_spec.rb
Adds a test that checks that only a subset of change_history is
returned. An example being for the fifth edition we only want the
fourth, third etc change_history but not the sixth or higher.
=> Add missing test to change_history_spec

lib/whitehall_importer/integrity_checker.rb
This is to remove some confusion where we're dealing with non-scalar
objects such as Time objects when trying to perform a comparison with
what the Publishing API has against what Content Publisher has.
As part of this the hashes involved in this are now using strings as
keys rather than symbols, since that is the default for JSON.
=> Convert PublishingApiPayload to JSON when performing integrity checks

app/views/featured_attachments/_featured_attachment.html.erb
=> Switch order of the Download and Delete actions

app/views/file_attachments/new.html.erb
=> Make "Choose file" bold

db/migrate/20200313130700_rename_official_document.rb
https://trello.com/c/HRUXGp3K/1518-support-metadata-for-featured-file-attachments-db-modelling
=> Add missing migration file from ca45f25

app/views/components/_reorderable_list.html.erb, app/views/components/docs/reorderable_list.yml
https://trello.com/c/xEgx182V/1585-guidance-for-non-javascript-version-of-reordering-attachments
=> Rename 'Order index' to 'Position' in no-JS view

config/locales/en/document_type_selections.yml
Adding publication to flag to users they'll need to include an attachment.
=> Rename transparency data

Rakefile
https://github.com/alphagov/content-publisher/pull/1928#discussion_r397977554
=> Explicitly run RSpec as part of default rake task

spec/factories/timeline_entry_factory.rb, spec/spec_helper.rb, spec/views/components/_attachment_meta.html.erb_spec.rb, spec/views/components/_page_preview.html.erb_spec.rb, spec/views/documents/history/_content_publisher_entry.html.erb_spec.rb, spec/views/documents/history/_whitehall_entry.html.erb_spec.rb, spec/views/documents/index/_filters.html.erb_spec.rb, spec/views/documents/index/_results.html.erb_spec.rb, spec/views/documents/show.html.erb_spec.rb, spec/views/featured_attachments/index.html.erb_spec.rb, spec/views/featured_attachments/reorder.html.erb_spec.rb, spec/views/file_attachments/replace.html.erb_spec.rb, spec/views/images/crop.html.erb_spec.rb, spec/views/new_document/guidance.html.erb_spec.rb, spec/views/new_document/show.html.erb_spec.rb, spec/views/tags/edit.html.erb_spec.rb
This is worth reviewing commit by commit as the overall diff looks a lot more dramatic than the actual changes made and there are full explanations of each change.
Mostly these changes continue the work and discussion from: https://github.com/alphagov/content-publisher/pull/1977
Happy to drop off the last commit if that is contentious.
=> Address a number of consistency issues in view specs

lib/date_parser.rb, lib/datetime_parser.rb, lib/image_normaliser.rb, lib/requirements/checker_issues.rb
Finishes: https://github.com/alphagov/content-publisher/pull/1734
=> Remove redundant '<<' method for CheckerIssues

spec/spec_helper.rb
As specified by the SimpleCov docs [1].
[1]: https://github.com/simplecov-ruby/simplecov#getting-started
=> Ensure we check coverage for all code in tests

app/controllers/healthcheck_controller.rb, config/routes.rb, lib/healthcheck/active_storage.rb, spec/lib/healthcheck/active_storage_spec.rb
This is a critical dependency, so it should be part of the readiness
healthcheck.
---
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)
=> Check ActiveStorage in /healthcheck/ready

app/views/components/docs/image_cropper.yml, app/views/components/docs/image_with_metadata.yml, app/views/new_document/guidance.govspeak.md
Trello card: https://trello.com/c/WbNNHNqB/764-update-publishing-apps-to-reflect-change-of-monarch
=> Change references from the Queen to the King

config/political_organisations.yml
This is part of preparation for the July 2024 general election.
This list was generated by using the below command in the Whitehall integration environment, as per the documentation at the top of the config file.
```ruby
puts Organisation.where(political: true).order(:name).map { |o| "- '#{o.content_id}' # #{o.name}" }.join("\n")
```
Trello: https://trello.com/c/q90F4zsa
=> Updated political organisation config
