app/assets/javascripts/modal/modal-workflow.js

This PR scopes overwrite actions to the modal content instead of the entire document.
We're currently doing this at the document level and every time we open a modal we create an exponential chain of events attached to the elements that initialise modals (which also rely on `data-modal-action` attributes, set to "open"). This is not only a waste of resources but it creates a series of `ModalWorkflow` instances that race in configuring and opening the modal, which results in a series of bugs captured by the card where the modal size config is not respected (a race of `this.$modal.resize('narrow')` in different instances) or the content of the modal changes without interacting with it (a race of `this.$modal.open()`).
Thinking to add a test to prevent this from happening again I realised we …

Scope overwrite actions to the modal content

---

app/assets/javascripts/components/markdown-editor.js

This PR initialises JavaScript components from both GOV.UK Modules and GOV.UK Frontend scoped to the preview container.
This is aligned with how we're currently initialising JavaScript from components in the [modal workflow](https://github.com/alphagov/content-publisher/blob/cfdd485cf5a8372b0839264acf6517551c98bc22/app/assets/javascripts/modal/modal-workflow.js#L12).
[Trello card](https://trello.com/c/tryqn3d2)

Fix JavaScript-dependent components in markdown preview

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Rather embarrassingly I accidentally committed a commented out line that disabled chromedriver logger in https://github.com/alphagov/content-publisher/commit/b85a3d52c9585f7c52b4037d15cf7227d3095047#diff-93830fa29d616f7c87903d08b5b1b29aR66 since that no longer works with newer versions of Chrome.
Since we've been on a fork of capybara-chromedriver-logger for a while now and it no longer works I think it makes sense to remove it. 
This also sets the javascript driver to be selenium_chrome_headless until govuk_test is fixed to work with newer versions of Chrome. I have a pr to raise for that.

Resolve test problems for Chrome 75.0.3770.90 and up

---

app/controllers/documents_controller.rb
app/controllers/tags_controller.rb
app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/tags/edit.html.erb
app/views/tags/tags/_multi_tag_input.html.erb
app/views/tags/tags/_single_tag_input.html.erb
config/locales/en/tags/edit.yml
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb
spec/features/editing_images/upload_image_spec.rb

Trello: https://trello.com/c/4Uc4JL4T/870-add-a-publishing-requirement-to-select-a-primary-organisation
This corrects these two forms where we weren't linking to and highlighting issues.
Before:
After:
Before:
After:

Link and highlight issues for edit and tag forms

---

app/services/requirements/backdate_checker.rb
app/views/backdate/edit.html.erb
config/locales/en/requirements.yml
spec/services/requirements/backdate_checker_spec.rb

For https://trello.com/c/aBHXR82t/932-user-can-backdate-or-set-document-as-new
This ensures that users can't backdate content to a date that is unreasonably
far in the past.

Enforce earliest date for backdating

---

app/assets/javascripts/modules/gtm-copy-paste-listener.js
app/views/components/_page_preview.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/publish/published.html.erb
spec/javascripts/modules/gtm-copy-paste-listener-spec.js

https://trello.com/c/tAXP6pf1/948-analytics-for-topics
Previously we had a single listener to emit custom copy/paste events to
GTM. In order to accommodate more listeners to support analytics for
topics, this modifies the copy/paste listener to emit a new 'dataGtm'
variable directly on the dataLayer, with the same meaning as the current
'data-gtm' attribute present on many elements, but formed dynamically
out of the event being tracked by the listener, and a 'data-gtm-suffix'
attribute coming from the element itself; in contrast, using 'data-gtm'
statically on an element generally implies it only supports one event.

Standardise copy/paste listener

---

spec/features/workflow/publish_spec.rb
spec/mailers/publish_mailer_spec.rb

As the ScheduledPublishMailer needs a mailer spec, we thought it would
be a good idea to include a PublishMailer spec. This also means we can
make the feature for publishing simpler by removing alternative publishing
scenarios which actually only tested the different variations of the
email (now covered by the tests in the publish_mailer_spec).
Trello:
https://trello.com/c/uC28c63Y/949-tie-up-scheduling-loose-ends

This adds a spec for the PublishMailer

---

app/assets/javascripts/components/autocomplete.js
app/helpers/time_options_helper.rb
app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/contacts/search.html.erb
app/views/schedule/_datetime.html.erb
app/views/tags/tags/_multi_tag_input.html.erb
app/views/tags/tags/_single_tag_input.html.erb
spec/features/scheduling/propose_publish_time_and_schedule_spec.rb
spec/features/scheduling/propose_publish_time_requirements_spec.rb
spec/features/scheduling/update_proposed_publish_time_spec.rb
spec/features/scheduling/update_publish_time_requirements_spec.rb
spec/features/scheduling/update_publish_time_spec.rb

Trello: https://trello.com/c/uC28c63Y/949-tie-up-scheduling-loose-ends
This refactors the autocomplete component to allow initialising based off on an input or a select element. See commits for further details.

Enhance input element rather than select for time input

---

app/views/documents/show/_actions.html.erb

https://trello.com/c/uC28c63Y/949-tie-up-scheduling-loose-ends
This should behave similarly to the lack of any 'Publish' action in this
scenario, with the slight downside that a user won't be able to propose
a schedule in this (hopefully unlikely) scenario.

Remove schedule action if preview not synced

---

app/helpers/application_helper.rb
app/views/components/_markdown_guidance.html.erb
app/views/documents/index/_filters.html.erb
app/views/documents/show/_proposed_scheduling_notice.html.erb
app/views/layouts/application.html.erb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
app/views/publish/confirmation.html.erb
app/views/schedule/edit.html.erb
app/views/schedule/new.html.erb
app/views/schedule_proposal/edit.html.erb

https://trello.com/c/fjVo0aK9/877-analytics-for-scheduling
This renames the 'gtm-action' attribute to 'gtm-value' so it makes more sense, irrespective of the weird way we're using it in GTM ;-).

Rename action to value

---

app/services/publishing_api_payload.rb
spec/services/publishing_api_payload_spec.rb

For https://trello.com/c/x6ImOUSP/918-create-a-form-so-user-can-save-the-backdate-for-their-content
We send `public_updated_at` to the Publishing API when a user backdates content. This only applies to the first edition as users currently can only backdate first editions.

Send public_updated_at to Publishing API

---

app/assets/stylesheets/objects/_side.scss
app/helpers/actions_helper.rb

Trello: https://trello.com/c/uC28c63Y/949-tie-up-scheduling-loose-ends
This removes a persistent margin-bottom from app-side__actions box,
which doesn't seem to have a particular use and makes the padding on
this box bottom heavy.
To consistently make the padding even we need to remove the margins from
buttons when they are the last item in the actions. This can be
complicated because the buttons could be embedded in forms, which makes
the usage of :last-child tricky.
There is also a margin removed on .govuk-link elements which isn't
needed since it only has an effect when this is floated.
@alex-ju this all got a bit hairier than I'd have liked. You'll have to let me know if
I've made any CSS sins.

More consistent app-side__action padding

---

app/views/documents/index/_filters.html.erb

Previously we dispatched visibility events for all filters on the index
page, but then applied a selector in GTM to only really trigger if the
'data-gtm-action' attribute was set. As we start to use this attribute
for other elements, it's become normal to fire visibility events without
an associated 'action' e.g. for guidance. This pushes the special case
behaviour for these four elements into the codebase, using a question
method to determine if each has a 'value' and thus if we want to track.

Only send filter events that have values

---

app/views/publish_mailer/publish_email.text.erb
app/views/scheduled_publish_mailer/failure_email.text.erb
app/views/scheduled_publish_mailer/success_email.text.erb

https://trello.com/c/fjVo0aK9/877-analytics-for-scheduling
Previously we only used the utm_content query param on the in-app links
we send out in emails, which is not sufficient for tracking the use of
these links in GA. This replaces utm_content with three params:
- utm_source: this is what we put in utm_content previously
- utm_medium: always 'email'
- utm_campaign: always 'govuk-publishing'
The last param is optional, but potentially useful to distinguish other
links to our app that populate the other two parameters, which would
pollute our analytics. Since the text of the link is now quite long,
this replaces the original text with a markdown link approach to
completely hide the query params, although they will still be shown in
the text variant of the email.

Fix tracking attributes on email links

---

app/jobs/scheduled_publishing_job.rb

Trello: https://trello.com/c/Bdccoiqd/735-notify-users-that-scheduled-content-has-failed-to-publish
The retry_on block will prevent exceptions working their way up the
stack. This means that errors are not reported to sentry by default.
This calls `GovukError.notify` to notify sentry for the reason the scheduling
failed. This will allow us to determine whether we need to fix code or handle
the exception. If the failure is due to an intermittent error (such as
timeout) this wouldn't make it to Sentry as they are filtered out in
govuk_test config.

Log the error a scheduled publishing fails on

---

app/views/documents/index/_filters.html.erb

This ensures we really don't set the 'data-gtm-visibility-tracking'
attribute when the value of the index filter is not present.

Fix tracking attribute for index filters

---

app/assets/stylesheets/components/_image-cropper.scss
app/assets/stylesheets/components/_inset-prompt.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/components/_markdown-guidance.scss
app/assets/stylesheets/components/_page-preview.scss
app/assets/stylesheets/components/_side-navigation.scss
app/assets/stylesheets/components/_summary.scss
app/assets/stylesheets/components/_toolbar-dropdown.scss
app/assets/stylesheets/core/_link.scss

A quick clean-up in our SCSS files. Prefixing app-level SCSS variables consistently - helps figuring out where that variable/mixin is defined (`govuk-` for govuk-frontend, `gem-` for govuk_publishing_components and `app-` for app-level code) and lint using [govuk_publishing_components sass-lint rules](https://github.com/alphagov/govuk_publishing_components/blob/master/.sass-lint.yml).

Prefix scss variables and lint

---

app/views/schedule/scheduled.html.erb

For https://trello.com/c/j7pcf6Nm/960-copy-review-for-scheduling
The same copy was appearing in the title and panel on the scheduled page, so we remove the title to
avoid duplication.

Remove duplicated copy on scheduled page

---

app/interactors/backdate/update_interactor.rb
spec/features/workflow/backdate_spec.rb

For https://trello.com/c/CnWIubp8/955-publishing-api-to-use-publicupdatedat-for-change-note-times
In order for the Publishing API to be made aware that content has been
backdated, we need to make a PutContent request.

Make PutContent request after backdating content

---

app/views/documents/show/_submitted_for_review.html.erb
app/views/publish/published.html.erb

Previously we just used the 'utm_content' attribute, which isn't
sufficient to support tracking in GA. This swaps out the old attribute
for a new set that's consistent with the way we do this for email links.

Fix 2i link tracking to use standard attributes

---

app/views/backdate/edit.html.erb
app/views/components/_markdown_editor.html.erb
app/views/components/_side_navigation.html.erb
app/views/components/docs/side_navigation.yml
app/views/documents/edit.html.erb
app/views/documents/index.html.erb
app/views/documents/index/_filters.html.erb
app/views/documents/index/_results.html.erb
app/views/documents/show.html.erb
app/views/documents/show/_delete_draft.html.erb
app/views/documents/show/_external_links.html.erb
app/views/documents/show/_history_tab.html.erb
app/views/documents/show/_lead_image.html.erb
app/views/documents/show/_withdrawn_notice.html.erb
app/views/file_attachments/show.html.erb
app/views/images/_image.html.erb
app/views/images/_lead_image.html.erb
app/views/images/crop.html.erb
app/views/images/edit.html.erb
app/views/layouts/_phase_banner_elements.html.erb
app/views/layouts/application.html.erb
app/views/publish/published.html.erb
app/views/publisher_information/_publication_info_nav.html.erb
app/views/tags/edit.html.erb
app/views/topics/edit.html.erb
app/views/unwithdraw/_confirm.html.erb
app/views/withdraw/new.html.erb

The aim of this PR is to uplift the app so that it (mostly) fulfils ours tracking strategy, which is to "track everything" and still needs to be documented thoroughly. However, all the tracking that is added in this PR has a precedent elsewhere in the app. It's possible there are still some bits missing, but this should cover the majority of "user actions".

The big one

---

app/views/documents/show/_lead_image.html.erb
config/locales/en/documents/show.yml

Previously we had code to render a link to upload an image directly from
the summary, which would act the same as clicking 'Change'. Now that the
'Change' link is renamed to 'Edit', we don't believe the additional link
is necessary. It's also been broken for ages. This removes it!

Remove broken/unwanted image upload link

---

README.md
app/assets/stylesheets/components/_markdown-guidance.scss
app/controllers/withdraw_controller.rb
app/views/withdraw/new.html.erb

This fixes a few issues with the withdraw feature:
- Requirements issues should not be persistent flashes
- The guidance should be confined to the central page
- The README should correctly say how to enable the feature

Fix withdraw guidance

---

app/controllers/backdate_controller.rb
app/interactors/backdate/destroy_interactor.rb
app/models/timeline_entry.rb
app/views/backdate/edit.html.erb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
config/routes.rb
spec/factories/edition_factory.rb
spec/features/workflow/clear_backdate_spec.rb

For https://trello.com/c/TBs5E8vv/919-clear-the-set-backdate-if-content-has-not-been-published
This allows users to clear a set backdate.  We also fix a bug where we used the edition's `backdate_to`
value instead of the `backdated_to` value associated with a revision, which caused nil errors and incorrect dates to appear in timeline entries.
> <img width="668" alt="backdate_1" src="https://user-images.githubusercontent.com/13434452/60183456-470d3700-981e-11e9-89a1-61b68437d13d.png">
> <img width="677" alt="backdate_2" src="https://user-images.githubusercontent.com/13434452/60183469-4c6a8180-981e-11e9-81bc-ec227162328c.png">
> <img width="663" alt="backdate_3" src="https://user-images.githubusercontent.com/13434452/60183488-53918f80-981e-11e9-891b-70d09cb5ad4c.png">
> <img width="490" …

Clear the set backdate if content has not been published

---

app/views/documents/show/_summary_tab.html.erb
app/views/publisher_information/beta_capabilities.govspeak.md
app/views/publisher_information/how_to_use_publisher.govspeak.md
app/views/publisher_information/publisher_updates.govspeak.md

For https://trello.com/c/MciuKE6C/970-release-backdating
updates to 
What's New
What Content Publisher Can and Cannot do
How to use Content Publisher
Date may need updating.

BH backdate release

---

app/interactors/schedule/new_interactor.rb

This is in response to the error we saw in sentry [1] where we saw an
error trying to run a greater than operator on a nil object. This
exception allows aborting this interactor when we are in the wrong
state.
This exception will still result in an error to the user but this is at
least something we don't need to debug which is the current case of the
nil comparison.
[1]: https://sentry.io/organizations/govuk/issues/1088840269/?project=202208&referrer=slack

Add exception for user accessing schedule/new in wrong state

---

app/models/access_limit.rb
app/models/edition.rb
app/services/publish_service.rb
db/migrate/20190626155821_create_access_limits.rb
db/schema.rb
spec/factories/access_limit_factory.rb
spec/factories/edition_factory.rb
spec/models/edition_spec.rb
spec/services/publish_service_spec.rb

Trello: https://trello.com/c/gdQrj56v/956-design-the-modelling-of-access-limiting
This creates a model for AccessLimit, sets up a method for assigning an access limit and removes an existing one at the point of publishing.
One thing I wrestled with a bit was the syntax for methods to add and remove access limits to an edition. I ended up going with a single method that can be used to add and remove:
```
edition.assign_access_limit(limit_type: :all_organisations, user: user) # to add
edition.assign_access_limit(limit_type: nil, user: user) # to remove
```
Another option could be `edition.remove_access_limit(user)` or `edition.assign_no_access_limit(user)`, I wasn't so keen on dropping the assign convention and felt `assign_no_access_limit` was a bit weird.

Initial model for Access Limit

---

README.md

This removes the somewhat redundant section about importing documents
from Whitehall, and makes the dev permissions section more concise.

Trim a few bits off the README

---

app/assets/javascripts/modules/gtm-copy-paste-listener.js

We've seen errors come into sentry where the event target property does
not have a dataset value [1]
Alex and I have set together and tried to replicate this problem and
have not managed to do so. All we can conclude is that there are scenarios
where the event.target property can potentially not point to a HTML
element.
As this event handler runs globally it feels for any copy or paste event
it feels prudent to put protection against it so that we prevent this
error from occurring.
[1]: https://sentry.io/organizations/govuk/issues/1088753936/?project=202208&referrer=slack

Check that event.target has a dataset property

---

app/assets/javascripts/application.js
app/assets/javascripts/components/autocomplete.js
app/assets/javascripts/modules/gtm-topics-listener.js
spec/javascripts/modules/gtm-search-topic-listener-spec.js

Trigger an event when searching for topics using the autocomplete component, so it can be tracked with analytics. It uses a `triggerEvent` function which acts as a polyfill for browsers that don't support CustomEvents..
It can be used/tested as shown in the example below:
```js
var autocomplete = document.querySelector('[data-autocomplete-type="topics"]')
autocomplete.addEventListener('search-topic', function(e){
console.log(e.detail.topicNames.join(' > '))
})
```
[Trello card](https://trello.com/c/tAXP6pf1)

Trigger search topic event on autocomplete for search topics

---

app/assets/javascripts/modal/modal-workflow.js
app/assets/javascripts/modules/inline-image-modal.js
app/assets/javascripts/modules/video-embed-modal.js
app/services/requirements/video_embed_checker.rb
spec/services/requirements/video_embed_checker_spec.rb

A couple of issues were caught with video embeds in the scenario testing round yesterday:
- an invalid URI caused the video embed requirements checker to exception
- an error response wasn't being handled by the modals.
It does look like we have a testing black spot with regards to the modal flows.

Fix video woes

---

app/interactors/backdate/update_interactor.rb

This will ensure additional actions, such as creating a timeline entry, don't
happen if an edition hasn't actually changed.

Backdate Update Interactor fails if edition unchanged

---

package.json
yarn.lock

Update paste-html-to-govspeak to 0.2.3 which [fixes two IE11 issues](https://github.com/alphagov/paste-html-to-govspeak/blob/master/CHANGELOG.md#023).
Trello cards:
https://trello.com/c/MOMnfctt
https://trello.com/c/YUzyMrrn

Update paste-html-to-govspeak to 0.2.3

---

app/interactors/schedule/create_interactor.rb
app/interactors/schedule/update_interactor.rb
app/services/schedule_service.rb
spec/features/scheduling/scheduled_publishing_spec.rb
spec/services/schedule_service_spec.rb

https://trello.com/c/P3z1xFBW/968-investigate-methods-to-prevent-access-to-document-based-on-access-limit-and-state
This makes scheduling consistent with other actions, noting that the
creation of timeline entries is not inherently part of the scheduling of
an edition.

Move schedule timeline entries into interactors

---

README.md
docs/approach-to-analytics.md

https://trello.com/c/KND0MCdd/962-document-approach-to-google-analytics-google-tag-manager
This adds some documentation to describe the user actions we track in
the app and how this is achieved for different elements and special
cases. More specific detail on how and why our analytics works this way
can be found in individual PR and GTM version descriptions.

Add doc for our approach to analytics

---

app/interactors/withdraw/create_interactor.rb
app/services/withdraw_service.rb
spec/features/workflow/edit_withdrawal_spec.rb
spec/features/workflow/withdraw_publishing_api_down_spec.rb
spec/features/workflow/withdraw_spec.rb
spec/services/withdraw_service_spec.rb

Previously the WithdrawService managed the TimelineEntry for a withdraw
action, as well as change detection when editing a withdrawal; both of
these are standard tasks for an interactor. This moves both of these
responsibilities out of the service and into the associated interactor.

Move bits of withdraw service into interactor

---

app/interactors/access_limit/update_interactor.rb
app/models/timeline_entry.rb
app/views/access_limit/edit.html.erb
config/locales/en/access_limit/edit.yml
config/locales/en/documents/history.yml
spec/features/editing_content_settings/remove_access_limit_spec.rb

Allow users to remove a set access limit

---

app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/components/_input-length-suggester.scss
app/assets/stylesheets/components/_url-preview.scss
app/views/components/docs/contextual_guidance.yml
app/views/documents/edit.html.erb

This PR updates the contextual guidance component and document edit page after a design iteration to improve the user interface on small screens or when using magnifying tools.
Changes:
- Set highlight border on the left for mobile views b13d318
- Increase margin-bottom for the guidance container for mobile views cbf4e43
- Hide the input length suggester container when no message is presented d03ee7a
- Add documentation to contextual guidance and update the example 534029b
- Update edit page to place the url preview section in a new row 51b1050
- Remove inset text top margin when used in the url preview component f295751
[Preview contextual guidance component](https://content-publisher-revi-pr-1253.herokuapp.com/component-guide/contextual_guidance)
[Preview the component in edit document …

Improve contextual guidance on small screens

---

app/controllers/topics_controller.rb
app/interactors/topics/update_interactor.rb

Previously we required the edition to be editable for a user to
edit/update topics, but this wasn't consistent with our 'always
editable' approach in the UI. However, we should keep the access
limiting assertion as this page reveals the title of the edition.

Remove editable/access assertions for topics

---

app/models/access_limit.rb
app/services/edition_assertions.rb
app/views/access_limit/edit.html.erb
config/locales/en/access_limit/edit.yml
config/locales/en/documents/show.yml
spec/factories/edition_factory.rb
spec/features/editing_content_settings/edit_access_limit_spec.rb
spec/features/editing_content_settings/set_access_limit_spec.rb
spec/models/edition_spec.rb
spec/services/edition_assertions_spec.rb

Previously we used 'all_organisations' to refer to an access limited
edition where users in the primary and any supporting orgs had access,
which was a little confusing due to the use of 'all'. This renames it to
'tagged_organisations', based on the copy we show to the user.

Rename all_organisations -> tagged_organisations

---

app/controllers/documents_controller.rb
app/services/edition_filter.rb
spec/services/edition_filter_spec.rb

https://trello.com/c/OJwGOdvd/988-dont-show-access-limited-documents-in-index-page-when-user-is-not-part-of-a-relevant-organisation
This adds an additional filtering step to the EditionFilter that scopes
the query to only include access limited editions the user can access.

Filter editions to respect access limiting

---

app/assets/stylesheets/components/_url-preview.scss
app/assets/stylesheets/utilities/_overwrites.scss
app/views/publish/published.html.erb
app/views/schedule/scheduled.html.erb

This PR updates the confirmation pages (for scheduled and published workflows) to render markup consistently and use inset text and links for URLs. It also breaks words in URLs for both links within inset-text components and for URLs in the url-preview component. This prevents long URLs from overflowing the containers (which is currently creating issues on mobile devices).
[Trello card](https://trello.com/c/X9vsbFTC)

Improve confirmation pages

---

app/interactors/access_limit/update_interactor.rb

Previously we raised an ArgumentError if the user managed to submit the
access limit form without a selection, or with an incorrect limt_type
value. This iterates the approach to be more comparable with e.g. the
PublishInteractor, so that we remove any access limit by default.

Default to all access if user subverts form

---

db/migrate/20190717170541_allow_edition_deletion.rb
db/migrate/20190717203348_allow_revision_deletion.rb
db/schema.rb
db/scrub_access_limited.sql
spec/db/scrub_access_limited_spec.rb

Trello: https://trello.com/c/X8hmEQKk/990-data-syncing-access-limited-content-to-integration
This introduces a SQL script, tests for that script and database migrations that allow for content to be removed as part of the [production to integration data sync](https://docs.publishing.service.gov.uk/manual/alerts/data-sync.html). The SQL file should be copied to https://github.com/alphagov/env-sync-and-backup/tree/master/sanitising-sql, it is included here so that it can be tested as part of any database schema changes.
The approach used here is very similar to [Email Alert API](https://github.com/alphagov/email-alert-api/blob/2d8c09117cd8bea1c696940283ccc64ec2be6e14/lib/data_hygiene/anonymise_email_addresses.sql) with the following differences:
- SQL file is put in `./db` for Content …

SQL script to remove access limited content

---

app/assets/stylesheets/utilities/_overwrites.scss
app/controllers/access_limit_controller.rb
app/views/access_limit/edit.html.erb
app/views/access_limit/edit_api_down.html.erb
app/views/documents/forbidden.html.erb
app/views/documents/tags/_multi_tag.html.erb
app/views/documents/tags/_single_tag.html.erb
config/locales/en/access_limit/edit.yml
config/locales/en/documents/forbidden.yml
spec/features/editing_content_settings/edit_access_limit_publishing_api_down_spec.rb
spec/features/editing_content_settings/edit_access_limit_spec.rb
spec/features/editing_content_settings/remove_access_limit_spec.rb
spec/features/editing_content_settings/set_access_limit_spec.rb

This adds organisation 'hints' when the user is editing the access limit for an edition, and when they see a 'forbidden' page, so they can follow-up with the owner org.

Access limit hints

---

app/assets/javascripts/components/autocomplete.js

Update the `syncResults` function of the `AutoCompleteWithHintOnOptions` to return suggestions when a mix of text and hint terms is used in the query string.
[Trello card](https://trello.com/c/vPEvzSY9)

Return suggestions when querying a mix of result and hint

---

app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/objects/_grid.scss
app/assets/stylesheets/objects/_history.scss
app/assets/stylesheets/objects/_side.scss
app/assets/stylesheets/utilities/_overwrites.scss
app/views/components/_inset_prompt.html.erb
app/views/components/_summary.html.erb
app/views/documents/show.html.erb
app/views/documents/show/_summary_tab.html.erb
app/views/layouts/application.html.erb

This PR update the document summary page layout so that on small screens (or when increasing the size) publisher are able to interact with it without scrolling too much.
- Refactor summary tab layout to move actions between flash messages/requirements and document summary. The tab order is so updated and the mobile layout will preserve the above mentioned order.
- After the code introduced by the above work:
- bring the `app-grid-column` modifiers in line to make it more clear which does what.
- align contextual guidance wrapper with side wrapper
- Add headings to tab sections on mobile
- After the code introduced by the above work:
- Remove relict class `app-timeline-heading` as it's not used anymore
- Restructure heading levels for summary page
```
H1: Document title
├─ H2: Document …
```

Improve summary page

---

app/controllers/access_limit_controller.rb
app/interactors/access_limit/update_interactor.rb
app/services/requirements/access_limit_checker.rb
app/views/access_limit/edit.html.erb
config/locales/en/requirements.yml
spec/features/editing_content_settings/set_access_limit_requirements_spec.rb
spec/services/requirements/access_limit_checker_spec.rb

This adds a requirements checker to ensure a user cannot set an access
limit that would lock them out of an edition.

Stop user locking themselves out

---

app/views/tags/edit.html.erb
config/locales/en/tags/edit.yml
spec/features/editing_tags/edit_tags_access_limited_spec.rb

Trello: https://trello.com/c/RUUozLeb/1006-warn-users-before-changing-organisations-on-an-access-limited-edition
This adds a warning for when an edition is access limited that users may experience undesirable consequences if they change an organisation.
It looks like this:
Few areas where I had to make some decisions:
- I assumed it was to be placed above the field rather than the intro text, this would lead well into having this warning be part of the view for primary_publishing_organisation field when we move forward with formats;
- the copy doesn't cater for the different types of access limit, but I don't think that's a big problem;
- the copy doc specified inset or warning component, I picked warning since we were doing a warning;
- feature testing this is a bit tricky as it's the …

Show a warning on the tags page for access limited editions

---

app/services/requirements/backdate_checker.rb
app/services/requirements/checker_issues.rb
app/services/requirements/content_checker.rb
app/services/requirements/edit_page_checker.rb
app/services/requirements/edition_checker.rb
app/services/requirements/file_attachment_checker.rb
app/services/requirements/image_revision_checker.rb
app/services/requirements/image_upload_checker.rb
app/services/requirements/path_checker.rb
app/services/requirements/publish_time_checker.rb
app/services/requirements/tag_checker.rb
app/services/requirements/topic_checker.rb
app/services/requirements/video_embed_checker.rb
app/services/requirements/withdrawal_checker.rb
spec/services/requirements/backdate_checker_spec.rb
spec/services/requirements/content_checker_spec.rb
spec/services/requirements/file_attachment_checker_spec.rb
spec/services/requirements/image_revision_checker_spec.rb
spec/services/requirements/image_upload_checker_spec.rb
spec/services/requirements/path_checker_spec.rb
spec/services/requirements/publish_time_checker_spec.rb
spec/services/requirements/topic_checker_spec.rb
spec/services/requirements/video_embed_checker_spec.rb
spec/services/requirements/withdrawal_checker_spec.rb

This makes the CheckerIssues behave more like an array, so that we can
always work with this class instead of going backwards and forwards
between arrays in order to emulate '<<', '+=' and 'empty?'.

Add array-like methods to CheckerIssues

---

app/models/access_limit.rb
app/models/edition.rb
app/models/revision.rb
app/models/tags_revision.rb
app/services/edition_assertions.rb
app/services/requirements/access_limit_checker.rb
app/views/access_limit/edit.html.erb
spec/features/editing_content_settings/set_access_limit_requirements_spec.rb
spec/models/access_limit_spec.rb
spec/services/edition_assertions_spec.rb
spec/services/requirements/access_limit_checker_spec.rb

https://trello.com/c/jvJZCHPG/989-present-access-limited-documents-to-publishing-api-and-asset-manager
This moves some of the access limit code into the model to remove the existing duplication and in anticipation of its re-use as part of the future payloads for the Publishing API and for assets.
This also renames the `TagsRevision#organisation` method to `supporting_organisation_ids`, to make it less ambiguous and more consistent with `primary_publishing_organisation_id`.

Access limit orgs

---

docs/adr/0013-permitted-deletion.md
docs/adr/00xx-permitted-deletion.md

Trello: https://trello.com/c/X8hmEQKk/990-data-syncing-access-limited-content-to-integration
[Rendered version](https://github.com/alphagov/content-publisher/blob/deletion-adr/docs/adr/00xx-permitted-deletion.md)
Given that we now allow deletion it seemed prudent to provide a follow
up to the ADR on restricted deletion.

ADR on permitted deletion

---

app/services/requirements/access_limit_checker.rb
config/locales/en/requirements.yml
spec/services/requirements/access_limit_checker_spec.rb

This adds a requirement that a user has an organisation associated with their account to set access limits. This is to prevent a user locking themselves out of content.

Add check for user's organisation to set access limit

---

app/views/documents/forbidden.html.erb

https://trello.com/c/Mb7uReAC/995-analytics-for-access-limiting
This adds visibility tracking for the global 'forbidden' page. Since
the title is the only analytics-visible indicator for this page (the URL
doesn't change and no events occur on it), we should have a deliberate
indicator that the user is not able to access an edition.

Track visibility of the 'forbidden' page

---

app/interactors/access_limit/update_interactor.rb
app/interactors/editions/create_interactor.rb
app/models/edition.rb
app/services/publish_service.rb
spec/interactors/editions/create_interactor_spec.rb
spec/models/edition_spec.rb

https://trello.com/c/P3z1xFBW/968-investigate-methods-to-prevent-access-to-document-based-on-access-limit-and-state
This moves a few of the methods in the Edition class to the (mostly) single points where they are used, making space to add another method in https://github.com/alphagov/content-publisher/pull/1297. Please see the commits for more details.

Move edition methods into other classes

---

app/views/layouts/application.html.erb
config/locales/en/application.yml

- Add link to guidance in footer
- Move footer content into locales so it can be edited by content designer
Requested by content designer and agreed with project manager.

Add guidance link to footer

---

app/controllers/application_controller.rb
app/models/edition.rb
app/models/user.rb
app/services/edition_filter.rb
spec/models/edition_spec.rb
spec/models/user_spec.rb
spec/services/edition_filter_spec.rb

https://trello.com/c/nRJAyOex/983-access-limiting
This adds a new permission that overrides the normal 'foridden' and
filtering behaviours for access limited editions, so that users are
still able to provide support with requests associated with these
editions, which they would otherwise be unable to find/view/edit.
While some existing apps use more role-like permissions, such as 'GDS
Admin', the permission here is specific to its functionality, as well as
which users it should be applied to. This helps avoids confusion about
the behaviour and applicability of permissions that are actually roles.
Previously it was only possible to test this behaviour at the feature
level, which would be complex due to the three variables - permission,
limit type, organisations - involved. This extracts …

Allow GDS users to override access limits

---

app/interactors/access_limit/update_interactor.rb
app/services/preview_asset_service/payload.rb
app/services/publishing_api_payload.rb
spec/features/editing_content_settings/edit_access_limit_requirements_spec.rb
spec/features/editing_content_settings/edit_access_limit_spec.rb
spec/features/editing_content_settings/enforce_access_limit_spec.rb
spec/features/editing_content_settings/remove_access_limit_spec.rb
spec/services/preview_asset_service/payload_spec.rb
spec/services/publishing_api_payload_spec.rb

https://trello.com/c/jvJZCHPG/989-present-access-limited-documents-to-publishing-api-and-asset-manager
This extends the existing feature to do API calls with the necessary
access limit metadata. In order to better distinguish between the the
different tests for access limits (the form vs. the behaviour), this
also renames the previous 'set_access_limit_spec' to 'enforce_'.

Try to create preview when editing access limits

---

app/services/preview_asset_service/payload.rb
app/services/publishing_api_payload.rb

https://trello.com/c/jvJZCHPG/989-present-access-limited-documents-to-publishing-api-and-asset-manager
Looks like a combination of PRs introduced a small bug...
This adds a guard conditional to ensure we only set organisation IDs to
limit access to the Publishing API payload when an access limit exists.

Fix access limit exception in payload

---

spec/lib/requirements/access_limit_checker_spec.rb
spec/lib/requirements/backdate_checker_spec.rb
spec/lib/requirements/content_checker_spec.rb
spec/lib/requirements/file_attachment_checker_spec.rb
spec/lib/requirements/image_revision_checker_spec.rb
spec/lib/requirements/image_upload_checker_spec.rb
spec/lib/requirements/path_checker_spec.rb
spec/lib/requirements/publish_time_checker_spec.rb
spec/lib/requirements/tag_checker_spec.rb
spec/lib/requirements/topic_checker_spec.rb
spec/lib/requirements/video_embed_checker_spec.rb
spec/lib/requirements/withdrawal_checker_spec.rb
spec/support/requirements_helper.rb

Previously our requirements specs contained repetitious code for
checking that different kinds issue could be rendered in the context of
a form and (potentially) on the summary page, which we do by checking
the associated translations. This DRYs-up the code to check issues can
be rendered in form/summary contexts by replacing it with a couple of
RSpec matchers: 'have_form_item' and 'have_summary_item'
```
I18n::MissingTranslationData:
translation missing: en.requirements.backdate_date.in_the_futur.form_message
Failure/Error: expect(issues).to have_form_item(:backdate_date, :in_the_future)
expected [{:text=>"Enter a date from 1 January 1995 onwards", :href=>nil, :target=>nil}] to have item {:text=>"Enter a …
```

DRY-up requirements specs with a new matcher

---

app/controllers/images_controller.rb
app/views/images/_image.html.erb
app/views/images/_lead_image.html.erb
app/views/images/crop.html.erb
spec/features/editing_images/edit_image_metadata_requirements_spec.rb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/upload_image_spec.rb

This pr makes a few small changes to the workflow for lead and inline images to better support users for actions involving crop and editing metadata.
For more information take look at the design document - https://docs.google.com/document/d/1DQvG8Q64SeHBYxplDIRaoFqGyMPdDdDGAkb3ovn2zbU/edit. 
Trello:
https://trello.com/c/TL1An3FR/1077-iterate-crop-edit-workflow-for-lead-and-inline-images

Iterate images workflow

---

app/controllers/contacts_controller.rb
app/models/document.rb
app/models/topic.rb
app/views/access_limit/edit.html.erb
app/views/documents/forbidden.html.erb
app/views/documents/index/_filters.html.erb
app/views/documents/show/_tags.html.erb
app/views/tags/tags/_multi_tag_input.html.erb
app/views/tags/tags/_single_tag_input.html.erb
lib/contacts.rb
lib/govspeak_document/in_app_options.rb
lib/govspeak_document/options.rb
lib/govspeak_document/payload_options.rb
lib/linkables.rb
lib/organisations.rb
lib/topic_index.rb
spec/features/editing_content/insert_contact_no_js_spec.rb
spec/features/editing_content/insert_contact_spec.rb
spec/lib/contacts_spec.rb
spec/lib/govspeak_document/in_app_options_spec.rb
spec/lib/govspeak_document/options_spec.rb
spec/lib/govspeak_document/payload_options_spec.rb
spec/lib/linkables_spec.rb
spec/lib/organisations_spec.rb
spec/models/document_topics_spec.rb

As part of our work to cleanup the 'app/services' directory, we
identified a few non-services that act as adapters/interfaces to
retrieve data from external APIs. This moves these non-services to
the 'lib/' directory, pending further decisions on how they should
be structured (names, interfaces, directories).

Move API retrieval non-services to lib

---

lib/date_parser.rb
lib/datetime_parser.rb
spec/lib/date_parser_spec.rb
spec/lib/datetime_parser_spec.rb

This got missed when the original changes were made...
This refactors the date/time parsers to take advantage the new interface
for Requirements::CheckerIssues. This also refactors the associated
specs to make use the the new matcher for requirements.

Refactor date/time parsers to use new interfaces

---

app/services/delete_draft_service.rb
app/services/preview_service.rb
app/services/preview_service/payload.rb
app/services/schedule_service.rb
app/services/schedule_service/payload.rb
spec/services/delete_draft_service_spec.rb
spec/services/preview_service/payload_spec.rb
spec/services/schedule_service/payload_spec.rb
spec/services/schedule_service_spec.rb

Previously we had a single PublishingApiPayload class to generate
payloads for scheduling and draft preview. This splits up the class
into a couple of supporting classes for their respective services,
as part of the work to tidy up the 'app/services/' directory.
One potential issue was the location of the 'PUBLISHING_APP' constant,
which is used by three services. It makes sense for the constant to be
defined close to the 'put content' payload, since the other two services
that use this constant are coupled to the value specified here.

Split PublishingApiPayload into supporting classes

---

app/interactors/access_limit/update_interactor.rb
app/interactors/backdate/destroy_interactor.rb
app/interactors/backdate/update_interactor.rb
app/interactors/documents/update_interactor.rb
app/interactors/file_attachments/create_interactor.rb
app/interactors/file_attachments/destroy_interactor.rb
app/interactors/file_attachments/update_interactor.rb
app/interactors/images/destroy_interactor.rb
app/interactors/images/update_crop_interactor.rb
app/interactors/images/update_interactor.rb
app/interactors/lead_image/choose_interactor.rb
app/interactors/lead_image/remove_interactor.rb
app/interactors/tags/update_interactor.rb
app/services/failsafe_preview_service.rb
app/services/preview_asset_service.rb
app/services/preview_service.rb
spec/services/failsafe_preview_service_spec.rb
spec/services/preview_asset_service_spec.rb
spec/services/preview_service_spec.rb

This refactors the 'try' aspect of the existing PreviewService into a new 'Failsafe' version of the class, working towards our aim of each service having a single responsibility. Doing this creates some 'room' to solve a similar multiple-responsibility issue on the PreviewAssetService.

Refactor preview services

---

app/interactors/schedule/create_interactor.rb
app/interactors/schedule/update_interactor.rb
app/services/schedule_service.rb
spec/services/schedule_service_spec.rb

Previously the ScheduleService had both a 'schedule' and 'reschedule'
method, each differing in the way they constructed a Scheduling object.
This moves the construction logic into the lone callers for each method,
reducing the ScheduleService to a single 'schedule' method that is more
compliant with our intended interface for services.
Note that two of the aspects of the construction are still covered at
the feature test level, despite the code moving into interactors:
- storing the previous edition state (when unscheduled)
- storing the intended review status for after publishing

Refactor ScheduleService to have single method

---

app/views/images/edit.html.erb

As we split the editing image link into two actions here -
https://trello.com/c/TL1An3FR/1077-iterate-crop-edit-workflow-for-lead-and-inline-images
this caused a bug to be introduced where when the user clicks the back
button on the edit image page they are taken back to the crop image
page.
This should only happen when they are uploading a new image, when
they are editing an existing image they should be taken back to the
images index.

Fix back button bug

---

app/views/publisher_information/beta_capabilities.govspeak.md
app/views/publisher_information/how_to_use_publisher.govspeak.md
app/views/publisher_information/publisher_updates.govspeak.md

This updates the documentation to reflect that Whitehall has now been
changed to allow adding content that is created outside of Whitehall to
document collections.
Screenshots:

Add information on adding content to Document Collections

---

app/services/delete_draft_service.rb
spec/services/delete_draft_service_spec.rb

To resolve issue raised in: https://govuk.zendesk.com/agent/tickets/3795670
A peculiarity of the Publishing API is that it can respond with either a
404 or a 422 when an attempt to discard a draft is and the draft does
not exist [1]. Presumably this is a consequence of the Publishing API
considering the content a resource rather than the draft or live
edition, so it doesn't seem semantically correct to just change this to
a 404 (and may have consequences).
To resolve we thus respond to both Not Found and Unprocessable Entity
responses and check the message of Unprocessable Entity to check it
meets the scenario.
Content Publisher can fall into this situation when a draft has not been
synced with the Publishing API, such as if if the new doesn't meet
requirements. At this point a user …

Allow discarding drafts when no draft exists in Publishing API

---

app/services/preview_service/payload.rb
spec/services/preview_service/payload_spec.rb

Trello: https://trello.com/c/sUjBwDG0
Follows on from:
- https://github.com/alphagov/govuk-rfcs/blob/master/rfc-113-expanding-draft-access-for-unauthenticated-users.md
- alphagov/publishing-api#1614
`auth_bypass_ids` have been separated from the `access_limited` hash in publishing-api.
This updates content-publisher to send `auth_bypass_ids` to the new field.

Use new auth_bypass_ids field in publishing-api

---

app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/components/_toolbar-dropdown.scss

Update the focus state used in the markdown editor component and toolbar dropdown component to be aligned with the new styles:
- Fix focus state for markdown editor toggle button
- Align markdown editor focus styling with inputs
- Update focus styles for toolbar dropdown
**Note**
Zoom in for detailed differences or open the images in a new tab
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
</table>
[Trello card](https://trello.com/c/z6RKO2Jx)

Update focus states in markdown editor

---

lib/tasks/import.rake

Since the Whitehall document export API endpoint is behind authentication (with user requiring the 'Export data' permission), we need to use a bearer token in order to be able to login as an API user with the correct permissions.
The bearer tokens are already configured in govuk-secrets.
Trello card: https://trello.com/c/RyVOGpMX

Use a bearer token when retrieving export from Whitehall

---

app/models/document.rb
app/models/document_topics.rb
spec/models/document_topics_spec.rb

Trello: https://trello.com/c/N9Loqi9G
Stops Content Publisher from throwing a 500 error if a document is tagged to a taxon that is not in the single taxonomy.
Also makes sure that these tags are not overwritten when a user updates the taxons that a document is tagged to via Content Publisher.
Content Publisher only knows about taxons that have the gov.uk homepage as the root taxon.
However there is another branch of the taxonomy called Worldwide that has `/world/all` as its root taxon.
If a document is tagged to one of these Worldwide taxons (usually via another app like Content Tagger), Content Publisher throws a 500 exception because it's trying to populate the miller columns on the edit Topics page with a nil value. This means that we can have live documents that can't be edited.
While …

Handle tags to taxons outside the GOV.UK single taxonomy

---

app/assets/stylesheets/objects/_side.scss

Ensure all links in the action block are rendered with the same font-size - regardless of being wrapped in a paragraph with `govuk-body` applied to it or not.
[Trello card](https://trello.com/c/oo6GrYo7)

Ensure all action links have the same font size

---

app/models/document.rb
db/migrate/20191030085853_add_imported_from_to_document.rb
db/migrate/20191030093601_add_imported_to_revision.rb
db/schema.rb
lib/tasks/whitehall_importer.rb
spec/tasks/whitehall_importer_spec.rb

The changes here allow GOV.UK developers to see if a document (and which of it's revisions) was imported to Content Publisher, and if so, from which application.
For documents, we are setting the origin application name.  For revisions, we only set a boolean, since the origin application can be determined from the parent document.
Additionally, the Whitehall import process has been updated to set the relevant values for those imported documents.
Trello card: https://trello.com/c/C6UBegEP

Flag imported documents as imported

---

lib/tasks/whitehall_importer.rb
spec/tasks/import_spec.rb
spec/tasks/whitehall_importer_spec.rb

The format of the Whitehall document export was changed in https://trello.com/c/at9jVJVu.  This updates the import task to reflect these changes in the format.

Update Whitehall import task for new export format

---

lib/tasks/whitehall_importer.rb
spec/tasks/import_spec.rb
spec/tasks/whitehall_importer_spec.rb

Trello: https://trello.com/c/pHYtNC5z
Tags imported documents to:
- their Whitehall publishing organisation
- ministers and government appointments
- topical events
- world locations
Documents that have more than one lead publishing organisation are rejected as the other lead organisations wouldn't be able to update the document once it's been imported to Content Publisher.
The structure of the import from Whitehall is based on: https://github.com/alphagov/whitehall/pull/5093

Tag imported documents

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_edition.json
spec/fixtures/whitehall_export_with_two_editions.json
spec/support/fixtures_helper.rb
spec/tasks/import_spec.rb
spec/tasks/whitehall_importer_spec.rb

Editors of documents in Whitehall may never have logged into Content Publisher, so we will not have a row in the users table for them.  This change creates a user entry for every person who has ever edited the Whitehall document that is imported.
For security, we give these users no permissions in the Content Publisher database.  If they log into the application in the future, the permissions will get updated based on the values in Sign On.
Users who have logged into Content Publisher are skipped.
This code is branched from https://github.com/alphagov/content-publisher/pull/1416, so should not be merged until that PR is also merged.  It is also dependent on a users array being implemented in the Whitehall document export.
Trello card: https://trello.com/c/JPerZkxp

Import all users from Whitehall document export

---

db/migrate/20191104131759_add_document_type_id_to_metadata_revisions.rb
db/schema.rb

In order to support documents that can change type, the document_type_id has to
be moved from the Document to Metadata Revisions table. 
Further work will be completed in separate PRs.
[Trello card](https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type)
Co-authored-by: Jon Hallam <jonathan.hallam@digital.cabinet-office.gov.uk>

Add document_type_id column to Metadata Revisions table

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_edition.json
spec/fixtures/whitehall_export_with_two_editions.json
spec/tasks/whitehall_importer_spec.rb

So far, we have imported users and documents from Whitehall, but not linked the users to the documents they have edited.  When importing a document from Whitehall, we now attribute the following to Content Publisher users:
- document creator
- edition creator
- edition last editor
Trello card: https://trello.com/c/jOaNlx3c

Import user attribution from Whitehall

---

app/models/document.rb
app/models/edition.rb
app/models/revision.rb
spec/models/document_spec.rb
spec/models/edition_spec.rb
spec/models/revision_spec.rb

As part of allowing content publisher to change the document types of documents we need to have the document type id saved in metadata revisions. This duplicates thatf information across metadata revisions and document. This will be removed from Document after later schema changes.
Relies on - https://github.com/alphagov/content-publisher/pull/1419/files
Trello - https://trello.com/b/mn2MqH3M/publishing-workflow-doing-q4-2019-to
Co-authored-by: Aga Dufrat <agnieszka.dufrat@digital.cabinet-office.gov.uk>

Pass document_type_id through to metadata_revisions

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_edition.json
spec/fixtures/whitehall_export_with_two_editions.json

The name of an edition's edit history was changed from `history` to `revision_history` in the Whitehall document export as part of https://github.com/alphagov/whitehall/pull/5093.
This makes the corresponding change in the Content Publisher import code.

Rename "history" to "revision_history" in Whitehall import

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_edition.json
spec/fixtures/whitehall_export_with_two_editions.json
spec/tasks/whitehall_importer_spec.rb

There will sometimes be cases where we cannot fully import a document from Whitehall.  Currently, these documents are still being partially imported but being marked as successful in the database.
This changes the behaviour to abort on the following, and log a relevant message:
- An edition has an unsupported state
- An edition has an unsupported locale
- An edition has an unsupported document type
Note that for the latter, we are currently not storing the document type on import (there is a placeholder in the code) until the `document_type_id` has been fully migrated from `Document` to `RevisionMetadata`.
Trello card: https://trello.com/c/6ChA2UFY

Raise AbortImportError when Whitehall import is unsuccessful

---

db/migrate/20191106095154_populate_document_type_id_in_metadata_revisions.rb
db/schema.rb

Populate `document_type_id` in `metadata_revisions` table with the data from the `documents` table as a part of work to allow Content Publisher to change document types. 
In the next step we will switch the application to use data from the new column.
[Trello card](https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type)

Populate document_type_id in metadata_revisions

---

app/assets/javascripts/application.js
app/assets/javascripts/components/autocomplete.js
app/assets/javascripts/components/contact-preview.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_contact-preview.scss
app/controllers/contact_embed_controller.rb
app/interactors/contact_embed/create_interactor.rb
app/views/components/_contact_preview.html.erb
app/views/components/docs/contact_preview.yml
app/views/contact_embed/new.html.erb
config/locales/en/contact_embed/new.yml
config/routes.rb
spec/features/editing_content/insert_contact_embed_no_js_spec.rb
spec/features/editing_content/insert_contact_embed_spec.rb
spec/javascripts/components/contact-preview-spec.js

This PR:
- creates a new contact preview component (following the pattern used in the url preview component) - this component refers and uses a select element as a source of truth, a govspeak snippet template and a govspeak path (all being passed as data attributes at component's root level)
- uses the contact preview component it in the contact embed view and
- updates the contact autocomplete to properly sync the select element that's enhanced by it.
See previews in the [previous approach](https://github.com/alphagov/content-publisher/pull/1310) (as the outcome is the same).
[Trello card](https://trello.com/c/8NN6jQiI/1025-modal-experience-for-contacts)
[Trello card](https://trello.com/c/6uzRis6D/1145-when-a-user-chooses-a-contact-they-can-preview-it-and-insert-it-in-content)

Add contact preview component and use it on contact embed insertion

---

app/assets/stylesheets/components/_autocomplete.scss

Improve tag selection on small devices.
Update the focus state styles to align them with `govuk-frontend` 3.x.
On mobile, the page is quite dense and elements are close together, making it hard to scan and read.
Focus state was using the old styles (most probably the only component that wasn't updated yet).
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
</table>
[Trello card](https://trello.com/c/4T9XiLh7)

Improve tag selection

---

app/assets/stylesheets/components/_autocomplete.scss

When JavaScript is enabled a `select[multiple]` element part of the autocomplete will be enhanced via JavaScript. Between the page load and the JavaScript load the `select[multiple]` switches from the default height (which shows a few options) to the enhanced autocomplete (which shows a basic input). This causes quick page movements that are confusing users. We now set the `select[multiple]` element to the default input height of 40px when JavaScript is enabled to prevent this from happening.
Live preview [before](https://content-publisher.integration.publishing.service.gov.uk/component-guide/autocomplete/select_multiple) and [after](https://content-publisher-revi-pr-1436.herokuapp.com/component-guide/autocomplete/select_multiple).
<details>
<summary>Before</summary>
</details>
<details> …

Prevent tags page movement

---

db/migrate/20191106152405_allow_null_on_document_document_type_id.rb
db/schema.rb

Trello - https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type
Content publisher currently sets `document_type_id` on the `Document` and `MetadataRevision` table. Before the `document_type_id` column can be removed from `Document` it needs to be able to be set to nill otherwise code changes that do not set it will fail.
This allows the setting of that column to null in order that changes can be made to the underlying code

Allow document_type_id to be null on the Document table

---

app/models/document.rb
app/models/edition.rb
app/models/metadata_revision.rb
app/models/revision.rb
app/services/path_generator_service.rb
lib/edition_filter.rb
lib/requirements/topic_checker.rb
lib/tasks/whitehall_importer.rb
spec/factories/document_factory.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/features/workflow/withdraw_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/lib/requirements/topic_checker_spec.rb
spec/models/edition_spec.rb
spec/models/revision_spec.rb
spec/services/path_generator_service_spec.rb

We are moving document_type_id column from Documents table to MetadataRevisions table so we can change the type of the documents.
This switches the app to use data from the new column in the MetadataRevisions table.
In this PR we:
- Move `document_type` method from Document to MetadataRevision
- Edition delegates document_type_id to Revisions and further to MetadataRevision
- Update factories
- Update tests that rely on document type id
- Update WhitehallImporter
- Ignore `document_type_id` in Document model 
[Trello card](https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type)
Co-authored by @JonathanHallam, with help from @leenagupte

Switch to use document_type_id from MetadataRevisions

---

app/models/document.rb
app/models/edition.rb
app/models/metadata_revision.rb
app/models/revision.rb
app/services/path_generator_service.rb
lib/edition_filter.rb
lib/requirements/topic_checker.rb
lib/tasks/whitehall_importer.rb
spec/factories/document_factory.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/features/workflow/withdraw_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/lib/requirements/topic_checker_spec.rb
spec/models/edition_spec.rb
spec/models/revision_spec.rb
spec/services/path_generator_service_spec.rb

Reverts alphagov/content-publisher#1437
This can't be deployed until after https://github.com/alphagov/content-publisher/pull/1441 has been deployed.

Revert "Switch to use document_type_id from MetadataRevisions"

---

db/migrate/20191114123329_repopulate_document_id_in_metadata_revisions.rb
db/schema.rb

This fixes forward the migration introduced in [06c03c5][] which updated
the document_type_id's incorrectly.
This problem was identified by comparing the backfilled data:
```
irb(main):001:0> Document.joins(current_edition: { revision: :metadata_revision }).where("documents.document_type_id != metadata_revisions.document_type_id").count
(19.7ms)  SELECT COUNT(*) FROM "documents" INNER JOIN "editions" ON "editions"."document_id" = "documents"."id" AND "editions"."current" = $1 INNER JOIN "revisions" ON "revisions"."id" = "editions"."revision_id" INNER JOIN "metadata_revisions" ON "metadata_revisions"."id" = "revisions"."metadata_revision_id" WHERE (documents.document_type_id != metadata_revisions.document_type_id)  [["current", true]]
=> 97
```
After running this migration here these are …

Re-populate document_type_id for MetadataRevision

---

app/models/document.rb
app/models/edition.rb
app/models/metadata_revision.rb
app/models/revision.rb
app/services/path_generator_service.rb
lib/edition_filter.rb
lib/requirements/topic_checker.rb
lib/tasks/whitehall_importer.rb
spec/factories/document_factory.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/features/workflow/withdraw_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/lib/requirements/topic_checker_spec.rb
spec/models/edition_spec.rb
spec/models/revision_spec.rb
spec/services/path_generator_service_spec.rb

Reverts alphagov/content-publisher#1442
Now that https://github.com/alphagov/content-publisher/pull/1441 is merged this can can be re-added to the codebase.

Revert "Revert "Switch to use document_type_id from MetadataRevisions""

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_withdrawn_edition.json
spec/support/fixtures_helper.rb
spec/tasks/whitehall_importer_spec.rb

Trello: https://trello.com/c/8U7JPIHT
Update `WhitehallImporter` to support documents that have a status of `withdrawn`.
The public explanation and the internal reason why the document was withdrawn have also been imported.
As Content Publisher supports undoing a withdrawal of content which involves using the published status to determine what to revert the content to (published or published_but_needs_2i_review), the published status details for the document have also been imported.
[Link to Whitehall export data](https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/export/document/353919)
```
#<Document id: 623, content_id: "2817f9a0-7c4a-4b48-a272-3c28251e79fe", locale: "en", document_type_id: "news_story", created_at: "2017-03-13 17:39:03", updated_at: …
```

Import documents a withdrawn status into Content Publisher

---

db/migrate/20191114135544_add_not_null_constraint_on_document_type_id.rb
db/schema.rb
spec/factories/metadata_revision_factory.rb

We are adding "not null" constraint on document_type_id in metadata_revisions table 
to ensure that this value is stored for each metadata_revision. 
We also have to update the metadata revision factory in line with this change.
[Trello card](https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type)

Add not null constraint on document_type_id in metadata_revisions

---

db/migrate/20191115103058_remove_document_type_id_from_documents.rb
db/schema.rb

Trello - https://trello.com/c/kwnmsIe9/1095-permit-content-publisher-to-have-documents-that-change-type
This is among the last pieces of work in a stream set to move document_type_id from Documents to MetadataRevisions. It will allow us to change document types on documents within content-publisher. This PR removes document_type_id from Documents now that all of its functionality has been moves to MetadataRevisions.

Remove document_type_id from Document

---

app/models/document.rb

There was a small amount of code that was left over after the movement of document_type_id from Documents to MetadataRevisions. This removes code that refers to a table column that is no longer extant.

Post document.document_type_id removal cleanup

---

lib/tasks/whitehall_importer.rb
spec/fixtures/whitehall_export_with_one_edition.json
spec/fixtures/whitehall_export_with_one_withdrawn_edition.json
spec/fixtures/whitehall_export_with_two_editions.json
spec/tasks/whitehall_importer_spec.rb

We were previously hard-coding the first part of the base path, then adding the document's slug when importing from Whitehall.  This change assigns the correct base path to each revision, based on the information provided in the Whitehall export.
Trello card: https://trello.com/c/IKL78lqj

Use base path supplied by Whitehall when importing

---

lib/tasks/whitehall_importer.rb
spec/tasks/whitehall_importer_spec.rb

Whitehall sets access limiting by setting `access_limited: true` on Edition. Whereas in Content Publisher, we have AccessLimit model which points to an edition.
When importing AccessLimit:
- created_at is set to the time the edition was last edited
- revision is the last one for this content
- there is no user attribution
- limit_type is set to "tagged_organisations" as this is the only option in Whitehall
The only statuses considered for access_limit are draft, rejected, submitted. In both apps access_limit is cleared once the document is published ([Content Publisher](https://github.com/alphagov/content-publisher/blob/master/app/services/publish_service.rb#L50 ), [Whitehall](https://github.com/alphagov/whitehall/blob/13ccb069d3df45371c7c7390c292968d052c7ea5/app/services/edition_publisher …

Import AccessLimit from Whitehall

---

config/political_organisations.yml
lib/political_edition_identifier.rb
spec/lib/political_edition_identifier_spec.rb

Trello: https://trello.com/c/WKUoYhxb/1189-spike-into-defining-the-history-mode-feature
This is a port of the logic from Whitehall that is used to determine
whether an edition is political [1]. This is simplified as Content
Publisher is currently only working with news and press releases and
will need to be expanded with the introduction of more document types
(or logic abstracted to those document types).
Whitehall checks whether content is associated with a minister and a
political organisation. Content Publisher however associates with role
appointments and isn't aware whether these are ministers or not. We
expect that nearly all associations will be ministers so until we have
the ability to determine between these just a check of a role
appointment should suffice.
[1]: …

Determine whether edition is political is not

---

app/models/government.rb
app/models/topic.rb
config/governments.yml
spec/factories/government_factory.rb
spec/models/government_spec.rb

Trello: https://trello.com/c/WKUoYhxb/1189-spike-into-defining-the-history-mode-feature
This hardcodes government data as config for Content Publisher to have
access to this data. This is intended to be a short-term approach until
governments are exposed to the Publishing API and Content Publisher
consumes them. The effects of duplicating this data is that any changes
to governments will require the config for Content Publisher to be
re-generated.
I decided to pull the data for this directly from the Whitehall database
rather than using the API at https://www.gov.uk/api/governments. The API
seems to only use slugs as identifying information and these slugs seem
to change when governments change to represent the end date, this didn't
strike me as a reliable field we could use and felt the …

Import governments from Whitehall

---

app/controllers/errors_controller.rb
config/environments/test.rb
spec/requests/errors_spec.rb

Content Publisher currently returns an [unstyled 500 error](https://github.com/rails/rails/blob/98a57aa5f610bc66af31af409c72173cdeeb3c9e/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L20-L24) when a 404 page
is encountered. This happens because an exception loop occurs during the
rendering of an error response. The problem occurs because `check_user_access`
before action runs before all actions (including error actions). So if a
document is going to 404, the `ActiveRecord::RecordNotFound` is raised once
before the requested action and then again in the ErrorsController.
To avoid this we are using skip_before_action callback in ErrorsController so
the `check_user_access` action only runs once.
We are setting `config.action_dispatch.show_exceptions` to `true` in the test …

Fix Content Publisher returning 500 on document 404s

---

spec/features/editing_content/url_preview_spec.rb

Previously we tested the URL preview of a title by clicking the 'body'
field as a way to generate a blur event. This replaces the click method
with an explicit 'tab', as the former doesn't seem to work anymore.

Fix URL preview spec due to lack of blur event

---

app/interactors/images/create_interactor.rb
app/services/image_blob_service.rb
lib/whitehall_importer/create_image_revision.rb
lib/whitehall_importer/create_revision.rb
spec/factories/whitehall_export/edition_factory.rb
spec/factories/whitehall_export/image_factory.rb
spec/fixtures/files/coffee.svg
spec/lib/whitehall_importer/create_image_revision_spec.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/services/image_blob_service_spec.rb

This PR imports image data from Whitehall. It does not do the following (links to their Trello cards):
1) [deal with attachments](https://trello.com/c/4FF2oprK/1182-import-attachments-into-content-publisher)
2) [change Govspeak markdown to use content publisher image syntax](https://trello.com/c/ubTM9ylI/1176-use-imported-images-and-attachments-in-content-publisher)
------
Trello card: https://trello.com/c/jzV3scso/1093-import-images-and-attachments-to-content-publisher

Import images from Whitehall

---

app/models/edition.rb
app/models/government.rb
app/models/revision.rb
app/services/preview_service/payload.rb
config/governments.yml
db/migrate/20191120110949_add_editor_political_to_metadata_revision.rb
db/migrate/20191120113230_add_system_political_to_edition.rb
db/migrate/20191120204541_add_government_id_to_edition.rb
db/schema.rb
spec/factories/edition_factory.rb
spec/factories/government_factory.rb
spec/factories/revision_factory.rb
spec/models/edition_spec.rb
spec/models/government_spec.rb
spec/services/preview_service/payload_spec.rb

Trello: https://trello.com/c/WKUoYhxb/1189-spike-into-defining-the-history-mode-feature
This PR adds the database changes and associated methods for an Edition to know whether it is in history mode. This data can then be included in data sent to the Publishing API.
The approach taken here is to have two fields on Edition that can be set each time the content is updated or published which represent the government and the automatically determined political status. This data can be worked out on the fly but is stored to allow filtering and to make everything simpler. These are represented as `government_id` and `system_political` fields.
A user can override political status which is represented by a boolean field in a metadata_revision of `editor_political`. A nil value for this indicates …

Allow presenting history mode content to Publishing API

---

lib/whitehall_importer/create_revision.rb
lib/whitehall_importer/embed_body_references.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/lib/whitehall_importer/embed_body_references_spec.rb

Trello card: https://trello.com/c/ubTM9ylI/1176-use-imported-images-and-attachments-in-content-publisher

Use imported images and attachments

---

package.json
yarn.lock

Update `miller-columns-element` to [1.2.0](https://github.com/alphagov/miller-columns-element/pull/26).
[Trello card](https://trello.com/c/ApHlPUDQ/1146-improve-topic-selection-on-small-screens-and-when-used-with-magnifying-tools)

Update miller-columns-element to 1.2.0

---

lib/tasks/csv_report.rake
spec/lib/tasks/csv_report_spec.rb

Several published documents on Content Publisher will go into history mode when a government falls.  We need to let managing editors know which documents are politically sensitive and will go into history mode so they can audit their documents and identify exceptions.
This rake task produces a CSV files with a list of live documents with their political status for each organisation.
It is intended to be removed once the history mode is implemented in the user interface. We will raise an exception as a prompt.
_Tested in integration_
[Trello card](https://trello.com/c/JP693RnO/1188-work-out-which-docs-are-political)

Add rake task for creating CSVs of political status by organisation

---

app/services/preview_service/payload.rb
spec/factories/edition_factory.rb
spec/features/workflow/create_document_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/services/preview_service/payload_spec.rb

Platform Health (well mostly @cbaines) have been doing work to represent governments in the Publishing API (see: https://github.com/alphagov/whitehall/pull/5178 and https://github.com/alphagov/govuk-content-schemas/pull/936) this work is leading towards the frontend apps to consider what content a government is linked to rather than the [government data in the details](https://github.com/alphagov/content-publisher/blob/62306c4f15edf9795631d5e2389334e5e0c12b86/app/services/preview_service/payload.rb#L79)
So that Content Publisher can be compatible with this change we will include links to government as well as government data in the details. Once Platform Health complete this change we can then remove the government data from our details hash.

Use edition links to governments

---

lib/tasks/import.rake
spec/lib/tasks/import_spec.rb

This ensures we get an exit code of 1 to indicate an error and outputs
text to explain why it failed.

Abort import task if import fails

---

app/models/edition.rb
app/services/edit_edition_service.rb
app/services/publish_service.rb
spec/models/edition_spec.rb
spec/services/edit_edition_service_spec.rb
spec/services/publish_service_spec.rb

Trello: https://trello.com/c/KxlsWBzq/1207-automatically-determine-political-status-and-government-at-the-point-of-editing
This is a method that returns the date that is shown on GOV.UK to show
the first published at time on an edition. It is intended to be used to
calculate the government at a particular time.

Edition method for public first published time

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/migrate_state.rb

This simplifies how we set the `withdrawn` status. We know that the state will be `withdrawn` so there is no need to call MigrateState.
Since that simplified the `set_withdrawn_status` method we can move the logic of creating Withdrawal there.
We want to use similar pattern for importing scheduled documents.

Refactor importing withdrawn status

---

app/assets/javascripts/components/autocomplete.js
app/assets/stylesheets/components/_autocomplete.scss
app/views/components/_autocomplete.html.erb

This PR updates the markup that's generated by the autocomplete component and then updated by the autocomplete script to meet web standards.
Initial (non-enhanced) markup
```
<div class="app-c-autocomplete app-c-autocomplete--search" data-module="autocomplete">
<fieldset class="govuk-fieldset">
<label for="autocomplete-search" class="gem-c-label govuk-label">Search</label>
<input name="autocomplete-search" class="govuk-input" id="autocomplete-search" list="autocomplete-search-list" type="search">
</fieldset>
</div>
```
JavaScript enhanced markup
```
<div class="app-c-autocomplete app-c-autocomplete--search" data-module="autocomplete">
<div class="autocomplete__wrapper" role="combobox" aria-expanded="false">
<input aria-owns="autocomplete-search__listbox" autocomplete="off" …
```

Fix topics search markup

---

app/views/documents/show/_historical_notice.html.erb
app/views/documents/show/_summary_tab.html.erb
config/locales/en/documents/show.yml
spec/requests/historical_banner_spec.rb

As part of the work to introduce history mode to content publisher we need to let publishers know when a document is in history mode. This introduces a notice that warns publishers when a political document is marked as being from a previous government. This feature is not yet ready for release and as such is hidden behind a feature flag. This will be removed at a later date.
Trello - https://trello.com/c/rhEtuy5V/1208-show-history-mode-status-on-summary-view
Co-authored-by: Bruce Bolt <bruce.bolt@digital.cabinet-office.gov.uk>

Add in history mode status banner

---

app/assets/stylesheets/utilities/_overwrites.scss
app/views/access_limit/edit.html.erb
app/views/documents/edit/_change_notes.html.erb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
app/views/publish/confirmation.html.erb
app/views/schedule/new.html.erb

This PR updates the markup generated for the radios across the application ensuring that each instance has a legend. It doesn't contain any visual changes.
An example of using the main page heading as legend below:
```
<h1 class="govuk-heading-l">What is the content for?</h1>
...
<fieldset class="govuk-fieldset">
<div class="govuk-radios" data-module="govuk-radios">
<div class="gem-c-radio govuk-radios__item">
<input type="radio" name="supertype" id="radio-0802af77-0" value="news" class="govuk-radios__input" aria-describedby="label-hint-20c762ca" data-gtm="choose-supertype" data-gtm-value="News" aria-controls="conditional-ced84d75" aria-expanded="false">
<label for="radio-0802af77-0" class="gem-c-label govuk-label govuk-label--s govuk-radios__label">News</label>
</div>
...
</div> …
```

Add legends to radios

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/edition_history.rb
spec/factories/whitehall_export/edition_factory.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb

We want to have the ability to import a document that is scheduled for publication.
In Whitehall you can determine that an edition is scheduled as it has a state of “scheduled” and a field of `scheduled_publication` with the time.
In Content Publisher the scheduled publishing is represented by a status of “scheduled” with a Scheduling object that knows:
- who created the scheduling. This is handled in the existing `build_status` method
- whether the content was reviewed before scheduling. This is set based on the value of `force_published` on the `whitehall_edition`. If this is true, reviewed should is false otherwise this is true.
- the status prior to the scheduling to allow rolling back to that. We determine the status using whitehall document's `revision_history` by checking if the …

Import scheduled Whitehall documents

---

app/jobs/scheduled_publishing_job.rb
spec/factories/whitehall_export/document_factory.rb
spec/factories/whitehall_export/edition_factory.rb
spec/factories/whitehall_export/image_factory.rb
spec/factories/whitehall_export/revision_history_event.rb
spec/factories/whitehall_export/unpublishing_factory.rb
spec/features/scheduling/clear_proposed_publish_time_spec.rb
spec/features/scheduling/propose_publish_time_and_schedule_spec.rb
spec/features/scheduling/propose_publish_time_spec.rb
spec/features/scheduling/scheduled_publishing_failed_spec.rb
spec/features/scheduling/scheduled_publishing_spec.rb
spec/features/scheduling/scheduled_publishing_without_review_spec.rb
spec/features/scheduling/unschedule_spec.rb
spec/features/scheduling/update_proposed_publish_time_spec.rb
spec/features/scheduling/update_publish_time_spec.rb
spec/features/workflow/publish_spec.rb
spec/features/workflow/publish_without_review_spec.rb
spec/lib/requirements/publish_time_checker_spec.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/import_spec.rb
spec/models/edition_spec.rb
spec/services/assign_edition_status_service_spec.rb
spec/services/edit_edition_service_spec.rb
spec/services/publish_service_spec.rb
spec/services/withdraw_service_spec.rb
spec/spec_helper.rb

This changes our use of Time.zone.now to Time.current for consistency across the app as we have a preference for Time.current.
It also moves the TimeHelpers include to the spec_helper.rb so this no longer needs to be included manually - since we hit including this file in a fair number of files.

Some small time consistency tweaks

---

app/models/government.rb
app/services/edit_edition_service.rb
app/services/preview_service.rb
app/services/preview_service/payload.rb
app/services/resync_service.rb
lib/tasks/resync.rake
spec/factories/edition_factory.rb
spec/factories/removal_factory.rb
spec/factories/scheduling_factory.rb
spec/factories/status_factory.rb
spec/factories/withdrawal_factory.rb
spec/features/scheduling/schedule_requirements_spec.rb
spec/lib/tasks/resync_spec.rb
spec/models/government_spec.rb
spec/services/preview_service/payload_spec.rb
spec/services/preview_service_spec.rb
spec/services/resync_service_spec.rb

Trello: https://trello.com/c/cT9yYO4X
Replaces PR #1487 
Adds a service to re-sync a document with publishing-api. This will mainly be used in two scenarios:
1. Documents imported from Whitehall will need to be re-presented to publishing-api and have their base_path reservation moved from Whitehall to Content Publisher.
2. All documents will need to be represented to publishing-api to associate them with the correct government, so that if there is a new government, they can successfully transition into history mode.
co-authored with @ChrisBAshton

New service to re-sync documents with publishing-api

---

app/controllers/documents_controller.rb
app/views/documents/index/_filters.html.erb
config/locales/en/documents/index.yml
lib/edition_filter.rb
spec/features/finding/index_filtering_spec.rb
spec/lib/edition_filter_spec.rb

Adds two new filters to the index page:
- `Marked as political` => "", "Yes", "No"
- `In history mode` => "", "Yes", "No"
We did consider having labels for the latter as "Yes - past government", "No - current government", but these don't fully explain what constitutes history mode (e.g. a document published by a past government is not in history mode if it is not classed as political content).
Screenshot:
Trello card: https://trello.com/c/7ZtSXVFx/1211-filter-index-page-based-on-political-and-history-mode-status

Filter index page based on political and history mode status

---

app/views/images/crop.html.erb
app/views/images/edit.html.erb
config/locales/en/images/edit.yml

Provide the user with a placeholder alt text for freshly uploaded images.
[Trello card](https://trello.com/c/6idOVWgU)

Set placeholder alt text for images

---

app/controllers/editions_controller.rb
app/controllers/unwithdraw_controller.rb
app/controllers/withdraw_controller.rb
app/models/user.rb
app/views/missing_permissions/update_history_mode.govspeak.md
app/views/missing_permissions/update_history_mode.html.erb
config/locales/en/missing_permissions/update_history_mode.yml
config/locales/en/withdraw/withdraw.yml
spec/factories/user_factory.rb
spec/features/workflow/edit_withdrawal_spec.rb
spec/features/workflow/unwithdraw_publishing_api_down_spec.rb
spec/features/workflow/unwithdraw_spec.rb
spec/features/workflow/withdraw_publishing_api_down_spec.rb
spec/features/workflow/withdraw_requirements_spec.rb
spec/features/workflow/withdraw_spec.rb
spec/requests/editions_spec.rb
spec/requests/unwithdraw_spec.rb
spec/requests/withdraw_spec.rb
spec/spec_helper.rb

We need to create a permission that can be granted to GDS Editors that will allow them to make changes to a live edition that is in history mode.
This PR starts to go down the road of request testing which is the new approach we want to take where logic doesn't need an explicit feature test. There is some repetition especially concerning the withdrawn / unwithdrawn permission logic so maybe we could abstract this away to a class to deal with permissions but then again we'd still have to handle the rendering from within the controller.
The two managing editor feature tests for withdraw and unwithdraw flows could be moved into request tests and will be in future work.
GDS editor permission error screen:
TODO:
Trello:
https://trello.com/c/DXonAtIX/1209-permission-to-create-new-edition-withdra …

History mode permissions

---

app/models/government.rb
app/services/preview_service/payload.rb
spec/models/government_spec.rb
spec/services/preview_service/payload_spec.rb

Using a government link is the preferred method for setting the
government association and whether the government is current. By
removing this data we remove the risk of this data conflicting with that
provided by the links.

Stop sending government information in details

---

lib/tasks/import.rake
lib/whitehall_importer.rb
lib/whitehall_importer/clear_linkset_links.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer/clear_linkset_links_spec.rb
spec/lib/whitehall_importer_spec.rb

Trello: https://trello.com/c/Ni6YDPQd
Whitehall uses a mixture of [link-set links](https://github.com/alphagov/publishing-api/blob/master/doc/link-expansion.md#patch-link-set---link-set-links) and [edition links](https://github.com/alphagov/publishing-api/blob/master/doc/link-expansion.md#put-content---edition-links) depending on at what point the content was migrated.
Content Publisher however uses edition links near exclusively. As part of migration we need to reset links that shouldn't be set as linkset links based on the document type.
Based on [digging in Whitehall](https://github.com/alphagov/whitehall/blob/master/app/presenters/publishing_api/news_article_presenter.rb#L35-L43) and the [schema](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/news_article.jsonnet …

Clear linkset links after resync

---

app/controllers/political_controller.rb
app/interactors/political/update_interactor.rb
app/models/timeline_entry.rb
app/views/documents/show/_content_settings.html.erb
app/views/political/edit.html.erb
app/views/political/non_managing_editor.html.erb
config/locales/en/documents/history.yml
config/locales/en/documents/show.yml
config/locales/en/political/edit.yml
config/locales/en/political/political.yml
config/routes.rb
spec/features/editing_content_settings/political_spec.rb
spec/interactors/political/update_interactor_spec.rb
spec/requests/documents_spec.rb

Publishers need to be able to see the political status of their documents.  Managing editors need to be able to override the automatically determined political status for their documents.
To this end, this PR adds a "Political content" value to the "Content settings" section of the document summary page.  This also has a link to change the political status, which can only be done when the edition is editable (i.e. it is draft).  Non-managing editors will see a message asking them to contact their managing editor, whilst managing editors will see a form with radio buttons.  Once the status has been overridden, a timeline history entry is added and the preview updated (in case the document has been backdated and a history mode banner needs to be shown).
This sits behind a pre-release …

Show political status and allow status to be overridden

---

app/views/documents/show/_content_settings.html.erb
app/views/documents/show/_summary_tab.html.erb

Trello: https://trello.com/c/ssksY6cO
Display the "Content Settings" section even if the document has been published so that the 'gets history mode' setting is always displayed.
The rules for showing if the document has been access limited or backdate have not changed.

Show content settings for published documents

---

app/views/topics/edit.html.erb

Group topics' inputs in a fieldset using the current heading as legend.
[Trello card](https://trello.com/c/gYQgI6Xg)

Wrap topics' inputs in a fieldset

---

app/views/publisher_information/publisher_updates.html.erb
config/locales/en/publisher_information/publisher_updates.yml

Add hidden h2 to avoid skipping heading levels from h1 to h3, provide document structure and landmarks to navigate page content.
**Note:** The updated copy is pending a review from a content designer.
[Trello card](https://trello.com/c/fgE3IdKq)

Fix publishing information headings

---

app/views/components/_side_navigation.html.erb
app/views/components/docs/side_navigation.yml
app/views/publisher_information/_publication_info_nav.html.erb
app/views/topics/edit.html.erb

Landmarks must have a unique role or role/label. Given that we always have the main navigation on the page, any additional navigation landmark must be accompanied by a label to make it unique. `aria-label` is being appended to the landmark type (e.g. navigation) when provided – as seen in the example below.
**Note:** The updated copy is pending a review from a content designer.
**Example:** Using VoiceOver (⌘+F5 to enable VoiceOver, Ctrl+⎇+U to switch to landmarks and arrows to switch mode)
[Trello card](https://trello.com/c/oCRMPDT2)

Make navigation landmarks unique

---

config/application.rb

Turns out none of the log messages we were setting in jobs was making it
through to the sidekiq logs. Just another ActiveJob pain point.

Use Sidekiq logger for ActiveJob

---

lib/bulk_data/cache.rb
spec/lib/bulk_data/cache_spec.rb

I'm not sure how but we ended up in a situation on staging where the
created key was set but the cache entry was not. This causes the app to
fall into a loop where it will keep trying to run the job to populate
the cache and this job won't do anything because it thinks the cache is
populated.

BulkData resilient to time existing but key not

---

config/application.rb
config/environments/development.rb
config/environments/production.rb

Sorry! https://github.com/alphagov/content-publisher/pull/1533 wasn't such a good idea.
It turns out that setting the active_job.logger to use Sidekiq was not
great for the test environment as all log entries were output to STDOUT.
This remedies this by setting the Sidekiq logger only in the production
and development environments, which allows the test environment to
continue to use the Rails default.
I initially tried to do this by changing the test environment file and
leaving dev and prod to use application.rb but this was harder to get
working since I'd have needed to initialise a new logger for this as the
Rails one had not yet been created.

Quieten down Sidekiq for tests

---

app/jobs/populate_bulk_data_job.rb
lib/bulk_data/government_repository.rb
spec/jobs/populate_bulk_data_job_spec.rb

Trello: https://trello.com/c/TQ6GPOHU/1228-spike-into-loading-governments-from-publishing-api
I learnt today that the Publishing API can take a shockingly long amount of time to return data from the editions endpoint. See:
To handle these situations a bit better this adds further logging in for when an error occurs and increases the timeout massively. Hopefully I can have a chat with Platform Health to see if they can look into this as it's very strange that it's taking quite so long.

Yet more resilience on BulkData

---

app/interactors/unwithdraw/unwithdraw_interactor.rb
app/models/document_topics.rb
app/services/delete_draft_service.rb
app/services/preview_service.rb
app/services/preview_service/payload.rb
app/services/publish_service.rb
app/services/remove_service.rb
app/services/resync_service.rb
app/services/withdraw_service.rb
lib/bulk_data/government_repository.rb
lib/contacts.rb
lib/linkables.rb
lib/organisations.rb
lib/requirements/path_checker.rb
lib/topic_index.rb
lib/whitehall_importer/clear_linkset_links.rb
spec/services/resync_service_spec.rb
spec/spec_helper.rb
spec/support/topics_helper.rb

`publishing_api` and `publishing_api_v2` were combined in version 63.1.0 of `gds-api-adapters`, so all references to publishing_api_v2 have been removed.

Remove use of publishing_api_v2

---

app/models/whitehall_import.rb
db/migrate/20191213094311_add_document_ref_to_whitehall_imports.rb
db/schema.rb
lib/tasks/import.rake
lib/whitehall_importer.rb
spec/factories/whitehall_import_factory.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer_spec.rb

Currently the [WhitehallImport](https://github.com/alphagov/content-publisher/blob/fb45dd1ff913e9ffed8ab59ed4799be033f6eb59/app/models/whitehall_import.rb) has 3 statuses (importing, completed and failed) these are now not sufficient for the amount of things that can happen.
Below is the full list of import statuses implemented in this PR:
- importing -> doing the import process
- imported -> importing is complete
- import_aborted -> an AbortImportError is raised during import
- import_failed -> an unexpected error is raised during import
- syncing -> syncing the data with GOV.UK
- sync_failed -> an unexpected error is raised during syncing
- completed -> everything was successful
Related PR (separates out the migration which is also used by …

Add more import statuses

---

docs/adr/0006-tagging-governments.md
docs/adr/0014-political-and-government-tagging.md
docs/adr/00XX-political-and-government-tagging.md

This is to supersede the previous ADR that explained our decision to not
implement this tagging.
[Rendered version](https://github.com/alphagov/content-publisher/blob/government-rfc/docs/adr/00XX-political-and-government-tagging.md)

Add ADR to record government and political tagging decision

---

spec/models/document_topics_spec.rb

The convention in Content Publisher is to use the `have_been_requested` matcher rather
than the assertions in gds-api-adapters.

Update topic tests to use `have_been_requested`

---

app/models/edition.rb
app/services/assign_edition_status_service.rb
app/services/edit_edition_service.rb
app/services/publish_service.rb
app/services/scheduled_publishing_failed_service.rb
db/migrate/20191220080147_create_edition_editors.rb
db/schema.rb
spec/models/edition_spec.rb
spec/services/assign_edition_status_service_spec.rb
spec/services/edit_edition_service_spec.rb

**As a** User who has edited a Whitehall edition
**I want** to receive a notification when the edition is published
**So that** I can admire my work
Content Publisher has a concept of [editors](https://github.com/alphagov/content-publisher/blob/151f9b447880b8c63a20444624e17c82f74f78dd/app/models/edition.rb#L145-L148) who are people who have either modified content or have changed the state of it. We currently work this out at runtime by determining who created statuses and who created revisions of a particular edition. This approach will no longer work for content that is migrated from Whitehall, as we don't have revisions and statuses, and instead we should turn this into a database association. 
This pull request is for the following changes required by this story:
* Create a new table …

Importing editors

---

db/migrate/20191223091535_populate_edition_editors.rb
db/schema.rb

Trello: https://trello.com/c/cS8R0OFd
Follows on from PR #1547 
Content Publisher has a concept of editors who are people who have either modified content or have changed the state of it. We currently work this out at runtime by determining who created statuses and who created revisions of a particular edition. This approach will no longer work for content that is migrated from Whitehall, as we don't have revisions and statuses, and instead we should turn this into a database association.
Creates a database migration to set the editor associations on existing editions. The migration we should uses as little application code as possible as this can break migrations that run later.

Add migration to populate editors of old editions

---

app/models/edition.rb
spec/features/workflow/publish_spec.rb
spec/features/workflow/publish_without_review_spec.rb
spec/models/edition_spec.rb
spec/services/assign_edition_status_service_spec.rb
spec/services/edit_edition_service_spec.rb

Trello: https://trello.com/c/cS8R0OFd
Follows on from PRs #1547 and #1566
Now that we're populating editors directly and have migrated editors to all be assigned in the database,
the old `editors` method on Edition can be replaced with the renamed has_many :editors association.

Retire the old `editors` method

---

app/models/whitehall_migration.rb
app/models/whitehall_migration/document_import.rb
db/migrate/20191223085531_create_whitehall_migrations.rb
db/migrate/20191223092938_namespace_whitehall_import.rb
db/schema.rb
lib/tasks/import.rake
lib/whitehall_importer.rb
spec/factories/whitehall_migration_document_import_factory.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer_spec.rb

We currently have a model (`WhitehallImport`) that stores the status, content and outcome for an individual document that is imported from Whitehall.  Once we begin importing based on specific document types for a single organisation, we need to also store information about this run.  Therefore the `WhitehallMigration` model has been created to store this information.
The `WhitehallImport` model (which has been namespaced `WhitehallMigration::DocumentImport` to avoid creating many different types of `WhitehallSomething` models), references the WhitehallMigration record (one `WhitehallMigration` will have many `WhitehallMigration::DocumentImport`).
Additionally, the `import:whitehall[document-id]` rake task has been renamed `import:whitehall-document[document-id]` to make it clear this …

Create placeholder rake task for importing documents from Whitehall by organisation and document type

---

app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/images/edit.html.erb
app/views/withdraw/new.html.erb

Using `aria-described-by` we now bind the guidance content to each input so it's being appended to the input description and provide additional information to screen readers' users.
Example for the document title using VoiceOver
[Trello card](https://trello.com/c/LQIMhHs0)

Bind contextual guidance to inputs

---

app/jobs/populate_bulk_data_job.rb
spec/jobs/populate_bulk_data_job_spec.rb

Trello: https://trello.com/c/TQ6GPOHU/1228-spike-into-loading-governments-from-publishing-api
Previously this job would use the default amount of retries which is 5
with 3s between them. This had the effect that it was quite vulnerable
to reporting an error particularly in integration and staging during a
data sync.
Initially I thought we'd not want this to be retrying for more than 15
minutes as we run the job on a 15 minute interval. However I think it's
actually fine for a job to be still retrying for a lot longer after that
so then it only needs to tell us an error after a long time has passed.
Given it's now such a long time it seems reasonable to alert on any
error.

Longer retry cycle for PopulateBulkDataJob

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/edition_history.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb

Trello: https://trello.com/c/cS8R0OFd
Follows on from PRs:  #1547 #1566 and #1567 
We need to import editors in as part of a Whitehall import. Determines all the distinct user ids who are in the revision history of a whitehall edition and assigns them as editors when we create an edition.
Whitehall document: https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/export/document/426794
Running:
```
https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/107464/console
```
creates a document: 
```
#<Document id: 666, content_id: "09568fdb-0497-445b-a84a-d62cf9959b5a", locale: "en", created_at: "2019-09-17 15:33:54", updated_at: "2019-09-18 16:00:01", created_by_id: 48, first_published_at: nil, imported_from: "whitehall">
irb(main):002:0> edition = …
```

Import edition editors

---

app/models/timeline_entry.rb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
lib/whitehall_importer.rb
spec/lib/whitehall_importer_spec.rb

As a publisher
I want to see the history of a document
So that I can see what has changed and why it has changed over time.
We want to indicate when a document was imported into Content Publisher so that
publishers can understand any variations in how the history events are
presented.
[Trello card](https://trello.com/c/5Rfe68rk/1279-create-timeline-entry-for-when-its-imported)
_Tested in integration:_

Create timeline entry for when document is imported

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_secondary-navigation.scss
app/views/components/_secondary_navigation.html.erb
app/views/components/docs/secondary_navigation.yml

Because of the high number of history entries that some documents have we need to paginate the history page. This involves splitting the History page away from the Summary page and replace the current tabs component with a secondary navigation component.
This implementation follows the visual appearance of [sub-navigation component from MoJ](https://moj-design-system.herokuapp.com/components/sub-navigation). 
Tested in `app/views/documents/show.html.erb`
```
<%= render "components/secondary_navigation", {
aria_label: "Document",
items: [
{
label: "Document summary",
href: "/document-summary",
current: true,
data_attributes: {
gtm: "summary-tab"
}
},
{
label: "Document history",
href: "/document-history",
data_attributes: {
gtm: "history-tab"
}
}
]
} %>
<%= …
```

Add secondary navigation component

---

db/migrate/20191223091535_populate_edition_editors.rb

Fixes the populate edition migration so that it uses a mocked version of the Edition code,
and is therefore future proofed against any changes to the Edition model.

Fix migration so that it runs with future app code

---

lib/whitehall_importer/create_edition.rb

Removes and possible nil values from the editors history as we can't guarantee that every
user "whodunnit" in the edition history of a Whitehall import will actually be imported.

Do not try and import a "nil" editor

---

config/locales/en/access_limit/edit.yml
config/locales/en/contact_embed/new.yml
config/locales/en/documents/edit.yml
config/locales/en/documents/show.yml
config/locales/en/file_attachments/preview_pending.yml
config/locales/en/remove/remove.yml
config/locales/en/tags/edit.yml
config/locales/en/topics/edit.yml

We have a preference for presenting users with curly quotes rather than
straight ones as they are more semantic visually. The vast majority of
our translation files use curly quotes but a few stray ones are
lingering around. This resolves that.

Replace straight quotes with curly ones in locale files

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/create_revision.rb
lib/whitehall_importer/edition_history.rb
lib/whitehall_importer/import.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb
spec/lib/whitehall_importer/import_spec.rb

We were missing some data when importing a document from Whitehall to Content Publisher.
This PR adds the following:
- Imported editions are marked with a `backdated_to` timestamp where appropriate (when the edition was backdated in Whitehall, determined by comparing the first published timestamp with the time of the first publish event)
- Import the `first_published_at` date for the document (taken from the first publish event on the first edition of a document; cannot be overridden by backdating)
- Editions have a `last_edited_at` timestamp (most recent edit event from the Whitehall `revision_history`)
- Imported editions are not marked as `revision_synced` (i.e. not marked as synced with Publishing API, which has not been completed at the import stage)
Trello card: …

Add missing data lost during import from Whitehall to Content Publisher

---

app/controllers/schedule_controller.rb
app/interactors/schedule/create_interactor.rb
app/interactors/schedule/update_interactor.rb
spec/factories/edition_factory.rb
spec/interactors/schedule/create_interactor_spec.rb
spec/interactors/schedule/update_interactor_spec.rb

This resolves an inconsistency we had where API errors are handled in ScheduleController rather than the corresponding interactor. This also adds in tests for the interactors.

Consistently handle API errors in ScheduleController

---

spec/lib/requirements/backdate_checker_spec.rb

Test was failing because 01/01/2020 is no longer a date in the future.

Fix backdate checker spec

---

config/initializers/bulk_data_rack_middleware.rb
lib/bulk_data/cache.rb

This should help anyone who's confused when changes to the class don't
auto-reload in development.

Add explanation about 'requiring' BulkData::Cache

---

spec/features/editing_content/edit_edition_publishing_api_down_spec.rb
spec/features/editing_content/insert_contact_embed_publishing_api_down_no_js_spec.rb
spec/features/editing_content/insert_contact_embed_publishing_api_down_spec.rb
spec/features/editing_content_settings/edit_access_limit_publishing_api_down_spec.rb
spec/features/editing_tags/edit_tags_publishing_api_down_spec.rb
spec/features/editing_topics/edit_topics_publishing_api_down_spec.rb
spec/features/finding/index_organisation_filtering_publishing_api_down_spec.rb
spec/features/scheduling/propose_publish_time_and_schedule_spec.rb
spec/features/scheduling/schedule_publishing_api_down_spec.rb
spec/features/scheduling/scheduled_publishing_failed_spec.rb
spec/features/scheduling/scheduled_publishing_spec.rb
spec/features/scheduling/scheduled_publishing_without_review_spec.rb
spec/features/scheduling/unschedule_publishing_api_down_spec.rb
spec/features/scheduling/update_publish_time_publishing_api_down_spec.rb
spec/features/scheduling/update_publish_time_spec.rb
spec/features/workflow/delete_draft_publishing_api_down_spec.rb
spec/features/workflow/preview_publishing_api_down_spec.rb
spec/features/workflow/publish_requirements_publishing_api_down_spec.rb
spec/requests/unwithdraw_spec.rb
spec/requests/withdraw_spec.rb
spec/services/resync_service_spec.rb
spec/services/schedule_service_spec.rb

Fixes warnings for:
```
#publishing_api_isnt_available is deprecated on GdsApi::TestHelpers::PublishingApi and will be removed in a future version. Use #stub_publishing_api_isnt_available instead
#stub_default_publishing_api_put_intent is deprecated on GdsApi::TestHelpers::PublishingApi and will be removed in a future version. Use #stub_any_publishing_api_put_intent instead
.
.
.
```

Fix publishing-api deprecation warnings

---

app/models/whitehall_migration/document_import.rb
db/migrate/20191224093450_remove_not_null_from_document_import.rb
db/migrate/20191224112030_rename_organisation_slug.rb
db/schema.rb
lib/gds_api/whitehall_export.rb
lib/tasks/import.rake
lib/whitehall_importer.rb
spec/factories/whitehall_export/index_document_factory.rb
spec/factories/whitehall_export/index_factory.rb
spec/lib/gds_api/whitehall_export_spec.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer_spec.rb

In #1565, we created a rake task (`import:whitehall_migration`) that takes organisation and document type as arguments, then creates a `WhitehallMigration` model.  The changes here build on that work to:
* get a list of documents to import from Whitehall's export API (and deal with the paginated response from Whitehall)
* allow `WhitehallMigration::DocumentImport` to have a status of 'pending' (i.e. ready to import, but no import has been started yet)
* remove not-null requirement for two fields on `WhitehallMigration::DocumentImport` (since we will not have that data whilst the import is in a pending state)
* create a pending `WhitehallMigration::DocumentImport` for each document due to be imported
* create the `WhitehallMigration` and `WhitehallMigration::DocumentImport` models within a …

Update organisation import rake task to get list of documents from Whitehall

---

app/jobs/application_job.rb
spec/jobs/application_job_spec.rb

This remove the option to run a job exclusively outside of a
transaction, since we don't use this capability and to avoid the
risk of locks being persisted if the app fails. (Also fix the
typo for 'acquired'.)

Always 'run_exclusively' within a transaction

---

app/controllers/review_controller.rb
app/views/documents/show/_submitted_for_review.html.erb
app/views/documents/show/_summary_tab.html.erb
config/locales/en/documents/show.yml
spec/features/workflow/submit_for_2i_spec.rb

For https://trello.com/c/1zOX0xmQ/1285-submit-for-2i-review-banner
This changes the submit for review banner to use the inset prompt component and ensures it persists while a document is in a `submitted_for_review` state.
**Before**
**After**

Change submitted for review banner

---

spec/lib/tasks/import_spec.rb

The class name was missing two characters in the `it` text.

Fix typo in test name

---

app/views/documents/confirm_delete_draft.html.erb

When multiple lines are specified in an I18N YML file - and then rendered via govspeak -
govspeak will automatically generate `<p>` tags.  So, the use of `render_govspeak` should 
be inside a `<div>` tag not a `<p>` tag.  
Fixes an issue introduced in a previous PR.

Fix incorrect govspeak HTML generation issue

---

spec/requests/review_spec.rb

This snuck in as something got merged
(https://github.com/alphagov/content-publisher/pull/1609) which caused a
breaking change to
https://github.com/alphagov/content-publisher/pull/1598 which was merged
but with a stale test build, this is due to the tests not running
everytime master is updated.

Fix locale bug

---

db/migrate/20200107151448_cascade_edition_editor_deletion.rb
db/schema.rb
spec/factories/edition_factory.rb

The Content Publisher integration data sync has been broken since we used edition editors. These are not able to be automatically deleted as part of the removal of access limited content.
This PR first modifies the default factory so the problem was exposed in the unit tests and then applies a migration to fix the issue.
This is intended to resolve the regular [Sentry S3 asset not found issue](https://sentry.io/organizations/govuk/issues/1407796268/?referrer=slack) which I believe is because Postgres and S3 are out of sync.

Fix DB blocking data sanitisation process

---

app/models/whitehall_migration/asset_import.rb
app/models/whitehall_migration/document_import.rb
db/migrate/20191230093500_create_whitehall_imported_assets.rb
db/schema.rb
lib/whitehall_importer.rb
lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/create_file_attachment_revision.rb
lib/whitehall_importer/create_image_revision.rb
lib/whitehall_importer/create_revision.rb
lib/whitehall_importer/import.rb
lib/whitehall_importer/migrate_assets.rb
spec/factories/whitehall_export/file_attachment_factory.rb
spec/factories/whitehall_export/image_factory.rb
spec/factories/whitehall_migration_asset_import_factory.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/create_file_attachment_revision_spec.rb
spec/lib/whitehall_importer/create_image_revision_spec.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/lib/whitehall_importer/import_spec.rb
spec/lib/whitehall_importer/migrate_assets_spec.rb
spec/lib/whitehall_importer_spec.rb
spec/models/whitehall_migration/asset_import_spec.rb
spec/models/whitehall_migration/document_import_spec.rb

This PR has all the code for tidying up a Whitehall document's assets once the document has been imported into Content Publisher. After import, we can run the new `MigrateAssets` service to:
* delete all Whitehall assets (images/file attachments) that only existed on the draft stack
* redirect all 'master' assets (e.g. the 960 size image, rather than its thumbnails) to the new master version on Content Publisher, if the Whitehall assets were on the live stack
* delete all variants of Whitehall file attachments (whether on live or draft stack), since they'll no longer appear anywhere
* redirect all variants of Whitehall images to the new master image on Content Publisher, since the old images may be hotlinked from elsewhere
* log any assets that fail to migrate, and fail the sync step at …

Redirect Whitehall images and attachments

---

spec/features/editing_content/insert_inline_image_no_js_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_requirements_spec.rb

This flag is only necessary to support lead image and some image
management functions.

Remove redundant uses of the 'images' flag

---

spec/requests/editions_spec.rb

Trello: https://trello.com/c/wgkfOJsE/1283-improve-consistency-in-content-publisher-tests
This follows on the test strategy introduced in #1590. Towards this I've done a bunch of writing of request tests and deleting of feature tests. Rather than do one large PR I thought it was best to separate into distinct PR's that are easier to review and thought I'd start with one that covers a few.
This PR does some refactoring of the edition request tests we already had to make them consistent with other request tests.

Change edition request tests to match consistent strategy

---

app/models/document_type.rb
config/document_types.yml
spec/factories/document_type_factory.rb

https://trello.com/c/NLAjn71N/1101-spike-and-test-approach-for-format-field-definitions
Previously we had to manually specify that topics were supported on
every format, which is unnecesary since they always are. This makes
having topics the default for a format, but inverts this for (most)
tests, in order to avoid having extra API stubs.
It seems reasonable to keep the 'topics' flag, since it represents a
'unit feature' of a format, even though it's technically mandatory.

Add defaults for 'topics' feature on formats

---

spec/features/scheduling/update_publish_time_spec.rb

This change removes the warning below when the update_publish_time_spec.rb test file is run.

Use non-deprecated put-intent stub

---

app/jobs/whitehall_document_import_job.rb
app/models/whitehall_migration.rb
app/models/whitehall_migration/document_import.rb
lib/tasks/import.rake
lib/whitehall_importer.rb
spec/factories/whitehall_migration_factory.rb
spec/jobs/whitehall_document_import_job_spec.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer_spec.rb
spec/models/whitehall_migration_spec.rb

This allows us to queue a series of jobs to import multiple documents from Whitehall based on an organisation slug and document type.
Previously importing was being done by running a rake task (`whitehall_document`) that imported a single document.  This takes that logic and executes the same process inside a Sidekiq job.
A `WhitehallMigration` is created when the process begins, and is also marked as completed (by means of a `end_time`) when the import has finished.
Trello - https://trello.com/c/HxOpHnf9/1272-queue-a-job-to-import-document-from-whitehall

Enqueue document import

---

db/migrate/20200114140323_remove_migration_start_time.rb
db/schema.rb
lib/whitehall_importer.rb
spec/factories/whitehall_migration_factory.rb
spec/lib/whitehall_importer_spec.rb

It was surplus to requirements and also doesn't fit in with rails convention. We'll be using the `created_at` column from here on out. This also changes any references to the `start_time` column.
Trello - https://trello.com/c/HxOpHnf9/1272-queue-a-job-to-import-document-from-whitehall
Related - https://github.com/alphagov/content-publisher/pull/1615

Remove the start_time column from Whitehall Migrations

---

app/models/whitehall_migration.rb
db/migrate/20200114163932_rename_whitehall_migrations_end_time.rb
db/schema.rb
spec/models/whitehall_migration_spec.rb

This makes it more in line with rails customs. It also renames the references to the column.
Trello - https://trello.com/c/HxOpHnf9/1272-queue-a-job-to-import-document-from-whitehall

Rename the Whitehall Migrations end_time column

---

db/migrate/20200109094012_add_integrity_check_problems_to_whitehall_document_migration.rb
db/schema.rb
lib/whitehall_importer.rb
lib/whitehall_importer/import.rb
lib/whitehall_importer/integrity_check_error.rb
lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/import_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb
spec/lib/whitehall_importer_spec.rb

Trello: https://trello.com/c/A9GjvYyp
The integrity check added in PR #1602 has highlighted some discrepancies between how some of the fields are handled. 
For example, if the image caption is blank, it's recorded in publishing-api as `nil`, however, the import process tries to replace this value with an empty string. Also, some fields are being sent to publishing-api with an extra space or newline at the end of them.
All of these discrepancies will cause the integrity check and therefore the import to fail. 
Debugging integrity check failures is difficult. As the integrity check runs within a transaction, when the import fails and the transaction rolls back, all of the documents, editions and revisions the import created are obliterated, which means that the proposed payload that we …

Store integrity check failures

---

docs/adr/0004-editing-microcopy.md

This was originally an experiment, but has been largely successful in
its objective to separate text code in a way that supports editing by
a Content Designer.

Mark ADR on Editing Microcopy as 'accepted'

---

app/views/documents/history.html.erb
app/views/documents/index.html.erb
config/locales/en/documents/history.yml
spec/features/finding/index_pagination_spec.rb
spec/features/history/pagination_spec.rb

The page information was missed on the first pass of implementing the pagination
feature, I believe because the prototype was out of date. Now the
pagination links display information around what page is currently being
displayed.
This comes after a product review from @Tobiogunsina.
Trello:
https://trello.com/c/TsRTLbiW/1276-move-document-history-from-tab-to-secondary-navigation-and-add-pagination

Add page info to pagination links

---

app/models/supertype.rb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
config/locales/en/supertypes.yml
config/supertypes.yml
spec/features/formats/consultation_spec.rb
spec/features/formats/detailed_guide_spec.rb
spec/features/formats/news_story_spec.rb
spec/features/formats/not_sure_spec.rb
spec/features/formats/press_release_spec.rb
spec/features/workflow/create_document_spec.rb
spec/models/supertype_spec.rb
spec/requests/new_document_spec.rb

Trello - https://trello.com/c/hAJkXW1T/1325-use-i18n-to-manage-copy-for-each-supertype
This moves the copy from a yaml file to be internationalised. This is more in line with how i18n is meant to be used and will make configuration easier once we start iterating the supertype model.

Use I18n for supertypes

---

app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/topics/edit.html.erb

The autocomplete component (being an enhanced input), as any other form element rely on `govuk-form-group` class to generate consistent spacing across elements. This class assumes the form elements are at a sibling level (and not nested in unnecessary div wrappers) to style the last element without spacing. This updates the way we apply the `app-js-only` class to this instance of the component by applying the class to the component based on a `jsonly` flag.
[Trello card](https://trello.com/c/rO5ssI8S)

Allow autocomplete component to be shown only when JavaScript is enabled

---

spec/lib/whitehall_importer/create_edition_spec.rb

These tests were asserting that an array contained the expected items
and was in a certain order. This ordering is non-deterministic so we're
at risk of these causing failed builds as was seen in
https://ci.integration.publishing.service.gov.uk/job/content-publisher/job/modal-tests/4/console
The verify that these tests were actually flakey and that this fixed the
issue I ran these both 5000 times (I know that seems rather high, the
issue didn't seem to reveal itself on a 500 test run). The results were
as follows:
Before:
Finished in 5 minutes 51 seconds (files took 5.4 seconds to load)
10026 examples, 8294 failures
After:
Finished in 6 minutes 25 seconds (files took 5.73 seconds to load)
10026 examples, 0 failures

Fix flakey array assertions

---

app/assets/javascripts/modal/modal-fetch.js
app/assets/javascripts/modal/modal-workflow.js
package.json
spec/javascripts/components/markdown-editor-spec.js
spec/javascripts/components/url-preview-spec.js
spec/javascripts/helpers/fetch-mock.js
spec/javascripts/helpers/markdown-editor.js
spec/javascripts/helpers/modal-dialogue.js
spec/javascripts/modal/modal-editor-spec.js
spec/javascripts/modal/modal-fetch-spec.js
spec/javascripts/modal/modal-workflow-spec.js
spec/javascripts/modules/contact-embed-modal-spec.js
spec/javascripts/modules/inline-attachment-modal-spec.js
spec/javascripts/modules/inline-image-modal-spec.js
spec/javascripts/modules/video-embed-modal-spec.js
yarn.lock

Trello: https://trello.com/c/wgkfOJsE/1283-improve-consistency-in-content-publisher-tests
This card ties into the [Contact Embed PR](https://github.com/alphagov/content-publisher/pull/1626), where Ben pointed out that feature tests were the only thing testing some modal code and a [wall of pain card](https://trello.com/c/GVp3CoMH/1030-our-modal-scripts-dont-have-tests) that Alex raised back in June following problems with the modal and discovering there wasn't prior art to testing them.
In these tests I wrestled a couple of things I wasn't too sure about: on one side what the convention is for the naming of Jasmine unit tests (for example `describe("Class.method")`) and wondering whether similar modal code should be tested with shared helpers or not.
Easiest way to review this would be to …

Add JS tests for modals

---

app/helpers/application_helper.rb
app/views/documents/index.html.erb
app/views/layouts/application.html.erb
app/views/new_document/choose_document_type.html.erb

Follow up on https://github.com/alphagov/content-publisher/pull/1642.
Document type description may contain links which means the associated content needs to be rendered as govspeak to be styled properly.

Fix govspeak render in document type description

---

app/views/topics/edit.html.erb

This aligns the components used within the topics form to be each wrapped in a `govuk-form-group` container. By doing so the miller-columns component will be the last instance of a `govuk-form-group` (instead of the search autocomplete). This will make the spacing between these components consistent.
This is the second attempt at [Trello card](https://trello.com/c/rO5ssI8S) while #1662 did cover it entirely.

Wrap miller-columns element in a govuk-form-group

---

app/assets/javascripts/modules/contact-embed-modal.js
app/assets/javascripts/modules/inline-attachment-modal.js
app/assets/javascripts/modules/inline-image-modal.js
spec/features/editing_content/insert_contact_embed_spec.rb
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb

This fixes a test issue where the use of 'match' was mis-interpreting
the hyphen characters in a UUID as regex ranges, leading to a
Regexp error:
empty range in char class ...
Fixing this then exposed a timing issue, where the JS code had not yet
inserted the expected (contact) snippet into the body field. This adds
missing expectations to ensure we wait for the modal to close before
checking for the inserted snippet, as well as changing the modal
workflows to only close the modal when all its operations are finished.

Fix flakey modal insertion

---

spec/features/editing_content_settings/history_mode_spec.rb
spec/requests/history_mode_spec.rb

Trello: https://trello.com/c/wgkfOJsE/1283-improve-consistency-in-content-publisher-tests
This follows on the test strategy introduced in #1590. Towards this I've done a bunch of writing of request tests and deleting of feature tests. Rather than do one large PR I thought it was best to separate into distinct PR's that are easier to review and thought I'd start with one that covers a few.
This PR does some minor refactoring of the history mode request tests to make them consistent with the other request tests now that conventions have emerged.

Refactor history mode request tests

---

lib/whitehall_importer/create_revision.rb
spec/factories/whitehall_migration_factory.rb
spec/lib/whitehall_importer/create_revision_spec.rb

We now want to import editions which have multiple lead organisations
but use the 'primary' (lowest numerical lead_ordering) to assign to the
edition.
A check is already done [here](https://github.com/alphagov/whitehall/blob/master/app/controllers/admin/export/document_controller.rb#L45) to decipher if the lead organisation passed in matches the primary lead org of the latest edition, this makes sure we are only importing documents which the most current version is owned by the organisation queried in whitehall.
Trello:
https://trello.com/c/7t6Nv8YT/1321-import-editions-with-multiple-lead-organisations

Multiple lead orgs

---

db/seeds.rb

There is an assumption that documents within Content Publisher - are always associated with either:
- a valid user - someone who has a signon account and has activated that account by logging into a system; or 
- are un-assigned - where `created_by_id` is nil, in the case of Whitehall documents that are associated with 'system' users.  
However, this assumption is currently not implemented in the test suite, where a seed 'test' user is created without a UID and subsequently widely used in document creation and maintenance.
This change re-enforces that assumption within the test suite for consistency.
**Please note** If accepted all developers on Content Publisher will need to re-create their Test database following merge...
```
govuk-docker-run rails db:reset RAILS_ENV=test
```

Add UID to test user

---

lib/whitehall_importer/import.rb
spec/lib/whitehall_importer/import_spec.rb

Trello: https://trello.com/c/NhFom5Rj
- As a GOV.UK developer migrating documents from Whitehall
- I want have edits assigned to the correct users
- So that the document edit history is correct
On importing some documents from Whitehall, we get the following error:
```bash 
13:49:44 Import failed
13:49:44 Error: #<ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_edition_editors_on_edition_id_and_user_id"
13:49:44 DETAIL:  Key (edition_id, user_id)=(3253, 157) already exists.
```
This happens when the assigned user for that incoming document does not have a signon account, i.e they are not a real person, but a system or maintenance user instead.  Users of this type will not have an associated uid.
The current behaviour is to …

Ignore users without a uid when importing users

---

spec/models/supertype_spec.rb

This introduces a bang when calling internationalization in one of our test. This will stop that test from silently failing if a translation doesn't exist. See coomment linked below for introduction of the issue.
https://github.com/alphagov/content-publisher/pull/1658#discussion_r368465923

Add bang to internationalisation on supertypes

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/edition_history.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb

Whitehall stores document history in three places.  This PR addresses the import of one of these (revision history, i.e. changes in state) into Content Publisher.
Trello card: https://trello.com/c/PITc94le

Import Whitehall revision history (History tab in Whitehall) to Content Publisher

---

db/migrate/20200122110833_add_body_to_timeline_entry_whitehall_imported_entries.rb
db/schema.rb

- Required for upcoming implementation of: https://trello.com/c/o8PhjdUc/1312-map-whitehall-fact-check-requests-fact-checking-tab-in-whitehall-to-content-publisher-timeline-entries-on-import and https://trello.com/c/tNsWXZZj/1314-map-whitehall-editorial-remarks-notes-tab-in-whitehall-to-content-publisher-timeline-entries-on-import
- Will allow us to store the notes body content as well as the fact check data
Co-authored-by: Graham Lewis <graham.lewis@digital.cabinet-office.gov.uk>

Add body to timeline_entry_whitehall_imported_entries

---

package.json

In the past, we added a few vendored files to the ignore list of standard linting configuration. These files don't exist anymore by we forgot to remove them from the list.

Remove ignored files that no longer exist

---

app/controllers/content_controller.rb
app/controllers/documents_controller.rb
app/controllers/editions_controller.rb
app/interactors/content/update_interactor.rb
app/interactors/editions/destroy_interactor.rb
app/views/content/edit.html.erb
app/views/content/edit/_change_notes.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/editions/confirm_delete_draft.html.erb
config/locales/en/content/edit.yml
config/locales/en/editions/confirm_delete_draft.yml
config/routes.rb
spec/features/editing_content/url_preview_spec.rb
spec/features/editing_content_settings/enforce_access_limit_spec.rb
spec/features/workflow/edition_spec.rb
spec/interactors/content/update_interactor_spec.rb

Trello - https://trello.com/c/ZTRjP9eT/1099-break-up-the-actions-in-the-documentscontroller
The Documents controller has been largely unchanged since we introduced the concept of editions. This moves functionality from the documents controller into the editions controller and a newly created content controller to better fit with our data models. It also adjusts the copy and tests accordingly.

Controller Reshuffle

---

config/locales/en/documents/history.yml

The `first_created` translation was missed in #1644.

Add missing translation for Whitehall imported history

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/edition_history.rb
spec/lib/whitehall_importer/create_edition_spec.rb

Whitehall has a change of state to 'superseded' which happens when an existing published edition is replaced with a new published edition. The existing one is given a new state of superseded, however this is not to be shown to users.
We should therefore skip any history entries that have a state change to superseded, as detailed in https://docs.google.com/spreadsheets/d/1I7TbA9glyFyhyWq5wQJAGykkXFwOJjyd--kLCycXbSY/edit#gid=0.
This fix allows us to import 53 of NDA's documents which are currently failing.
Trello: https://trello.com/c/3AV7mZTG

Ignore superseded revision history state changes from Whitehall

---

app/helpers/document_type_helper.rb
app/models/document_type.rb
app/views/content/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_tags.html.erb
app/views/new_document/choose_document_type.html.erb
app/views/tags/tags/_multi_tag_input.html.erb
app/views/tags/tags/_single_tag_input.html.erb
config/document_types.yml
config/locales/en/document_types.yml
spec/factories/document_type_factory.rb
spec/factories/tag_field_factory.rb
spec/features/editing_tags/edit_tags_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/document_type_helper_spec.rb
spec/helpers/edition_url_helper_spec.rb
spec/lib/requirements/tag_checker_spec.rb
spec/requests/access_limit_spec.rb
spec/requests/tags_spec.rb
spec/services/preview_draft_edition_service/payload_spec.rb
spec/views/documents/show.html.erb_spec.rb
spec/views/tags/edit.html.erb_spec.rb

This PR rips out copy from `config/document_types.yml` and into a new `config/locales/en/document_types.yml`, so that we can internationalise Content Publisher in the future. `config/document_types.yml` is now solely about the configuration of each document type, which would apply to any language.
The [Trello card](https://trello.com/c/AuzTdQVt/1100-use-i18n-to-manage-copy-for-each-document-type) makes it quite clear that we want to avoid duplicating text/config between similar document types, and proposes a `document_types.default` namespace. The only duplication I've come across so far is in the tagging of the `news_story` and `press_release` document types, whose configurations remain under `config/document_types.yml`; I have used standard YAML inheritance to avoid duplicating the …

Use I18n to manage copy for each document type

---

app/controllers/editions_controller.rb
app/controllers/new_document_controller.rb
app/helpers/actions_helper.rb
app/views/content/edit.html.erb
app/views/documents/show/_contents.html.erb
app/views/documents/show/_requirements.html.erb
app/views/editions/confirm_delete_draft.html.erb
config/routes.rb
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb
spec/features/editing_content_settings/enforce_access_limit_spec.rb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/upload_image_spec.rb
spec/requests/content_spec.rb
spec/requests/documents_spec.rb
spec/requests/editions_spec.rb
spec/requests/new_document_spec.rb

https://github.com/alphagov/content-publisher/pull/1681 introduced some inconsistency with our routes. This fixes that.
The above pull request made it so that we had the same paths going to different controllers based on the request method. This makes paths consistent with controllers and updates the tests accordingly.

Iterate our route config after a controller reshuffle

---

app/controllers/withdraw_controller.rb
app/interactors/withdraw/create_interactor.rb
app/views/layouts/application.html.erb
spec/requests/unwithdraw_spec.rb
spec/requests/withdraw_spec.rb

Trello: https://trello.com/c/wgkfOJsE/1283-improve-consistency-in-content-publisher-tests
This follows on the test strategy introduced in #1590. Towards this I've done a bunch of writing of request tests and deleting of feature tests. Rather than do one large PR I thought it was best to separate into distinct PR's that are easier to review and thought I'd start with one that covers a few.
This does some refactoring of the existing withdraw and unwithdraw request tests to make them consistent with the conventions of request tests.
They also catch a couple of issues. It allows to return a 503 on an API error rather than redirect for a withdraw that hits a Publishing API error (this required resolving a hash keys issue on the layout) and fixes that the assert edition status on the …

Consistent withdraw request tests

---

db/migrate/20200124142150_rename_body_on_timeline_entry_whitehall_imported_entries_to_contents.rb
db/schema.rb

Trello: https://trello.com/c/o8PhjdUc/1312-map-whitehall-editorial-remarks-notes-tab-in-whitehall-and-fact-check-requests-fact-checking-tab-in-whitehall-to-content-publish
Makes column name consistent with existing naming convention, e.g. 'content_revisions'

Rename 'body' to 'contents' on TimelineEntry::WhitehallImportedEntry

---

lib/whitehall_importer.rb
lib/whitehall_importer/import.rb
spec/lib/whitehall_importer/import_spec.rb
spec/lib/whitehall_importer_spec.rb

For https://trello.com/c/g0GfY8PF/1364-fix-import-script
Our problem is that we mutate the document_import object during the
import, which conflicts with our 'all or nothing' strategy for
transactions. What happens is that we create a document and various
other models in the database and then, when a transaction fails, roll
them back. However as we set the document attribute on a document_import
the rolled back model still exists in memory and when we save the
document_import it tries to save the document model meaning we at best
get an exception and at worst get a half created document.
An approach to resolve this is to reload the document_import object at
the point of the exception occurring.
A different, more complex context based approach, is considered in …

Ensure document creation is rolled back when an import exception occurs

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

When presenting a Whitehall image to Publishing API, empty strings in the caption are replaced with nil values.
https://github.com/alphagov/whitehall/blob/9396ec5a69750bd41c106fa7517d8c3476988d31/app/presenters/lead_image_presenter_helper.rb#L26-L31
Content Publisher does not do this.  Therefore, we need to ignore any mismatch failures on this field for that reason only.
This affects six of NDA's news articles.
Trello card: https://trello.com/c/3AV7mZTG

Do not report integrity failure for caption nil/empty mismatch

---

app/views/documents/show/_withdrawn_notice.html.erb
app/views/file_attachments/show.html.erb
app/views/images/_image.html.erb
app/views/images/edit.html.erb
app/views/new_document/choose_supertype.html.erb

Hint text is only defined for some supertypes, not others.
An attempt was made to only display hint text if it is not
'nil', however it is never 'nil' because the fallback value
is a string 'translation missing: en.supertypes.not-sure.hint'
This commit does an explicit check using 'exists?' and
removes a redundant 'hint' var that is only used in the
ternary.
Fixes this bug:

Fix 'translation missing' errors for supertype selection

---

app/models/whitehall_migration/document_import.rb
lib/whitehall_importer.rb
spec/factories/whitehall_migration_document_import_factory.rb
spec/lib/whitehall_importer_spec.rb

For https://trello.com/c/Y3hKP4W9/1366-handle-retrying-whitehall-import-job
This removes 'importing' and 'syncing' states from
WhitehallMigration::DocumentImport as they don't provide much value. This also
simplify our approach to retrying the import job, which will be implemented in
a future commit.

Remove syncing state from Document Import

---

lib/edition_assertions.rb

https://trello.com/c/85gkiigT/1397-enforce-which-features-a-user-can-and-cannot-access-per-document-type-lead-images
This was left over from 79f0fd964.

Remove redundant AccessError subclass

---

spec/features/editing_content/edit_edition_spec.rb
spec/features/editing_content_settings/enforce_access_limit_spec.rb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/features/editing_images/choose_lead_image_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/delete_lead_image_spec.rb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/remove_lead_image_spec.rb
spec/features/editing_images/upload_image_spec.rb
spec/features/editing_tags/edit_tags_spec.rb
spec/features/formats/news_article_spec.rb
spec/features/workflow/create_document_spec.rb

Previously we added these steps to many features as a way to check the
tangential outcomes of a user action, including the document state and API
requests to Publishing API and Asset Manager, which arise from the
PreviewDraftEditionService. Checking API requests in features was pragmatic
when we had limited tests at lower levels, and the idea was that each
feature would cover its specific part of the Publishing API payload. Since
then, we've introduced the
'failsafe preview' feature, such that its far less important or
'optional' that a request is made, since a fallback exists. The checker for
draft user state was added with a similar mindset, to ensure that the
edition state is (re)set …

Remove checks for 'put_content' in features

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

News articles with no user uploaded image were being rejected when importing from Whitehall.  This was because the integrity check was failing.
In the case of no image being specified for a news article, we fall back to the organisation default, or failing that to a placeholder.
Whitehall submits the default organisation or placeholder image to Publishing API as part of the payload, with an alt_text of "placeholder": https://github.com/alphagov/whitehall/blob/9396ec5a69750bd41c106fa7517d8c3476988d31/app/presenters/lead_image_presenter_helper.rb#L18-L24
Content Publisher does not do this.  Instead no images are sent to Publishing API and the image is determined by the frontend application: https://github.com/alphagov/government-frontend/blob/2ef6483d9fb96baf5af0294a07cbddb9c0e4d420/app/pres …

Ignore missing images on import when organisation default is used

---

spec/features/formats/news_article_spec.rb

- Added 'fill_in "revision[contents][body]"' to make this a valid doc
- Checks are made against Document.last, rather than Document.first,
as this makes more sense
- Avoid stubbing role appointment links, as these aren't required for
a minimum viable document
- Choose only a primary publishing organisation tag, as the others
aren't required for a minimum viable document
- Move 'reset_executed_requests!' call to later in the test, so that
it is more obvious why it is needed
- Assert that the 'Publish' link exists. This isn't strictly necessary
but is a peace-of-mind quick check that our UI is showing that the
document is publishable when it is publishable.
...and then simplified further:
- We only care that a user can create a document from scratch and take
the minimal steps necessary to …

Stripped 'news_article_spec.rb' down to its bare essentials

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

The 'alert_with_items' and 'confirmation' flash types are no longer
used, so we can remove support for them.
https://github.com/alphagov/content-publisher/pull/1611
https://github.com/alphagov/content-publisher/commit/6a3ce564157e8d06a497e149f547781daf60cdf4

Remove redundant flash types / rendering

---

README.md
docs/user-permissions.md

Rather than explaining the pre_release_features permission over Slack I
thought it'd be useful to have it documented, and then I thought if I'm
doing one permission I should probably document them all.

Document user permissions

---

lib/whitehall_importer/create_edition.rb
spec/factories/whitehall_export/edition_factory.rb
spec/factories/whitehall_export/editorial_remark_event.rb
spec/factories/whitehall_export/fact_check_event_factory.rb
spec/factories/whitehall_export/revision_history_event.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb
spec/lib/whitehall_importer/import_spec.rb

Whitehall stores document history in three places. This PR addresses the import of two of these into Content Publisher:
-  Editorial remarks (Notes tab in Whitehall) 
- Fact check requests (Fact checking tab in Whitehall)
Trello: https://trello.com/c/o8PhjdUc/1312-map-whitehall-editorial-remarks-notes-tab-in-whitehall-and-fact-check-requests-fact-checking-tab-in-whitehall-to-content-publish

Whitehall notes and fact check - import

---

db/migrate/20200130090021_add_whitehall_migration_subtypes.rb
db/schema.rb
lib/gds_api/whitehall_export.rb
lib/tasks/import.rake
lib/whitehall_importer.rb
spec/lib/gds_api/whitehall_export_spec.rb
spec/lib/tasks/import_spec.rb
spec/lib/whitehall_importer_spec.rb

We may wish to import documents of a single subtype (e.g. only news stories and press releases for the news article type) from Whitehall, since Content Publisher does not yet support the other subtypes of news article.
An optional subtype parameter has been added to the document index endpoint in Whitehall (https://github.com/alphagov/whitehall/pull/5303), so these are the corresponding changes in Content Publisher.
Trello card: https://trello.com/c/dmS7BYoG

Allow import from Whitehall to be filtered by document subtype

---

config/environments/test.rb

This is a shameless tweak to improve performance when running tests
in Docker, which is sensitive to heavy disk IO. I'm pretty sure we
don't have a use case for info-level logs in tests. I'm also open to
making this an environment variable, which might be a more reusable
approach across some of the other apps. I'm seeing about a 30-40s
improvement in test runtime on my machine.
Before
govuk-docker-run bundle exec rspec  1.59s user 0.27s system 0% cpu 3:44.85 total
After
govuk-docker-run bundle exec rspec  1.55s user 0.27s system 0% cpu 3:02.77 total

Increase test log level to 'warn'

---

app/views/documents/history/_whitehall_entry.html.erb
spec/views/documents/history/_whitehall_entry.html.erb_spec.rb

Whitehall stores document history in three places. This PR addresses the display of two of these into Content Publisher:
- Editorial remarks (Notes tab in Whitehall)
- Fact check requests (Fact checking tab in Whitehall)
For fact checks, there are two things we need to maintain: a fact check request (i.e. a request sent to a department or individual) and a fact check response (i.e. the response coming back from the recipient(s) of the original request).
In all cases, Whitehall entries with content are highlighted to the user, entries without content are not.
**Before...**
**After...**
Trello: https://trello.com/c/tNsWXZZj/1314-user-interface-display-for-imported-whitehall-editorial-remarks-notes-tab-in-whitehall-and-fact-check-requests-fact-checking-tab

Whitehall notes and fact check - display

---

config/schemas/document_type.json

This should make it easier to track down a typo in the config, which
would otherwise lead to less obvious failures elsewhere in the tests.

Restrict content fields to those that exist

---

lib/whitehall_importer/create_edition.rb
spec/lib/whitehall_importer/create_edition_spec.rb

The 'user_ids' hash is constructed by mapping a Whitehall user id to the same user's id in Content Publisher via their uid.  
For example:
- Fred Flintstone has a uid of `dce8e3a3-2872-4d45-848e-d1012d8cfd89` in both Whitehall and Content Publisher.  
- In Whitehall their id `615` and in Content Publisher it is `27`.  
The resulting hash to map this user would then be `{ 615 => 27 }`. _Note that the key is the Whitehall user id._
On migration the users from the various time line entries from Whitehall need to be mapped to their Content Publisher equivalent in order to avoid miss-matched or nil user id's on migration.
This change ensures that the mapping between Whitehall and Content Publisher user is done in one place: inside the `create_timeline_entry` method, and that all user id's …

Update use of user_ids and centralise lookup for consistency

---

app/interactors/contact_embed/create_interactor.rb
app/interactors/new_document/choose_supertype_interactor.rb
app/interactors/new_document/create_interactor.rb
app/interactors/publish/publish_interactor.rb
app/interactors/schedule/create_interactor.rb
app/interactors/schedule_proposal/update_interactor.rb
app/models/document_type/body_field.rb
app/models/document_type/summary_field.rb
app/models/document_type/title_and_base_path_field.rb
lib/requirements/access_limit_checker.rb
lib/requirements/backdate_checker.rb
lib/requirements/checker_issues.rb
lib/requirements/content_checker.rb
lib/requirements/file_attachment_checker.rb
lib/requirements/image_revision_checker.rb
lib/requirements/image_upload_checker.rb
lib/requirements/publish_time_checker.rb
lib/requirements/tag_checker.rb
lib/requirements/topic_checker.rb
lib/requirements/video_embed_checker.rb
lib/requirements/withdrawal_checker.rb
spec/interactors/file_attachments/create_interactor_spec.rb
spec/interactors/images/create_interactor_spec.rb
spec/lib/requirements/content_checker_spec.rb

Previously the syntax to add an issue was quite verbose, especially when
used outside of the Requirements namespace. This introduces a
'create' method to replace '<< Issue.new' everywhere.

Add CheckerIssues.create helper method

---

app/models/document_type.rb
app/models/document_type/title_and_base_path_field.rb
config/schemas/document_type.json
spec/factories/document_type_factory.rb
spec/features/editing_content/edit_edition_spec.rb
spec/features/editing_content/govspeak_preview_spec.rb
spec/features/editing_content/insert_contact_embed_spec.rb
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb
spec/features/editing_content/url_preview_spec.rb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/upload_image_spec.rb
spec/features/workflow/create_document_spec.rb
spec/features/workflow/delete_draft_after_publishing_spec.rb
spec/features/workflow/submit_for_2i_spec.rb
spec/interactors/content/update_interactor_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb
spec/models/document_type/title_and_base_path_field_spec.rb
spec/requests/contact_embed_spec.rb
spec/requests/content_spec.rb
spec/requests/preview_spec.rb
spec/services/failsafe_preview_service_spec.rb
spec/views/documents/show.html.erb_spec.rb

Previously we added this flag to avoid having extra stubs in many tests,
due to the API call we make in order to check a base path is
(probably) available. This removes the flag, so that the check is always
enabled, noting that we should be able to use the new flexibility of the
TitleAndBasePathField to achieve the same effect.
Please see the commits for further details.

Remove check_path_conflict_flag for base paths

---

.gitignore

Reverts alphagov/content-publisher#1744 due to further discussion on the PR after the merge.

Revert "Ignore .DS_Store"

---

app/views/topics/edit.html.erb
config/locales/en/topics/edit.yml

Add instructions on how to navigate topics for screen reader users.
co-author: @pollygreen 
Raising this as a draft. It should be merged after the miller-columns-element gets bumped to [1.3.0](https://github.com/alphagov/miller-columns-element/pull/33).
Update: This can now be reviewed and merged as [we're now using the latest version of miller-columns element](https://github.com/alphagov/content-publisher/pull/1750)

Add instructions to navigate topics

---

db/migrate/20200206153428_remove_null_constraints_from_whitehall_migrations.rb
db/migrate/20200206162051_add_whitehall_migration_null_constraint_to_document_imports.rb
db/schema.rb
lib/tasks/import.rake
spec/factories/whitehall_migration_document_import_factory.rb
spec/lib/tasks/import_spec.rb

Updates the single document import task to use a worker instead of being synchronous.
More details in the commits -> 
Trello:
https://trello.com/c/ffU41pHl/1391-adapt-import-single-document-rake-task-to-create-a-migration

Update single doc import

---

app/services/remove_document_service.rb
app/services/resync_document_service.rb
app/views/documents/history/_content_publisher_entry.html.erb
config/locales/en/documents/history.yml
db/migrate/20200207224528_rename_removal_alternative_path_to_alternative_url.rb
db/schema.rb
docs/removing-documents.md
lib/tasks/remove.rake
lib/tasks/unpublish.rake
lib/whitehall_importer/create_edition.rb
spec/factories/user_factory.rb
spec/lib/tasks/notify_spec.rb
spec/lib/tasks/remove_spec.rb
spec/lib/tasks/unpublish_spec.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/services/remove_document_service_spec.rb
spec/services/resync_document_service_spec.rb
spec/views/documents/history/_content_publisher_entry.html.erb_spec.rb

Trello: https://trello.com/c/yqXt0RGc/1417-remove-documents-at-dwps-request
Following the first request to remove documents from Content Publisher we have learnt that there are some issues to resolve.
Firstly Content Publisher uses misleadingly named terminology from the Publishing API of `alternative_path`to describe the redirect destination. This is actually a URL rather than a path, however Content Publisher had assumed it could only be a path which caused some poor rendering:
To resolve this I've switched our naming to follow the Whitehall precedent of `alternative_url` throughout the app.
Secondly, it turned out the links we are showing users in the document history for a removal or incorrect. This is because we passed in nil as the wrong parameter of `link_to`. Passing a url as the …

Removals: support absolute URLs and allow attributing users

---

app/interactors/editions/destroy_interactor.rb
app/services/delete_draft_edition_service.rb
spec/interactors/editions/destroy_interactor_spec.rb
spec/services/delete_draft_edition_service_spec.rb

Trello: https://trello.com/c/yqXt0RGc/1417-remove-documents-at-dwps-request
It turns out that we have a bug in the code used to assign the status of a timeline entry. The `DeleteDraftEditionService` accepts a document as input and modifies the current_edition of that. As the edition that is used in the interactor is not the same object as `document.current_edition` the edition in the interactor becomes stale and using that to populate the timeline entry uses an out of date status.
Looking on production we have 175 discarded timeline entries and only 32 of those are attributed to the correct status:
```
irb(main):010:0> TimelineEntry.draft_discarded.map { |te| te.status.state }.each_with_object(Hash.new(0)) { |state, memo| memo[state] += 1 }
=> {"discarded"=>32, "draft"=>129, …
```

Fix discarded draft attribution in timeline entries

---

app/jobs/whitehall_document_import_job.rb
lib/gds_api/whitehall_export.rb
lib/whitehall_importer/import.rb
lib/whitehall_importer/sync.rb
spec/jobs/whitehall_document_import_job_spec.rb
spec/lib/gds_api/whitehall_export_spec.rb
spec/lib/whitehall_importer/import_spec.rb
spec/lib/whitehall_importer/sync_spec.rb

For https://trello.com/c/Y3hKP4W9/1366-handle-retrying-whitehall-import-job
This calls the Whitehall export API at various stages of the import and sync job so that Whitehall knows about a document's status.
- We call the lock endpoint before a document is exported from Whitehall
- We call the unlock endpoint if a document import fails, not the sync
- We call the migrated endpoint if the document imports and syncs successfully

Update Whitehall document when importing

---

app/views/components/_attachment_meta.html.erb

The `hide_help_text` attribute was [renamed in govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/commit/66c1f9f7b43c9cdd26bb2c6acb3e0973cfe3c916) to `hide_opendocument_metadata`.
Thanks @ChrisBAshton for spotting this 🕵

Fix attribute name in attachment component

---

app/jobs/whitehall_document_import_job.rb
spec/jobs/whitehall_document_import_job_spec.rb

If an error occurs when running the Whitehall Document Import Job, we still
need to check if the migration has finished, otherwise we could have a
situation where on the Whitehall Migration record it looks like the migration
has never finished.

Check migration finished when handling errors

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

Strings were previously being used to compare the attribute when the
attribute was always a symbol, the strings have now been converted to
symbols.
There was multiple reasons these issues were not caught by the tests:
For the `default_image?` scenario the reason was because the 'image
problems' logic would never be called due to the if statement -
`publishing_api_image[attribute] != proposed_image_payload[attribute]`
reporting false due to a missed level of nesting in the
publishing_api_content stub, `[:image][:caption]` instead of what it
should be `[:details][:image][:caption]`. This caused a false positive to
be returned.
For the `empty_caption?` scenario the reason was due to the
document_type not being set to accept images and the edition not having
a lead_image_revision set, this …

Fix image integrity bugs

---

app/jobs/whitehall_document_import_job.rb
lib/whitehall_importer/import.rb
spec/jobs/whitehall_document_import_job_spec.rb

Both `WhitehallImporter::Import` and `WhitehallImporter::Sync` will update the
document import when called and we don't need to assign the document import to
a variable, so there's no need to return the document import when these classes
are done with it.

Stop returning document import from Import and Sync

---

app/jobs/asset_cleanup_job.rb
spec/jobs/asset_cleanup_job_spec.rb

This is a little bit of a cleanup on the `AssetCleanupJob` where we marked assets as absent in an ensure block, however this would get called for all types of exceptions.
It also removes a bunch of duplication in the tests and makes their expectations a bit clearer to read.

Don't mark assets as absent in an ensure

---

spec/db/scrub_access_limited_spec.rb

Follows on from: https://github.com/alphagov/content-publisher/pull/1781#discussion_r379402007
`reload_` only reloads the one association of the document that's changed (one query on an edition) whereas `document.reload.current_edition` reloads the document model and then `current_edition` is called, another query is made for that association and any other cached associations are lost

Don't reload the whole document, only the changed edition

---

app/services/publish_draft_edition_service.rb
spec/services/publish_draft_edition_service_spec.rb

As part of tinkering with change notes prototypes I made some tweaks to PublishDraftEditionService that simplified the code and added some guards against bad states.
More info in commits.

Small cleanup on PublishDraftEditionService

---

app/models/whitehall_migration/asset_import.rb
lib/whitehall_importer/migrate_assets.rb
spec/factories/whitehall_migration_asset_import_factory.rb
spec/lib/whitehall_importer/migrate_assets_spec.rb
spec/models/whitehall_migration/asset_import_spec.rb

For https://trello.com/c/piW0fhqa/1454-fix-documents-that-failed-the-sync
Previously we were getting an ID from the `original_asset_url` exported with an
image from Whitehall and sending this to Asset Manager in order to make changes
to the asset. This isn't the right ID however, and resulted in Asset Manager
being unable to find the asset. What we actually need is to find out the Asset
Manager ID and send that to Asset Manager. We can do this by getting the legacy
URL path from the `original_asset_url` and looking this up in Asset Manager to
get the correct Asset Manager ID.

Send asset ID to Asset Manager

---

lib/whitehall_importer/embed_body_references.rb
spec/lib/whitehall_importer/embed_body_references_spec.rb

When migrating two of NDA's news articles from Whitehall to Content Publisher, we encounter integrity check failures on the body.  The cause of this is the presence of image markdown in the proposed payload which we have failed to convert to an actual image, i.e. we're sending '[Image:wood_640_x_960.jpg]' rather than '<img ....'.
The documents are:
- [ID: 431866 Content ID: 809d70b1-3e9b-4833-a28b-41366a925805](https://www.gov.uk/government/news/barrnon-and-wood-move-to-next-stage-of-innovation-competition)
- [ID: 370367 Content ID: 5a88536b-7831-4184-b5fd-c40275ba7558](https://www.gov.uk/government/news/awards-recognise-supply-chain-excellence)
It is expected that a similar situation will occur with attachments due to the similarity of their handling.
On inspection of the original …

Fix import of embedded files in news articles

---

db/migrate/20200217112039_add_change_history_to_metadata_revisions.rb
db/schema.rb

We want to create a column for a revision that can store the change history for that edition. By change history we mean an array of all the past change notes with their times.
Created a new column on `metadata_revisions` called `change_history`.  Column type is JSON, default is [] (empty array), and is not nullable.
Trello: https://trello.com/c/xMRotBoK/1460-create-a-changehistory-json-column-on-metadatarevisions-and-populate-it-when-new-editions-are-added

Add change_history to metadata_revisons

---

app/interactors/editions/destroy_interactor.rb
app/services/delete_draft_assets_service.rb
app/services/delete_draft_edition_service.rb
app/services/discard_draft_edition_service.rb
app/services/discard_path_reservations_service.rb
spec/interactors/editions/destroy_interactor_spec.rb
spec/services/delete_draft_assets_service_spec.rb
spec/services/delete_draft_edition_service_spec.rb
spec/services/discard_draft_edition_service_spec.rb
spec/services/discard_path_reservations_service_spec.rb

Trello: https://trello.com/c/yqXt0RGc/1417-remove-documents-at-dwps-request
Following up from https://github.com/alphagov/content-publisher/pull/1755 this separates out some of the responsibilities of the DeleteDraftEditionService to be handled by separate services for discarding path reservations and deleting assets.
As part of this I re-considered the naming of the service and felt that DiscardDraftEditionService was more fitting with the nomenclature we use within the application.
Finally I found and resolved a bug where we updating the edition in the event of re-raising an exception which had no effect as the transaction would be aborted.
More info in commits.

Split and rename delete draft service

---

app/models/file_attachment/blob_revision.rb
lib/whitehall_importer/create_file_attachment_revision.rb
lib/whitehall_importer/import.rb
lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/body_text_check.rb
lib/whitehall_importer/sync.rb
spec/lib/whitehall_importer/integrity_checker/body_text_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

When doing a test migration of NDA's news stories, we found three articles with an embedded PDF attachment did not import with an error:
```
NoMethodError: undefined method `tempfile' for #<Tempfile:/tmp/open-uri20200129-1-g41dgq>
/govuk/content-publisher/app/services/create_file_attachment_blob_service.rb:37:in `number_of_pages'
```
This manual testing revealed there were a number of issues that we had not previously seen through the existing automated tests, which are resolved through this PR:
- Adds require statements for `gds_api/whitehall_export` that were missing
- Adds a `tempfile` method for the imported PDF, solving the issue giving the error above
- Uses a string for a missing asset URL when this would otherwise be nil (i.e. assets not yet synced to asset manager), which …

Fix import of documents with PDF attachments from Whitehall to Content Publisher

---

spec/factories/whitehall_migration_factory.rb

We don't need to set an id for factories that create db records, these
will be given an id automatically when created. This resolves an issue
where any existing WhitehallMigration records in the DB led to primary
key conflicts.

Remove unnecessary factory attribute

---

app/services/publish_draft_edition_service.rb
db/migrate/20200218153946_add_published_at_to_editions.rb
db/schema.rb
spec/services/publish_draft_edition_service_spec.rb

First PR to populate `published_at` column for editions when publishing an edition, we also move when publishing times are set to be before the syncing with publishing-api.
Trello:
https://trello.com/c/ShhyTqqU/1459-create-store-and-backfill-publishedat-on-editions

Add published at data

---

db/migrate/20200218161942_backfill_published_at_for_editions.rb
db/schema.rb

This backfills the published_at column for previously published
editions, we use when the published status was created as a means to
work this time out as this should reflect the actual publishing time.
This relies on:
https://github.com/alphagov/content-publisher/pull/1777
Trello:
https://trello.com/c/ShhyTqqU/1459-create-store-and-backfill-publishedat-on-editions

Backfill published_at column for edition

---

app/assets/javascripts/modal/modal-workflow.js
app/views/components/_multi_section_viewer.html.erb
spec/javascripts/helpers/modal-dialogue.js
spec/javascripts/modal/modal-workflow-spec.js

In [#1300](https://github.com/alphagov/govuk_publishing_components/pull/1300) we enabled `aria-label` on modal dialogue component to make it less verbose. Because in Content Publisher we generate the modal dialogue content dynamically we'll need to set this property via JavaScript as part of the `modalWorkflow` logic.
[Trello card](https://trello.com/c/xZwFwpul)

Make modals less verbose for screen readers

---

lib/whitehall_importer/embed_body_references.rb
spec/lib/whitehall_importer/embed_body_references_spec.rb

Now when there are no contacts for an edition the embed is ignored, the
same is true for when there is no matching contacts for an embed.
Previously the code would throw an error at either of these two
scenarios listed above as it tried to look for a content-id on nil.
Trello:
https://trello.com/c/OzdqkkW2/1455-fix-documents-that-failed-the-import-with-an-array-error

Make contacts code more resilient

---

spec/support/schemas/document_type_selection.json

Trello: https://trello.com/c/tbxRLYMP
If the format is not one that can be created in Content Publisher, we need to route users to
the correct publishing app or piece of guidance. To be able to do that we need to make
"path" a required field, but only if the type is "managed elsewhere".
There is is no elegant way to do this.
I investigated using the new [if-then-else][1] logic, or trying to set [dependencies][2],
but neither of these approaches failed schema validation when a "path" was removed from
`config/document_type_selections.yml`, so I went with the only approach that did work:
[creating two schemas][3]
[1]https://json-schema.org/understanding-json-schema/reference/conditionals.html
[2]https://json-schema.org/understanding-json-schema/reference/object.html#dependencies …

Make "path" required if "type" is "managed_elsewhere"

---

app/assets/stylesheets/core/_link.scss

When we originally used `$govuk-error-colour` for destructive links it met the
contrast requirements on the `light-grey` colour (which is used for panels or
to highlight sections on a page). After the colour palette update, destructive links
on panels became non-compliant with AA level of WCAG2.1. We decided to darken
the `$govuk-error-colour` by 5% to make sure it meets the required contrast ratio
regardless of it being presented on a default (white) background or on a light
grey background.
[Trello card](https://trello.com/c/f9JwfwIW)

Update destructive link colour

---

spec/models/document_type_selection_spec.rb

Trello: https://trello.com/c/tbxRLYMP
This is to prevent the same radio button appearing multiple times on a document type selection page.

Only allow unique options in a document type selection

---

app/models/metadata_revision.rb
spec/models/metadata_revision_spec.rb

`change_history` is a JSON column that has been added to `MetadataRevision` and defaults to an empty array.
Change notes will be added to this column.
Each change note should be a JSON object with 3 attributes:
- `id` - A uuid that we generate
- `note` - the change note content or text
- `public_timestamp` - a string representing the RFC3339 representation of the `edition.published_at` timestamp.
To have confidence in this JSON structure, we should add a validator on`MetadataRevision` that tests both the structure and that the fields are what we expect them to be (e.g. `id` is a valid UUID and `public_timestamp` is a valid RFC3339 representation).
The validator is defined as `strict`.  This ensures a particular exception is raised and that the application will crash with suitable debug …

Add validation for change notes stored in MetadataRevision

---

config/document_type_selections.yml
config/locales/en/document_type_selections.yml

Trello: https://trello.com/c/tR0CUleU
Updates the document type selections config to:
- add a new section (specialist notices)
- expand the news, guidance and transparency sections with nested
selections
- update the guidance
- alphabetise the entries to make them easier to update in the future.

Update document type selections to match new structure

---

app/controllers/whitehall_migration_controller.rb
app/views/whitehall_migration/document.html.erb
app/views/whitehall_migration/documents.html.erb
app/views/whitehall_migration/show.html.erb
config/routes.rb
lib/tasks/import.rake
spec/lib/tasks/import_spec.rb
spec/requests/whitehall_migration_spec.rb

Have set up the following for the migration UI:
- routes
- controller
- request specs
- placeholder views which display some migration data
This PR is for the initial setup, the next PR will contain the full data that we wish to display.
Example:
Trello card: https://trello.com/c/yFGFseiN

Basic UI for viewing Whitehall migration status

---

app/views/images/crop.html.erb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/upload_image_spec.rb

https://trello.com/c/QZmkUoTr/1516-support-metadata-just-unique-reference-for-file-attachments
Previously we used custom 'Crop image' text when passing through the
'crop image' page. This updates the text to make it consistent with
the upcoming work on file attachments (as we add an extra edit page).
When no crop is occurring, we still say 'Continue'. The 'Crop image'
text may have been intended to reassure the user of the outcome of the
crop, but we think that 'Save' should accomplish this just fine.

Use consistent naming for button to crop image

---

app/controllers/application_controller.rb
app/interactors/images/update_interactor.rb
app/interactors/lead_image/choose_interactor.rb
app/interactors/lead_image/remove_interactor.rb
app/models/document_type.rb
app/services/preview_draft_edition_service/payload.rb
app/views/documents/show.html.erb
app/views/images/_image.html.erb
app/views/images/edit.html.erb
app/views/images/index.html.erb
config/document_types.yml
lib/edition_assertions.rb
spec/factories/document_type_factory.rb
spec/features/editing_images/choose_lead_image_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/download_image_spec.rb
spec/features/editing_images/edit_image_spec.rb
spec/features/editing_images/remove_lead_image_spec.rb
spec/features/editing_images/upload_image_spec.rb
spec/lib/edition_assertions_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb
spec/requests/images_spec.rb
spec/requests/lead_image_spec.rb
spec/services/preview_draft_edition_service/payload_spec.rb
spec/support/schemas/document_type.json

https://trello.com/c/85gkiigT/1397-make-disabled-features-more-robust-lead-images
This introduces a new 'assert_edition_feature' method and applies it to
lead image actions in order to render/return a 404 response when the user
tries to perform a lead image action on an edition that does not support
that feature, as specified in its document type.

Add new assertion for edition features

---

app/models/document_type.rb
app/models/document_type_selection/option.rb
app/services/preview_draft_edition_service/payload.rb
app/views/documents/index/_filters.html.erb
app/views/new_document/show.html.erb
config/document_type_selections.yml
config/document_types.yml
config/locales/en/document_type_selections.yml
config/locales/en/document_types.yml
spec/features/formats/publication_spec.rb
spec/models/document_type_selection/option_spec.rb
spec/models/document_type_spec.rb
spec/spec_helper.rb
spec/support/schemas/document_type.json
spec/support/schemas/document_type_locale.json
spec/support/schemas/document_type_selection.json
spec/views/documents/index/_filters.html.erb_spec.rb
spec/views/new_document/show.html.erb_spec.rb

Trello: https://trello.com/c/KI9c4Uue
Allows users with `pre_release_features` to select and create documents in group 1 publications:
- correspondence
- independent report
- foi release
- corporate report
- transparency
- research and analysis
- promotional material
- impact assessment
- policy paper

Enable Group 1 Publication formats for pre-release users

---

app/controllers/healthcheck_controller.rb
config/routes.rb
lib/bulk_data/cache.rb
lib/bulk_data/government_repository.rb
lib/healthcheck/government_data_check.rb
spec/lib/healthcheck/government_data_check_spec.rb
spec/requests/healthcheck_spec.rb

Trello - https://trello.com/c/FaHAEajH/1318-alert-2ndline-when-we-have-no-cached-data-on-governments
This iterates out healthcheck endpoint to include a check for government data, a connection to redis and to the database. This will allow us to alert 2nd line and our slack channel in the event that government data is unavailable. 
https://github.com/alphagov/govuk-developer-docs/pull/2301
https://github.com/alphagov/govuk-puppet/pull/10129

Introduce government data alert

---

Gemfile
Rakefile
lib/tasks/brakeman.rake
lib/tasks/development_permissions.rake
lib/tasks/factorybot.rake
lib/tasks/lint.rake
lib/tasks/notify.rake
lib/tasks/remove.rake
lib/tasks/resync.rake

https://github.com/alphagov/content-publisher/pull/1769 removed the need for the frozen string literal thing. A few of them seem to have snuck back in so this removes them.

Remove frozen string literals

---

lib/bulk_data/government_repository.rb

The cop to enforce Time.zone.now (instead of Time.current) was merged recently, but it appears this file was merged afterwards.

Fix time linting error

---

README.md
docs/import-from-whitehall.md
lib/bulk_data/government_repository.rb

These include instructions for running the migration locally without needing to replicate data.
Trello card: https://trello.com/c/W6Ay4rYb

Add instructions for running a migration from Whitehall

---

app/interactors/editions/create_interactor.rb
app/models/edition.rb
app/models/revision.rb
app/services/create_next_edition_service.rb
spec/factories/edition_factory.rb
spec/interactors/editions/create_interactor_spec.rb
spec/services/create_next_edition_service_spec.rb

We have previously created a JSON column in which to store the change history of all editions of a document.  We have also added validation of the fields and structure of the JSON data to be stored.  
We now need to ensure that as each new edition is created - the change history is updated with the superseded edition's change note(s) - if appropriate - and store them with the newly created edition.
This change adds that functionality by introducing a service object (`CreateNextEditionService`) and updating the existing code where required.
Trello: https://trello.com/c/xMRotBoK/1460-create-a-changehistory-json-column-on-metadatarevisions-and-populate-it-when-new-editions-are-added

Store the cumulative change history of all document editions as each new edition is created 

---

app/jobs/whitehall_document_import_job.rb
lib/whitehall_importer/import.rb
spec/jobs/whitehall_document_import_job_spec.rb
spec/lib/whitehall_importer/import_spec.rb

For https://trello.com/c/gao9twxQ/1524-skip-import-if-document-import-is-not-in-pending-state
We originally checked if a document import is in a pending state within the
WhitehallImporter::Import class. However we've found that it's beneficial to do
this check before the class is called, as in situations where a document has
successfully been imported but the job is being retried as a result of an error
in the syncing process, the job errors since the document import is no longer
pending.

Move check for pending document import before importing

---

app/controllers/application_controller.rb
app/controllers/errors_controller.rb
app/views/documents/access_limited.html.erb
app/views/errors/forbidden.html.erb
config/application.rb
config/locales/en/documents/access_limited.yml
config/locales/en/errors/forbidden.yml
config/routes.rb
spec/features/editing_content_settings/enforce_access_limit_spec.rb
spec/requests/errors_spec.rb

Trello: https://trello.com/c/HILuWHOt
Builds on: #1825 
Publications were added in: #1810, but the ability to create new publications, or filter by publications on the index page was restricted to users who have the "pre_release_features" permission.
This restriction has been expanded to viewing and editing any publications documents as well. This includes everything from viewing the document summary page, to being able to tag the document etc. Users without the correct permission are shown a generic 403 Forbidden page.
This is so that we don't end up with users being in the position of being able to do some parts of pre-release format work based off a link but not being able to create one or find it in the index.
Co-authored with @kevindew

Restrict access to pre release

---

app/models/status.rb
lib/whitehall_importer/create_edition.rb
spec/lib/whitehall_importer/create_edition_spec.rb

In this commit we populate the published_at column on each imported
edition if the edition has been published in the past. The editions
which will have this field populated will either have a state of
'published', 'published_but_needs_2i', 'superseded', 'removed' or
'withdrawn'.
Trello:
https://trello.com/c/MeyxpGHG/1465-import-publishedat-and-changehistory-for-whitehall-content

Set published_at time during import

---

db/migrate/20200220111317_backfill_change_history_for_metadata_revisions.rb
db/schema.rb

This migration backfills the change_history for all metadata_revisions,
the change_history is built up from the individual change notes from
each edition where they have been published with a major change.
The change_history for an edition is built up from the previous editions
change notes and consolidated into the change_history field on the
corresponding metadata_revision. Not all change notes should be included
in this history however, the first published change note and the current
change note should be excluded from this list. E.g for the 4th edition
of a document it would contain the change notes from the 2nd and 3rd
edition but not the 1st (first published) and 4th (current).
Each change note included in the change history will include a UUID,
public_timestamp (publishing time) …

Backfill change_history for metadata_revisions

---

config/initializers/govuk_error.rb

`ApplicationController::Forbidden` errors occur when users try to access something they shouldn't. As this is a user behaviour error and not a problem with the application, we don't need to report it to Sentry. 
[Example in publishing-api](https://github.com/alphagov/publishing-api/blob/76679ce5fc1d300408a80a9bc1a14e30b6f24151/config/initializers/govuk_error.rb)
See: https://sentry.io/organizations/govuk/issues/1537088552/?project=202208

Don't send `Forbidden` errors to sentry

---

docs/import-from-whitehall.md

Document updated with the following:
- Fix typos in 'govuk-docker run' command line options
- Add clarity on email use when getting bearer tokens
- Add command to unlock all records for testing and comparison

Minor document updates

---

lib/edition_filter.rb
spec/factories/document_type_factory.rb
spec/lib/edition_filter_spec.rb
spec/models/document_type_selection/option_spec.rb
spec/views/documents/index/_filters.html.erb_spec.rb
spec/views/new_document/show.html.erb_spec.rb

Trello - https://trello.com/c/wzzVIihM/1521-exclude-prerelease-publications-from-edition-filter-results
As it stands, users without the pre_release_features permission are able to see editions with the pre release flag when they visit content-publisher. This will give the false impression that these are things that can be edited. This adds the functionality to remove these editions from the list of things that such users can see.

Exclude pre-release publications from edition filter results

---

db/migrate/20200220111317_backfill_change_history_for_metadata_revisions.rb
db/schema.rb

Trello: https://trello.com/c/ymfW8Eeh/1462-backfill-the-changehistory-of-existing-content
This re-instates https://github.com/alphagov/content-publisher/pull/1806 which I reverted in https://github.com/alphagov/content-publisher/pull/1836 with a fix for the issue found of changing change history ids.
The difference in this may be best shown through an image:
Before:
After:

Re attempt change history backfill

---

db/migrate/20200220111317_backfill_change_history_for_metadata_revisions.rb

Trello: https://trello.com/c/ymfW8Eeh/1462-backfill-the-changehistory-of-existing-content
Oh dear - I only noticed this when this migration had been run in
production. It's not too big a concern as we don't validate that the
change history is in a particular order and can likely recover from it
being out of order.
However since this is a backfill it'd be good to set the precedent to be
in the order we expect.
To resolve this I plan to rollback the migration in each environment
(which won't do anything) and then re-run it to reset the change
history. It doesn't seem to be a sufficiently big problem to warrant
creating a new migration.
Before this change change_history was appended:
After it is prepended:

Fix incorrect ordering of change history migration

---

lib/whitehall_importer/create_edition.rb
spec/lib/whitehall_importer/create_edition_spec.rb

It turns out only published and withdrawn documents were being imported
as live editions. This can be resolved by using the status.live? method
that was introduced in 648932f

Fix removed editions not being imported as live

---

app/services/discard_path_reservations_service.rb
app/services/preview_draft_edition_service.rb
app/services/schedule_publish_service/payload.rb
lib/publishing_api_payload.rb
lib/publishing_api_payload/history.rb
lib/whitehall_importer/integrity_checker.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/lib/publishing_api_payload/history_spec.rb
spec/lib/publishing_api_payload_spec.rb
spec/services/discard_path_reservations_service_spec.rb
spec/services/preview_draft_edition_service_spec.rb
spec/services/schedule_publish_service/payload_spec.rb

Now that we store a full `change_history` for an edition, we need to send this full history (along with the `first_published_date` and `public_updated_at`) to Publishing API.
For the first edition, we always sent a fixed change note.  For subsequent major editions, the user entered change note is used.
This change also moves `Payload` out of the `PreviewDraftEditionService` namespace, into `PublishingApiPayload` since this class is used in multiple contexts, not just when dealing with the preview of draft editions.
Not to be merged until #1806 is merged and deployed.
Trello card: https://trello.com/c/KBFWEkKG

Include change history in Publishing API payload

---

db/migrate/20200303115207_add_removed_at_to_removals.rb
db/schema.rb
lib/tasks/remove.rake
spec/lib/tasks/remove_spec.rb

This adds a `removed_at` column to Removal and sets this value when creating a Removal in the remove content rake tasks.  At this stage we are not making this a required value for a Removal; we will need to backfill existing Removals before doing so.

Add removed_at to removals

---

lib/whitehall_importer/create_edition.rb
spec/lib/whitehall_importer/create_edition_spec.rb

If a Whitehall document has been removed, then when it is imported into Content
Publisher we set its Removal `removed_at` value to the unpublishing
`created_at` value. This means we can ensure that the Publishing API is
accurately updated when we sync this imported content.

Set removed_at for Whitehall imports

---

app/models/document_type.rb
config/document_types.yml
lib/publishing_api_payload.rb
spec/factories/document_type_factory.rb
spec/support/schemas/document_type.json

https://trello.com/c/dzFScHVI/1498-disable-inline-file-attachments-when-featured-attachments-are-available
This does some of the initial work on the card to unblock the next ones.
Previously we only supported (inline) file attachments for news, but we
will have a different workflow for publications, which have (inline)
featured attachments. This adds a new attribute to clearly indicate in what
form attachments are available for a document type.

Add new 'attachments' attribute to document types

---

db/migrate/20200303143426_backfill_removals_removed_at.rb
db/schema.rb

In anticipation of making `removed_at` a required attribute for a Removal
record, we backfill the value for existing Removals. Since we set the
`removed_at` value to the current time when a Removal is created, it makes
sense to set `removed_at` for existing Removals to their `created_at` value.

Backfill removed_at value for Removals

---

app/services/resync_document_service.rb
spec/factories/removal_factory.rb
spec/services/resync_document_service_spec.rb

When syncing an edition that has been removed, the Resync Document Service
should now send the removal's `removed_at` value instead of `created_at`.

Change Resync Document Service to use removed_at

---

spec/requests/errors_spec.rb

https://trello.com/c/HILuWHOt
Previously the 'errors' spec was inconsistent with all other request
specs, and with itself: half of the file used a consistent format
describe "METHOD /path-under-test"
while the other half used freetext. I found this confusing when
reviewing a change to this file [[1]], as the request(s) under test was
unclear. This modifies the 'errors' spec to use a consistent format
around each test, using just enough freetext to indicate the range
of paths being described (even if they're not actually covered by
the test).
[1]: https://github.com/alphagov/content-publisher/pull/1826#discussion_r385275352

Use consistent describe blocks in request specs

---

db/schema.rb

This document_subtypes column is added through a migration, so ends up at the end of the column list.  However, due to a merge conflict that went unnoticed, it ended up in the wrong place in the schema that was committed in aa31f36e2.  This causes issues each time a developer runs a migration, since Git detects a change in the db/schema.rb file.

Re-order db/schema.rb

---

db/migrate/20200304083621_add_not_null_constraint_to_removed_at.rb
db/schema.rb

A removal should always have a `removed_at` timestamp so that we can accurately
update the Publishing API. Now that existing removals have this value
backfilled, we can add a not null constraint to it.

Add not null constraint to removed_at

---

app/services/remove_document_service.rb
lib/tasks/remove.rake
spec/services/remove_document_service_spec.rb

In cases where we attempt to remove an edition that has already been removed
(for example, if the explanation needs to be updated) then we need to ensure
that the existing `removed_at` date is kept the same. This modifies the Remove
Document Service to do this.  We also update the Remove Document Service to
send the `removed_at` date to the Publishing API as the `unpublished_at` value.

Maintain removed_at in Remove Document Service

---

spec/lib/whitehall_importer/integrity_checker_spec.rb

Originally reading through this spec i was confused as what payload
meant, was it the payload we would send to pub-api or the payload from
pub-api. publishing_api_item is much clearer and is how the valid block
of tests refer to this concept.

Make naming for item returned by pub-api consistent

---

app/controllers/whitehall_migration_controller.rb
app/models/whitehall_migration/document_import.rb
app/views/whitehall_migration/_document_imports_list.html.erb
app/views/whitehall_migration/document.html.erb
app/views/whitehall_migration/document_import.html.erb
app/views/whitehall_migration/document_imports.html.erb
app/views/whitehall_migration/documents.html.erb
app/views/whitehall_migration/show.html.erb
config/routes.rb
lib/tasks/import.rake
spec/requests/whitehall_migration_spec.rb

UI to display information resulting from a Whitehall migration.
- On the `whitehall_migration#documents` page, for unsuccessfully imported documents, the link to view an individual document import currently displays the `id` of the `document_import`. We want it to display the `content_id` but at the moment the import script is not importing `content_ids`. This will be addressed in a following PR.
- To anyone reviewing... Please review the code as per usual and also let us know of any additional information that you think would be useful to display.
Show page:
Document imports page for successfully imported documents:
Document imports page for unsuccessfully imported documents:
Document page:

Display data UI migration

---

app/services/withdraw_document_service.rb
spec/features/withdrawing/edit_withdrawal_spec.rb
spec/features/withdrawing/withdraw_spec.rb
spec/services/withdraw_document_service_spec.rb

This change will present the `withdrawn_at` time to Publishing API when a document is withdrawn.  This will ensure that the time held by Content Publisher to consistent with the time in Publishing API.
Trello card: https://trello.com/c/ntHbfCPB

Present withdrawn_at time to Publishing API when withdrawing a document

---

app/models/metadata_revision.rb
spec/models/metadata_revision_spec.rb

We've learnt in the last few days that is quite easy to get this wrong
and then have inconsistent ordering. This is applied so that anything
being saved has the ordering we expect.

Validate that change history is in the expected order

---

app/views/whitehall_migration/_document_imports_list.html.erb

This changes links to view migrated documents in Whitehall to use external links.

Change migration view to use external Whitehall links

---

lib/publishing_api_payload/history.rb
spec/lib/publishing_api_payload/history_spec.rb

Previously if an edition has been previously published with a major
change the public_updated_at time being sent to the publishing-api
would've been set to the current time, this is incorrect behaviour and
as the time should be set to the published_at time of the edition.

Fix public_updated_at time for published editions

---

lib/whitehall_importer/change_history.rb
lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/create_revision.rb
lib/whitehall_importer/import.rb
spec/factories/whitehall_export/edition_factory.rb
spec/lib/whitehall_importer/change_history_spec.rb
spec/lib/whitehall_importer/create_edition_spec.rb

We now want to generate change history for editions we import.  
Further info in the commits ->
Trello:
https://trello.com/c/MeyxpGHG/1465-import-publishedat-and-changehistory-for-whitehall-content

Import change history

---

lib/whitehall_importer/create_migration.rb
spec/factories/whitehall_export/index_document_factory.rb
spec/lib/whitehall_importer/create_migration_spec.rb

[Trello](https://trello.com/c/ACUVDeXD/1523-export-contentid-from-whitehall-into-content-publisher)
- Will enable the 'View on Whitehall' links in the migration UI to work (as they rely on having the content ID to form the URL path).
- It will also make it easier to find a relationship between the document_import and the whitehall document.
Merge after: https://github.com/alphagov/whitehall/pull/5417

Persist content_ids for document_imports on import

---

app/controllers/featured_attachments_controller.rb
app/controllers/file_attachments_controller.rb
app/views/documents/show.html.erb
app/views/documents/show/_featured_attachments.html.erb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/featured_attachments/index.html.erb
app/views/file_attachments/new.html.erb
config/locales/en/documents/show.yml
config/locales/en/featured_attachments/index.yml
config/locales/en/file_attachments/new.yml
config/routes.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/requests/featured_attachments_spec.rb
spec/requests/file_attachments_spec.rb
spec/views/featured_attachments/index.html.erb_spec.rb

Trello: https://trello.com/c/RTw12Wxq
Allow the user to upload a feature file attachment.
Publications, don't just allow inline attachments, linked to from within the body text of a document, they also allow a list of "featured" documents to be added to them. Featured documents are usually displayed along with some metadata about them.
This example has both: https://www.gov.uk/government/publications/the-uks-approach-to-trade-negotiations-with-the-us
To be able to support Publishers creating publications documents, we need to be support adding featured attachments to documents.
Until publications are ready to be released, adding a featured attachment is only available to users with "pre_release" permissions.
The following features are not covered by this change, they will be added as part …

Create featured file attachments

---

app/jobs/resync_document_job.rb
lib/tasks/resync.rake
spec/jobs/resync_document_job_spec.rb
spec/lib/tasks/resync_spec.rb

Trello: https://trello.com/c/aOl2VwhV
The resync job frequently fails due to network timeout issues. Changing the service to a sidekiq job allows it to be retried.

Wrap Resync document service in sidekiq job with retries

---

lib/publishing_api_payload.rb
lib/publishing_api_payload/file_attachment_payload.rb
spec/lib/publishing_api_payload/file_attachment_payload_spec.rb
spec/lib/publishing_api_payload_spec.rb

Trello: https://trello.com/c/lHtCxM6V
Send attachment and featured attachment data to the publishing-api.
As part of the RFC on Attachments we now make data about attachments available in the Content API in a way that's machine readable so that's consumers of the Content API will soon no longer have to manually parse data about attachment from the rendered HTML.
Adding this data into the payload will also featured attachments to be rendered on the frontend as this is done by the publishing-api.

Send file attachments details in publishing-api payload

---

app/controllers/featured_attachments_controller.rb
app/controllers/file_attachments_controller.rb
app/views/components/_markdown_editor.html.erb
spec/requests/featured_attachments_spec.rb
spec/requests/file_attachments_spec.rb

Trello: https://trello.com/c/dzFScHVI
Follows on from: #1842 
Depends on: #1841 
Only allow inline attachments to be uploaded from the markdown editor if the document type allows inline attachments.
Only allow attachments to be uploaded via the Attachments section in the document summary if the document type allows featured attachments.
This allows different types of attachments to be configured ways, and stops users from accidentally stumbling across pages or options that might confuse them.

Restrict attachment actions

---

app/helpers/file_attachment_helper.rb
spec/lib/publishing_api_payload/file_attachment_payload_spec.rb

The schema for `publication_attachment_asset` which is used to populated `details.attachments` in the content item, expects the value for `number_of_pages` to be an integer:
https://github.com/alphagov/govuk-content-schemas/blob/ac8fb929789c3678e420f7e58db7eb2519692ac0/dist/formats/publication/notification/schema.json#L858
However, when an image is added as an inline attachment, the value is being set to `nil`. This means that when we try to update the document in publishing-api it's throwing an error:
https://sentry.io/organizations/govuk/issues/999142960/?project=1242052&referrer=slack
This change excludes `number_of_pages` from the payload if it doesn't have a value.

Remove number of pages from payload if nil

---

app/assets/javascripts/application.js
app/assets/javascripts/components/reorderable-list.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_reorderable-list.scss
app/views/components/_reorderable_list.html.erb
app/views/components/docs/reorderable_list.yml
package.json
spec/javascripts/components/reorderable-list-spec.js
yarn.lock

Add reorderable list component to be used for reordering attachments in Publications.
<table>
<tr><th>JavaScript enabled</th><th>JavaScript disabled</th></tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
<table>
<tr><th>JavaScript enabled</th><th>JavaScript disabled</th></tr>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
Examples using VoiceOver
<table>
<tr><th>JavaScript enabled</th><th>JavaScript disabled</th></tr>
<tr><td valign="top">
> Move Budget 2018 up, button, list 5 items.
</td><td valign="top">
> Order index for Budget 2019, edit text, list 5 items
</td></tr>
</table>
[Trello card](https://trello.com/c/H3T7JWtS)

Add reorderable list component

---

app/controllers/file_attachments_controller.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/file_attachments/confirm_delete.html.erb
config/locales/en/file_attachments/confirm_delete.yml
config/routes.rb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/requests/file_attachments_spec.rb

Trello: https://trello.com/c/qpeNzbYa
Adds a 'Delete attachment' link to the featured attachment preview block. Clicking delete takes the user to a confirmation page which then redirects them to the current `/attachments` page, where they can see that the attachment is gone.

Support "Delete file" action for featured file attachments

---

app/controllers/file_attachments_controller.rb
app/models/file_attachment/revision.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/file_attachments/_file_attachment.html.erb
config/routes.rb
spec/features/editing_file_attachments/download_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/features/editing_images/download_image_spec.rb
spec/requests/file_attachments_spec.rb

https://trello.com/c/OWZorYWA/1540-allow-attachments-to-be-downloaded

Add download action for file attachments

---

lib/publishing_api_payload.rb
spec/lib/publishing_api_payload_spec.rb

This logic is now covered by the PublishingApiPayload::History class.

Remove backdating conditional for PublishingApiPayload

---

app/models/file_attachment/metadata_revision.rb
app/models/file_attachment/revision.rb
db/migrate/20200312132425_add_file_attachment_metadata_for_publications.rb
db/schema.rb

https://trello.com/c/HRUXGp3K/1518-support-metadata-for-featured-file-attachments-db-modelling
This adds additional metadata fields for file attachments in order
support the extended workflow for publications. Since these fields
are inherent to the GOV.UK concept of attachments, we think they
should be represented as columns on the model - we also considered
a JSON blob alternative, but it seemed to be mostly disadvantageous.

Add file attachment metadata for publications

---

app/models/document_type/multi_tag_field.rb

This is a rather quick fix to resolve an issue where nil values in tags
are breaking Postgres JSON queries. It's a short term step before a
larger fix is put together.

Don't store tag params that aren't submitted

---

app/controllers/file_attachments_controller.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/file_attachments/edit.html.erb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb

Trello: https://trello.com/c/lZKUDZbj
Adds an "Edit attachment" link to the featured attachment preview block on the attachments index page. Clicking on "Edit attachment" takes the user to existing edit page where they can edit the title or replace the file.
These changes ignore the new designs for the edit attachment page. There is follow-up work to make this consistent between the modal for inline attachments and the page for featured attachments.

Support "Edit attachment" action for featured file attachments

---

app/views/file_attachments/index.html.erb
app/views/file_attachments/show.html.erb

Follows on from: https://github.com/alphagov/content-publisher/pull/1901
Render the file attachment and index and show pages at 2/3 width when JS is turned off (or not available)
and the page renders in the new screen rather than a modal

Render index & show at 2/3 width when full screen

---

app/models/file_attachment/metadata_revision.rb
app/models/file_attachment/revision.rb
db/schema.rb

https://trello.com/c/HRUXGp3K/1518-support-metadata-for-featured-file-attachments-db-modelling
This renames the attribute to better reflect it's value.

Rename official_document -> official_document_type

---

app/controllers/file_attachments_controller.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/replace.html.erb
config/locales/en/file_attachments/replace.yml
config/routes.rb
spec/requests/file_attachments_spec.rb

Trello: https://trello.com/c/QZmkUoTr
Renames the "edit" and "update" routes for file attachments to "replace" and "update_file" respectively.
In the next story we will be adding a page to add metadata about file attachments.
For images, metadata is added using the "edit" route and "POSTed" using the "update" route. To make file attachments more consistent with images, the "edit" and "update" routes are being renamed so that they can be used for the metadata paths later.

Rename file attachment routes

---

app/assets/javascripts/application.js
app/assets/javascripts/components/reorderable-list.js
app/assets/javascripts/modules/gtm-reorder-listener.js
spec/javascripts/components/reorderable-list-spec.js
spec/javascripts/modules/gtm-reorder-listener-spec.js

- Emit events when reordering items (via buttons or drag-and-drop)
- Add reorder listener script to capture these events and send them to GTM
Note: I'm not too opinionated about the structure of these events as long as they are consistent and usable for performance analysis.
[Trello card](https://trello.com/c/H3T7JWtS)

Add tracking to reorderable list component

---

README.md
docs/edit-change-note-history.md
lib/tasks/change_history.rake
lib/tasks/edition_updater.rb
spec/lib/tasks/change_history_spec.rb
spec/lib/tasks/edition_updater_spec.rb

Sometimes publishers have the need to modify the change notes on a published document.  They cannot currently do this through the UI, and developers cannot do this without performing many manual steps using a Rails console.
This adds rake tasks that allow change note history to be viewed, deleted, edited and added to by a developer.
It also adds documentation explaining how the tasks should be run.
Trello card: https://trello.com/c/I8oRBPjH

Add rake task to make edits to change note history on documents

---

config/document_type_selections.yml

https://trello.com/c/ZXpB0fBH/1493-reorder-document-types-based-on-usage
This orders document types by the most commonly created in the 'create new document' flow.

Change order in which document types are listed

---

config/locales/en/document_type_selections.yml

These changes came out of tree testing and to solve the problem that users must add a featured attachment to a publication but we weren't telling them they were choosing a publication type.
https://trello.com/c/ZXpB0fBH/1493-reorder-document-types-based-on-usage

Identify which document types are publications

---

app/controllers/errors_controller.rb
app/views/layouts/application.html.erb
spec/requests/errors_spec.rb

While looking at our previous incident I noticed we had a number of 500
responses for users being served a 404 page. These were occurring when
users were requesting a URL that Rails did not recognise and the
`authenticate_user!` action of warden was raising an exception, trace:
```
UncaughtThrowError
uncaught throw :warden
/data/vhost/content-publisher/shared/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/proxy.rb:134:in `throw'
/data/vhost/content-publisher/shared/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/proxy.rb:134:in `authenticate!'
/data/vhost/content-publisher/shared/bundle/ruby/2.6.0/gems/gds-sso-14.3.0/lib/gds-sso/controller_methods.rb:47:in `authenticate_user!'
/data/vhost/content-publisher/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:4 …
```

Support unautheticated error viewing

---

spec/javascripts/helpers/gtm-mock.js

Attach dataLayer object to `window` to fix flakey `reorderable-list` tests
The events emitted by the reorderable-list component are picked up by listeners that expect a `dataLayer` object to exist.
Fix tested with `jasmine:ci[true,64655]` seed [which currently fails](https://ci.integration.publishing.service.gov.uk/job/content-publisher/job/missing-full-stop/1/console).

Fix flakey reorderable-list tests

---

app/services/edit_draft_edition_service.rb
spec/services/edit_draft_edition_service_spec.rb

https://trello.com/c/7NXYdxZV/1538-user-can-set-desired-featured-attachment-order
Previously we had repeated tests to check that an updated payload
had been sent when a revision-type change was made e.g. editing content
or tags. Later we decided these tests added little value, since we have
a fallback mechanism to support the user doing this manually if need be,
making the need to call the preview service everywhere 'optional'.
However, the fallback mechanism only works if the edition has flagged
that the revision is not in-sync, using the 'revision_synced' attribute.
This works if we encounter a requirements issue, but not if we just forget
to call the preview service in our code.
This updates the EditDraftEditionService to ensure the edition flags
that a revision is out-of-sync, so that …

Flag that an updated revison is not in sync

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

We want to integrity check publishing times when we import whitehall documents, the times we're concerned about checking are public_updated_at and first_published_at.
More info in the commits ->
Trello:
https://trello.com/c/aCQ4qhB3/1464-check-integrity-of-whitehall-firstpublishedat-and-publicupdatedat

Integrity check published times

---

config/initializers/govuk_error.rb

Data is transferred from production to staging and integration each
night. This transfer involves dropping the database and creating a new
one, this leaves us vulnerable to errors for any scheduled tasks that
run which can cause unactionable noise in our sentry logs.
To try resolve these this change prevents the reporting of errors
to sentry for postgres errors from between midnight and 5am in
integration and staging.
I did hope that I could resolve this by doing configuration on sentry.io
however they don't provide any means to ignore specific errors at either
certain times or in certain environments.
Ideally too it'd be better if we didn't need to do this and had an env
sync process without this problem but that seems like something that is
unlikely to be resolved imminently.

Don't report postgres errors occurring during data sync

---

lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/unpublishing_check.rb
spec/lib/whitehall_importer/integrity_checker/unpublishing_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

For https://trello.com/c/e8zIJIoy/1526-expand-integrity-checks-to-cover-withdrawing-and-removing
This adds the below checks for withdrawn and removed content to the Integrity Checker:
- Unpublishing type in Publishing API is `withdrawal`
- `withdrawn_at` matches `unpublished_at` in Publishing API
- `public_explanation` matches `explanation` in Publishing API
- Unpublishing type in Publishing API is `gone` or `redirect`
- `public_explanation` matches `explanation` in Publishing API
- `alternative_url` matches `alternative_path` in Publishing API
- Unpublishing time is not checked

Integrity check for withdrawn and removed content

---

lib/whitehall_importer/create_edition.rb
spec/factories/whitehall_export/unpublishing_factory.rb
spec/lib/whitehall_importer/create_edition_spec.rb

Dependent on https://github.com/alphagov/whitehall/pull/5455
We have changed Whitehall to export an unpublishing alternative path instead of
an alternative URL.  This is because Whitehall sends the alternative path to
Publishing API when unpublishing content, and this discrepancy was causing the
integrity checker to detect a mismatch between the URL exported from Whitehall
and the path in Publishing API. This updates WhitehallImporter::CreateEdition
to set the removal `alternative_url` to the `alternative_path` that is now
exported from Whitehall.

Set alternative url to imported alternative path

---

app/controllers/featured_attachments_controller.rb
app/interactors/featured_attachments/update_order_interactor.rb
app/models/edition.rb
app/models/file_attachment/revision.rb
app/models/metadata_revision.rb
app/models/metadata_revision/change_history_validator.rb
app/models/metadata_revision/featured_attachment_ordering_validator.rb
app/models/revision.rb
app/models/timeline_entry.rb
app/views/components/_reorderable_list.html.erb
app/views/components/docs/reorderable_list.yml
app/views/featured_attachments/index.html.erb
app/views/featured_attachments/reorder.html.erb
config/locales/en/documents/history.yml
config/locales/en/featured_attachments/reorder.yml
config/routes.rb
db/migrate/20200317152759_add_featured_attachment_ordering.rb
db/schema.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/features/editing_featured_attachments/reorder_attachments_spec.rb
spec/interactors/featured_attachments/update_order_interactor_spec.rb
spec/models/metadata_revision/change_history_validator_spec.rb
spec/models/metadata_revision/featured_attachment_ordering_validator_spec.rb
spec/models/revision_spec.rb
spec/requests/featured_attachments_spec.rb

https://trello.com/c/7NXYdxZV/1538-user-can-set-desired-featured-attachment-order
This adds a new 'reorder' page/route so a user can set the order of
featured attachments. Ordering for newly uploaded attachments is currently
undefined, and will be addressed in future work. Note that I'm leaving out the 
'Cancel' actions [pending a decision on this](https://trello.com/c/wmJzDSA1/1678-audit-the-use-of-cancel-actions-and-implement-a-policy-for-them).

Add a new feature to reorder featured attachments

---

app/assets/javascripts/components/reorderable-list.js
spec/javascripts/components/reorderable-list-spec.js

https://trello.com/c/7NXYdxZV/1538-user-can-set-desired-featured-attachment-order
This also adds a spec to cover the 'onSort' behaviour of the component.
Ideally we would simulate actual drag events, which would test the
integration between the component and the Sortable wrapper. However,
this proved to be difficult, so we use the Sortable API instead.

Fix reorderable list drag not updating indices

---

app/views/featured_attachments/index.html.erb
spec/views/featured_attachments/index.html.erb_spec.rb

https://trello.com/c/7NXYdxZV/1538-user-can-set-desired-featured-attachment-order
This is consistent with the prototype.

Only show reorder action for multiple attachments

---

lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/change_history_check.rb
spec/lib/whitehall_importer/integrity_checker/change_history_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

[Trello](https://trello.com/c/EDTO7mb0/1466-perform-integrity-check-on-the-changehistory-during-migration)
- Update the integrity checker to ensure that the change notes we are replacing match the ones in the Publishing API
- Note to reviewer: I still need to run the import locally or on integration. This may effect whether the timestamps need to match exactly or within a range, but I wanted to open for an initial review.

Perform integrity check on the change_history during migration

---

config/document_type_selections.yml

This reorders specialist notices by the most commonly created type.

Changes order of specialist notices document_type_selections.yml

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

We now want to check the editions state in the integrity checker to verify it's represented correctly between content-publisher and publishing-api. The states don't always have a 1 to 1 matching as content-publisher can have multiple internal states which are equivalent to a publishing-api state. E.g content-publisher's published_but_needs_2i and published map to publishing-api's published state.
Trello:
https://trello.com/c/nuK7ICOU/1591-integrity-check-for-edition-state

Check edition state in integrity check

---

app/controllers/file_attachments_controller.rb
app/helpers/file_attachment_helper.rb
app/interactors/file_attachments/update_file_interactor.rb
app/interactors/file_attachments/update_interactor.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/featured_attachments/index.html.erb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/edit.html.erb
app/views/file_attachments/index.html.erb
app/views/file_attachments/show.html.erb
config/locales/en/file_attachments/edit.yml
config/locales/en/requirements.yml
config/routes.rb
lib/govspeak_document/in_app_options.rb
lib/govspeak_document/payload_options.rb
lib/publishing_api_payload.rb
lib/publishing_api_payload/file_attachment_payload.rb
lib/requirements/file_attachment_metadata_checker.rb
spec/factories/file_attachment_metadata_revision_factory.rb
spec/factories/file_attachment_revision_factory.rb
spec/features/editing_file_attachments/edit_file_attachment_file_spec.rb
spec/features/editing_file_attachments/edit_file_attachment_spec.rb
spec/lib/publishing_api_payload/file_attachment_payload_spec.rb
spec/lib/publishing_api_payload_spec.rb
spec/lib/requirements/file_attachment_metadata_checker_spec.rb
spec/requests/file_attachments_spec.rb

Trello: https://trello.com/c/QZmkUoTr
Adds an edit page that allows users to add a unique reference to existing attachments. The work to allow users to add a unique reference to new attachments will follow in the next PR.
This PR focuses on setting up the architecture of the edit details page (controller actions, route, validations and tests) and should hopefully unblock the work to add the ISBN and Command Paper details.

Allow users to add a unique reference to existing attachments

---

Jenkinsfile
Rakefile
config/locales/en/document_type_selections.yml
lib/tasks/i18n_cov.rake
spec/spec_helper.rb
spec/support/i18n_cov.rb
spec/views/documents/index/_results.html.erb_spec.rb
spec/views/documents/show.html.erb_spec.rb

https://trello.com/c/BhRV4Sqy/1679-increase-our-i18n-coverage-to-100
This add an extra step in our internal I18n coverage checker, which will
return a non-zero (error) exit code if the coverage is below 100%. While
this will be the case when running specific tests, it won't interfere with
the test runner e.g.
Finished in 0.56256 seconds (files took 6.93 seconds to load)
1 example, 0 failures
Coverage report generated for I18n to /govuk/content-publisher/coverage/i18n. 7 / 648 keys (1.08%) covered.
I18n coverage (1.08%) is below the expected minimum coverage (100%)
I18nCov failed with exit 1
Coverage report generated for RSpec to /govuk/content-publisher/coverage. 296 / 528 LOC (56.06%) covered.
SimpleCov failed with exit

Enforce 100% I18n coverage from now on

---

app/controllers/file_attachments_controller.rb
app/views/featured_attachments/_featured_attachment.html.erb
app/views/featured_attachments/index.html.erb
app/views/file_attachments/confirm_delete.html.erb
app/views/file_attachments/edit.html.erb
app/views/file_attachments/replace.html.erb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/requests/file_attachments_spec.rb
spec/spec_helper.rb
spec/views/file_attachments/replace.html.erb_spec.rb
spec/views/images/crop.html.erb_spec.rb

https://trello.com/c/QZmkUoTr/1516-allow-users-to-add-the-unique-reference-as-metadata-for-featured-file-attachments
This changes the upload behaviour for a featured attachment, so that we now
redirect to the additional page for the user to enter metadata.

Go to new attachment metadata page after upload

---

app/assets/javascripts/modules/inline-attachment-modal.js
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/confirm_delete.html.erb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/javascripts/modules/inline-attachment-modal-spec.js

When interacting with attachments via the markdown editor the option to "Delete attachment" will now route the user to a confirmation page. Previously clicking this link would have deleted the attachment and displayed a flash message in the modal.  
Adding a confirmation page in this manner brings attachments in line with other delete actions.

Confirm delete attachment

---

app/controllers/file_attachments_controller.rb
spec/requests/file_attachments_spec.rb

https://trello.com/c/QZmkUoTr/1516-allow-users-to-add-the-unique-reference-as-metadata-for-featured-file-attachments
This fixes the 'Back' link on the new metadata page so that going back
and forth between this page and the replace page works correctly in the
context of replacing an uploaded file, while still in the upload workflow.
I've added some missing request tests to cover the (new) behaviour. We
don't have a precedent for testing the 'Back' links specifically, so I'm
going to defer testing that and write 'pain' card about that instead.
https://trello.com/c/rfna82RY/1712-our-back-actions-are-not-tested

Fix 'Back' link to replace a just-uploaded file

---

lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/change_history_check.rb
spec/lib/whitehall_importer/integrity_checker/change_history_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

https://trello.com/c/EDTO7mb0/1466-perform-integrity-check-on-the-changehistory-during-migration
We have found instances of Whitehall documents with no changes notes; somehow
these were first published in 2016 with no change note. This lack of history is
consistent with the edition representation in the Publishing API, which also
has no change notes. While at least there is consistency in the lack of change
history between Whitehall and Content Publisher, the Integrity Checker fails
for these documents because in the proposed payload we have generated a "First
published." change note which of course doesn't match with what's in the
Publishing API. We've decided it's ok to send the "First published." change
note to Publishing API after these documents have been imported since they
should …

Handle editions with no change history in Integrity Checker

---

lib/whitehall_importer/integrity_checker/body_text_check.rb
spec/lib/whitehall_importer/integrity_checker/body_text_check_spec.rb

[Trello](https://trello.com/c/sSUQCIJp/1559-skip-accessible-format-notice-in-integrity-checker-dwp-dhsc)
There are instances where the proposed payload body for an attachment may include the 'request an accessible format' notice, whereas in the Publishing API body the attachment does not display this notice.
This notice occurs in Whitehall when a checkbox is selected, whereas in Content Publisher, the accessibility notice is determined by the file type.
It may be the case that Whitehall displays this notice, whereas Content Publisher may not. For example, a PDF in Content Publisher will always be deemed in-accessible, whereas in Whitehall, a publisher could mark the content as accessible.
Co-authored-by: 1pretz1 <peter.hartshorn@digital.cabinet-office.gov.uk>

Skip accessible format notice in integrity checker

---

.rubocop.yml

https://trello.com/c/3B7k3YN1/1680-make-our-linting-config-for-rspec-the-standard-for-govuk
Previously we disabled this cop for feature specs with the intention to
explore using 'let' or 'given' instead of instance variables.
This removes the 'TODO', noting instance variables in our feature tests
are assigned *during the test*, so cannot be replaced by 'let' or
'given'. The documentation for this cop also indicates it's meant to be
specific to instance variables assigned in a 'before' block, which could
be replaced with 'let' or 'given'.
```
describe MyClass do
before { @foo = [] }
it { expect(@foo).to be_empty }
end
describe MyClass do
let(:foo) { [] }
it { expect(foo).to be_empty }
end
describe MyClass do
it { <feature_steps> }
def step_x; ... @foo = input_in_form; ... end
def step_y; …
```

Remove 'TODO' to change RSpec/InstanceVariable

---

app/helpers/file_attachment_helper.rb
app/interactors/file_attachments/update_interactor.rb
app/views/file_attachments/edit.html.erb
config/locales/en/file_attachments/edit.yml
config/locales/en/requirements.yml
lib/requirements/file_attachment_metadata_checker.rb
spec/factories/file_attachment_revision_factory.rb
spec/features/editing_file_attachments/edit_file_attachment_spec.rb
spec/lib/publishing_api_payload/file_attachment_payload_spec.rb
spec/lib/requirements/file_attachment_metadata_checker_spec.rb
spec/requests/file_attachments_spec.rb

Trello: https://trello.com/c/vs8MEQKB/1519-support-isbn-for-featured-file-attachments
I wasn't too sure of the error message to use, as it's complicated to explain fully what an ISBN should look like. I'll check the error message with a content designer.

Support ISBN for featured file attachments

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

Annoyingly whitehall rounds down the first_published_at time after the
first edition to the nearest minute for the following editions. This is
reflected in the publishing-api's first_public_at timestamp and so we
have to take this into consideration when doing an integirty check.
```Examples of this behaviour are below:
irb(main):018:0> Document.last(1001).first.editions.order(:id).pluck(:first_published_at)
=> [Mon, 16 Mar 2020 11:00:03 GMT +00:00, Mon, 16 Mar 2020 11:00:00 GMT +00:00, Mon, 16 Mar 2020 11:00:00 GMT +00:00, Mon, 16 Mar 2020 11:00:00 GMT +00:00, Mon, 16 Mar 2020 11:00:00 GMT +00:00]
irb(main):019:0> Document.last(1002).first.editions.order(:id).pluck(:first_published_at)
=> [Sun, 15 Mar 2020 20:31:18 GMT +00:00, Sun, 15 Mar 2020 20:31:00 GMT +00:00]
irb(main):020:0> …
```

Increase the range for comparing first_published_at

---

lib/whitehall_importer/integrity_checker/body_text_check.rb
spec/lib/whitehall_importer/integrity_checker/body_text_check_spec.rb

We need to exclude the file size of the document from both inline and linked inline attachments (those with an anchor tag associated) when comparing the output from Publishing API with that of the proposed Content Publisher output. The proposed will have a space between the size and
the size type, (i.e. 119 KB) and the output on Publishing API will not (i.e. 119KB).
First we need to find all possible attachment HTML blocks, their classes and markup for inline and linked inline attachments on Content Publisher and Publishing API. From there we can create appropriate tests and remove them from the comparison process.
Trello: https://trello.com/c/j3kBctLj/1543-dont-compare-inline-attachment-file-sizes-cma-dwp-dhsc

Don't compare attachment file sizes

---

app/views/file_attachments/replace.html.erb

https://trello.com/c/rfna82RY/1712-our-back-actions-are-not-tested
I've chosen to make this an explicit conditional branch, so it's clear
which 'wizards' the logic applies to.

Fix back link for featured attachment replace

---

app/assets/javascripts/modules/inline-attachment-modal.js
app/assets/javascripts/modules/inline-image-modal.js
app/controllers/images_controller.rb
app/views/file_attachments/confirm_delete.html.erb
app/views/images/_image.html.erb
app/views/images/_lead_image.html.erb
app/views/images/confirm_delete.html.erb
app/views/images/crop.html.erb
app/views/images/edit.html.erb
config/locales/en/images/confirm_delete.yml
config/routes.rb
spec/features/editing_images/delete_image_spec.rb
spec/javascripts/modules/inline-attachment-modal-spec.js
spec/javascripts/modules/inline-image-modal-spec.js
spec/requests/images_spec.rb

Trello Card: https://trello.com/c/duxwb607/1443-confirm-before-deleting-an-image
When interacting with images via the markdown editor the option to "Delete image" will now route the user to a confirmation page. Previously clicking this link would have deleted the image and displayed a flash message in the modal. Adding a confirmation page for deletion is in keeping with changes made to other delete actions, such as deleting drafts and deleting attachments. 
The user will also be routed to this confirmation page in a non-modal context when deleting a lead image.

Confirm delete image

---

lib/whitehall_importer/create_revision.rb
lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/change_history_check.rb
spec/factories/whitehall_export/edition_factory.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/lib/whitehall_importer/import_spec.rb
spec/lib/whitehall_importer/integrity_checker/change_history_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

The previous code for backdating was doing some unexpected things and wasn't fully functional leading to cryptic errors in other parts of the import. This PR addresses those issues. 
More info in the commits ->
Trello:
https://trello.com/c/yR8ES4fq/1628-fix-backdate-bug

Fix backdate bug

---

lib/whitehall_importer/create_edition.rb
lib/whitehall_importer/edition_history.rb
spec/lib/whitehall_importer/create_edition_spec.rb
spec/lib/whitehall_importer/edition_history_spec.rb

For https://trello.com/c/RfpyAbs1/1536-investigate-missing-superseded-event-cma-dwp-dhsc
While building the status for a number of imported superseded editions, an
error has been raised as there is no event with a "superseded" state in the
edition's revision history. After some investigation into the source data in
Whitehall, it transpires that we have instances where superseded editions have
a final event with the state "archived".  For example:
```
"document_id"=>124314,
"state"=>"superseded",
...
"revision_history"=>
[{"event"=>"create",
"created_at"=>"2013-03-06T09:37:56.000+00:00",
"state"=>"imported",
"whodunnit"=>256},
...
{"event"=>"update",
"created_at"=>"2013-09-23T13:27:42.000+01:00",
"state"=>"archived",
"whodunnit"=>817}],
```
"Archived" looks to be an old edition state which …

Import superseded editions with archived history events

---

docs/import-from-whitehall.md
lib/tasks/import.rake
spec/lib/tasks/import_spec.rb

This change adds the ability to import multiple Whitehall documents via a single rake task.
This is especially useful when re-running imports that have failed for debugging purposes.
The associated `import-from-whitehall.md` documentation has also been updated to include this rake task.
Also, removed a un-required environment variable from the `import-from-whitehall.md`.
Trello: https://trello.com/c/RGNEM7u3/1632-add-whitehall-import-rake-task-for-multiple-documents

Add import documents migration task

---

lib/whitehall_importer/integrity_checker.rb
lib/whitehall_importer/integrity_checker/change_history_check.rb
spec/lib/whitehall_importer/integrity_checker/change_history_check_spec.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

Previously this code assumed that publishing-api would return
change_history for draft editions. This has turned out to be incorrect
as publishing-api only returns change_history for live editions. This
has lead to some discrepancies when checking the state of change history
between cp and pub-api.
The difference in behaviour is that content-publisher can return
change_history for non-live editions if the draft edition is a major
change with a change_note and is not the first edition. See ->
https://github.com/alphagov/content-publisher/commit/72b6556e218d66d49e4fd21f14743ea49926d36f#diff-4e6bc683d583eff1852c25cce42073d2R26
The above means that content_history can be different when comparing
drafts so we need to trim the latest draft change_note in cp to reflect
the state in …

Enable change history check to check non first drafts

---

spec/views/documents/history/_content_publisher_entry.html.erb_spec.rb
spec/views/documents/history/_whitehall_entry.html.erb_spec.rb
spec/views/documents/index/_filters.html.erb_spec.rb
spec/views/documents/index/_results.html.erb_spec.rb

https://trello.com/c/3E2vqBkS/1507-support-official-documents-for-featured-file-attachments
This replaces the duplication of the partial to render with the
'top_level_description', which couples the partial rendered to the
described text of the view spec. Using 'top_level_description' is
more consistent with our other specs, where we use 'described_class'.
One caveat is that the description of the view specs is no longer
compatible with the direct use of 'render' (they now lack the '_'),
which seems reasonable, since we should be passing locals to partials,
instead of relying on instance variables in the parent view.

Use 'top_level_description' to render view specs

---

db/migrate/20200403165044_allow_official_document_type_to_be_null.rb
db/schema.rb

https://trello.com/c/3E2vqBkS/1507-support-official-documents-for-featured-file-attachments
Previously we defaulted the official document type to 'unofficial',
but this is inconsistent with the design/intention to force users to
make an explicit selection. If the user aborts the upload workflow
for an attachment, it's also unclear if a selection was made or not.
This changes the column to default the official doc type to null.

Allow official document type to be null

---

app/services/create_next_edition_service.rb
spec/services/create_next_edition_service_spec.rb

When we create a new edition we previously threw a method error if the
current editions change note was nil as we were calling empty? on nil.
As imported editions can have a change note of nil (first edition) we
want to update the conditional to also cater for nil change notes.

Check for nil change_note when creating edition

---

config/document_type_selections.yml
config/document_types.yml
config/locales/en/document_type_selections.yml
config/locales/en/document_types.yml

We want to enable Group 2 Publications for pre-release users so that they can publish them if they onlyneed to add file attachments.
In this PR I have made the following document types 'publishable' by pre-release users 
- Guidance 
- Statutory Guidance
- Decision
- Forms
- Maps
- Regulation
- Promotional material
- Notice
'Non-statutory guidance' is referred to as guidance in the Gov.uk schema, so i've had to rename any reference to 'non_statutory_guidance' to 'guidance.'
Some existing references to 'guidance' have had to be changed to 'guidance_title" in order not to
conflict with my changes made to the 'non_statutory_guidance' id

Make new document types accessible to pre-release

---

lib/tasks/i18n_cov.rake

Outputting the report is not useful if we already have 100%
coverage, and is momentarily confusing as you need to read
the text to establish whether or not the build succeeded.
By only displaying the report if we fall below 100% coverage,
it is immediately obvious when a local build fails and
requires attention.

Avoid outputting i18n report unless it is below 100%

---

app/models/revision.rb
lib/versioning/revision_updater/file_attachment.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/lib/versioning/revision_updater/file_attachment_spec.rb
spec/models/revision_spec.rb

https://trello.com/c/UDEgwkWF/1556-apply-featured-attachment-order-everywhere
This extends the updater module for file attachments to manage the featured
attachment ordering when file attachments are added or removed, so that it
is always representative of the file attachments that are currently
associated with a revision.
We have arbitrarily decided to append new file attachments to the existing
ordering. Please see the commits for more details.

Manage featured attachment ordering

---

app/models/content_revision.rb
app/models/content_revision/contents_validator.rb
app/models/document_type/multi_tag_field.rb
app/models/document_type/topical_events_field.rb
app/models/document_type/world_locations_field.rb
app/models/tags_revision.rb
app/models/tags_revision/tags_validator.rb
spec/interactors/new_document/select_interactor_spec.rb
spec/lib/edition_filter_spec.rb
spec/lib/versioning/revision_updater_spec.rb
spec/lib/whitehall_importer/create_revision_spec.rb
spec/models/content_revision/contents_validator_spec.rb
spec/models/document_type/multi_tag_field_spec.rb
spec/models/document_type/organisations_field_spec.rb
spec/models/document_type/role_appointments_field_spec.rb
spec/models/document_type/topical_events_field_spec.rb
spec/models/tags_revision/tags_validator_spec.rb

https://trello.com/c/xkQzBiFE/1614-content-publisher-document-filter-incident-follow-up
This adds a custom validator around the 'contents' and 'tags'
columns, to ensure that we don't store syntactically invalid
data in these otherwise flexible JSON columns. With this change,
we now apply this schema-like approach to all JSON columns.
Note that, although we could use the document type to detect which
tag fields are permitted, this approach doesn't extend to validating
'contents', since the document type isn't accessible from the
associated ContentRevision.

Add data integrity validations for JSON columns

---

README.md

Previously we explored returning to the original testing behaviour, in a
more fine grained way [1], but ultimately it's necessary for at least some
of the tests, and it occasionally confuses people due to the vague nature
of the errors. This should help future developers understand how to
diagnose errors in tests involving a request.
[1]: https://github.com/alphagov/content-publisher/pull/1890

Add info about debugging errors with requests

---

app/views/featured_attachments/_featured_attachment.html.erb

https://trello.com/c/3E2vqBkS/1507-support-official-documents-for-featured-file-attachments
We want to avoid showing this action in Content Publisher itself,
since it's only relevant for users on GOV.UK itself.

Do not show non-action to 'Order a copy'

---

config/initializers/govuk_error.rb

ActiveRecord can wrap PG:Error exceptions [1] which means that these
can still be sent to Sentry. By also checking the exception cause we can
identify these to ignore them.
Sentry does something a bit more complex than this to ignore exceptions
by building an array of exceptions based off traversing the tree of
causes [2]. Currently this doesn't seem necessary for the types of
exceptions that we're seeing.
[1]: https://github.com/rails/rails/blob/8d57cb39a88787bb6cfb7e1c481556ef6d8ede7a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L51
[2]: https://github.com/getsentry/raven-ruby/blob/8c1e62ba5b8797ea7c16b36bfb7bd1f7af8c6132/lib/raven/configuration.rb#L370

Ignore errors caused by a PG::Error during data sync

---

app/helpers/file_attachment_helper.rb
app/interactors/file_attachments/update_interactor.rb
app/views/file_attachments/edit.html.erb
app/views/file_attachments/edit/_act_paper.html.erb
app/views/file_attachments/edit/_command_paper.html.erb
app/views/file_attachments/edit/_official_document.html.erb
config/locales/en/file_attachments/edit.yml
spec/factories/file_attachment_revision_factory.rb
spec/features/editing_file_attachments/edit_file_attachment_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/interactors/file_attachments/update_interactor_spec.rb
spec/lib/publishing_api_payload/file_attachment_payload_spec.rb
spec/requests/file_attachments_spec.rb
spec/views/featured_attachments/_featured_attachment.html.erb_spec.rb
spec/views/file_attachments/edit.html.erb_spec.rb

https://trello.com/c/hCrcFkHT/1514-render-featured-attachments-in-the-preview-of-a-publication
This extends the existing metadata page/feature with a new radio selection
for the official document type of the attachment, which includes a
conditional paper number. Please see the commits for more details.
Things still to do:

Support official document type and paper number

---

app/services/create_document_service.rb
spec/factories/revision_factory.rb
spec/lib/publishing_api_payload/history_spec.rb
spec/services/create_document_service_spec.rb

Trello: https://trello.com/c/EPhrhTdz/1612-stretch-remove-the-first-published-change-note-from-content-publisher
Setting this no longer has any affect for users as the first change note
is dynamically created at the point of updating the Publishing API and
uses the PublishingApiPayload::History::FIRST_CHANGE_NOTE constant.

Stopping create initial change note

---

docs/adr/0016-publishing-times-and-change-history.md

Trello: https://trello.com/c/GrVzLvnd/1468-document-the-change-note-decisions-in-content-publisher-adr-and-publishing-api-documentation

ADR to record publishing times and change note decisions

---

app/views/documents/show/_featured_attachments.html.erb
config/locales/en/documents/show.yml

https://trello.com/c/a5SwDzjX/1440-show-featured-attachment-metadata-when-reordering-and-on-the-document-summary
I've made the copy consistent with 'No topics', instead of using
what's in the prototype.

Show message when there are no attachments

---

config/initializers/govuk_error.rb

It transpires that this block is called not just with an exception
class in the report of an error it is also called with a Raven::Event
which does not respond to a cause event.
This updates the error filtering to be resilient to the object being
passed in to not conform to a particular interface.
Expected type inputs to this lambda would be a Ruby Exception, a
Raven::Event and a String.
Testing on integration to demonstrate problem before and resolved:
before error: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/137787/
after resolved: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/137789/

Fix Sentry should capture block

---

config/locales/en/document_type_selections.yml

In a tree test there was evidence that users were confusing statutory and non-statutory guidance categories.

Emphasise statutory guidance's role in helping users comply with the law

---

config/document_type_selections.yml
config/locales/en/document_type_selections.yml

Move authored article to news and communications group and correspondence to transparency group because of evidence that users responding to a tree test expected to find correspondence in the transparency group.

Remove articles and correspondence group

---

app/models/document_type/primary_publishing_organisation_field.rb
app/views/tags/edit/_multi_tag_field.html.erb
app/views/tags/edit/_primary_publishing_organisation_field.html.erb
spec/models/document_type/primary_publishing_organisation_field_spec.rb
spec/requests/tags_spec.rb

Previously we added validations on the JSON stored for the 'tags',
which has uncovered a bug where '[""]' was being stored when the
user had no primary publishing organisation (or cleared it). This
fixes the field to properly cleanup the input and also changes it
to behave similarly to a MultiTagField when the param isn't there.

Fix allowing empty primary orgs

---

app/views/documents/show/_requirements.html.erb
spec/views/documents/show/_requirements.html.erb_spec.rb

This also adds a test for the 'requirements' partial. Although there
are lots of potential links to fix requirements, most of them are
shown elsewhere on the summary page, so are arguably for convenience
only. Previously, we found that an alt text issue was blocking for
users, without a link to the page to fix it.
This also removes redundant linking capability for 'credit' and
'caption', since issues for these fields will never appear on the
document summary.
Bug introduced in: 24dce0940cb7b1195a22bfe5226bb89872f5c313

Fix missing link for image alt text issue

---

lib/topic_index.rb

In Content Publisher we expect that the Publishing API has level one
taxons for the homepage and this is needed to render a taxonomy. Today,
however, we experienced the very strange scenario that in integration
the homepage no longer had any links. This caused Content Publisher to
begin to raising syntax errors for running methods on nil.
As this is a very bizarre situation I don't particularly want to write
custom code for handling this but I do think it's better that, in the
event of this situation, the app doesn't raise syntax errors.

Add resiliency to missing level_one_taxons

---

app/interactors/file_attachments/create_interactor.rb
app/interactors/file_attachments/update_file_interactor.rb
app/interactors/file_attachments/update_interactor.rb
app/views/documents/show/_requirements.html.erb
app/views/file_attachments/edit/_act_paper.html.erb
app/views/file_attachments/edit/_command_paper.html.erb
config/locales/en/requirements.yml
lib/requirements/edition_checker.rb
lib/requirements/file_attachment_metadata_checker.rb
lib/requirements/file_attachment_upload_checker.rb
lib/whitehall_importer/create_file_attachment_revision.rb
spec/interactors/file_attachments/create_interactor_spec.rb
spec/interactors/file_attachments/update_interactor_spec.rb
spec/lib/requirements/file_attachment_metadata_checker_spec.rb
spec/lib/requirements/file_attachment_upload_checker_spec.rb
spec/lib/whitehall_importer/create_file_attachment_revision_spec.rb
spec/requests/file_attachments_spec.rb
spec/views/documents/show/_requirements.html.erb_spec.rb

https://trello.com/c/3E2vqBkS/1507-support-official-documents-for-featured-file-attachments
In doing the work for this PR, I noticed that the [EditionChecker](https://github.com/alphagov/content-publisher/blob/master/lib/requirements/edition_checker.rb) has no spec, despite not being (fully) covered at a higher level. It's difficult to add one due to the lack of a common interface for the checkers it delegates to. For the purpose of this PR, I've avoided making any changes to the structure of checkers, and will look at how to write a test for this in a subsequent PR.

Add requirements checks for official docs

---

db/migrate/20200411150039_remove_superfluous_initial_change_notes.rb
db/schema.rb

Trello: https://trello.com/c/EPhrhTdz/1612-stretch-remove-the-first-published-change-note-from-content-publisher
This removes all of the "First published." change notes that are stored
on revisions. This entry does not represent any user input as these were
set automatically when users created the document. These entries are now
superfluous as the initial change note is dynamically created using the
PaublishingApiPayload::History::FIRST_CHANGE_NOTE constant.
There is a risk that this would wipe any user specified change notes of
this note (as unusual as that would be) but as of 11th April 2020 there
are none:
```
MetadataRevision.joins("INNER JOIN revisions ON revisions.metadata_revision_id = metadata_revisions.id").joins("INNER JOIN editions_revisions ON editions_revisions.revision_id = …
```

Remove superfluous initial change note from revisions

---

spec/interactors/file_attachments/create_interactor_spec.rb
spec/interactors/file_attachments/update_file_interactor_spec.rb
spec/interactors/images/create_interactor_spec.rb

https://trello.com/c/UDEgwkWF/1556-apply-featured-attachment-order-everywhere
This turned out to be wasted work, as I realised I was adding the specs in
the wrong place to complete the above card. However, I think it's an overall
improvement, and worth a review. Please see the commits for more details.

Remove redundant interactor specs

---

app/interactors/file_attachments/update_interactor.rb
lib/requirements/edition_checker.rb
lib/requirements/file_attachment_metadata_checker.rb
spec/lib/requirements/file_attachment_metadata_checker_spec.rb

Previously we added new requirements checks that should only apply
to featured attachments, as defined by the type of document they're
associated with. Although the checks primarily run in the context
of the form, which is only available for featured attachments, we
also run these checks at the 'edition level' before publish. This
fixes the edition level check to reflect the type of attachment.

Restrict requirements to featured attachments

---

app/interactors/schedule_proposal/destroy_interactor.rb
app/interactors/schedule_proposal/update_interactor.rb
spec/features/scheduling/propose_publish_time_and_schedule_spec.rb
spec/features/scheduling/propose_publish_time_spec.rb
spec/features/scheduling/update_proposed_publish_time_spec.rb
spec/requests/schedule_proposal_spec.rb

Since 9392d8dcd5a0524bfd2c21c8e8c485b57cd84cb3 we now mark all editions
with revision_synced of false when using the EditDraftEditionService.
This means that when we change proposed publish time we are shown the
actions view to indicate a preview was not successful.
Previously I believe that we didn't update the preview on these actions
as these changes didn't actually affect the Publishing API. However it's
probably best not to treat this as something special.

Update previews when changing schedule proposal

---

config/locales/en/publisher_information/publisher_updates.yml

Online training is now available on how to use Content Publisher. This tells users how to sign up for it.

Include information about how to request training

---

app/views/layouts/_phase_banner_elements.html.erb
app/views/layouts/application.html.erb
app/views/publisher_information/_publisher_info_nav.html.erb
app/views/publisher_information/request_training.html.erb
config/locales/en/application.yml
config/locales/en/publisher_information/request_training.yml
config/routes.rb
spec/features/publisher_information/visit_publisher_information_pages_spec.rb

Trello: https://trello.com/c/3VHD9yYu/1642-add-request-content-publisher-training-page-to-the-publisher-information-section
This adds in the page to explain requesting training. It also has a couple of consistency fixes. See commits for more detail.
Screenshot:

Add "Request Content Publisher training" page

---

lib/tasks/i18n_cov.rake

This prevents any subsequent rake tasks from running.

Don't exit process on full i18n coverage

---

.dependabot/config.yml

Previously we used the Dependabot UI to get top-level updates for
all gems in the Gemfile, which in turn leads to a lot of daily,
manual effort to review and deploy.
However, most of the gems we have in our repos contribute very little
to the codebase, and the risk of them being out-of-date is minimal,
provided we still get any security updates.
This adds an explicit config for Dependabot (to override the UI),
which specified the updates we actually want:
- Security updates. We want to protect are apps the best we can.
Dependabot PRs can help to notify us about vulernabilities, and
make it easy for us to incorporate these into our apps.
- Internal gem updates. We should always be using the latest version
of our internal gems, because they exist to provide consistency among
our apps, which …

Add explicit config for Dependabot

---

README.md
docs/scheduled-publishing.md
lib/tasks/scheduling.rake
spec/lib/tasks/scheduling_spec.rb

This can be used to add any schedulings for publishing to Sidekiq and
has been prepared in anticipation of losing Redis data during a server
migration.
If there are already jobs scheduled this will add them again, this won't
cause any actual problems since the publishing job is idempotent.
However, if we were to run this a lot we'd create rather a lot of noise
in Redis so this isn't advised.
I've included some documentation for this which includes info of our
common risk with scheduled publishing that has mostly lived in status
docs before. I've included some rather cumbersome instructions on how to
fix a failed scheduled publishing were one of those to occur. It seemed
more prudent to provide cumbersome UI steps than to suggest running code
since the task can be achieved with the UI and …

Add rake task to repopulate scheduled jobs

---

app/controllers/errors_controller.rb
spec/requests/errors_spec.rb

We learnt in a recent incident that broke sign-on that it is possible
for the application to error before warden is available as per the
following stack trace:
```
{
"exception_class": "Faraday::SSLError",
"exception_message": "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)",
"stacktrace": [
"/usr/lib/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'",
"/usr/lib/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'",
"/usr/lib/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:996:in `connect'",
"/usr/lib/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'",
"/usr/lib/rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'",
"faraday (1.0.1) …
```

Only authenticate if warden is initialised

---

Gemfile
Gemfile.lock

21.55.1 introduced a bug which causes the component-guide to crash in
Content Publisher.
Issue: https://github.com/alphagov/govuk_publishing_components/issues/1570

Lock to govuk_publishing_components 21.55.0

---

Gemfile
Gemfile.lock

Reverts alphagov/content-publisher#2091

Revert "Bump govuk_publishing_components from 21.55.0 to 21.55.3"

---

app/models/edition.rb
db/migrate/20200701093902_add_auth_bypass_id_to_editions.rb
db/schema.rb

Trello: https://trello.com/c/IQ26eiaW/240-make-content-publisher-use-changing-auth-bypass-tokens
This column is intended to be populated by a uuid that is created for
each edition. The value of this will be shared with the Publishing API
and used in the process to bypass authentication to the draft stack for
a particular content item.
This is introduced to replace the current approach where the documents
content id is used. This approach is flawed for the following reasons:
- It allows an old token to view later drafts of a piece of content
- It isn't practical to change the id in the event of a leak
In order for this system to be backwards compatible these
auth_bypass_id's are initially set-up to use the same algorithm as is
used currently to produce identical ids. Once this is applied …

Add auth_bypass_id column to editions table

---

db/migrate/20200701100346_backfill_auth_bypass_id.rb
db/migrate/20200701131534_auth_bypass_id_not_null.rb
db/schema.rb

Trello: https://trello.com/c/IQ26eiaW/240-make-content-publisher-use-changing-auth-bypass-tokens
This is marked as draft until https://github.com/alphagov/content-publisher/pull/2105 has been merged and deployed to production.
This PR backfills the editions table to populate auth_bypass_id values for every row. Once this migration is complete all entries will have an auth_bypass_id so we can also set it with a NOT NULL db constraint.
In the next PR for this I'll make use of this column in code.

Backfill backwards compatible auth_bypass_id

---

spec/lib/whitehall_importer/create_edition_spec.rb

This is an attempt to fix the test failures seem in https://ci.integration.publishing.service.gov.uk/job/content-publisher/job/master/1860/console. I've identified that the cause of these was expecting the database to return a consistent order (the source of so many test failures).
I also did some cleaning in this epic 500 line spec to make things a bit more consistent and concise.

Fix flakey tests and some other test cleanup

---

lib/tasks/i18n_cov.rake

Since Rails will load this task automatically, we need to prevent
a LoadError in production, where the 'i18n-coverage' gem is not
available. This wraps the whole task definition in a conditional,
since it only makes sense to define the task in dev/test.

Don't LoadError for i18n task in production

---

Gemfile
spec/javascripts/support/jasmine_helper.rb
spec/javascripts/support/jasmine_selenium_runner.yml

Previously we worked around the configuration that JasmineSeleniumRunner
tries to do automatically by removing it from the require option. This
approach is counter to the configuration method the gem provides.
Now that we're recommending using the Content Publisher approach as a
GOV.UK convention it is less surprising to embrace the configuration
approach the gem provides and documents (even though it is a little
strange) rather than having lots of GOV.UK apps try to work around it.
This was prompted by govuk_publishing_components employing a workaround for
the gem `require: false` [1] which felt like a bit of a smell starting.
This functions the same as before (as far as I can tell) just uses the
configuration approach the gem recommends.
I did ponder about whether the Configurer class …

Embrace JasmineSeleniumRunner configuration

---

lib/whitehall_importer/integrity_checker.rb
spec/lib/whitehall_importer/integrity_checker_spec.rb

The Whitehall to Content Publisher migration code uses the presence of the word "placeholder" to determine if we're using a default image.
Whitehall has [recently been updated](https://github.com/alphagov/whitehall/pull/5756) to remove "placeholder" as the
default for image alt text as this was an accessibility fail. The alt text field should now be blank by default

Remove the word "placeholder" from image checker

---

app/interactors/preview/create_interactor.rb
spec/interactors/preview/create_interactor_spec.rb
spec/requests/preview_spec.rb

This resolves a bug where we asserting that an edition had to be
editable to be previewable, this is incorrect as you can preview
scheduled editions. This is easy enough to fix.
A bit more painful was deciding what process to take to add a regression
test for this - as this seemed a relatively easy mistake to make as most
work we do asserts an edition is editable rather than it being pre-live.
We don't really have a pattern to exhaustively test state assertions.
I added the interactor test for this action since there wasn't one
already and validated that the edition assertion test returned the
appropriate message. This seemed sufficient to me as you couldn't change
this without re-considering the logic of the condition.
I then added an explicit test at the request point for the GET …

Fix bug where you can't preview scheduled documents

---

Gemfile.lock

v2.5.1 changes how exceptions in `data_sync_excluded_exceptions`
are treated. They used to be evaluated purely on class name, i.e.
does `exception == "PG::Error"`, meaning if a subclass of the
exception is raised, the evaluation would return false
(`"PG::UndefinedTable" !== "PG::Error"`).
2.5.1 now treats exceptions polymorphically:
`exception.is_a?(PG::Error)`, which now includes subclasses
(`PG::UndefinedTable.new.is_a?(PG::Error) == true`).
The impact of this is that we can suppress the entire suite of
"PG::Error" errors that occur during a data sync, without having
to manually specify each subclass of exception.
See 2.5.1 changenote:
https://github.com/alphagov/govuk_app_config/blob/master/CHANGELOG.md#251
Trello: https://trello.com/c/rAlvGlSp/2123-5-ignore-data-sync-errors-in-govukapp …

Bump govuk_app_config to v2.5.1

---

Jenkinsfile
Rakefile
lib/tasks/lint.rake
package.json

Trello: https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
This app, like many, seemed to get missed in the transition towards removing the lint task in https://github.com/alphagov/govuk-jenkinslib/pull/74. I've also spruced up the rake and standard files a little.

Fix app no longer being linted in CI

---

spec/lib/whitehall_importer/create_revision_spec.rb

Previously the test would change behaviour if the beginning of the
week coincided with yesterday. This ensures the backdated date is
always older than the original publishing date.

Fix test always failing on a Tuesday

---

app/controllers/healthcheck_controller.rb
lib/healthcheck/active_storage.rb
spec/lib/healthcheck/active_storage_spec.rb

https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps
This adds a new check to verify that the app is able to connect to
the backing service we use for ActiveStorage (S3). In order to avoid
any coupling with the contents of the bucket, the check simply makes
a connection to determine whether an item exists.
ActiveStorage plays a critical role in lots of user journeys for this
app. We assume the service is robust and don't provide any special
error handling for it, so we should be aware if it stops working. It's
worth noting a few potential pitfalls of this check:
- Amazon charge per-request to S3. However, request pricing is very cheap:
with 3 backend machines, and roughly 6 requests per minute, it amounts to
about £4pa, per app. I don't think this is a …

Add health check for ActiveStorage service

---

.github/pull_request_template.md

https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps
This is part of enabling CD for the app [1].
[1]: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md#automatic-deployments
:warning: This application is Continuously Deployed: :warning:
- Merged changes are automatically deployed to staging and production.
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) **before** you merge.
- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/content-publisher), after merging.

Add PR template for Continuous Deployment

---

.github/pull_request_template.md

https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps
This got missed as part of the discussion on [1].
[1]: https://github.com/alphagov/content-publisher/pull/2207

Actually shorten PR template

---

app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/modal/modal-workflow.js
package.json
spec/javascripts/components/contact-preview-spec.js
spec/javascripts/components/input-length-suggester-spec.js
spec/javascripts/components/markdown-editor-spec.js
spec/javascripts/components/multi-section-viewer-spec.js
spec/javascripts/components/reorderable-list-spec.js
spec/javascripts/components/toolbar-dropdown-spec.js
spec/javascripts/components/url-preview-spec.js
spec/javascripts/helpers/fetch-mock.js
spec/javascripts/helpers/gtm-mock.js
spec/javascripts/helpers/markdown-editor.js
spec/javascripts/helpers/modal-dialogue.js
spec/javascripts/modal/modal-editor-spec.js
spec/javascripts/modal/modal-fetch-spec.js
spec/javascripts/modal/modal-workflow-spec.js
spec/javascripts/modules/contact-embed-modal-spec.js
spec/javascripts/modules/gtm-copy-paste-listener-spec.js
spec/javascripts/modules/gtm-reorder-listener-spec.js
spec/javascripts/modules/gtm-topic-listener-spec.js
spec/javascripts/modules/inline-attachment-modal-spec.js
spec/javascripts/modules/inline-image-modal-spec.js
spec/javascripts/modules/video-embed-modal-spec.js
spec/javascripts/modules/warn-before-unload-spec.js
yarn.lock

This switches to StandardX so that we can quiet down the many warnings of: "Unexpected var, use let or const instead.". These are a bit misleading as GDS Frontend developers are still keen to use var for improved browser compatibility.
I've also set the eslint envs and globals in package.json to reduce the amount of declarations we need in JS files.

Switch from Standard to Standardx for JS linting

---

app/services/preview_asset_service/payload.rb
spec/services/preview_asset_service/payload_spec.rb

https://trello.com/c/fHPHwU5H/980-look-into-content-publisher-xss-pdf-issue
This depends on: https://github.com/alphagov/asset-manager/pull/828
This tells Asset Manager a files content type when it is uploaded. This
is to resolve a previous problem where Content Publisher determines a
content type by inspecting a files contents, whereas Asset Manager uses
a file extension - when these disagree the output can be inconsistent.
Since Content Publisher already determines the content-type for
validation and storage it seems logical to me that this app tells Asset
Manager rather than leaving Asset Manager to determine itself, the
latter approach could have a few inconsistencies.
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Include content type in the data passed to Asset Manager

---

Jenkinsfile

This is no longer necessary following: https://github.com/alphagov/govuk-jenkinslib/pull/82

Remove Jenkinsfile yarn install step

---

Procfile.dev
README.md
startup.sh

https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This removes legacy "startup.sh" files from this project in favour
of using GOV.UK Docker, which provides more functionality. In order
to keep the README environment-agnostic, we avoid prefixing commands
like "bundle exec rake" with "govuk-docker-run". However, any setup
commands are removed as these are covered by GOV.UK Docker Makefiles,
and are seldom sufficient for comprehensive local development.

Favour GOV.UK Docker for running the app

---

app/views/documents/index/_results.html.erb

This was caused by a change to the underlying component to always insert
a top border. There was then a fix applied in https://github.com/alphagov/govuk_publishing_components/pull/1907
which needs to be manually applied.
Before:
After:

Fix ugly border that has crept into documents

---

Gemfile
Gemfile.lock

This is to resolve a problem where this application is undeployable as
the relied upon gem has been yanked and the current release of the gem
(0.3.7) crashes when it runs.

Switch to using Michael Walker's fork of mimemagic

---

app/views/access_limit/edit.html.erb
app/views/new_document/show.html.erb
app/views/publish/confirmation.html.erb
app/views/schedule/new.html.erb

Changes are being implemented to retire the `is_page_heading` parameter,
using `heading_level`/`heading_size` to achieve the same effect instead.
The reasons behind this are described in more detail in [this issue](https://github.com/alphagov/govuk_publishing_components/issues/1953).
Replace the `is_page_heading:true` option with `heading_level: 1` and `heading_size: 'xl'`

Remove `is_page_heading` param from radio components

---

README.md

In response to: https://github.com/alphagov/govuk_publishing_components/pull/2060#discussion_r631761457
This makes the format consistent with other repos. I've also changed
the overall test command to "rake", which is what we have in all our
other repos. If we need to tell people how to check which framework
is being used, we should do this centrally.

Tweak guidance on running JS tests

---

Jenkinsfile

This changes the Jenkins CI configuration to use Postgres 13.
Postgres 13 is [available at port `54313`][1] on the CI server. By explicitly setting the `TEST_DATABASE_URL`, we're telling Rails to use that Postgres server.
Previously, Rails implicitly used the default Postgres port `5432` which is a Postgres 9.6 server.
Trello ticket: https://trello.com/c/zVdVJqFM
[1]: https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-on-jenkins-ci.html#specifying-which-database-to-use

Use Postgres 13 on Continuous Integration server

---

lib/govspeak_document/in_app_options.rb
spec/lib/govspeak_document/in_app_options_spec.rb

In order for attachments to render a link to the request accessible format form, we need to supply the attachment_id and the owning_document_content_id. This commit adds these to the attachment_attributes hash so that the correct link may be displayed in the in-app preview.
Note: this change is dependant on [this update being made to govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/pull/2636)
[trello](https://trello.com/c/rKvWEhgJ/1095-accessible-format-request-content-publisher-add-parent-document-contentid-to-the-attachment-model)

Allow attachments to show accessible form link in preview

---

lib/govspeak_document/in_app_options.rb
lib/govspeak_document/payload_options.rb
spec/lib/govspeak_document/in_app_options_spec.rb
spec/lib/govspeak_document/payload_options_spec.rb

This commit does two things:
- Adds two attributes to the outgoing payload to Publishing API for
attachments. These are needed to view the new accessible format link
[1].
- Fixed the `attachment_id` for in_app (markdown preview) and
payload_options (Publishing API payload) which was previously pointing
at the incorrect ID, as the attachment ID is the filename in Content
Publisher [2].
[1]: https://github.com/alphagov/govuk_publishing_components/blob/8b8219aa9f8ca615d033c7fb3cd703b5f00e0bed/app/views/govuk_publishing_components/components/_attachment.html.erb#L86
[2]: https://github.com/alphagov/content-publisher/blob/f83065eea9d1e2c617d3c613d8842557af23ca7a/app/helpers/file_attachment_helper.rb#L9
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Adds attachment payload data and fix attachment id

---

docs/removing-documents.md

This change clarifies the difference between the two `remove:` rake tasks in Content Publisher.
Whilst removing and redirecting a document, we found the instructions didn't clearly explain that the `remove:redirect` task would both remove AND redirect the document. It wasn't clear if `remove:gone` needed to be run first or not.
It turns out both tasks will remove the document – so I've tried to tweak the wording to make that more obvious.

Clarify difference between the two removal tasks

---

lib/govspeak_document/in_app_options.rb
lib/govspeak_document/payload_options.rb
spec/lib/govspeak_document/in_app_options_spec.rb
spec/lib/govspeak_document/payload_options_spec.rb

Now that there are no longer any departments taking part, remove code
while we rethink.
https://trello.com/c/iZEzpeFy/1340-remove-dfe-from-the-accessible-format-pilot

Remove support for request accessible format form pilot

---

Gemfile.lock

This fixes the issue that led to the revert in https://github.com/alphagov/content-publisher/pull/2542

Bump to govuk_publishing_components 29.15.1

---

package.json
yarn.lock

Currently, the Paste to Govspeak converter (paste-html-to-govspeak) in the publishing applications automatically converts any H4s, H5s and H6s to a H3 - see https://github.com/alphagov/paste-html-to-govspeak/blob/main/src/html-to-govspeak.js#L88:L89.
We want to remove this functionality and allow H4s, H5s and H6s without them being converted to H3s.
Although GOV.UK doesn't style H4s and below (in non-HTML attachments), it's important for users using assistive technology get the correct heading structure.
https://trello.com/c/aWGmHS2s/573-allow-h4s-to-h6s-with-paste-to-govspeak-converter

Bump paste govspeak to v0.3

---

app/assets/javascripts/components/autocomplete.js

`.forEach` was incorrectly made available to all DOM Iterators in core-js. This has now been fixed in the package: https://github.com/zloirock/core-js/issues/988
The recommended approach for HTMLCollections objects is to use `Array.from` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection). This has been applied to the code to support the `.forEach` function.
This was originally noticed when updating the yarn.lock file in PR #2551.
Credits: @ollietreend for finding the solution.

Fixes incorrectly applied .forEach

---

app/models/document_topics.rb
app/models/topic.rb
lib/topic_index.rb
spec/features/editing_topics/edit_topics_search_spec.rb
spec/features/editing_topics/edit_topics_spec.rb
spec/models/document_topics_spec.rb
spec/requests/topics_spec.rb
spec/support/topics_helper.rb

When a user tags their document to the topic taxonomy, sometimes the document is auto-tagged to a specialist topic. This happens when the topic taxonomy tag (`taxon`) has been provided with a mapped legacy_taxon value in Content Tagger.
Do not automatically tag documents to the specialist topic tree.
**Related PR and full explanation of why we are removing auto-tagging**: https://github.com/alphagov/whitehall/pull/6646
**Trello**: https://trello.com/c/u5dnc3HW/1285-remove-autotagging-to-legacy-taxons-from-content-publisher-m

Remove auto-tagging to legacy-taxons (aka specialist topics)

---

app/controllers/new_document_controller.rb
spec/requests/new_document_spec.rb

This controller redirects to both local and external hosts. This problem wasn't identified as the test only checked local requests.

Fix redirecting to external host on NewDocumentController

---

config/application.rb

This removes code changes that was applied for the transition to Rails
7. Now we have deployed on Rails 7 these are no longer needed.

Resolve post Rails 7 TODOs

---

app/views/components/docs/attachment_meta.yml

Components require a default rendering of a component, which is labeled with default. Without it errors occur when viewing a component preview [1].
I did wonder if there was a better way this could be handled in GOV.UK Publishing Components, as this just produces a cryptic exception when it fails. However both routes I considered seemed problematic:
1) Don't assume there is a "default" example and instead label all
examples with their descriptions. This conflicts with various aspects
of the design for component guide and would require some design
changes
2) Have something that checks the YAML validity of this collection.
There is no YAML checks in the component guide, so adding some in for
this would be unconventional and adding it for the whole file would
be a relatively large task. …

Add a default component for Attachment Meta component guide

---

README.md

Change link from `https://github.com/alphagov/content-publisher/blob/main/docs/editing-change-note-history.md` to `https://github.com/alphagov/content-publisher/blob/main/docs/edit-change-note-history.md`

Fix link to docs in readme

---

.dockerignore
Dockerfile
config/application.rb
config/sidekiq.yml
spec/support/jasmine-browser.json

- Add Dockerfile and .dockerignore
- Fix Rails assets path to include the app name so that assets remain namespaced when uploaded to S3.
- Have Sidekiq log to stdout by default.
Content Publisher is similar to Whitehall in that it has an image (JPEG, PNG etc.) upload feature and expects to be able to exec Imagemagick binaries but doesn't check for them on startup. It also uses Bootsnap and Yarn.
Tested: builds locally on Docker Desktop and runs as far as Puma startup (needs external dependencies to go further so makes sense to test on the integration cluster beyond that point).

Add container image build for running on Kubernetes.

---

.dockerignore
Dockerfile
Gemfile

- Initialise bootsnap [the way we're supposed to](https://github.com/Shopify/bootsnap#usage), to maximise cache efficacy.
- Remove unnecessary use of `bundle exec`.
- Whitespace for clarity.
Tested: app builds and runs locally on Docker Desktop.

Dockerfile cleanup + fix bootsnap.

---

package.json
yarn.lock

Change dependency from Kevin Dew's private repo to `alphagov`
https://trello.com/c/iNuMxfk4/893-adopt-kevins-fork-of-accessible-autocomplete

Change accessible autocomplete dependency

---

app/models/user.rb
app/views/documents/index.html.erb
spec/features/formats/news_article_spec.rb
spec/features/formats/publication_spec.rb
spec/features/workflow/create_document_spec.rb

Users should still be able to edit existing documents. We want to reduce publishing news articles to zero, so that we can eventually retire content publisher.
[Trello card](https://trello.com/c/HLbTAFfK/1497-remove-the-ability-for-users-to-create-new-news-articles-in-content-publisher-or-banner)

Remove the ability for users to create new news articles

---

app/views/layouts/_google_tag_manager.html.erb
app/views/layouts/application.html.erb

In order to be consistent with the other publishing apps we have moved the google tage snippet into a partial. This matches the way this was done in all the other publishing apps owned by the publishing experience team.
Google Tag Manager (GTM) can be included on all pages of the app by configuring the following environment variables:
GOOGLE_TAG_MANAGER_ID
GOOGLE_TAG_MANAGER_AUTH
GOOGLE_TAG_MANAGER_PREVIEW
All three variables are optional.
If none are set, GTM will not be included on the page.
If only GOOGLE_TAG_MANAGER_ID is set, the default environment of the GTM container will be used.
If GOOGLE_TAG_MANAGER_AUTH and GOOGLE_TAG_MANAGER_PREVIEW are set, the specified GTM container environment will be used. This is used for managing the rollout of changes to integration so they can be …

Move google tag manager snippet

---

yarn.lock

This will enable us to upgrade to Yarn 4

Upgrade accessible autocomplete multiselect to latest version

---

lib/whitehall_importer/migrate_assets.rb
spec/lib/whitehall_importer/migrate_assets_spec.rb

We are removing the whitehall_asset endpoint from gds-api-adapters so the script will not be able to run anymore.
To keep most of the code in case it would be needed for future migration, we raise an error and ask to be re-implemented instead. A lot of tests are broken now due to removal of key functionality in migrate assets so we decided to skip them for now so that they can be easily modified and work again if needed.
[Trello card](https://trello.com/c/Kp9nquOr/71-task-remove-whitehallasset-concept-from-asset-manager-and-gds-api-adapters)

Remove usage of whitehall asset

---

app/views/layouts/_phase_banner_elements.html.erb
app/views/layouts/application.html.erb
config/locales/en/publisher_information.yml

Content publisher no longer has it's own feedback form, following https://github.com/alphagov/support/pull/1354 so these links were going to 404 pages.
This updates the links to use the General feedback form, which is intended to be used for issues that don't fit into other categories. We probably don't get much feedback through this route, but broken links look bad. So let's fix 'em.

Update feedback link for content publisher

---

app/views/layouts/_phase_banner_elements.html.erb
app/views/layouts/application.html.erb
app/views/publisher_information/beta_capabilities.html.erb
app/views/publisher_information/how_to_use_publisher.html.erb
app/views/publisher_information/publisher_updates.html.erb
config/locales/en/publisher_information.yml

In https://github.com/alphagov/support/pull/1354, the Content Publisher specific feedback form was removed, and in #3138 the form link was updated to point to the General support form (not specifically designed for feedback).
Content Publisher is no longer actively maintained and it is [destined for archival](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-161-technical-direction-in-publishing-2023.md) at some point. We are therefore not open to feedback requests and should not be pretending we are - so this commit removes references to giving feedback.
Users can still report technical problems via the linked "Raise a support request" technical fault form.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/developme …

Remove feedback form links from Content Publisher

---

.github/workflows/rspec.yml
README.md
spec/db/scrub_access_limited_spec.rb

The Github pipelines are checking out helm charts, whereas it is not doing so locally, so tests are failing locally.
Changing the test to look at a relative path version of helm-charts so it passes both locally and in CI. Unfortunately this means that we are tied to having the helm charts repo checked out to get it passing locally.

Get tests to run locally

---

.github/dependabot.yml
README.md

We're going to reduce the amount of time we spend maintaining this app. See commits for details.
Trello 1: https://trello.com/c/kpf7rWEq/2979-change-dependabot-configs-for-content-publisher-and-maslow
Trello 2: https://trello.com/c/SfO3TzQ3/3017-add-deprecated-notice-to-the-readmes-of-content-publisher-and-maslow
---

Deprecate Content Publisher

---

.github/workflows/rspec.yml

The CI was failing due to ubuntu latest now being ubuntu-24.04, which does not have the ImageMagick library installed.

Pin ubuntu version in rspec workflow

---

config/document_types.yml

- this affects news_story and press_release
- 
https://trello.com/c/6qhFX0hH/524-move-newsarticle-from-government-frontend-to-frontend

Change rendering app for news_article to Frontend

---

app/models/whitehall_migration/document_export.rb
lib/tasks/export.rake
lib/versioning/revision_updater.rb
spec/factories/edition_factory.rb
spec/lib/tasks/export_spec.rb
spec/models/whitehall_migration/document_export_spec.rb

This PR defines two rake tasks that can be used to export content out of Content Publisher:
1. `export:live_document_and_assets`, which exports a single document, given its content ID. By default it outputs to STDOUT but will write to a JSON file if a path is provided.
2. `export:live_documents_and_assets`, which exports all of the live documents and assets. By default it outputs to STDOUT but will write a separate JSON file for each exported document if an output directory is provided.
Usage (respectively):
```bash
rake export:live_document_and_assets["4c2ff601-4494-458b-bdc3-7d358122c2ae","./chris/foo.json"]
rake export:live_documents_and_assets["./chris"]
```
The latter rake task is what we imagine we'll use alongside an import script in Whitehall, to be built in …

Export documents and assets (WHIT-2419)
