alphagov/content-publisher

app/views/layouts/application.html.erb

In other apps, it's conventional to be taken back to Signon when you
click on the user name in the navigation bar (unless we've got something
better).

Fix signon dashboard link for user

---

app/controllers/documents_controller.rb
app/controllers/new_document_controller.rb
app/formats/document_types.yml
app/formats/supertypes.yml
app/views/documents/choose_format.html.erb
app/views/documents/edit.html.erb
app/views/documents/index.html.erb
app/views/layouts/application.html.erb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
config/routes.rb
spec/integration/create_a_document_elsewhere_spec.rb
spec/integration/create_a_document_spec.rb

This implements the 2-step flow of choosing a document type. The designs for this I found [on the Google Drive for Q1][1], so the copy might not match the latest thinking. It should be easy enough to change though.
The commits contain all the details, but I expect a few follow up PRs to this one:
- Refactor YAML handling. I've resisted the temptation to refactor the `YAML.load_file` stuff into classes at this time, because I want to avoid making the decisions about naming / placing stuff now. For what it's worth, I'm thinking about something like `DocumentType.all` and `DocumentType.find("press_release")`.
- Start validating the YAML files and testing them against the schemas.
- Add error handling for when a user doesn't select an option and submits
- Implement whatever happens when you …

Create the choose a format page

---

app/controllers/new_document_controller.rb
app/formats/supertypes.yml
app/views/new_document/choose_supertype.html.erb
app/views/new_document/guidance.govspeak.md
app/views/new_document/guidance.html.erb
config/routes.rb
spec/integration/create_a_document_not_sure_spec.rb

When somebody selects "I'm not sure this should be on GOV.UK", they'll now be redirected to the guidance page.
To achieve this, we've:
- Added a guidance page with the content from https://github.com/alphagov/whitehall-prototype/commit/503d77eb49d0c4e36457039dff23fa7a246ab65f (which is wrong in parts, but that will be fixed later)
- Removed the "I'm not sure this should be on GOV.UK" supertype from the supertypes YAML, because it's unlike the others.
- Created a temporary `SupertypeThing` abstraction that captures some of the logic to generate the radio button input. This will be refactored in a future pull request (likely together with the form
validation).
Paired with @benthorner.
https://trello.com/c/egKyMGRP

Send people who select "Not sure" to guidance page

---

config/application.rb

Currently integration is broken, because we're passing in the `ENV["ERRBIT_ENVIRONMENT_NAME"]` into the layout component, which loads a favicon that doesn't exist:
https://sentry.io/govuk/app-content-publisher/issues/614468696
This commit instead calculates the environment more safely, so that the environment will always be one of production, staging, integration, or development. By default it will be development.

Fix environment indicators

---

app/controllers/documents_controller.rb
app/formats/document_types.yml
app/models/document.rb
app/services/document_type_schema.rb
app/views/documents/edit.html.erb
app/views/documents/input_types/_govspeak.html.erb
db/migrate/20180723183132_add_contents_to_documents.rb
db/schema.rb
spec/integration/edit_a_document_spec.rb

This PR adds the minimum to create a system of format-dependent content editing. It is the first step to allow us to specify the formats in this app in a YAML.
It works like this:
- In the the document types YAML we define `fields` for a type
- Fields have a `id`, `label` and `type`
- Using these fields, we build a form with the correct inputs. In this PR that's just the "govspeak" input, but I imagine we'll have inputs like dates, dropdowns, booleans and more.
- The input of the form is then used in the controller (with an additional param sanitisation step)
- The extracted input is then persisted into the `contents` JSON column, which the forms can access
For future PRs:
- Add more input types
- Add more fields for formats
- Use the `contents` in the payload to the publishing-api
- Use …

Add MVP for format-specific content editing

---

app/controllers/new_document_controller.rb
app/services/document_type_schema.rb
app/services/supertype_schema.rb
app/views/new_document/choose_document_type.html.erb
spec/services/document_type_schema_spec.rb

This refactors the app to use the `DocumentTypeSchema` and `SupertypeSchema` classes. Also fixes the bug that we tried to fix in https://github.com/alphagov/content-publisher/pull/36.
Best reviewed per-commit, and with reading the commit message about ActiveModel.
https://trello.com/c/PxtaaObC/69-how-can-we-define-format-rules-l

Refactor Document type / Super type concepts

---

Gemfile
Gemfile.lock
spec/factories/document_factory.rb
spec/integration/edit_a_document_spec.rb
spec/spec_helper.rb

https://trello.com/c/Vbwd7cye/68-allow-sending-news-to-publishing-api-m
The previous edit spec was actually testing the new document
interaction. Rewriting the spec to test the edit path then prompted
adding FactoryBot to avoid assigning boilerplate document fields (like
the content_id) as part of the test.

Change edit spec to actually test editing

---

db/migrate/20180725084729_fix_document_contents_default.rb
db/schema.rb

The default value for a JSON column should apparently be expressed as the equivalent ruby object, rather than the JSON string.

Fix default for for document contents column

---

app/controllers/documents_controller.rb
app/services/document_publishing_service.rb
app/views/documents/edit.html.erb
app/views/documents/show.html.erb
db/migrate/20180725095923_add_base_path_to_documents.rb
db/schema.rb
spec/factories/document_factory.rb
spec/integration/create_a_document_spec.rb

https://trello.com/c/Vbwd7cye
In order to effectively test publishing, we need to be able to generate
unique URLs for each document. Rather than preempt the intended work of
generating these automatically, for now the user can specify them
manually, without any validation.

Allow user to specify base_path for now

---

app/services/document_type_schema.rb
spec/services/document_type_schema_spec.rb

Trello: https://trello.com/c/Zx8mNyZi/35-investigate-how-could-data-be-exported-from-whitehall-m-1-day
I hit an issue experimenting with Whitehall data as the document_type is news_story rather than news_article (which is the schema name) - I've set this up to raise an exception now as it's quite cryptic debugging this without. 
I've also fixed the document_type values to have news_story - note this will cause problems editing documents if you have news_article document_types in your database.

Raise exception on unknown document types

---

config/initializers/govuk_publishing_components.rb
config/routes.rb

This adds the component guide to the application. This means we can start developing components that are only in this application.
Because we've disabled Static in this app, the normal GOV.UK styling won't work:
https://github.com/alphagov/content-publisher/blob/fee9dbc6c25f4b9f71903daa3cc3284be6599cae/config/application.rb#L30-L33
This is not a big issue, because the components preview correctly. Alex will look at tidying up the component guide so it's better usable in admin apps as well.
https://trello.com/c/YWkUAjtN/45-make-sure-everything-is-documented

Add the component guide to the application

---

app/services/document_publishing_service.rb
spec/integration/publish_a_document_spec.rb

By default, the `publish` endpoint assumes an english locale. This works in this app because we're defaulting to english as well. But in the future we'll have other translations, this PR prepares us for that.
@benthorner

Publish the content in the correct language

---

app/services/document_publishing_service.rb

This is covered by the top-level `first_published_at` field.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/801 for the tests to pass, and https://github.com/alphagov/government-frontend/pull/996 for the frontend.
https://trello.com/c/bMv5Tkgp/77-solve-firstpublicat-issue

Don't send `first_public_at` in the details

---

app/formats/document_types.yml

https://trello.com/c/Vbwd7cye
Avoiding detailed guides for now, as they have additional fields (e.g.
related mainstream URLs), for which we should establish a testing
strategy before adding the new field types to support this behaviour.

Add body field to other document types

---

app/controllers/documents_controller.rb
app/services/document_publishing_service.rb
app/views/documents/edit.html.erb
db/migrate/20180725091148_add_summary_to_documents.rb
db/schema.rb
spec/integration/edit_a_document_spec.rb

This field contains a summary of the document. All of the formats will have this field.
https://trello.com/c/PxtaaObC

Add a summary field to documents

---

app/services/document_publishing_service.rb

https://trello.com/c/Vbwd7cye
This is a required field for email alerts, which gets extracted by the
Publishing API and added to any existing change history i.e. the history
is set and stored incrementally.

Add change_history to API Payload for email alerts

---

app/services/document_publishing_service.rb

https://trello.com/c/Vbwd7cye
We mistakenly thought that change_note was workable attribute for
Whitehall content, but looking again at the schema shows that only
change_history is a documented part of the schema. We should use this
property for now until we make the change history/note dynamic.

Fix email alerting (change_note vs change_history)

---

lib/tasks/import.rake
lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

Trello: https://trello.com/c/Zx8mNyZi/35-investigate-how-could-data-be-exported-from-whitehall-m-1-day
This takes the big wad of JSON that the export:news_documents task produce and imports them as documents. As we don't store much information currently this means that most of that data is ignored.
This relies on: https://github.com/alphagov/whitehall/pull/4238 and can be used like so:
```ssh
cd whitehall
rake export:news_documents ORGS=nuclear-decommissioning-authority OUTPUT=/tmp/nda.json
cd ../content-publisher
rake "import:whitehall_news[/tmp/nda.json]"
```
The test really cuts down the JSON to just the bare minimum for the sake of brevity in the test and may need extending if our required fields increase.
I wasn't quite sure what would be the best place to drop the class for the rake …

Import Whitehall JSON into documents

---

app/controllers/new_document_controller.rb
app/formats/document_types.yml
app/services/document_type_schema.rb
spec/services/document_type_schema_spec.rb
spec/spec_helper.rb

We currently hard code the entire edit URL. This is surprising to users who expect to be redirected to integration when they use the application in that environment.
https://trello.com/c/PxtaaObC

Redirect users to the correct environment

---

app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/index.html.erb
app/views/documents/show.html.erb
spec/integration/edit_a_document_spec.rb
spec/integration/publish_a_document_api_down_spec.rb
spec/integration/publish_a_document_spec.rb

This is another attempt to beautify the app - feel free to modify the branch and discuss :-)
* We should have a way of showing label+value for the show page (currently abusing the label component); similarly for govspeak
* Some of the buttons and text have the wrong font, except for the Publish button - presumably because it's type=submit
*  The Publish button doing a post request is a bit of a hack - should be able to do this by setting the method like rails button_to
* The document list indentation for the index page is messed up, and we should be translating the document_type to look nice
* The flash messages are hard-coded and not very informative in the case of an error - we should expose more detailed info
* The error_message component has an orange and a red outline when it first …

Beautify the pages again

---

app/views/documents/show.html.erb
config/routes.rb
spec/integration/create_a_document_elsewhere_spec.rb
spec/integration/create_a_document_spec.rb
spec/integration/edit_a_document_spec.rb

We currently have integration tests to create and edit a format. We're using the "press release" format as an example for this. This isn't ideal: we're not performing integration tests for the other formats in [document_types.yml](https://github.com/alphagov/content-publisher/blob/master/app/formats/document_types.yml). We might make configuration mistakes like putting in an incorrect `schema_name` for a format, and we have no way to know.
This PR changes the 3 relevant integration tests to instead loop through all the document types we have, and test them as best as we can. Because the formats are pretty much the same at the moment it's pretty easy to do. It might get harder if we introduce new types, but it's probably still worth it.
Best reviewed [without whitespace …

Test all formats automatically

---

spec/factories/document_factory.rb
spec/integration/publish_a_document_api_down_spec.rb
spec/integration/publish_a_document_spec.rb
spec/integration/show_a_document_spec.rb

We should avoid using specific document types in the tests, because we'll implicitly rely on format-specific configuration. We should either test against all formats (https://github.com/alphagov/content-publisher/pull/64) or randomise the document type as is done here.
https://trello.com/c/PxtaaObC

Avoid relying on specific formats in tests

---

startup.sh

Since introducing Puma via govuk_test, we're accidently running Puma when using startup.sh. This makes it use Unicorn like we do in production.

Use unicorn when starting the app from startup.sh

---

app/services/document_publishing_service.rb
app/services/publishing_api_payload.rb
spec/factories/document_factory.rb
spec/services/publishing_api_payload_spec.rb

This converts fields of the type "govspeak" into HTML before sending it to the publishing-api.
The system of transformations is meant to be extensible. if we have more types, they can be added to the `perform_input_type_specific_transformations` method. If it grows sufficiently large, it can be moved into a separate class as well.
I've refactored some payload generation to make this change easier. Those commits can be reviewed separately.
https://trello.com/c/PTR8kN7U

Convert Govspeak to HTML before sending it to publishing-api

---

app/formats/document_types.yml
app/services/content_validator.rb
app/services/document_type_schema.rb
app/views/documents/show.html.erb
spec/factories/document_factory.rb
spec/integration/publishing_validations_spec.rb
spec/services/content_validator_spec.rb

This PR adds validations for content.
There are 2 types:
- Validations that apply to all formats, like title and summary
- Validations that are configured per format. The only example we currently have is the body.
The per-format configuration is intended to use the same syntax as JSON schema. Thus, `min_length` has the same behaviour as `minLength` for strings:
http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3
Caveats:
- I'm not a 100% sure this pattern of validation will scale well. I think we'll see if it works once we add more format-specific validations.
- The minimum number of characters (10) was chosen completely arbitrarily.
https://trello.com/c/PxtaaObC

Show validations for content

---

config/environments/production.rb

In light of https://github.com/alphagov/content-performance-manager/pull/829 this reduces the log level from debug

Change production log level to info

---

spec/integration/edit_a_document_spec.rb

First, this fixes a bug in this test - the `@schema.fields` code is
missing an `each`, so it's currently not doing anything.
Secondly, this makes sure that we raise an error if we encounter an unknown field type. This will come in handy if we add a new field type, because the tests will fails.
Thirdly, this adds a field-specific test to the application. This would have caught the error mentioned earlier.
I'm imagining this being extracted into some kind of class or helper if
we have more field types.

Fill in field specific content

---

spec/integration/edit_a_document_spec.rb
spec/integration/publish_a_document_api_down_spec.rb
spec/integration/publish_a_document_spec.rb
spec/integration/publishing_validations_spec.rb
spec/integration/show_a_document_spec.rb
spec/services/content_validator_spec.rb
spec/services/publishing_api_payload_spec.rb

In most cases in unit tests we need an object of a particular model and it's not required to be persisted.
Using `build` doesn't save the record to the database and makes the tests run faster.

Build models rather than creating

---

app/controllers/documents_controller.rb
app/controllers/new_document_controller.rb
app/formats/document_types.yml
app/services/content_validator.rb
app/services/document_type_schema.rb
app/services/publishing_api_payload.rb
app/services/supertype_schema.rb
app/views/documents/edit.html.erb
app/views/documents/show.html.erb
app/views/new_document/choose_document_type.html.erb
spec/factories/document_factory.rb
spec/formats/configuration_spec.rb
spec/integration/create_a_document_elsewhere_spec.rb
spec/integration/create_a_document_spec.rb
spec/integration/edit_a_document_spec.rb
spec/services/document_type_schema_spec.rb
spec/services/supertype_schema_spec.rb

This PR renames 'fields' to 'contents' to support future data keys at
this level, such as the upcoming 'associations' work.
This PR also makes the document types more consistent with fields and
supertype schemas by renaming 'document_type' to 'id', as well as nested
schema_name and rendering_app under a 'publishing_metadata' hash to
reduce the number of top-level keys and thereby improve readability.
To make this change easier, I refactored the configuration_spec to make
use of the schema models, as opposed to accessing the YAML files
directly. I also replaced several instances of SupertypeSchema.find with
document_type.supertype, so the lookup is done automatically.
This PR also contains a …

Reorganise document types to improve readability

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

This adds a gem & config to make sure that when a Javascript error occurs, the tests fail. 
Looks like this:
If this works in the app we'll push this up to govuk_test.

Make sure the tests fail on Javascript errors

---

app/controllers/new_document_controller.rb
app/formats/supertypes.yml
app/services/supertype_schema.rb
app/views/new_document/choose_supertype.html.erb
spec/formats/configuration_spec.rb

Previously a static not-sure supertype was defined in the new documents
controller, which required a proxy SupertypeThing class to handle the
generation and processing of options. My original intention was simply
to move this class into /services to highlight its existance, but
instead this PR is an attempt to remove it altogether by adding a 'path'
option to supertypes, behaving similarly to managed_elsewhere for docs.
I also added a few more configuration_specs after the required spec to check
a document_type has not been associated with the new "not-sure" supertype.

Replace supertype thing as a first-class supertype

---

spec/factories/document_factory.rb
spec/features/publishing_validations_spec.rb
spec/services/content_validator_spec.rb
spec/services/publishing_api_payload_spec.rb

The previous document trait of :with_body implied the resulting document
would have a populated body. Since the trait is actually effecting the
document_type, it makes more sense to say it as :with_body_in_schema.

Make factory traits about schemas more clear

---

app/formats/document_types.yml
app/formats/supertypes.yml

Fix typos for 'Transparency' in a couple of places.

Fix typos for 'Transparency' content

---

app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show.html.erb

The separation between the source of the data (the schema) and the use
of that data in a field partial (name, label) making it hard to remember
which value came from where. Passing the schema through to the partial
and explicitly calling it a schema (it's not a field) makes the link
between data and view more visible. In general we should try to be more
consistent in our variable names to differentiate between a schema from
the config file and something that's created to conform to the schema.

Pass schema through to field partials

---

app/models/user.rb
db/migrate/20180725084729_fix_document_contents_default.rb
lib/tasks/lint.rake
spec/spec_helper.rb

govuk-lint-ruby has some rails-specific checks, which we should turn on.

Turn on rails linting (and fix offences)

---

.gitignore
Jenkinsfile
README.md
app/assets/javascripts/application.js
lib/tasks/lint.rake
package-lock.json
package.json

This adds the StandardJS linter as advised in https://github.com/alphagov/styleguides/blob/master/js.md#linting
This uses NPM to install the linter rather than Yarn as our CI servers
do have NPM installed and don't have Yarn. Since Yarn plays nicer with
Rails that is probably a better option to take moving forward if we make
use of node-modules in the app, but this seems a reasonable approach for
now.
This sets up a lint and a lint:fix command, the latter can be used to
fix issues automatically.
Slightly annoying thing with this is not caching the node_modules between builds :-/
@alex-ju you might have opinions on this and the usefulness of it. It also seems like we've jumped from a no semi-colon land to a semi-colon land in GDS JS standards in the switch from standardJs to XO.

Lint Javascript with StandardJS

---

spec/services/document_type_schema_spec.rb

This spec was originally written to ensure we were doing a to_a on the
fields param, but it's very much covered by the feature tests - all of
them fail if it's removed. Rather than copy/paste this for the upcoming
'associations' param, it seems better to remove it but keep the coverage.

Remove redundant spec for document_type_schema

---

spec/spec_helper.rb

Note this still supports showing JavaScript errors in the test output.

Stop showing puma startup logs in JS tests

---

app/controllers/documents_controller.rb
app/controllers/publish_document_controller.rb

In particular, we should handling GdsApi::TimedOutException explicitly.

Catch more API errors and display them well

---

app/assets/javascripts/application.js
app/assets/javascripts/components/contextual-guidance.js
app/assets/javascripts/components/markdown-editor.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/views/components/_contextual-guidance.html.erb
app/views/components/docs/contextual-guidance.yml
app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb
package-lock.json
package.json
startup.sh

This PR:
- Sets up a basic markdown editor using GitHub's toolbar web component. For the moment the editor doesn't contain the govspeak syntax and will be extended in a separate PR
- Add contextual guidance component with dummy content for now. It will be updated when the content is ready and the content will be separated from the view.
[Trello card](https://trello.com/c/yKPf7Kd6)

Add basic govspeak editor and contextual guidance

---

app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/vendor/marked/lib/marked.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/views/components/_markdown-editor.html.erb
app/views/components/docs/markdown-editor.yml
app/views/documents/fields/_govspeak_input.html.erb

This PR:
- Makes the markdown editor a component
- Allows markdown preview
- Sets `$govuk-global-styles: true;` to style anchors, paragraphs and headings in markdown preview

Add markdown preview

---

app/controllers/new_document_controller.rb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
config/routes.rb
spec/features/choose_a_format_spec.rb

https://trello.com/c/EDDD2DYl/128-handle-when-the-user-doesnt-select-a-supertype-or-document-type
This prevents the user reaching an error page in the case where they
forget to choose a supertype or a document type, and then click the
'Continue' button when creating a document.
The page to choose a document type was previously a POST route, which
made it awkward to re-visit the page if the user doesn't select a
document type and clicks 'Continue'. To support re-visiting the page,
the route is now a GET route and the form_tag for choosing a supertype
now has the explicit route to get to it, turning off the UTF8 character
set param to keep the resulting URL query params clean.
Note that there's still a spurious 'button' query param, which is added by the 
form submit button. There's a …

Ensure user chooses supertype / document type

---

app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/vendor/@github/markdown-toolbar-element/dist/index.umd.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/components/_markdown-toolbar.scss
app/views/components/_markdown-toolbar.html.erb
app/views/components/docs/markdown-toolbar.yml
app/views/documents/fields/_govspeak_input.html.erb

This PR:
- moves markdown-toolbar in a component
- groups toolbar items in sections using the `details` component and add links to the relevant guidance (the content of these sections will be reviewed with a content designer and potentially read from a separate file)
- ~prevents markdown contextual guidance to overlap footer or other components on small screens~
- extends markdown-toolbar with the following snippets:
- heading 2 (`##`), heading 3 (`###`), heading 4 (`####`)
- ~call to action~ (`$CTA [Start](url) %CTA`)
- link email (`<john.doe@mail.tld>`)
- ~address~ (`$A 10 Whitechapel $A`)
- ~configures marked renderer to~
- support line breaks
- render tables
- sanitise user input
- removes the absolute position of contextual guidance
[Trello card](https://trello.com/c/yKPf7Kd6)

Extend markdown toolbar

---

app/formats/document_types.yml

The lack of any format for the policy supertype is leading to Sentry
errors where the user click 'Continue' but no format is selected.
We should separately also validate the supertype form and the format
form to check that an option has been selected.

Add at least one format for the policy supertype

---

Gemfile.lock

This removes the spurious button query param when creating a new document.

Upgrade govuk-publishing-components

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_summary.scss
app/views/components/_summary.html.erb
app/views/components/docs/summary.yml
app/views/documents/associations/_multi_association.html.erb
app/views/documents/fields/_govspeak.html.erb
app/views/documents/show.html.erb
spec/features/create_a_document_api_down_spec.rb

This PR:
- Adds the summary component based on [Check answers pattern](https://design-system.service.gov.uk/patterns/check-answers/)
- Defines two examples for the summary page component
- Updates `show` and `multi_association` views to use the summary component
Note:
The associations section in the summary page spans both `show` view and `multi_association` partial - due to iteration over `document_type_schema.associations`. Would be good to pair with a backend dev and try and refactor this so we can use the component instead of plain markup.
[Trello card](https://trello.com/c/lsCHlZTt)

Update summary page

---

app/assets/javascripts/components/markdown-editor.js
app/assets/stylesheets/components/_markdown-editor.scss
app/views/components/_markdown-editor.html.erb
app/views/components/docs/markdown-editor.yml
app/views/documents/fields/_govspeak_input.html.erb

This PR:
- makes the preview bar hidden by default (when JavaScript is disabled the preview bar will not be shown) and enable it via JavaScript
- moves the "Nothing to preview" message from markup to JavaScript to be consistent with "Error previewing content" - it won't be shown/used anyway without having JavaScript enabled.
- adds a `js-markdown` prefix for element queries to prevent clashes with other components
- adds a default example for the markdown editor component

Update markdown editor component

---

app/views/components/_markdown-editor.html.erb

Explicitly sets types for secondary buttons in forms.
@tijmenb found a bug when hitting enter on an input field would trigger the first button on the form (in our case the preview button) instead of the "Save" button. Setting these buttons explicitly to `type="button"` will avoid having this issue when the component is used in any form.

Set type button for toggle preview

---

app/views/documents/show.html.erb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_contents.html.erb
app/views/documents/show_api_down.html.erb

This PR updates `documents/show` and `documents/show_api_down` to share `_contents` and `_actions` as partials
[Trello card](https://trello.com/c/lsCHlZTt)

Update show views to share partials

---

app.json
app/services/document_url.rb
app/services/publishing_api_payload.rb
app/views/documents/show/_actions.html.erb
spec/services/document_url_spec.rb
spec/spec_helper.rb

This temporarily adds 3 links to the action menu:
- View on GOV.UK - for the live version of the page
- Preview - the draft page on the draft stack, Signon required
- Shareable preview - the draft page with secret token to bypass Signon
I'm assuming we'll redesign the placing of these links, so I haven't added integration tests for this. This PR is just to add the logic of the links.
The "bypass" code is mostly taken from mainstream publisher and collections-publisher (who introduced the same feature recently - https://github.com/alphagov/collections-publisher/pull/428). It's a complicated system, and I hope I've explained it a bit in the comments.
For this to work on production, we'll need to make `JWT_AUTH_SECRET` available to content publisher: …

Add preview & shareable preview links

---

config/application.rb
config/locales/en.yml
spec/models/document_spec.rb

The `publishing` state was renamed to `sending_to_live` at some point. This fixes that and adds tests.
https://trello.com/c/i6C3pY03

Fix renamed state name in translations

---

app/controllers/documentation_controller.rb
app/views/documentation/index.html.erb
config/routes.rb
spec/features/documentation_spec.rb

This is a first stab at a documentation approach for this app. The target of these docs are the people working on it - the PM, DM, user researchers, designers, content designers, and developers.
My dream for documentation is that content publisher will be able to "explain itself", rather than needing developers to explain it. It's mainly inspired by the difficulty we have in understanding the current workings of Whitehall.
This PR adds two things to `/documentation`:
- All the formats. This is to answer the question "What formats are currently available in this application?". Instead of reading the code, or clicking through the entire app, team members have access to a single list.
- All the publication states. This is especially important because some will be rare or transient, so having …

Start exposing the inner workings of the application

---

app/views/documentation/index.html.erb
config/locales/en/documentation/index.yml

Note that publication_states now violate the convention for where to put
translations, as they appear across multiple views. This should be
looked at in a subsequent PR.

Add missing translations for documentation

---

app.json

It also make sense to automatically populate the values to avoid losing
them if something goes wrong with Heroku.

Fix missing env variable for Publishing API

---

Jenkinsfile
app/services/document_url.rb
config/application.rb
config/secrets.yml
spec/services/document_url_spec.rb
spec/spec_helper.rb

Trello: https://trello.com/c/ECYqAHfX/98-allow-users-to-preview-the-content-s
This moves the handling of this to be done by inclusion in the secrets
file and a check in application.rb rather than using ENV.fetch.
This was prompted by a number of instances where devs were getting
caught without this ENV var.

Manage JWT_AUTH_SECRET by Rails secrets

---

app/services/document_url.rb
spec/services/document_url_spec.rb

This happens when a user aborts the document creation process (never
clicks save on the edit form) before we can assign (even a blank)
base_path. We can't set a default in the DB, as this would violate the
uniqueness constraint when multiple users start creating documents.

Fix url preview errors when base_path is nil

---

app/assets/stylesheets/components/_markdown-editor.scss
app/formats/document_types.yml
app/javascript/components/markdown-editor.js
app/javascript/components/markdown-toolbar.js
app/views/components/_markdown-editor.html.erb
app/views/documents/edit.html.erb
config/locales/en/documents/edit.yml
package.json

This PR:
- Disables the autocomplete on the edit form
- Updates edit page content
- Replace toggle link with tabs for markdown preview
- use `webcomponents-bundle` instead of `webcomponents-loader`, as the loader doesn't contain the polyfills (Firefox and IE fail now because of the lack of this polyfill)
- Replace Markdown toolbar elements with the extended version (this was causing the Heading injectors to fail, because they're not part of the original Github Toolbar)
- Github doesn't doesn't publish the source code for the markdown toolbar element in its package so we need to publish our own fork to npm. Until then we'll bring the transpiled code in the project.

Update edit document page

---

app/javascript/packs/application.js
app/views/layouts/application.html.erb
config/webpack/production.js
package.json
yarn.lock

Trello: https://trello.com/c/0pzXlC9R/144-track-javascript-errors-s
Raven-js is a JS module that is used to send errors to sentry.io. To
enable us to do this we expose our SENTRY_DSN and SENTRY_CURRENT_ENV
environment variables to HTML meta tags. We then read those attributes
in as part of our Javascript initialisation and install Sentry.
The code for the application is then wrapped in a Raven.context function
as recommended by: https://docs.sentry.io/clients/javascript/#configuring-the-client
Finally we set Raven as a global variable on window so that it can be
available in the console for testing purposes.
I've configured sentry to just accept errors from *.publishing.service.gov.uk hosts, ~I'm going to expand this to include heroku too.~ - actually I can't do that since we don't have a …

Integrate application with raven-js

---

public/404.html
public/500.html

These were created with a relative path and thus fail if you get an
error or 404 on a page that is not at a root path. E.g. we'd fail to
load the stylesheet on a page like /documents/id as it would try load
the stylesheet at documents/error.css

Fix links to error.css

---

app.json
config/environments/development.rb
config/environments/production.rb

This allows us to configure Heroku to use the local settings for this
rather than hook it up to AWS - Heroku does warn us about using this
since the data wouldn't be available if the dyno is restarted or if we
run multiple dynos. But this seems a pretty low risk scenario for PR
previews.

Make active storage service configurable by env var

---

app/formats/document_types.yml
app/models/document.rb
app/views/documents/edit.html.erb

For https://trello.com/c/Gm1BOO1O/151-review-pages-with-updated-content-in-content-publisher-s
_Note:_ It's unclear where Worldwide Organisations should go. I've tagged Ben H in the Google doc to check; in the meantime it seems logical to place it near to Organisations.

Additional content changes

---

app/views/documents/show_api_down.html.erb

In the translation files `document.show.title` has been renamed
`document.show.title_default`. This is an instance where this hasn't been
updated and is causing the page to break.

Fix title bug on show_api_down page

---

config/application.rb

We store dates in the database in UTC, which means that when we're displaying
dates and times in the views they're an hour out of date during daylight saving
time. This sets the app's time zone to 'London' so that ActiveRecord
automatically converts dates and times to the UK's current time zone, whether
it's GMT or BST.

Set app time zone to London

---

app/views/layouts/application.html.erb

This PR adds the Google Tag Manager component and it needs [Add Google Tag Manager env vars for Content Publisher](https://github.com/alphagov/govuk-puppet/pull/8041) to get merged in order to render the component. Raised this PR to have it ready.
[Trello card](https://trello.com/c/wh7K3ul2)

Add Google Tag Manager script

---

app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/utilities/_overwrites.scss

This PR: 
- Prevent textarea component to be resized beyond the bounds of its container
- Disallow horizontal resize for the markdown editor's textarea
Textarea resized beyond the bounds of its container
Markdown editor resized horizontally

Fix textarea resize

---

app/javascript/components/markdown-editor.js

This PR adds target blank to anchors generated in the preview container so the user doesn't loose the current page when clicking them.

Set anchors in the preview container to open in a new tab

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_formatted-text.scss
app/views/components/_formatted_text.html.erb
app/views/components/docs/markdown_raw.yml
app/views/documents/fields/_govspeak.html.erb

https://trello.com/c/tOx0eK0R/176-show-raw-markdown-and-truncate-output-on-summary-page
We think users will find it confusing to see styled markdown content
next to static page content (e.g. titles), so this commit changes the
preview to show the raw markdown using a new 'markdown_raw' component.
The component truncates the raw markdown by lines, for which 3 lines
seems to give a reasonable preview (two paragraphs, or title and a
paragraph).

Show raw markdown on the summary page

---

app/controllers/new_document_controller.rb
app/models/document.rb
app/models/user.rb
app/views/documents/show/_actions.html.erb
config/locales/en/documents/show.yml
db/migrate/20180831100426_add_creator_to_documents.rb
db/schema.rb
spec/factories/document_factory.rb
spec/features/show_a_document_spec.rb
spec/features/show_a_document_with_no_creator_spec.rb

For https://trello.com/c/Th0t8cUb/165-associate-a-document-with-the-user-who-created-it
In this PR we associate a document with a creator so we're able to look up who created it.  This allows us to display information about the person who created the document; for now it will just be the creator's name on the document summary page, but in future could include their organisation for example.
We also handle instances where a document has no creator by displaying it as "Unknown".

Associate document with user who created it

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_page_preview.scss
app/controllers/preview_controller.rb
app/views/components/_page_preview.html.erb
app/views/components/docs/page_preview.yml
app/views/preview/show.html.erb
config/routes.rb
spec/components/page_preview_spec.rb
spec/features/preview_document_spec.rb

This adds the first bit of the [preview page](https://trello.com/c/KO7s5XJG/152-design-the-preview-page-s). 
It only implements the desktop view (see other todo's on the Trello ticket).
https://trello.com/c/i2Fi5qNQ

Add separate preview page

---

lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

https://trello.com/c/ORACsrIh/172-create-a-jenkins-job-to-update-integration-content-publisher-with-whitehall-content
The Whitehall export of news articles now includes the locale-specific
base_path as part of each translation. Previously we were using the
document-level slug, which caused conflicts for documents with multiple
locales.

Import document from custom translation base path

---

app/assets/stylesheets/components/_page_preview.scss
app/views/components/_page_preview.html.erb
app/views/components/docs/page_preview.yml
app/views/preview/show.html.erb
spec/components/page_preview_spec.rb

This adds a search engine snippet preview to the preview page.
https://trello.com/c/i2Fi5qNQ

Add search engine snippet preview

---

lib/tasks/import.rake
lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

https://trello.com/c/ORACsrIh/172-create-a-jenkins-job-to-update-integration-content-publisher-with-whitehall-content
This will allow us to stream documents into the app without having to
copy the export file onto the machine.

Allow streaming documents from Whitehall export

---

app/views/documents/show/_actions.html.erb
spec/features/preview_document_spec.rb

This changes the action link to go to the new separate preview page, so the user can see the preview on mobile, desktop and Google.
https://trello.com/c/i2Fi5qNQ

Link to the separate preview page

---

app/views/documents/show/_actions.html.erb
config/locales/en/documents/show.yml

We established a convention that clickable items should not have
translations, as we felt it made the tests too difficult to read. These
ones appear to have been missed when we applied this convention.

Remove stray translations for clickable items

---

lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

For https://trello.com/c/LVpjWa42/173-update-whitehall-import-script-to-support-organisations
This updates the Whitehall import script to handle a document summary and its various associations.

Update Whitehall import script

---

app/controllers/document_images_controller.rb
app/models/image.rb
app/validators/image_aspect_ratio_validator.rb
config/locales/en/validations.yml
config/routes.rb
spec/controllers/document_images_controller_spec.rb
spec/factories/image_factory.rb
spec/models/image_spec.rb
spec/validators/image_aspect_ratio_validator_spec.rb

Trello: https://trello.com/c/jY14RKov/182-create-endpoint-for-cropping-image-via-javascript
This is a refactor of https://github.com/alphagov/content-publisher/pull/188 based on feedback. 
This switches the validations to be done on model layer and then, since we're doing that, sets up an update image endpoint rather than a crop endpoint.
Because we're updating the image directly we then need to accept the parameters in the form of the db structure (or we have to do some mapping and swapping). 
Having put this together I'm feeling that this is potentially the worse of the routes, it may be way more consistent with how Rails does things in a RESTful context but since we don't really seem to be operating in this manner for the rest of the app it feels like an exception. It also fears like …

Update image endpoint for cropping

---

lib/tasks/whitehall_news_importer.rb

The `lead_organisations` instance variable is only instantiated once when
importing many documents, which meant that it didn't return the correct lead
organisations for each document. We remove this and return the current
edition's lead organisations instead.
We also remove the `to_import` attr_reader as this instance variable is not
used by anything anymore.

Remove unncessary code from Whitehall News Importer

---

app/controllers/govspeak_preview_controller.rb
app/javascript/components/markdown-editor.js
spec/features/previews_govspeak_when_editing_spec.rb

https://trello.com/c/ORACsrIh/172-create-a-jenkins-job-to-update-integration-content-publisher-with-whitehall-content
It looks like Rack is interpreting the body text as ASCII-8BIT rather
than UTF-8, so we need to force this encoding.

Fix encoding issue with govspeak preview body

---

app/assets/javascripts/components/markdown-editor.js
spec/features/previews_govspeak_when_editing_spec.rb

I got caught by this test failing a number of times for me locally which
seems to be related to a timing issue. The hypothesis is that if the
fetch request doesn't return rendered govspeak before capybara looks up
the rendered govspeak then the test will fail.
This can be confirmed by adding a sleep(1) to the render govspeak
controller.
This resolves this issue by adding a class when govspeak is rendered -
this means the capybara finder will keep trying until the class exists.

Add state class as selector to avoid flaky test

---

app/controllers/document_tags_controller.rb
app/controllers/documents_controller.rb

This allows us to have multiple views containing GdsApi code and still
handle the API down case gracefully via a dedicated view.

Make API down rescue mechanism generic

---

app/services/document_type_schema.rb
app/services/supertype_schema.rb

The redirect URLs aren't working on integration because we're using the internal hostname
(`whitehall-admin.integration.govuk-internal.digital`) instead of the external (`whitehall-admin.publishing.service.gov.uk`).
https://trello.com/c/5GSUif0g

Fix URLs on integration

---

app/services/user_facing_state.rb
spec/services/user_facing_state_spec.rb

This makes sure that we handle the transitional states `sending_to_draft` and `sending_to_live` consistently. As discussed in https://trello.com/c/VkVrVGeB, users don't need to see these states. We'll consider something `sending_to_draft` to be the same as `sent_to_draft`, and `sending_to_live` the same as `sent_to_live`.
https://trello.com/c/VkVrVGeB

Consistently handle transitional states

---

app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb

This fixes a slight reposition of the radio items when there is no conditionally revealed content. It was caused by the empty paragraph generated by the govspeak converter.
https://trello.com/c/5GSUif0g

Fix issue with a slight reposition of conditional content

---

app/controllers/review_controller.rb
app/views/documents/show/_submitted_for_review.html.erb
app/views/documents/show/_summary_tab.html.erb
config/locales/en/documents/show.yml
spec/features/force_publishing_spec.rb

This is the flash message that occurs when the user has submitted the
content for review.
https://trello.com/c/9szY348f

Implement flash messages after 2i submit

---

app/assets/stylesheets/components/_page_preview.scss
app/views/components/_page_preview.html.erb

This PR updates the page preview component to:
- restrict the share component width to two thirds
- refactors the SCSS and calculate the mobile frame width and height
- make the search engine snippet preview responsive (setting `max-width`)
[Trello card](https://trello.com/c/i2Fi5qNQ)

Update mobile preview

---

app/controllers/documents_controller.rb
app/controllers/new_document_controller.rb
app/models/document.rb
app/services/document_publishing_service.rb
app/services/publishing_api_payload.rb
app/views/documents/edit.html.erb
app/views/documents/edit/_change_notes.html.erb
app/views/documents/show/_contents.html.erb
config/locales/en/documents/edit.yml
config/locales/en/documents/show.yml
db/migrate/20180906154457_add_has_live_version_on_govuk_to_documents.rb
db/migrate/20180906155513_add_change_notes_to_documents.rb
db/schema.rb
spec/features/change_notes_spec.rb
spec/features/create_a_document_spec.rb
spec/features/publish_a_document_spec.rb
spec/services/document_publishing_service_spec.rb

This implements the change note and update type feature.
- Users can now add a change note and select an update type in the edit screen.
- When a document is first created, it has a "major" update type by default and "First published." as change note. This can't be changed.
- The update type and change note are sent to the publishing-api, so change notes for major updates will be displayed on the site. The update type is no longer part of the `publish` call.
- The change note is displayed on the summary page as well.
- After a document is published, we reset the update type and change note.
- I've added a test for the creation of a document, because there wasn't a feature test that tests all the things that need to be set up when the document is first created.
- The layout of the new form …

Implement change note and update type feature

---

app/views/publish_document/published.html.erb

This PR updates the published page to use the "newly added to the gem" [panel component](https://govuk-publishing-components.herokuapp.com/component-guide/panel).
[Trello card](https://trello.com/c/1fOAUyRc)

Use panel component

---

app/views/documents/show/_actions.html.erb

This PR updates the styles used for action links to reflect the design.

Update action link styles to reflect design

---

app/views/documents/edit/_change_notes.html.erb
config/locales/en/documents/edit.yml

This replaces the hint and guidance for change notes with right-hand contextual guidance. This makes the page less busy and is more consistent with the other fields.
https://trello.com/c/NEQWHpoU

Redesign guidance for change notes

---

app/views/components/_autocomplete.html.erb
app/views/components/_markdown_editor.html.erb
app/views/document_tags/tags/_multi_tag_input.html.erb
app/views/document_tags/tags/_single_tag_input.html.erb
app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb

This PR:
- sets bold labels for textarea fileds on edit document page
- sets bold labels for autocomplete fileds on edit tags page

Set bold labels for edit pages

---

app/controllers/documents_controller.rb
app/views/documents/show/_actions.html.erb
config/locales/en/documents/show.yml
config/routes.rb
spec/features/create_a_document_api_down_spec.rb

When a document is saved, we attempt to send it to the publishing-api as draft. This goes wrong sometimes, either because the publishing-api isn't available (in development), the publishing-api is slow to respond
(when it's busy) or when we're accidentally sending an invalid payload to the publishing-api (this should not be possible, but it's likely that we'll make mistakes in this).
This commit adds a "retry" button to the page when the draft publishing hasn't succeeded. This isn't a particularly elegant solution (as in, requiring fewer lines of code), but I can't think of anything better at the moment.
It's intent is to communicate to the user that something went wrong, and gives an option to fix the problem.
https://trello.com/c/VkVrVGeB

Deal consistently with errors sending to draft

---

app/controllers/document_tags_controller.rb

This will raise an error is the document is invalid, instead of silently swallowing it. `Model#update` is only to be used if we're using the return value to check if the update was successful or not.

Use `update!` to save documents

---

app/services/user_facing_state.rb
spec/services/user_facing_state_spec.rb

Trello: https://trello.com/c/l8MAts3s/205-build-the-index-page-with-filtering
This ties into the index page PR: https://github.com/alphagov/content-publisher/pull/244as that's still in flight I've extracted this aspect of it out, since it could be controversial. 
This creates scope methods for each of the current known user facing
states.
The intention is to use these as part of the document index where there
is a Whitehall quirk that is intended to be kept as a feature. This is
that for when a filter is applied to published documents this returns
results all published items whether they need a review or not.

Scopes methods for user facing state

---

app/views/documents/index/_results.html.erb
app/views/documents/show/_document_metadata.html.erb
config/locales/en/documents/index.yml
config/locales/en/documents/show.yml
spec/features/show_a_document_with_no_creator_spec.rb

This is to fix the index page currently throwing an exception when the
user who created the document does not exist.
I felt the key unknown_data was a bit abstract so went for a more
explicit unknown_creator

Handle unknown document creator on index page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/image_list.scss
app/controllers/document_lead_image_controller.rb
app/formats/document_types.yml
app/models/document.rb
app/models/image.rb
app/services/document_type_schema.rb
app/views/document_lead_image/_image_list.html.erb
app/views/document_lead_image/edit.html.erb
app/views/document_lead_image/index.html.erb
app/views/documents/show/_lead_image.html.erb
app/views/documents/show/_summary_tab.html.erb
app/views/documents/show_api_down.html.erb
app/views/layouts/application.html.erb
config/locales/en/document_lead_image/edit.yml
config/locales/en/document_lead_image/index.yml
config/locales/en/documents/show.yml
config/routes.rb
db/migrate/20180905142136_add_lead_image_to_document.rb
db/migrate/20180905150545_add_image_metadata_fields.rb
db/schema.rb
spec/features/choose_lead_image_spec.rb
spec/features/edit_lead_image_spec.rb
spec/features/remove_lead_image_spec.rb
spec/features/upload_invalid_lead_image_spec.rb
spec/features/upload_lead_image_spec.rb
spec/features/upload_no_file_as_lead_image_spec.rb

For https://trello.com/c/kwumHz3Q/189-set-up-a-minimal-lead-image-workflow-upload-and-select-xl
Paired with @davbo 
This adds a minimal lead image workflow in order for users to be able to perform basic tasks relating to a document's lead image:
- Uploading an image
- Adding and modifying metadata relating to a lead image
- Selecting an image from a list of existing images as a lead image
- Removing an image as a lead image
We also display the chosen lead image on the summary page for a document and display an error if a user chooses an invalid image to upload.
We expect some new components to be built after this PR has been merged, for a example for the image list, so there is some temporary code here which will need to be removed after these components have been created.

Add lead image workflow

---

app/services/user_facing_state.rb
app/views/documents/show/_actions.html.erb
config/locales/en/documents/show.yml
spec/features/publish_a_document_api_down_spec.rb
spec/services/user_facing_state_spec.rb

This is a continuation of https://github.com/alphagov/content-publisher/pull/250.
Something publishing to the publishing-api goes wrong, either because the publishing-api isn't available (in development), the publishing-api is slow to respond (when it's busy).
This commit adds a message and button to the summary page when something has gone wrong, so the user can fix the issue themselves.
https://trello.com/c/VkVrVGeB

Deal consistently with errors publishing

---

app/controllers/documents_controller.rb
app/services/document_filter.rb
app/services/user_facing_state.rb
app/views/documents/index/_filters.html.erb
config/locales/en/documents/index.yml
spec/features/index_filtering_spec.rb
spec/services/document_filter_spec.rb
spec/services/user_facing_state_spec.rb

Trello: https://trello.com/c/rCESaDMh/240-filter-index-page-by-state
This adds in the state filter for the index page.
It does have a bit of a WTF going on for handling the scenario where there is a state passed in that is unknown to us: https://github.com/alphagov/content-publisher/blob/25c6b5d786600a50baf2e0096c67a1152357ded8/app/services/document_filter.rb#L49-L51
Alternative options if people dislike this approach are:
1 - moving the where("1 = 2") into [UserFacingState](https://github.com/alphagov/content-publisher/blob/master/app/services/user_facing_state.rb#L23) instead of exception
2 - be inconsistent with other query string filters and return all results

Index filter by state

---

spec/spec_helper.rb

https://trello.com/c/AZHmdkPM/251-spechelper-has-a-before-block-that-stubs-the-publishing-api-with-unclear-purpose
This is apparently not needed for the tests to pass, and it's not clear
why it was added.

Remove redundant org stub

---

app/models/document.rb
app/views/document_lead_image/edit.html.erb
app/views/document_lead_image/index.html.erb
app/views/document_tags/edit.html.erb
app/views/document_tags/edit_api_down.html.erb
app/views/documents/edit.html.erb
app/views/documents/show.html.erb
app/views/documents/show_api_down.html.erb
app/views/preview/show.html.erb
config/locales/en/document_lead_image/edit.yml
config/locales/en/document_lead_image/index.yml
config/locales/en/document_tags/edit.yml
config/locales/en/documents.yml
config/locales/en/documents/edit.yml
config/locales/en/documents/show.yml
config/locales/en/preview/show.yml

This makes the titles for the edit pages consistent.
They use the form "{thing} `{page title}`".

Rationalise page titles for document editing

---

.rubocop.yml
app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb
app/services/document_type_schema.rb
db/seeds.rb
spec/factories/document_type_schema_factory.rb
spec/services/document_url_spec.rb

More permanent fix to https://github.com/alphagov/content-publisher/pull/251.
If you save/create a record without checking the return value, there's a risk that your record won't be saved, but nothing will tell you.
This enables the Rubocop that checks for occurrences, so we don't do it again.
> This cop identifies possible cases where Active Record save! or related should be used instead of save because the model might have failed to save and an exception is better than unhandled failure.

Consistently save-bang records

---

lib/tasks/import.rake

This is an alternative to https://trello.com/c/KhxwyMKK/243-fix-not-supporting-government-response-and-world-new-story.
We currently don't support 'government response' and 'world news story'
document types, so we should avoid importing them until the migration
path is clear.

Filter out unwanted new document types

---

Gemfile
Gemfile.lock
Jenkinsfile
Rakefile
spec/javascripts/jasmine_examples/PlayerSpec.js
spec/javascripts/support/jasmine.yml
spec/javascripts/support/jasmine_helper.rb

https://trello.com/c/AgFY5UN1/214-setup-jasmine-testing-for-javascript-and-add-some-tests-m
This is based on the approach taken in govuk_publishing_components,
which uses the 'jasmine' gem locked to a 2.x version - there seems to be
a problem running 'rake jasmine:ci' for version 3.x.

Add Jasmin for testing our JavaScript

---

app/assets/stylesheets/components/_image_meta.scss
app/views/components/_image_meta.html.erb
app/views/components/docs/image_meta.yml
app/views/document_lead_image/_image_list.html.erb
app/views/document_lead_image/edit.html.erb
app/views/documents/show/_lead_image.html.erb
config/locales/en/document_lead_image/edit.yml
spec/features/upload_lead_image_spec.rb

This PR:
- updates the image meta component to group meta attributes and only display meta list when presented
- updates the image meta component to allow no_border modifier
- updates the edit image page to use the updated image meta component
- updates tests to reflect changes
[Trello card](https://trello.com/c/RCoMnQcK)

Update edit image page

---

app/assets/stylesheets/utilities/_overwrites.scss
app/views/document_lead_image/_image_list.html.erb

Overwrite `.govuk-link` to allow buttons to be styled as link.
This is not something that we would promote, but currently we use a mix of buttons and links to choose/edit/remove an image and we need them to look consistent.
One way to avoid this is to use links/GET actions for remove and choose actions.
[Trello card](https://trello.com/c/k5BjyOKw)

Overwrite govuk-link to allow buttons to be styled as link

---

app/controllers/document_tags_controller.rb
app/controllers/documents_controller.rb
app/controllers/new_document_controller.rb
app/controllers/publish_document_controller.rb
app/controllers/review_controller.rb
app/models/document.rb
app/models/timeline_entry.rb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
db/migrate/20180907121447_create_timeline_entries.rb
db/schema.rb
spec/features/document_timeline_spec.rb
spec/models/timeline_entry_spec.rb

This is a first PR for the "history" feature. It's very rudimentary:
Whenever a relevant action takes place, we create a `TimelineEntry` record. I've called this a "timeline entry", because I couldn't come up with a better generic name. We expect that this page will also include comments, so "timeline entry" seems appropriate for that too. We display the timeline entry in the history tab:
Note that this doesn't implement all of the things from the Trello ticket, there will be follow up PRs (see "To do" checklist).
- Does the naming of "timeline entry" make sense?
- Have we captured entries for all the relevant user-initiated actions at the moment?
https://trello.com/c/TVcThaKi

Create MVP for history feature

---

app/services/asset_manager_service.rb

For https://trello.com/c/2BSsLGFS/239-upload-images-to-asset-manager-and-set-lead-image-in-publishing-api

Pass Asset Manager bearer token to API adapters

---

app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb

`find_by` will return nil if the record is not found, while `find` (or `find_by!`) will raise an exception. `find` takes an ID, so we can simplify these calls.

Simplify `find_by` usage

---

app/views/documents/show/_actions.html.erb
spec/features/publish_a_document_spec.rb

When a document was ever published you'll be able to click this link to view it on GOV.UK.
https://trello.com/c/mOwMX0fW

Add "View on GOV.UK" link

---

app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb
app/models/image.rb
app/services/asset_manager_service.rb
app/services/document_publishing_service.rb
spec/factories/image_factory.rb
spec/services/asset_manager_service_spec.rb

https://trello.com/c/QAEhhJdf/244-build-workflow-for-delete-draft-remove-and-retire-document-m
This adds #delete to the AssetManagerService so we can manage deleting
images and other assets, which will come in a subsequent PR.
I struggled quite a bit when adding this method, because there were a
few concepts that need to be understood. I've tried to make that easier:
* asset_id: this was generated in AssetManagerService using 'url',
which came from AssetManagerFile, which came from Image. To make it
easier to understand how the value is generated, I've moved this method
directly onto the Image model, so that it's easier to see the data flow.
* asset_manager_file_url: this is generated by Asset Manager itself.
Each test required 3 lines in order to mock it accurately, which was
distracting …

Support deleting assets from asset manager

---

app/controllers/documents_controller.rb
app/controllers/new_document_controller.rb
app/models/timeline_entry.rb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
db/migrate/20180919150956_current_edition_number_to_documents.rb
db/schema.rb
lib/tasks/whitehall_news_importer.rb
spec/factories/document_factory.rb
spec/features/document_timeline_spec.rb
spec/tasks/whitehall_news_importer_spec.rb

This PR adds an edition number to documents. This number will be shown in the document history, where it increases every time a new draft is created.
https://trello.com/c/TVcThaKi

Implement edition numbering

---

app/controllers/application_controller.rb
app/controllers/documents_controller.rb
app/models/document.rb
app/services/document_publishing_service.rb
app/services/user_facing_state.rb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_delete_draft.html.erb
app/views/layouts/application.html.erb
config/locales/en/documents/show.yml
config/locales/en/states.yml
config/routes.rb
db/migrate/20180917162353_nullify_lead_image_foreign_key.rb
spec/features/delete_draft_after_publishing_spec.rb
spec/features/delete_draft_api_down_spec.rb
spec/features/delete_draft_asset_manager_down_spec.rb
spec/features/delete_draft_publishing_api_down_spec.rb
spec/features/delete_draft_spec.rb
spec/services/document_publishing_service_spec.rb
spec/services/user_facing_state_spec.rb

This enables the 'Delete draft' button, which for now will delete a
document but in future should be changed to work on the current edition.
* Added a new 'confirmation' flash type to support the interstitial "Yes, delete draft" box
* Relaxed a foreign key constraint on lead images that was impeding deletion of images
* Ensures we delete any associated images (S3, Asset Manager) including API down test
* Restricts "Delete draft" so it's only available when the document hasn't been published
* Ensures we delete the draft from the Publishing API including API down test
I took the long approach for the API down case (the short approach would just be 
to click "Delete draft" again), using a new publication state to display a "Try again" button 
as we do for other error states. Doing it this …

Support deletion of drafts (with confirmation)

---

lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

This changes `current_edition_number` to be set to the number of editions
belonging to a document when imported from Whitehall. The previous
implementation didn't take into account minor editions, so this should be more
accurate.

Change how current_edition_number is set on import

---

lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

For https://trello.com/c/uBqWwIqu/234-set-the-correct-state-when-importing-from-whitehall-m
This sets `publication_state` and `review_state` on documents that are imported from Whitehall based on their Whitehall state.  Whitehall states have been mapped to Content Publisher publication states and review states in this document: https://docs.google.com/spreadsheets/d/1R3tfzhWDsO2zize6s-8EzjW7rvgKZQhu3NLYEVXouWk/edit#gid=0
We have chosen not to import documents with the following states:
- `imported` - There are only 4 imported documents which were last updated in 2013 it seems unncessary to import these.
- `scheduled` - We don't currently support scheduling in this app, so for now we won't import documents that are scheduled for publication.
- `superseded` - These are documents that have …

Set state on imported documents

---

app/views/documents/show/_contents.html.erb
spec/features/creating_documents/create_a_document_spec.rb

If the document has never been published, we'll have an automatic change note of "First published."

Only show the change notes when the document was ever published

---

app/services/publishing_api_payload.rb

This is overriding the actual change history that the publishing-api builds from the change note.

Remove default change history

---

app/controllers/publish_document_controller.rb
config/locales/en/documents/history.yml
spec/features/workflow/publish_a_document_spec.rb

This fixes a bug where we accidentally only show the "Published without review" entry on the timeline, even if the document was reviewed. Also adds a test.

Fix bug with publish history on timeline

---

app/assets/javascripts/components/image_cropper.js

Disables rotation and scaling in the cropper. This prevents cropper.js from
making an additional XHR request to download the image again. This XHR request
creates CORS errors and isn't necessary for us unless we want the rotation
feature to work.
Digging into why it makes the request it seems to be to download the image into
an arraybuffer to parse the exif data for things like handling image rotation.
The code which makes the XHR is here:
https://github.com/fengyuanchen/cropperjs/blob/23b2e6c07c0c636082cc3bbf3509e3cb3d531271/src/js/cropper.js#L98-L159
Disabling these options stops the XHR from being sent.

Fix CORS errors caused by cropper

---

app/views/documents/index/_results.html.erb
config/locales/en/documents/index.yml

This wasn't added in after the user facing state work was done.
This now looks like so:

 Show user facing state on the index view

---

app/controllers/new_document_controller.rb
app/models/document.rb
app/services/document_update_service.rb
app/views/documents/index/_results.html.erb
app/views/documents/show/_document_metadata.html.erb
config/locales/en/documents/index.yml
config/locales/en/documents/show.yml
db/migrate/20180925082624_add_last_editor_to_document.rb
db/schema.rb
spec/features/editing_content/edit_a_document_spec.rb
spec/features/finding/index_results_spec.rb
spec/features/workflow/viewing_a_document_with_no_creator_or_editor_spec.rb
spec/features/workflow/viewing_a_document_with_no_creator_spec.rb

For https://trello.com/c/OdqQe7J2/269-store-and-present-the-user-that-last-edited-a-document
This adds a `last_editor` to Document which is updated every time an edit is made to a document.  We have defined an edit to mean a change to the document itself rather than a state change such as sending for review or publishing.
Make `last_editor` available allows us to display that last person who edited a document:
**Summary page**
**Index page results**

Associate document with user who last edited it

---

app/controllers/remove_document_controller.rb
app/controllers/retire_document_controller.rb
app/views/documents/show/_actions.html.erb
app/views/remove_document/remove.govspeak.md
app/views/remove_document/remove.html.erb
app/views/retire_document/retire.govspeak.md
app/views/retire_document/retire.html.erb
config/locales/en/remove_document/remove.yml
config/locales/en/retire_document/retire.yml
config/routes.rb

https://trello.com/c/QAEhhJdf/244-build-workflow-for-delete-draft-remove-and-retire-document-m
This adds two separate placeholder screens for retiring/removing a
document, so that a user can see the feature isn't supported and know
what to do. I wanted to keep the new actions out of the already bulging
DocumentsController, so I've created two completely separate placeholder
routes, which will allow these features to be implemented separately.
In order to render the textual content on the page, I've used the same
pattern as for new_document/guidance.html.erb.

Add placeholder screens for retire/remove

---

app/models/image.rb
app/services/asset_manager_service.rb
spec/services/asset_manager_service_spec.rb

The ensures the content type is passed explicitly to Asset Manager
instead of being inferred by Rest Client. It also ensures we pass the
filename without any surrounding path, which is what Rest Client looks
for by default.

Fix metadata not being passed to Asset Manager

---

app/formats/document_types.yml
app/services/publishing_api_payload.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/services/publishing_api_payload_spec.rb

Trello: https://trello.com/c/3GT17tkH/211-associate-content-with-ministers-l
This allows the functionality to tag news/press releases to ministers by allowing a tag to role appointments. It does this because there is currently no clear way to get a list of ministers from the Publishing API and there does not seem to be a particular reason why all roles/people can't be associated with a news story.
Things still to do:

Tagging to role appointments

---

app/services/document_filter.rb

This loads the related creators and editors for the documents in 1 query, instead of 1 query per document. Potentially saves up to 100 queries per page.

Fix N+1 query on index page

---

app/views/documents/index/_results.html.erb

Fix locale for unknown user

---

app/controllers/document_lead_image_controller.rb
app/views/document_lead_image/_image_list.html.erb
spec/features/editing_images/delete_image_after_publishing_spec.rb

https://trello.com/c/AJnfoZhI/271-provide-functionality-to-delete-an-uploaded-lead-image

Disable image deletion for published documents

---

app/views/layouts/application.html.erb
app/views/publish_document/published.html.erb
config/locales/en/publish_document/published.yml

Content taken from the prototype here:
https://content-publisher-prototype.cloudapps.digital/content-summary-published

Add missing page title for published screen

---

app/models/document.rb

This should fix this kind of Sentry error...
https://sentry.io/govuk/app-content-publisher/issues/702967549/?environment=integration-blue-aws

Make sure we do a 404 when we can't find a doc

---

app/controllers/document_lead_image_controller.rb
app/controllers/document_tags_controller.rb
app/controllers/documents_controller.rb
app/controllers/publish_document_controller.rb

This ensures we call 'Rails.logger.error(e)' whenever we rescue an
exception, so that we have sufficient information to fix the error. Most
of the errors are 'Intermittent retryable' and not right for Sentry.
https://github.com/alphagov/govuk-rfcs/blob/master/rfc-087-dealing-with-errors.md#intermittent-retryable-errors
This also removes an untested rescue for when we cannot generate a
unique path for a document, as this behaviour was not consistent for the
no-javascript path and it feels like we should solve this problem first.
This also removes Sentry reporting for exceptions originating from the
views, as we anticipate these are 'Intermittent errors with user
impact', such as timeouts, which don't require immediate attention.

Log exceptions so we can fix them ;-)

---

app/services/asset_manager_service.rb

https://trello.com/c/WQYgUVRO/274-look-into-sentry-errors-related-to-image-uploads
https://sentry.io/govuk/app-content-publisher/issues/682768231/?query=is:unresolved
This attribute isn't required for publishing and seems to be causing the
exceptions which say the 'file is blank'. I'm struggling to reproduce this 
locally, which makes me think it's something to do with the dev 
environment - either way this is still a valid change to try.

Remove redundant file attribute in asset publish

---

app/views/document_images/index.html.erb
config/locales/en/document_images/index.yml
spec/features/editing_images/upload_lead_image_asset_manager_down_spec.rb

Remove the text of "No images uploaded" when we have no images
This applies to documents which have no images on the upload images
page.
Trello: 
https://trello.com/c/IMdJcbEs/303-remove-the-text-of-no-images-uploaded-when-we-have-no-images

Remove no image text when no images

---

app/services/document_update_service.rb
spec/features/workflow/submit_for_2i_spec.rb

https://trello.com/c/7EQhBAvi/323-editing-content-shouldnt-reset-the-user-facing-state-back-to-draft
When a user edits a document that is submitted for review, we should
preserve this state and not set the review state back to 'unreviewed'.
Otherwise, the user has to re-submit the document every time they make a
change.

Maintain 'in review' state when the doc is edited

---

app/views/document_images/edit.html.erb

https://trello.com/c/EUgQ9ZQd/338-fix-back-link-for-lead-image-wizard
When editing an existing image's attributes, this should go back to the
images index page. But when the user is working through the lead image
wizard, it makes more sense to take them back to the crop screen, as
this is the previous screen they should have been on.

Fix back link for lead image wizard edit page

---

app/assets/stylesheets/components/_image_cropper.scss
app/assets/stylesheets/utilities/_display.scss
app/models/image.rb
app/views/components/_image_cropper.html.erb
app/views/document_images/crop.html.erb
config/locales/en/document_images/crop.yml

The image is automatically resized and cropped center-based
The image is displayed as is without the cropping functionality
[Trello card](https://trello.com/c/Mx0dBCHb)

Handle no-javascript/non-croppable experience for lead images

---

app/assets/stylesheets/utilities/_overwrites.scss
app/views/documents/index/_filters.html.erb
spec/features/finding/index_filtering_api_down_spec.rb

This PR replaces the autocomplete components with selects for filters in the index page.
The reason we're not using the select component is that the data doesn't come in a form that's usable for the component. It currently comes as two arrays one with for the options values and another with the selected items. The component takes a single array with a boolean flag (`selected: true`) for the selected options.
[Trello card](https://trello.com/c/DjDrH3lY)

Replace autocompletes with selects for filters

---

app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb
config/locales/en/document_images/edit.yml
config/locales/en/document_images/index.yml
config/locales/en/documents/show.yml
spec/features/editing_images/choose_lead_image_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/delete_lead_image_spec.rb
spec/features/editing_images/edit_image_crop_spec.rb
spec/features/editing_images/edit_image_metadata_spec.rb
spec/features/editing_images/remove_lead_image_spec.rb
spec/features/editing_images/upload_lead_image_spec.rb

Adds flash messages to the image management section of the workflow.
Provide a flash message when a user:
Trello:
https://trello.com/c/66Zaa8e0/304-add-flash-messages-for-image-actions

Add flash messages to image workflows

---

app/assets/stylesheets/components/_markdown-editor.scss
app/views/components/_markdown_editor.html.erb

Changes requested:
- Hover state #dee0e2
- Focus state filled rather than outline
- Size of icons to be increased by 40px
- Remove padding - 40px height
- Remove underline on links
- Reduce padding on toggle to 10px (so left side aligns)
Ticket: https://trello.com/c/TvmLqnxi/332-add-toolbar-to-markdown-editor

Improvements to styling of toolbar

---

app/views/documents/edit.html.erb
spec/features/editing_content/url_preview_spec.rb

This PR: 
- replaces the textarea component with a character-count component for title and summary on edit document page and sets the limit to 65 and 160 respectively
- updates a test to use a consistent selector throughout the test and removes a redundant id attribute
[Trello card](https://trello.com/c/28Ol82Ky)

Add character count to edit document page

---

app/controllers/document_images_controller.rb
app/services/image_drafting_requirements.rb
app/views/document_images/edit.html.erb
config/locales/en/document_images/edit.yml
spec/features/editing_images/image_drafting_requirements_spec.rb

https://trello.com/c/iecyxRBY/272-add-validations-for-image-details
This ensures we enter alt text for an image, as well as putting some
sensible limits on the maximum length of the text in these fields.
Although it's not possible to have multiple errors for each field in
this particular case, we'd like to adopt the pattern used here to
support it in other cases and maintain consistency.

Add image requirements for alt text / caption

---

app/views/layouts/application.html.erb

This PR adds current user's organisation to `dimension1` (which is configured to store organisations in GTM) via dataLayer.

Add organisation as a custom dimension via dataLayer

---

app/controllers/document_images_controller.rb
app/controllers/publish_document_controller.rb
app/controllers/review_controller.rb
app/formats/document_types.yml
app/services/document_type_schema.rb
app/services/publishing_requirements.rb
app/views/components/_notice.html.erb
app/views/documents/show.html.erb
app/views/documents/show/_contents.html.erb
app/views/documents/show/_publishing_requirements.html.erb
app/views/layouts/application.html.erb
config/locales/en/documents/show.yml
config/locales/en/publishing_requirements.yml
spec/factories/field_schema_factory.rb
spec/features/workflow/publishing_requirements_spec.rb

https://trello.com/c/yxeOlaA8/309-iterate-our-publishing-requirements
The previous publishing requirements are no longer applicable and we
want to iterate them to simply check for the presence of a summary and a
body. Instead of hard-coding the behaviour to the dynamic "body" field,
I've made it so that all dynamic field must be present on publish.
As all the requirements are now hard-coded, there's no need for the
'validations' hash for content fields. It's also good to remove this as
the new terminology of 'publishing requirements' and 'drafting
requirements' makes the lone term 'validations' pretty confusing.

Iterate publishing requirements to check presence

---

app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb
app/services/image_drafting_requirements.rb
app/services/image_normaliser.rb
app/services/image_upload_requirements.rb
app/services/image_uploader.rb
config/locales/en/document_images/edit.yml
config/locales/en/document_images/index.yml
config/locales/en/documents/show.yml
config/locales/en/validations.yml
spec/features/editing_images/choose_lead_image_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/delete_lead_image_spec.rb
spec/features/editing_images/edit_image_crop_spec.rb
spec/features/editing_images/edit_image_metadata_spec.rb
spec/features/editing_images/image_drafting_requirements_spec.rb
spec/features/editing_images/remove_lead_image_spec.rb
spec/features/editing_images/upload_invalid_lead_image_spec.rb
spec/features/editing_images/upload_lead_image_spec.rb
spec/features/editing_images/upload_no_file_as_lead_image_spec.rb
spec/services/image_normaliser_spec.rb
spec/services/image_upload_requirements_spec.rb
spec/services/image_uploader_spec.rb

https://trello.com/c/yxeOlaA8/309-iterate-our-publishing-requirements
This extracts the validation logic from the image uploader class to be
consistent with the 'requirements' pattern we've developed for document
drafting/publishing and image drafting. As the error messages won't be
shown away from the images index page, we no longer need the top level
locale file.

Extract image upload validations as requirements

---

app/views/components/_formatted_text.html.erb
app/views/documents/fields/_govspeak.html.erb

https://trello.com/c/nViNavOU/347-development-clean-up-for-user-research
The previous line-based approach made the summary screen too long when
publishers create content with long initial paragraphs.

Trim body on summary screen using character limit

---

app/controllers/document_images_controller.rb
app/controllers/document_lead_image_controller.rb
app/views/document_images/_image_list.html.erb
app/views/document_images/edit.html.erb
config/routes.rb
spec/features/editing_images/image_drafting_requirements_spec.rb
spec/features/editing_images/upload_lead_image_drafting_requirements_spec.rb

https://trello.com/c/iecyxRBY/272-add-validations-for-image-details
Checking for draft requirements for images had only been applied when
editing the image. Attempting to add the requirements checking to the
lead images controller failed because "render 'document_images/edit"
looses track of the lead_image wizard param. So this commit pulls some
of the lead-image-specific functionality back into the document images
controller, which actually seems to make the flow a bit clearer.

Fix not checking for draft requirements on upload

---

app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/index.html.erb

https://trello.com/c/flWT8HIe/408-external-guidance-for-supertypes-should-open-a-new-tab
Also make the use of 'target=_blank' consistent.

Fix target for markdown guidance so it opens a tab

---

README.md
lib/tasks/import.rake

This doesn't seem to be documented anywhere outside of commit messages,
so this adds this to the README.
I opted to go for the approach of creating a file rather than streaming
between tasks as since the streaming approach waits for STDIN it's easy
to get stuck waiting forever if there is nothing on STDIN and it
requires a delicate balance of being in the correct directories to run
the commands.

Add documentation on running Whitehall import

---

app/services/asset_manager_service.rb
app/services/document_publishing_service.rb
app/services/linkables_service.rb
app/services/path_generator_service.rb
app/services/publishing_api_payload.rb

Since the helper methods arrived in 53.2 of gds-api-adapters [1] we can
now shorten the code used for initialising them. I didn't see any
particular benefits for memoization of the adapters.
[1]: https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md#5320

Refactor GdsApi usage for helper methods

---

app/controllers/document_topics_controller.rb
app/models/user.rb
app/views/documents/show/_summary_tab.html.erb
db/seeds.rb
spec/features/editing_topics/access_topics_without_pre_release_features_permission_spec.rb

Trello: https://trello.com/c/pt9c438U/361-feature-flag-for-upcoming-user-research
This PR is to merge into https://github.com/alphagov/content-publisher/pull/392 so that can move from DO NOT MERGE. I intend to then update https://github.com/alphagov/content-publisher/pull/411 to be consistent with approaches in this.
See commits for details.

Restrict access to managing topics to pre-release features

---

app/controllers/document_topics_controller.rb
app/services/topics_service.rb
app/views/document_topics/edit.html.erb
app/views/documents/show/_tags.html.erb
app/views/documents/show/_topics.html.erb
config/locales/en/documents/show.yml
spec/features/editing_images/upload_lead_image_drafting_requirements_spec.rb
spec/features/editing_images/upload_lead_image_publishing_api_down_spec.rb
spec/features/editing_images/upload_lead_image_spec.rb
spec/features/editing_tags/show_tags_publishing_api_down_spec.rb
spec/features/editing_topics/edit_topics_publishing_api_down_spec.rb
spec/features/editing_topics/show_topics_publishing_api_down_spec.rb
spec/features/editing_topics/show_topics_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/spec_helper.rb

https://trello.com/c/5tAUflyY/331-show-current-taxons-for-a-document
This adds the ability to see the current topics for a document on the summary page. We extended the TopicsService to allow us to get the current topics, which meant doing some renaming to keep the purpose of the methods clear. We also cope with the Publishing API being down or slow.
We have some duplication of stubs in the tests, but I don't think it's enough to get a clear refactoring out of it. I'm expecting the final piece of work - to enable editing of topics - will involve revisiting these specs, rather than creating new ones, so it seems unlikely the duplication will spread.

Show topic on summary

---

README.md
app/controllers/documentation_controller.rb
app/controllers/documents_controller.rb
app/models/user.rb
app/views/documentation/index.html.erb
app/views/layouts/application.html.erb
lib/tasks/development_permissions.rake
spec/features/debug_spec.rb
spec/features/documentation_spec.rb
spec/spec_helper.rb

Trello: https://trello.com/c/pt9c438U/361-feature-flag-for-upcoming-user-research
This adds a "debug" permission which can be used by signon for features that provide information that shouldn't be available to normal users of the app and just to provide functionality for someone learning more about the app and how it works.

Debug permission flag

---

app/services/publishing_requirements.rb
config/locales/en/publishing_requirements.yml
spec/factories/document_factory.rb
spec/features/workflow/publishing_requirements_spec.rb

https://trello.com/c/IjE24eFh/415-update-publishing-requirements-for-creating-an-edition-of-a-document
This isn't in-play right now, but I had a few spare minutes...
When the user sets the "major" update type for a live document, we
should ensure they enter a change note before they publish.
We currently auto-select the "major" update type each time a user
creates a new edition, so this updates the document factory to match.
Using interpolated values for locale keys leads to grammatical
problems (e.g. Enter a alt text) and we should avoid it.

Enforce entering a change note when we publish

---

app/assets/javascripts/components/markdown-toolbar.js
app/assets/javascripts/vendor/@github/markdown-toolbar-element/dist/index.umd.js

We found in user research that publishers don't select the item they want to style, but rather position the cursor at the beginning of a line. With this approach, after pressing a markdown toolbar button (i.e. list) it currently makes the content break with a new line after the first word.
This PR fixes the issue by selecting the current line by default if not selection is made by the user.
The updated code comes from https://github.com/alphagov/markdown-toolbar-element. Plan to do releases and changelog soon, so I can point to those for changes instead.
[Trello card](https://trello.com/c/oVHHFHWJ)
👉[Test me in the preview deploy](https://content-publisher-revie-pr-430.herokuapp.com/)

Fix markdown buttons break content after firts word

---

app/assets/stylesheets/components/_image-cropper.scss

If they uploaded an image to the exact dimensions, some publishers didn't realise their images could be cropped. 
Making the crop handles bigger might help alleviate this.
https://trello.com/c/Yu5DjMk3/398-iterate-lead-image-workflow-based-on-user-research

Make the crop handles bigger

---

app/views/documents/show/_actions.html.erb
app/views/preview/show.html.erb

https://trello.com/c/psIGjsfm/393-preview-page-to-open-in-same-tab-and-add-back-button-to-return-to-content-summary
As a publisher
I get confused when a preview window opens automatically in a new tab
and I am trying to go back to the summary screen but I can't find a
'back' button because I don't get a notification that it opened in a new
window

Preview page opens on same tab with back button

---

Gemfile.lock
app/controllers/document_topics_controller.rb
app/services/topics_service.rb
app/views/document_topics/edit.html.erb
app/views/documents/show/_tags.html.erb
app/views/documents/show/_topics.html.erb
config/locales/en/document_topics/edit.yml
config/locales/en/documents/show.yml
config/routes.rb
spec/features/editing_tags/edit_tags_publishing_api_down_spec.rb
spec/features/editing_tags/edit_tags_spec.rb
spec/features/editing_tags/save_tags_publishing_api_down_spec.rb
spec/features/editing_topics/edit_topics_conflict_spec.rb
spec/features/editing_topics/edit_topics_publishing_api_down_spec.rb
spec/features/editing_topics/edit_topics_spec.rb
spec/features/editing_topics/edit_topics_without_permission_spec.rb
spec/features/editing_topics/save_topics_publishing_api_down_spec.rb
spec/features/editing_topics/show_topics_spec.rb
spec/support/topics_helper.rb

https://trello.com/c/82J6eESL/356-allow-the-user-to-modify-the-topics-for-a-document
This enables a user to edit the topics for a document:
* The user can see which topics are currently selected and change the selections (https://github.com/alphagov/content-publisher/commit/b0dadb13e92a9a8bb7273fb9d6e8a3c983da29ee)
* We cope when the Publishing API is down (https://github.com/alphagov/content-publisher/commit/3eb253272cbe78c2f0b8cdd61b115ad3ca1a7c61)
* We abort when the topics have been changed externally (https://github.com/alphagov/content-publisher/commit/ee9d022078bd7a1e5390d620b847dd4ecd8d22e8)
Because we don't store the topic taxonomy locally, we need to repeatedly stub parts of the tree, up to three levels deep. To avoid duplicate code, we've refactored this into our first helper, …

Edit topics

---

app/services/topics_service.rb
spec/features/editing_topics/edit_topics_conflict_spec.rb
spec/features/editing_topics/edit_topics_spec.rb
spec/features/editing_topics/save_topics_publishing_api_down_spec.rb
spec/support/topics_helper.rb

https://trello.com/c/lE8z7rmq/360-automatically-select-specialist-sectors-when-a-user-selects-a-topic
The new topic taxonomy has replaced a range of legacy alternatives,
except for 'topics' a.k.a specialist sectors. This makes sure we set
the specialist sectors for a document when the topics change, using the
legacy mappings for the selected topics and their parent lineage.
If the document already has specialist sectors, we will overwrite them.
This is a departure from the Whitehall behaviour, which we will validate
as with user testing. Hopefully we will retire specialist sectors before
the need arises to better support their existence ;-).

Auto populate legacy topics (specialist sectors)

---

app/services/topics_service.rb
spec/features/editing_topics/edit_topics_spec.rb

https://trello.com/c/fiIF8jNV/405-cleanup-superfluous-topics-on-save
Previously we assumed the frontend would ensure only leaf topics were
submitted on the edit page for topics; this assumption was false.
This changes the patch_links method to remove superfluous topics that
are an ancestor of another selected topic. To avoid implementing
multiple recursive methods, I extracted the recursive part of the
topic_breadcrumb method so that we can re-use it for ancestor cleanup.

Cleanup superfluous topics before patching links

---

app/services/topics_service.rb

https://trello.com/c/GCLUK6YV/411-sort-topics-alphabetically-at-each-level
This makes it easier to visually scan and find a topic, while also
matching the current behaviour of Whitehall.

Order topics alphabetically at each level

---

lib/tasks/whitehall_news_importer.rb
spec/tasks/whitehall_news_importer_spec.rb

Trello: https://trello.com/c/gEAMmD0g/386-ability-to-embed-a-contact-via-markdown
This changes the body field on imported documents from Whitehall so that
the values for [Contact:123] are instead represented by the content_id.
It expects the JSON for a document to have a hash of contacts which
has a mapping of whitehall id => content id (e.g. { "123" =>
"12345678-1234-1234..." } which covers all the contacts in all the
translations and all the editions of a document.
Pairs with this Whitehall PR: https://github.com/alphagov/whitehall/pull/4481

Replace Contacts in Whitehall import process

---

app/assets/javascripts/components/markdown-editor.js

This PR fixes the 'open in a new tab' for the preview markdown container.
The script was erroneously trying to set the `target` as `_blank` on an empty container as the `fetchGovspeakPreview` is starting a new thread of events
[Trello card](https://trello.com/c/h4YtRSCW)

Fix links in markdown preview

---

app/controllers/govspeak_preview_controller.rb
app/services/contacts_service.rb
app/services/govspeak_document.rb
app/services/govspeak_service.rb
app/services/publishing_api_payload.rb
spec/services/contacts_service_spec.rb
spec/services/govspeak_document_spec.rb
spec/services/govspeak_service_spec.rb

Trello: https://trello.com/c/gEAMmD0g/386-ability-to-embed-a-contact-via-markdown
This is marked as DNM as https://github.com/alphagov/govspeak/pull/130 needs to be released first
This PR introduces the ability to convert markdown such as `[Contact:e3dd86ba-508c-4e4c-9cba-1b98208d4de0]` and then insert the HTML of a contact. 
It does this by looking up all contact content_ids in the govspeak and then for each of them [looking them up](https://github.com/alphagov/publishing-api/blob/master/doc/api.md#get-v2contentcontent_id) in the Publishing API.
The means to look up in the Publishing API isn't perfect, it's as many calls as there are contacts embedded and may indadvertedly embed draft contact information. The expectation though is that the UI work to embed contacts may offer an …

Embed contacts via markdown

---

app/formats/supertypes.yml

Added 'news stories' to hint text for News supertype, as suggested in user testing

updated hint text for News

---

app/views/documents/show/_actions.html.erb

https://trello.com/c/64Ljsaoi/394-error-link-colour-to-be-updated-to-be-consistent-with-govuk-styling

Render govspeak action messages with component

---

app/views/layouts/application.html.erb

https://trello.com/c/64Ljsaoi/394-error-link-colour-to-be-updated-to-be-consistent-with-govuk-styling

Use GOV.UK style when rendering govspeak alerts

---

app/controllers/publisher_information_controller.rb
app/views/layouts/application.html.erb
app/views/publisher_information/_publication_info_nav.html.erb
app/views/publisher_information/beta_capabilities.govspeak.md
app/views/publisher_information/beta_capabilities.html.erb
app/views/publisher_information/how_to_use_publisher.govspeak.md
app/views/publisher_information/how_to_use_publisher.html.erb
app/views/publisher_information/publisher_updates.govspeak.md
app/views/publisher_information/publisher_updates.html.erb
app/views/publisher_information/request_feature.govspeak.md
config/locales/en/application.yml
config/locales/en/publisher_information/beta_capabilities.yml
config/locales/en/publisher_information/how_to_use_publisher.yml
config/locales/en/publisher_information/publisher_updates.yml
config/routes.rb
spec/features/publisher_information/visit_publisher_information_pages_spec.rb

Supporting epic: https://trello.com/c/f7iCiQMB/338-publishers-can-find-what-beta-features-are-included-and-have-a-feedback-option-in-content-publisher
These changes allow the application to show user more information about the content publisher through three views: 
(1) publisher updates, which shows the latest changes.
(2) beta capabilities, which indicates what users should expect from the beta version of the application
(3) a how to page that describes how to use the content publisher application.
There is some repetition in the views but I plan to develop a layout which can better support all three pages. This request does not include adding in back link navigation and it does not include the header that should contain a link to get to the views that are developed here.
The main …

Publisher updates page 383 1

---

app/formats/document_types.yml
app/views/documents/fields/_govspeak_input.html.erb

Added guidance links to markdown guidance section on right hand side of the Edit screen.
Links should open in a new tab or window.

Added guidance links

---

app/views/components/_page_preview.html.erb

Publishers did not see the option to share preview
Publishers did not know what they could use it for
https://trello.com/c/NJ4v3YFb/397-iterate-preview-page-sharing-based-on-user-research-insights

Update share link content

---

app/assets/stylesheets/components/_summary.scss
app/views/documents/tags/_multi_tag.html.erb

The different sections seem to blend together, spacing + lines between content blocks and individual items is a bit haphazard
Meta data block currently shows lots of stuff that may not all be necessary, and it's not grouped very logically.
**1. Remove base path field**
[More info in this section of Content improvement doc](https://docs.google.com/document/d/1LG9j1JbTyakGwv3qhPHBV6bmiQF8d7u9JxKQEc5cYOY/edit?ts=5be31510#bookmark=id.w04bw5q8ktz3)
Ticket: https://trello.com/c/OcxRWyd0/340-implement-styling-improvements-to-the-summary-page

Implement styling improvements to the Summary page

---

config/locales/en/documents/index.yml
spec/features/finding/index_filtering_spec.rb
spec/features/finding/index_ordering_spec.rb

Slug isn’t widely understood by users. 
Content Data use "Title or URL", we should be consistent. 
Approved by @paola-roccuzzo

Update label for search

---

config/locales/en/document_images/index.yml

This drops our mention of SVG as we don't support these yet
(unfortunately the guidance link may contradict that but then there's
various things in that document that currently don't accurate represent
Content Publisher.
It also drops the oxford comma and our use of jpg and jpeg.

Make image messages consistent

---

app/controllers/document_contacts_controller.rb
app/controllers/documents_controller.rb
app/services/contacts_service.rb
app/views/document_contacts/search.html.erb
app/views/document_contacts/search_api_down.html.erb
app/views/documents/fields/_govspeak_input.html.erb
config/locales/en/document_contacts/search.yml
config/locales/en/document_contacts/select.yml
config/routes.rb
spec/features/editing_content/insert_contact_publishing_api_down_spec.rb
spec/features/editing_content/insert_contact_spec.rb
spec/services/contacts_service_spec.rb
spec/services/govspeak_document_spec.rb

Trello: https://trello.com/c/a80pDKyV/412-browse-and-insert-a-contact-into-markdown
This card will be followed up with some design tweaks. More info in commits, main commit info below: 
This implements the design to insert contacts into a document that
involved loading a new page - with the intention of avoiding a modal
window and having an identical JS and No JS experience.
It involves allowing a user to submit the edit content with a different
button and because of that button changing the behaviour of the update
action to redirect the user to a select contact view. When this form is
submitted it then redirects the user back to the edit content form.
This approach is hopefully not something we will keep long term or use
again as it suffers from a number of issues:
- User can be …

MVP add contacts feature

---

app/views/layouts/application.html.erb

The debug links only need to be appended to one list of links.
Before:
After:

Remove footer link repetition

---

config/locales/en/documents/show.yml

We don’t have this yet. 
Let’s remove now in case we don’t by the time we launch. We can add the line back once the feature is built.
https://trello.com/c/WOEm2VQ2/452-review-the-entire-app-for-design-fixes

Remove default image content

---

app/views/layouts/_phase_banner_elements.html.erb
config/locales/en/application.yml

In research, users thought they should use the feedback form for technical support. In private beta, we should be super clear about where they should go when they need help.
https://trello.com/c/WOEm2VQ2/452-review-the-entire-app-for-design-fixes

Add link to raise support request

---

app/views/publisher_information/publisher_updates.govspeak.md

Remove dummy content from What's new page and replace with first release note
https://trello.com/c/JN04xUyt/458-update-publisher-information-in-whats-new-section

Publisher information changes

---

app/views/components/_summary.html.erb
app/views/publish_document/confirmation.html.erb

Having chatted to Andy it seems we're relying on some flaky means to track user interactions which can be solved with data attributes which may be easier to implement than initially thought.
This serves as a quick example adding a couple of basic ones just as a test for this approach.

Initial data attributes for Google Tag Manager

---

app/views/layouts/_phase_banner_elements.html.erb
app/views/layouts/application.html.erb
app/views/publisher_information/request_feature.govspeak.md

Trello: https://trello.com/c/uW4kBZYc/385-build-feedback-support-form-for-beta-users
This changes our support links to be hardcoded to use production environment - so that our integration test users get production and to keep them consistent - and updates the link to be the new form we've set up.

Update support links

---

spec/services/asset_manager_service_spec.rb
spec/services/document_publishing_service_spec.rb

Content Publisher has been configured to automatically include spec_helper when the tests are run,
so these entries are not required.

DRY-up test requirements

---

app/views/components/_page_preview.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/publish_document/published.html.erb
spec/features/workflow/submit_for_2i_spec.rb

Trello: https://trello.com/c/5LMeIN89/446-look-at-adding-a-suffix-to-the-preview-url-generated
This is to help Andy determine whether people are using / sharing the links
One thing I'm not sure about is using the value of utm_content=preview-link for the preview link as that link will be to draft gov.uk and not content publisher and thus may need a more specific name to distinguish it amongst other things we track on gov.uk as a whole.

Add utm-content values to copy to clipboard links

---

Gemfile
Gemfile.lock
README.md
app/services/document_unpublishing_service.rb
app/views/remove_document/remove.govspeak.md
app/views/retire_document/retire.govspeak.md
docs/retiring-and-removing-documents.md
lib/tasks/unpublish.rake
spec/features/workflow/unpublishing_spec.rb
spec/services/document_unpublishing_service_spec.rb
spec/spec_helper.rb

Trello: https://trello.com/c/H3jeLoZW
Supersedes PR #499 
We don't currently support unpublishing or withdrawing a document (which in our app has the terminology of remove and retire respectively).
Our intention is to do this for users if they ask us to do so while in private beta.
This implements the minimal functionality required to allow users to request a document be retired/removed via zendesk. Only the backend call to publishing-api has been implemented, and is executed via a rake task.
The frontend and changes to the "state" of the document will be implemented later.

Allow documents to be "removed" or "retired"

---

app/controllers/document_topics_controller.rb

This seems to have got missed in https://github.com/alphagov/content-publisher/pull/467

Remove need for pre-release features permission on topics

---

app/assets/stylesheets/core/_link.scss

Trello: https://trello.com/c/98iyJWkI/536-fix-override-on-destructive-links-that-is-causing-them-to-be-blue-instead-of-red-hover-is-still-red
This style was getting overriden by govuk-frontend as the :link selector
is more specific.
Before: 
After:

Fix destructive link styling

---

app/assets/stylesheets/components/_summary.scss
app/views/components/_notice.html.erb
app/views/documents/show/_actions.html.erb

It doesn't make too much sense for these links to have a visited state
as they are displaying contextual actions that mean different things.

Make call-to-action links not have a visited state

---

app/assets/javascripts/components/markdown-editor.js

https://trello.com/c/NZ6oOwYo/461-preview-tab-on-the-edit-content-page-doesnt-work-in-ie-11-and-edge
Previously we used Promise.prototype.finally to ensure we added a
particular CSS class irrespective of the outcome of the promise.
Unfortuantely this is only supported in the newest versions of MS Edge.
This moves and duplicates this one line into the .then and .catch blocks
as an alternative to using .finally. This is the only place we use this
method in the app, so it doesn't seem worth fixing with a polyfill.

Fix markdown preview not working on Microsoft Edge

---

app/assets/stylesheets/utilities/_overwrites.scss
app/views/documents/show/_topics.html.erb
spec/features/editing_topics/show_topics_spec.rb

Changing the way of rendering a topic from an enumerated list of more
specific categories to rendering it like "A > B > C", in the same way
breadcrumb trails are used to show web page path ways to users in other
parts of GOV.UK.

Render topics using GOV.UK's breadcrumb component

---

app/assets/javascripts/components/markdown-toolbar.js

as it currently blocks users from inserting text after using the injectors
This change was done in the main repository: https://github.com/alphagov/markdown-toolbar-element/pull/2. This PR updates the compiled JavaScript file.
https://trello.com/c/fLfbI7Vi

Remove contenteditable

---

app/views/layouts/application.html.erb
app/views/publish_document/published.html.erb

https://trello.com/c/JsrpqR3h/419-iterate-design-of-content-has-been-published-confirmation-screen
- Removes empty `<div class="govuk-grid-row">` above the confirmation
panel, which was causing extra spacing.
- Removes 30px margin below title in confirmation panel (https://github.com/alphagov/govuk_publishing_components/pull/628)
- Replace copy-to-clipboard section to just show link in normal govuk-body styling

Iterate design of 'Content has been published' confirmation screen

---

app/assets/javascripts/components/markdown-toolbar.js

Run the `orderedList` style args only when we have a selection, otherwise we default on a simple prefixing of the current line.
This change was done in the main repository: https://github.com/alphagov/markdown-toolbar-element/pull/3. This PR updates the compiled JavaScript file.
https://trello.com/c/37P9Kykk

Fix ordered list injector

---

app/views/layouts/application.html.erb

https://trello.com/c/5q8xBQf7/448-add-link-to-govuk-publishing-status-to-the-footer-of-content-publisher

Add link to GOV.UK publishing status to the footer of content publisher

---

app/controllers/documents_controller.rb
app/formats/document_types.yml
app/services/document_type_schema.rb
app/services/publish_service.rb
app/services/requirements/document_checker.rb
app/services/requirements/edit_page_checker.rb
app/services/requirements/path_checker.rb
app/views/documents/show/_requirements.html.erb
config/locales/en/requirements.yml
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb
spec/services/requirements/path_checker_spec.rb
spec/spec_helper.rb

https://trello.com/b/mn2MqH3M/publishing-workflow-q3-18-19-doing
This is my first attempt at doing an external check for URL conflicts. One of the things I'm not keen on is that we're running this (not inexpensive) check every time we generate a preview, and perhaps we should just do it on the edit page and display an error there if the Publishing API is down.
What do people think?
On the other hand, I wanted to keep the way we do requirements consistent and avoid showing the user nasty error messages they can't do anything about - having an error on the edit page would stop people creating documents if the Publishing API is down.

Detect external url conflicts

---

app/assets/stylesheets/components/_markdown-editor.scss
app/views/documents/fields/_govspeak_input.html.erb

[Trello card](https://trello.com/c/fI3HVOpp/436-update-markdown-toolbar)

Iterate markdown toolbar and textarea

---

app/assets/javascripts/application.js
app/assets/javascripts/vendor/@alphagov/miller-columns-element/dist/index.umd.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_miller-columns.scss
app/views/document_topics/edit.html.erb
config/locales/en/document_topics/edit.yml

This PR:
- uses the [miller-columns-element](https://github.com/alphagov/miller-columns-element) to enhance the topics page
- adds a related navigation component for guidance and topics suggestions
- adds a details component to display a warning/notice before saving
Doesn't include:
- Displaying selected topics as breadcrumbs in the summary page
Notes:
- related navigation component doesn't seem to work on its own, which means this may need to be created differently or the component updated.
[Trello card 1](https://trello.com/c/qPhY7IHR)
[Trello card 2](https://trello.com/c/NVntfeQL)

Add miller columns element for topics

---

app/views/documents/fields/_govspeak_input.html.erb

Grammarly interferes with markdown editor making it impossible to insert and preview
How to replicate:
- Install grammarly
- Go to edit markdown field
- Experience grim position absolute issues
https://trello.com/c/1pgYWuWB/447-enable-markdown-editor-to-work-with-grammarly

Disables grammarly plugin for markdown editor

---

app/assets/javascripts/components/contextual-guidance.js
app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/utilities/_overwrites.scss
app/views/components/_contextual_guidance.html.erb
app/views/documents/fields/_govspeak_input.html.erb

This PR changes the contextual guidance position to be absolute so it doesn't move items on the page below with an exception for the markdown guidance which will continue to be relative (otherwise it will overlap the footer)
[Trello card](https://trello.com/c/CK8NjnuB)

Update contextual guidance

---

app/controllers/document_contacts_controller.rb

Trello: https://trello.com/c/uYAPhvxH/504-error-not-making-a-choice-in-add-contacts-causes-this-page-isnt-working-error
This seemed a simpler approach than setting up a validation error to
avoid this error scenario.
It would have been good to have a test for this but it's not really a
feature so ¯\_(ツ)_/¯

Stop contacts 400ing without a contact selected

---

app/helpers/application_helper.rb
app/views/publish_document/published.html.erb
config/locales/en/publish_document/published.yml

https://trello.com/c/MrK9ulAL/474-add-govuk-live-url-to-force-publish-confirmation-page

Add GOV.UK live URL to force publish confirmation page

---

config/locales/en/requirements.yml

Updated to make consistent the way we display names of docs and assets

Double quotes to single quotes

---

app/views/document_images/edit.html.erb

This PR disables the contextual guidance overflow for the image credit field.

Disable contextual guidance overflow for image credit field

---

app/controllers/documents_controller.rb
app/services/requirements/content_checker.rb
app/views/documents/edit.html.erb
config/locales/en/requirements.yml
spec/features/editing_content/edit_document_with_line_breaks_and_spaces_spec.rb
spec/services/requirements/content_checker_spec.rb

For https://trello.com/c/fg0KKIGQ/399-iterate-title-and-summary-requirements-add-new-line-stripping
In this PR:
- Leading and trailing line breaks are stripped from title & summary input before saving
- Title maximum character count is increased to 300
- Maximum character count of 600 implemented for the summary
- Character count added to the summary text area
- Pre-preview check implemented for line breaks in summary input
**Outstanding**
- @paola-roccuzzo to add guidance for suggested summary character limit in the sidebar guidance.

Iterate title summary requirements

---

app/assets/stylesheets/components/_markdown-editor.scss

Update style of add contact button

---

app/services/publishing_api_payload.rb
app/views/documents/edit/_change_notes.html.erb
config/locales/en/documents/edit.yml
spec/services/publishing_api_payload_spec.rb

For https://trello.com/c/Ms2oWVgS/445-implement-changes-to-change-notes
We are currently showing the change note text area to users regardless of whether the changes they have made are major or minor updates.  Since user shouldn't need to provide a change note when making a minor update, we change this so that the text area only appears when the user has indicated that their changes are major.
This PR also update the copy in this section as per https://docs.google.com/presentation/d/1FW5YCuksU_HQnlK6wyQnQNalRDRvrzRQwy1cTHNWmZA/edit#slide=id.g45aa9227d9_0_594
Note that this implementation means that the contextual guidance for change notes is now aligned with the bottom of the title question, rather than the top of the change note text area.

Display change notes for major updates only

---

app/models/document_topics.rb
spec/models/document_topics_spec.rb

Fix for https://sentry.io/govuk/app-content-publisher/issues/703085886/
If we haven't wrote a document to the Publishing API then any call to
get the links for it will return a 404. This was previously getting
picked up in an exception handler in the view, but since this is a
pretty normal part of a documents flow then it makes sense to be handled
in the DocumentsTopic itself.

Handle topics 404ing for a document

---

app/assets/javascripts/application.js
app/assets/javascripts/components/input-length-suggester.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_input_length_suggester.scss
app/views/components/_input_length_suggester.erb
app/views/components/docs/input_length_suggester.yml
app/views/documents/edit.html.erb
config/initializers/govuk_publishing_components.rb

Trello: https://trello.com/c/M3d7G6YG/501-iterate-character-count-text-and-rules
This is to resolve the somewhat misleading approach we had to character counts where we told users how many characters were remaining on a hard limit rather than suggesting they enter a value less than the ideal amount.
Demo:

Suggest ideal length in character counts

---

app/views/documents/edit.html.erb

I corrected the suggested length back to 160, as the AZ style guide on GOV.UK is out of date

Updated summary suggested length

---

app/models/document.rb
app/models/removal.rb
app/models/retirement.rb
app/models/timeline_entry.rb
app/services/document_unpublishing_service.rb
app/services/publish_service.rb
app/services/user_facing_state.rb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
config/locales/en/states.yml
db/migrate/20181128112113_add_live_state_to_document.rb
db/migrate/20181203123128_create_retirements.rb
db/migrate/20181203134354_create_removals.rb
db/schema.rb
spec/factories/removals.rb
spec/factories/retirements.rb
spec/models/timeline_entry_spec.rb
spec/services/document_unpublishing_service_spec.rb
spec/services/user_facing_state_spec.rb

Trello: https://trello.com/c/2VIaBEOi
Supersedes: PR #548
In PR #510 a task was added to allow us manually remove or retire documents in publishing-api. Now we need to reflect the state of those documents in Content Publisher.
An explanation of what retired and removed documents are can be found [here](https://github.com/alphagov/content-publisher/blob/master/docs/retiring-and-removing-documents.md#retiring-and-removing-documents). 
1. Documents can be filtered by removed or retired from the "States" drop-down
2. State of document is displayed as "retired" or "removed" on index page
3. Document history has an entry for retired documents that displays a note about why the document was retired. This is the same as the explanation that appears in the banner on the live site.
4. Document …

Update the state of retired and removed documents

---

app/assets/stylesheets/components/_page-preview.scss

This PR updates the page preview component to drop the mobile frame and only present the default preview and the Google search snippet.
[Trello card](https://trello.com/c/qMVliSBq)

Disable mobile preview on mobile and use the default one instead

---

config/locales/en/documents/show.yml

@emmabeynon fixed default images
https://trello.com/c/w1QxJ7gk/500-update-rummager-to-lookup-organisation-default-news-image-when-setting-the-image-for-an-indexed-document?menu=filter&filter=member:emmabeynon2

Put the default image copy back

---

app/views/documents/show/_history_tab.html.erb

Fixes bug introduced in PR #575
Trello: https://trello.com/c/exMkuccz
The alternate_path is an optional field for removed documents. It is only required if the document is also being automatically redirected.
Add a guard so we don't try and display a link to this path if it doesn't exist.
Error in sentry: https://sentry.io/govuk/app-content-publisher/issues/792806891

Fix alternate path bug

---

app/views/components/_markdown_editor.html.erb
app/views/components/_summary.html.erb
app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/layouts/application.html.erb
app/views/publish_document/confirmation.html.erb
app/views/publish_document/published.html.erb

Trello: https://trello.com/c/yRnJfrDN/487-deployment-of-remaining-data-attributes-for-consistent-event-tracking-in-gtm
This completes most of the updates specified in https://docs.google.com/document/d/1VoX4Ef6IqjRLpLpHDWG_gEjpSe7vWoUNsnW5Q1Oqz4c/edit# that aren't a point of question at this point.
Hopefully most of the changes are relatively self explanatory.

Updates for google tag manager

---

app/views/documents/show/_contents.html.erb
spec/features/workflow/edition_spec.rb

https://trello.com/c/hj7RXU4S/532-content-summary-change-note-meta-data-and-fix-mobile-styles
This also fixes the metadata on the document summary page so that
we don't show the change note for minor changes, so that it's consistent
with the way we handle this on the edit page.

Only show edition metadata for subsequent editions

---

app/views/components/_markdown_editor.html.erb
app/views/components/_markdown_guidance.html.erb
app/views/components/_page_preview.html.erb
app/views/document_contacts/search.html.erb
app/views/document_images/index.html.erb
app/views/documents/edit.html.erb
app/views/documents/show.html.erb
app/views/documents/show/_delete_draft.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/layouts/application.html.erb

https://trello.com/c/yRnJfrDN/487-deployment-of-remaining-data-attributes-for-consistent-event-tracking-in-gtm
I paired with Andy to work out these bits of tracking so he doesn't have to rely on CSS selectors.
This does need https://github.com/alphagov/govuk_publishing_components/pull/662 to fully work as the error alert and error summary fields don't support data attributes yet, but to be honest it's probably not much of a concern if we merge this before.

Add more Google Tag Manager data attributes

---

app/controllers/document_images_controller.rb
app/views/document_images/_image_list.html.erb
app/views/document_images/_lead_image.html.erb
config/routes.rb
spec/features/editing_images/download_image_spec.rb

Clicking the download link will crop the image to 960x640 and download
it to the users computer. This is useful for whitehall users as images
uploaded here can easily be cropped and used in whitehall publisher.
Due to a discussion with Sonia, the link order has also been amended
which moves the `delete image` link to the end of the list.
Trello:
https://trello.com/c/w4aI961C/529-provide-a-960x640-download-link-for-images

Add download link to images

---

app/assets/stylesheets/components/_markdown-editor.scss

Not setting a default height and width on toolbar buttons results in not having these elements visible on the page unless there is a content/icon inside. Even when we set these values there is chance that the click will actually happen on the `<svg>` rather the `<md->` button so we're disabling the `pointer-events` on `<svg>`s inside these buttons.
This is currently causing issues with GTM tracking not being able to determine which element was clicked (it triggers a click on the svg inside the `<md->` element instead of the `<md->` element itself.
This change doesn't visually affect the component in any way.
[Trello card](https://trello.com/c/yRnJfrDN)

Fix markdown editor CSS

---

app/services/requirements/path_checker.rb

https://sentry.io/govuk/app-content-publisher/issues/682768231/events/39171131112/
Previously we used the Publishing API defaults to lookup any existing
owner (content_id) for a base_path, which excluded certain document
types like redirects. This overrides the default to check all types.

Make path checker more sensitive

---

db/migrate/20181214112140_nullify_user_for_timeline_entry.rb
db/schema.rb

This change alters what happens when a user is deleted. Previously, a
user could not be deleted if they had timeline_entries. Now, users_id
gets set to null on deletion of a user.
This enables us to remove users from the system without having errors
related to database relations.

Nullify users foreign key on delete for timeline_entries

---

app/assets/javascripts/components/autocomplete.js

Sorry, I accidentally introduced this [a few minutes ago](https://github.com/alphagov/content-publisher/pull/604/files#diff-e939db0e1c9c6b800d2850384df539c2R18), which disables the `minLength` and breaks in IE11.

Remove showAllValues: false

---

app/assets/stylesheets/components/_miller-columns.scss

This currently prevents the users from clicking checkboxes inside a miller-columns tag on a no-JavaScript experience.

Disable pointer-events for miller-columns checkboxes only if the JavaScript is enabled

---

app/services/asset_manager_service.rb
app/services/image_update_service.rb
spec/features/editing_images/edit_image_crop_asset_manager_down_spec.rb
spec/features/editing_images/edit_image_crop_spec.rb
spec/features/editing_images/edit_image_metadata_spec.rb
spec/features/editing_images/upload_lead_image_spec.rb

https://trello.com/c/czJdLQCW/552-updating-assets-in-assetmanager-requires-mutating-an-image-to-upload-a-new-asset-deleting-the-old-asset-then-updating-the-databa
Previously we used to delete and recreate images in Asset Manager
whenever the crop was changed. This changes the update code to do this
using a single request.

Update image in Asset Manager (vs delete/recreate)

---

app/services/publishing_api_payload.rb
spec/services/publishing_api_payload_spec.rb

Trello: https://trello.com/c/hGmJ5BfV
Follows on from https://github.com/alphagov/govuk-content-schemas/pull/850
Content Publisher allows publishers to add an image credit, but at the moment we don't have a way to access this data in the frontend.
This step passes the image credit to the payload for publishing-api so it is available for use by the frontend applications.

Add image credit to the payload for publishing-api

---

app/services/requirements/image_checker.rb
config/locales/en/requirements.yml
spec/services/requirements/image_checker_spec.rb

Trello: https://trello.com/c/hGmJ5BfV
Restrict the number of characters a user can enter in the credit field to 160 characters.

Add requirement for image credit

---

app/assets/javascripts/components/autocomplete.js

Ticket: 
- ~https://trello.com/c/pYDNDc14/565-issue-search-contacts-does-not-start-showing-choices-until-the-third-character-typed~
- https://trello.com/c/qXFrMELH/624-autocomplete-does-not-show-users-any-message-in-an-event-of-no-result
Screenshots:

Adds no results message

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/models/document.rb
app/models/internal_note.rb
app/models/timeline_entry.rb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
db/migrate/20181212165840_create_internal_notes.rb
db/schema.rb
spec/factories/internal_note_factory.rb
spec/factories/timeline_entry_factory.rb
spec/features/workflow/internal_note_spec.rb
spec/helpers/application_helper_spec.rb

Initial creation of the internal notes feature. Currently you can only create a internal note from the console which then displays in the document history section of the document page.
Trello:
https://trello.com/c/jilfIus0/547-mvp-of-reading-internal-notes

Add internal notes backend

---

spec/javascripts/components/contextual-guidance-spec.js
spec/javascripts/components/input-length-suggester-spec.js
spec/javascripts/components/url-preview-spec.js
spec/javascripts/modules/gtm-form-listener-spec.js
spec/javascripts/modules/warn-before-unload-spec.js

Quick clean in the JavaScript specs as a few StandardJS linting errors made their way in.
Also replaced the template literals for consistency, and, if I remember well they're not supported but our testing framework - also helps running the tests cross browser.

Lint JavaScript tests

---

app/views/components/_metadata.html.erb
app/views/components/docs/metadata.yml
app/views/documents/show.html.erb
app/views/documents/show/_document_metadata.html.erb
app/views/layouts/application.html.erb

This PR replaces document type and status pushed to dataLayer with `data-gtm` attributes
[Trello card](https://trello.com/c/QHmf1x47)

Add data-gtm attributes for document type and status

---

app/assets/javascripts/vendor/@alphagov/miller-columns-element/dist/index.umd.js

This release fixes the topics constructor failing to initialise.
Review the change in the [miller-columns-element](https://github.com/alphagov/miller-columns-element/pull/6) repository.
[Trello card](https://trello.com/c/g1linbAJ)

Update miller-columns to v0.0.2

---

spec/features/editing_images/upload_lead_image_spec.rb
spec/features/workflow/preview_publishing_api_down_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb

Made possible after https://github.com/alphagov/content-publisher/pull/658.

Replace TODO for Webmock with API method

---

app/services/versioned/asset_manager_service.rb
app/services/versioned/unpublish_service.rb
spec/services/versioned/asset_manager_service_spec.rb
spec/services/versioned/unpublish_service_spec.rb

When this was originally wrote there was an expectation that you could
use it to remove/retire a live version while there is a draft present.
It transpires that this is actually not possible in the Publishing API,
the options you have there is either you can transition a draft to
unpublished (with the allow_draft option) or you can discard the draft
at the same time as unpublishing the live edition (with the
discard_draft option). Without one of these Publishing API will error
422 with:
```
"error":{"code":422,"message":"Cannot unpublish with a draft present","fields":{}}}
```
Thus this changes this code here to do checks on whether we're actually
trying to remove a live one and that a draft is not present.
As …

Raise errors in UnpublishService when drafts are used

---

app/services/versioned/preview_service.rb
spec/features/versioned/editing_images/edit_image_crop_spec.rb
spec/features/versioned/editing_images/edit_image_metadata_spec.rb
spec/features/versioned/editing_images/remove_lead_image_spec.rb
spec/features/versioned/editing_images/upload_lead_image_spec.rb
spec/features/versioned/workflow/delete_draft_asset_manager_down_spec.rb
spec/features/versioned/workflow/delete_draft_spec.rb
spec/features/versioned/workflow/publish_asset_manager_down_spec.rb
spec/services/versioned/publish_service_spec.rb
spec/services/versioned/unpublish_service_spec.rb
spec/support/asset_manager_helper.rb

This undoes the change that only uploaded images to Asset Manager if the
file was the lead image. This is in preparation for inline images where
we may want to use any of these images.
As part of this the AssetManagerHelper for tests has been created to
provide access to the mocking methods that have thus far been set up
inconsistently across these tests.
We may well want to move those methods to GDS API Adapters.

Upload all images to asset manager

---

app/models/versioned/edition.rb
app/models/versioned/revision.rb
db/migrate/20190118102825_reinstate_versioned_edition_revisions.rb
db/schema.rb

This stops indirectly associating the edition history of a revision
through statuses and instead re-instates storing this directly. This is
to keep these concepts distinct and to remove the coupling.

Reinstate revision edition many to many

---

app/models/versioned/edition.rb
app/services/versioned/delete_draft_service.rb
app/services/versioned/preview_service.rb
app/services/versioned/publish_service.rb
app/views/versioned/documents/show/_actions.html.erb
app/views/versioned/documents/show/_requirements.html.erb
db/migrate/20190118121447_add_revision_synced_to_versioned_editions.rb
db/migrate/20190118151754_remove_draft_from_versioned_edition.rb
db/schema.rb
spec/factories/versioned_edition_factory.rb
spec/features/versioned/editing_content/edit_document_publishing_api_down_spec.rb
spec/features/versioned/workflow/preview_publishing_api_down_spec.rb
spec/features/versioned/workflow/preview_requirements_spec.rb
spec/services/versioned/delete_draft_service_spec.rb

This replaces the string column on versioned_editions with a
publishing_api_synced column. This column is to be of most use in a
draft context where we allow state changes and edits while a document is
not on the Publishing API. Whereas once we are in the realm of live
states the Publishing API must be synced for the state to be valid.
An area of confusion this introduces is whether this still makes
semantic sense on old editions that have been replaced on Publishing
API, in theory though since to publish the next item they have been
synced so I guess it still makes sense.

 Replace draft column on versioned_editions

---

db/migrate/20190116194130_cascade_image_revision_joins_on_revision_delete.rb
db/schema.rb

Prior to this change you would be unable to delete entries out of the
revision table if there were any associations with image revisions. This
might make these prohibitively hard to delete, instead we decide since
revision is the more important concept that if you want to delete that
then lose the joins.
We don't however allow the ability to remove an image revision without
removing the join first, this is because image_revisions are part of the
state of a revision and these should only be removed (without removing
the revision) with caution and exceptional circumstance.
Like many of these on_delete behaviours these are not here for day to
day to usage of the application, and are mostly anticipated to get used
in …

Fix image revisions blocking revision deletion

---

app/controllers/debug_controller.rb
app/models/metadata_revision.rb
app/models/revision.rb
lib/tasks/whitehall_news_importer.rb
spec/factories/metadata_revision_factory.rb
spec/factories/revision_factory.rb
spec/models/metadata_revision_spec.rb
spec/models/revision_spec.rb

This hopefully provides a more useful name to follow for the model which
stores the information such as update type and change log. The previous
name UpdateRevision was not remotely self explanatory and although I'm
not sure MetadataRevision tells a whole lot more it does seem an
improvement.
It is also consistent in naming with the Image::MetadataRevision model.
To follow on from this are database migrations that change the
underlying table and column names. As we have a batch of these to do and
they may momentarily cause application errors I intend to group these.

Rename UpdateRevision to MetadataRevision

---

app/assets/javascripts/components/markdown-editor.js
app/assets/stylesheets/components/_markdown-editor.scss
app/views/components/_markdown_editor.html.erb
app/views/components/docs/markdown_editor.yml
app/views/documents/fields/_govspeak_input.html.erb
spec/javascripts/components/markdown-editor-spec.js

Update component so is doesn't rely on absolute positioning while preserving the visual styles for focus state.
👉 [Preview markdown editor component](https://content-publisher-revie-pr-659.herokuapp.com/component-guide/markdown_editor)
Problems solved with the new approach:
- scrolling the textarea overlaps the editor header (https://trello.com/c/uiCA2sAo)
- grammarly interferes with the component positioning hiding the editor header (https://trello.com/c/1pgYWuWB)
[Trello card](https://trello.com/c/C7RtuUhV)

Re-approach the markdown editor styling

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/gtm-track-copy.js
app/views/components/_page_preview.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/publish/published.html.erb
spec/javascripts/modules/gtm-track-copy-spec.js

This PR enables tracking of `copy` and `paste` events using GTM on specific components (initially markdown-editor and copy-link).
Author of PR: @erino; I did some clean up and updated tests.
[Trello card](https://trello.com/c/QHmf1x47)

Add copy and paste tracking using GTM data layer

---

app/services/requirements/image_upload_checker.rb
config/locales/en/requirements.yml
spec/features/editing_images/upload_lead_image_requirements_spec.rb
spec/services/requirements/image_upload_checker_spec.rb

The combined message might be confusing when a user uploads an animated
image, as the message doesn't higlight this problem specifically.

Use separate messages for invalid image formats

---

app/controllers/unpublish_controller.rb
app/models/status.rb
app/models/timeline_entry.rb
app/models/withdrawal.rb
app/services/unpublish_service.rb
app/views/documents/index/_filters.html.erb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_history_tab.html.erb
app/views/unpublish/withdraw.html.erb
config/locales/en/documents/history.yml
config/locales/en/states.yml
config/locales/en/unpublish/withdraw.yml
config/routes.rb
docs/withdrawing-and-removing-documents.md
lib/tasks/unpublish.rake
spec/factories/withdrawal_factory.rb
spec/features/workflow/unpublish_spec.rb
spec/services/unpublish_service_spec.rb

For https://trello.com/c/oyI7eOlC/586-change-all-internal-references-to-retirement-withdrawal
This renames internal references to "retirement" to "withdrawal" ahead of building out the withdrawal workflow to ensure consistency and avoid future confusion.  This does not include renaming the `versioned_retirements` table, which will be renamed at a later date along with the other `versioned_` prefixed tables

Rename retirement to withdrawal

---

db/migrate/20190122104549_delete_pre_versioning_tables.rb
db/schema.rb

https://trello.com/c/5JMGsuBj/581-follow-up-work-from-versioning-review
This removes the tables that have been made redundant by the new
versioning code, and their associated foreign keys. We will rename the
new tables to omit the 'versioned' namespace in a subsequent PR, noting
that this change will cause some downtime.
The migration is deliberately non-reversible because these tables are
unused, so we do not expect to need to rollback for any reason.

Delete old tables superseded by versioning

---

app/controllers/internal_notes_controller.rb
app/models/timeline_entry.rb
app/views/documents/show/_history_tab.html.erb
config/locales/en/documents/history.yml
config/routes.rb
spec/features/workflow/access_internal_notes_without_pre_release_flag_spec.rb
spec/features/workflow/internal_note_spec.rb

Currently a developer can create a internal note through the console which will in turn display a internal note on the document history page. The functionality thats been added here is to create a form so publishers can add one themselves. 
Sister PR to:
https://github.com/alphagov/content-publisher/pull/612
Trello:
https://trello.com/c/HCnzVUss/549-ability-to-create-internal-notes

Add create internal notes form

---

app/controllers/editions_controller.rb
app/controllers/publish_controller.rb
app/models/document.rb
app/models/edition.rb
app/services/delete_draft_service.rb
app/services/requirements/content_checker.rb
app/views/debug/index.html.erb
app/views/documents/edit.html.erb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_contents.html.erb
app/views/documents/show/_history_tab.html.erb
app/views/documents/show/_lead_image.html.erb
app/views/documents/show/_requirements.html.erb
app/views/documents/show/_tags.html.erb
spec/services/delete_draft_service_spec.rb
spec/services/publish_service_spec.rb
spec/services/unpublish_service_spec.rb
spec/tasks/whitehall_news_importer_spec.rb

This PR comprises of a few updates in relation to ActiveRecord booleans.
It first adds in a `#editable?` method to Edition which returns the inverse of `#live?`.
It then uses a question mark suffix on the places we use ActiveRecord Booleans.
It removes a `#live?` method from Document so that's not confused with `#live?` on Edition.
And then updates tests for consistency.

Various versioning related boolean updates

---

app/controllers/contacts_controller.rb
app/controllers/documents_controller.rb
app/controllers/images_controller.rb
app/controllers/lead_image_controller.rb
app/controllers/tags_controller.rb
app/models/edition.rb

Edition used delegate_missing_to Revision, this was a somewhat divisive decision, so it has been changed to delegate just specific methods.
As part of this I pondered that we probably didn't want to have the `build_revision_update*` methods on an edition so I didn't delegate those and had a couple of extra lines to controllers to call them on a revision.

Stop using delegate_missing_to

---

app/models/document.rb
app/views/debug/index.html.erb
app/views/images/edit.html.erb
app/views/topics/edit_api_down.html.erb
spec/features/editing_content/url_preview_spec.rb
spec/features/workflow/show_with_creator_spec.rb
spec/services/path_generator_service_spec.rb

Using these didn't seem to add much value and seems to introduce some
confusion. Using a current_edition_title vs current_edition.title
doesn't save any characters.
So the main reason for these to exist is to conform to the Law of
Demeter, which we can always go back to if needed.

Remove delegated current_edition methods from document

---

.rubocop.yml
app/models/content_revision.rb
app/models/document.rb
app/models/edition.rb
app/models/image.rb
app/models/image/asset.rb
app/models/image/file_revision.rb
app/models/image/metadata_revision.rb
app/models/image/revision.rb
app/models/internal_note.rb
app/models/metadata_revision.rb
app/models/removal.rb
app/models/revision.rb
app/models/status.rb
app/models/tags_revision.rb
app/models/timeline_entry.rb
app/models/withdrawal.rb

This removes the rules requiring InverseOf and HasManyOrHasOneDependent. See commits for further details.

Loosen rails linter

---

app/models/edition.rb
spec/models/revision_spec.rb

This is a somewhat crude exception that prevents the situation where a
user is able to edit a live edition by preventing this with an exception
at the point of assigning a revision.
I'm writing the fateful words that haunt a developer in later years that
this is intended to be temporary. Ideally we'd have a view or an alert
presented to the user to describe the edition is now live and you should
create a new edition to make changes.
Before versioning was introduced this behaviour was managed by the
PreviewService which would automatically create a new edition if a user
managed to edit a live edition. This behaviour doesn't feel correct as
creating a new edition is quite a big step for a document so a user …

Block changing revision on a live edition

---

app/models/edition.rb
app/services/publish_service.rb
app/services/topic_index_service.rb
spec/factories/edition_factory.rb
spec/tasks/whitehall_news_importer_spec.rb

This makes this consistent rather than using Time.current in some places
and Time.zone.now in others.

Use Time.current everywhere

---

app/views/documents/index/_filters.html.erb

Since this link is used to reset a dynamic page it doesn't make sense
for this to show a visited state as this is more of an action than a
link to a consistent resource.
Before:
After:

Set clear all filters link to not show visited state

---

README.md

GitHub Markdown doesn't recognise non breaking spaces when rendering.

Use a U+0020 space over a U+00A0 space

---

db/migrate/20190125181528_remove_versioned_editions_current_and_live_indexes.rb
db/schema.rb

These are removed as we're not convinced these are currently adding any
value.
Initially the expectation was that the current index
provided performance benefits for the EditionFilter used on the index
page. The live index was then added to match.
However my most recent tests haven't shown a significant difference so
they may well be a drop in the bucket for the potential performance
problems on the index filter. So it's probably just simpler to remove
them now and do something if we discover a problem.
Some query plans:
<details>
<summary>With index</summary>
```
content_publisher_development# EXPLAIN ANALYZE SELECT  "versioned_editions".* FROM "versioned_editions" INNER JOIN "versioned_revisions" ON …
```

Remove live and current indexes

---

db/migrate/20190125181528_remove_editions_current_and_live_indexes.rb
db/migrate/20190125181528_remove_versioned_editions_current_and_live_indexes.rb

This change removes the `versioned_` prefix from this migration.

Amend editions current and live migration

---

docs/adr/0008-restricted-deletion.md

The numbering got missed in the merge process.

Assign ADR-8

---

Jenkinsfile
Rakefile
lib/tasks/factorybot.rake
lib/tasks/lint.rake
spec/factories/document_type_factory.rb
spec/factories/field_factory.rb
spec/factories/guidance_factory.rb
spec/factories/tag_field_factory.rb

FactoryBot offers a lint method to check the validity of each of the factories we have. This should be enabled to run as part of the default rake task and as part of our Jenkins build.
Trello:
https://trello.com/c/J48ZqCto/593-enable-factorybot-linting

Enable factory bot linting

---

Jenkinsfile

This was causing test failures in CI due to the linter being ran against an
old version of the db. As rails db:reset had not been run yet and there
was still migrations pending the linter was trying to create factories
against old tables (column names) which caused the lint to fail.
Moving this to run after the tests means the db is set up correctly for
the linter.

Run factorybot linter after db has been set up

---

lib/tasks/development_permissions.rake

This is so devs can easily get all the permissions they need to run all parts of the app

Add MANAGING_EDITOR_PERMISSION to dev permissions rake task

---

app/assets/stylesheets/core/_link.scss
app/assets/stylesheets/utilities/_overwrites.scss
app/views/documents/show/_delete_draft.html.erb

This removes the duplicated .govuk-link class from the overwrites and
moves the css styling from the `delete_draft` html template to the
link.css file.
While doing this the styling has also been modified to accommodate
mobile / tablet and functions have been used instead of hard coded
values.

Clean up css for govuk-link

---

app/formats/document_types.yml
app/models/document_type.rb
app/services/publishing_api_payload.rb
app/views/documents/show/_summary_tab.html.erb
spec/features/editing_images/choose_lead_image_spec.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/delete_lead_image_spec.rb
spec/features/editing_images/download_image_spec.rb
spec/features/editing_images/edit_image_crop_spec.rb
spec/features/editing_images/edit_image_metadata_requirements_spec.rb
spec/features/editing_images/edit_image_metadata_spec.rb
spec/features/editing_images/remove_lead_image_spec.rb
spec/features/editing_images/upload_inline_image_spec.rb
spec/features/editing_images/upload_lead_image_requirements_spec.rb
spec/features/editing_images/upload_lead_image_spec.rb
spec/features/workflow/preview_requirements_spec.rb
spec/services/publishing_api_payload_spec.rb

https://trello.com/c/ZYFBN0ns/560-support-rendering-inline-images
Now that we support inline images as part of the lead image workflow, it
makes sense to rename this flag, so it's not specific to lead images.

Rename lead_image flag to images

---

app/controllers/images_controller.rb
app/services/draft_asset_cleanup_service.rb
app/services/preview_service.rb
spec/features/editing_images/delete_image_spec.rb
spec/features/editing_images/delete_lead_image_spec.rb
spec/features/editing_images/edit_image_crop_spec.rb
spec/services/draft_asset_cleanup_service_spec.rb
spec/services/preview_service_spec.rb

This uses the point of creating a preview as a point to delete assets
from Asset Manager which are no longer used.
When an edition is sent to the preview service the previous revision
assets are compared with the current revision and any that are in a
draft state are then deleted from Asset Manager.
This doesn't feel like the most robust of solutions as if assets are not
removed at this point they will remain in draft forever. The approach
that would resolve that would be to have some form of scheduled task
that performs a cleanup of assets periodically. However since we don't
have prior art currently in scheduled tasks on this app I have not
implemented it.

Remove old draft assets from Asset Manager when they are no longer used

---

app/models/edition.rb

Off the back of https://github.com/alphagov/content-publisher/pull/709 I went down the road of trying out current_revision and current_status in https://github.com/alphagov/content-publisher/compare/make-names-verbose-and-current-repetitive
Doing that actually increased my concerns. But do have a look through and see if you feel that is actually a benefit or makes the code easier to understand.
The reasons I think adding the current prefix isn't a good idea are:
- It's implied and superfluous
- It starts a spread of increasing use of "current_" in various parts of an edition
- renames assign_status to assign_current_status
- renamed assign_revision to assign_current_revision
- should then rename …

Counter proposal on current_status and current_revision

---

app/assets/stylesheets/core/_link.scss
app/views/images/_image.html.erb
app/views/images/_lead_image.html.erb

Previously we overwrote govuk-link to style any links as buttons, but
the behaviour was lost in a recent PR. This re-instates the behaviour
using a specific class to complement govuk-link, so that the behaviour
is better documented, and only applied where it's actually necessary.

Fix styling for image button actions

---

app/views/withdraw/new.html.erb

This changes the link to be within a govuk-body class so that the size
of the text matches other body content. This brings this to be visually
closer to the design Sonia prepared.
Before:
After:
Design: https://content-publisher-prototype.cloudapps.digital/withdraw

Fix withdraw cancel link being smaller text

---

app/services/unpublish_service.rb
app/views/documents/show/_withdrawn_notice.html.erb
db/migrate/20190207183954_add_withdrawn_at_to_withdrawal.rb
db/schema.rb
spec/factories/edition_factory.rb
spec/factories/status_factory.rb
spec/factories/withdrawal_factory.rb
spec/services/unpublish_service_spec.rb

Trello: https://trello.com/c/GGxgDv3W/533-add-form-to-let-users-withdraw-a-document
We previously used the time a status was created to show a user when a
piece of content was withdrawn, however this is not accurate if you
update the explanation of a withdrawal as this creates a new status.
Thus the way I've approached resolving this is by passing a timestamp
among the details of Withdrawal objects so that this data is persisted.
If a user undoes a withdraw and re-withdraws this timestamp will be
reset.
Note: this migration relies on there not being any withdrawal records persisted, as is the case in production. In a dev environment it may well require a db:reset. For integration it should be straightforward if the data sync has ran, if not it’ll need any documents that have been …

Resolve issue where withdrawal time changes

---

app/views/withdraw/non_managing_editor.govspeak.md
app/views/withdraw/non_managing_editor.html.erb
config/locales/en/withdraw/withdraw.yml

This change comes from a content review by Ben Hazell.
Another change being made is moving the govspeak markdown from locales to its own template
as locales should only store around one line sentences and shouldn't be used to store larger bodies of text with multiple paragraphs.
As mentioned here:
https://trello.com/c/yhcKNEWr/587-allow-users-undo-withdraw

Update non_managing_editor error description for withdraw workflow

---

app/controllers/application_controller.rb

https://sentry.io/govuk/app-content-publisher/issues/882726330/events/45d88c2a6e914dd4a5c2206d628d95b9/
Previously we've seen errors arising with multiple users interacting
with the same document. Having the user ID associated with the error
will help us to better debug these issues.

Add user ID to context for Sentry errors

---

app/controllers/withdraw_controller.rb
app/models/timeline_entry.rb
app/services/unpublish_service.rb
app/views/documents/show/_history_tab.html.erb
app/views/withdraw/new.html.erb
app/views/withdraw/non_managing_editor.govspeak.md
app/views/withdraw/non_managing_editor.html.erb
config/locales/en/documents/history.yml
spec/factories/edition_factory.rb
spec/factories/status_factory.rb
spec/features/workflow/edit_withdrawal_spec.rb
spec/services/unpublish_service_spec.rb

Trello: https://trello.com/c/GGxgDv3W/533-add-form-to-let-users-withdraw-a-document
This addresses comments raised by Ben in: https://github.com/alphagov/content-publisher/pull/749#pullrequestreview-201081495
It redirects when a user submits the same explanation for updating a withdrawal.
It updates the button on the form to update an explanation. 
See:
And changes what's shown on the timeline entry:
See:
There's a secondary issue I noticed while doing this that the withdrawal date can go wrong so I'm going to fix that in a separate PR.

Don't store identical withdrawal submissions and withdrawn_update timeline entry

---

app/controllers/unwithdraw_controller.rb
app/controllers/withdraw_controller.rb
app/views/publisher_information/beta_capabilities.govspeak.md
app/views/publisher_information/publisher_updates.govspeak.md
app/views/unwithdraw/_confirm.html.erb
app/views/unwithdraw/non_pre_release.govspeak.md
app/views/unwithdraw/non_pre_release.html.erb
app/views/withdraw/withdraw.html.erb

This removes the pre-release flag and allows managing editors of content publisher to withdraw a document, they can also undo a withdrawal to reinstate the document to live on GOV.UK.
The following pr needs to be merged before this can be:
https://github.com/alphagov/content-publisher/pull/757
Trello:
https://trello.com/c/UAsOLgQ7/610-feature-release-master-card

Release withdraw feature

---

app/assets/stylesheets/objects/_side.scss

Fix side action buttons or links floating

---

db/migrate/20190212110438_rename_image_timeline_entry_types.rb
db/schema.rb

https://trello.com/c/JcQEznco/605-add-checkbox-to-select-unselect-a-lead-image-on-metadata-page
Previously we added support for 'lead_image_selected' and
'image_deleted' to replace 'lead_image_updated' and 'image_removed'.
This migrates the existing data to use the new entry types, after which
we will remove support for the old entry types.

Rename image TimelineEntry types

---

spec/javascripts/components/markdown-editor-spec.js

This is a workaround for our JS tests failing due to patchy support for
blur/focus in headless chrome. This is consistent with other synthetic
focus/blur events used in our tests see:
https://github.com/alphagov/content-publisher/blob/e077713857ffc8bc1404b9fa45e102cc582f1a18/spec/javascripts/components/url-preview-spec.js#L55
On my machine they now pass:
```
➜  content-publisher git:(fix-js-tests) ✗ rake jasmine:ci
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:62320
Use Ctrl-C to stop
jasmine server started
Waiting for suite to finish in browser ...
.................................
33 specs, 0 failures
Randomized with seed 76008 (rake …
```

Use synthetic blur/focus events in JS tests

---

app/views/documents/show/_withdrawn_notice.html.erb

https://trello.com/c/HcfYSpjX/634-allow-notice-component-to-accept-html
Previously the 'notice' component would accept govspeak as it's block
input, but this has changed to HTML in the most recent version, such
that the applied class now works. This manually renders the withdrawal
explanation with Govspeak to preserve the desired behaviour, as well as
replacing the <p> elements with a <br> to preserve the previous spacing.

Fix visited state on link to change withdrawal

---

app/assets/javascripts/components/modal-dialogue.js

This exposes a function to manually focus the dialog box of the modal,
in case the content changes dynamically and lose the previously focussed
element. Because the code uses the focus() function to achieve this,
it's not possible to verify this behaviour in our headless JS tests :-(.

Expose function to re-focus the modal dialog box

---

app/views/components/_modal_dialogue.html.erb
app/views/components/docs/modal_dialogue.yml
spec/javascripts/components/modal-dialogue-spec.js

Previously the modal had a title option and populate its own title
element that would act to describe the modal, using aria-labelledby.
Using static markup for the title makes it difficult to show existing
pages in the modal, which already contain markup for their own titles.
This removes the static title markup within the modal component and
instead adds an mandatory option to specify which title element to use.

Replace internal modal title with a title ID

---

app/views/components/_modal_dialogue.html.erb
app/views/components/docs/modal_dialogue.yml

Previously we used the attribute to identify the function of the modal,
but testing with a screen reader shows this is redundant, as the reader
simply reads the title twice. This removes the redundant attribute, as
we believe it's sufficient that the modal content provide a heading that
describes what the modal is about; no further markup seems necessary.

Remove aria-labelledby attribute on modal

---

app/assets/stylesheets/components/_autocomplete.scss
app/assets/stylesheets/components/_contextual-guidance.scss
app/assets/stylesheets/components/_formatted-text.scss
app/assets/stylesheets/components/_image-cropper.scss
app/assets/stylesheets/components/_image-meta.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/components/_markdown-guidance.scss
app/assets/stylesheets/components/_metadata.scss
app/assets/stylesheets/components/_side-navigation.scss
app/assets/stylesheets/components/_summary.scss
app/assets/stylesheets/components/_url-preview.scss
app/assets/stylesheets/components/_warning-summary.scss
app/assets/stylesheets/core/_link.scss
app/assets/stylesheets/objects/_pane.scss
app/assets/stylesheets/objects/_side.scss
app/assets/stylesheets/utilities/_overwrites.scss

We're currently [importing govuk-frontend/all via govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/_all_components.scss#L9) since [#683](https://github.com/alphagov/govuk_publishing_components/pull/683), so there's no point in continuing to explicitly import only the needed dependencies as they're all available.

Remove explicit scss imports

---

app/views/layouts/application.html.erb

Trello: https://trello.com/c/ZhLNktSm/644-add-user-id-tracking-to-content-publisher
This is so we can monitor session behaviour of particular users and see
when they're using different browsers/devices.
According to Andy it is acceptable privacy wise to send an id that has a
meaning in our internal systems but cannot be used out of context to
identify the user. I debated whether it would be better to run this
through a one way cryptographic hash function such as SHA1 but I'm not
sure that offers any actual benefits.

Send user uid value to Google Tag Manager

---

app/assets/javascripts/application.js
app/assets/javascripts/components/multi-section-viewer.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_multi-section-viewer.scss
app/views/components/_multi_section_viewer.html.erb
app/views/components/docs/multi_section_viewer.yml
spec/javascripts/components/multi-section-viewer-spec.js

Add component to show one section at a time
This component is intended to show a single block of HTML (a 'section').
Sections can be specified in the config, or dyanmic content can be shown
in a special section, using the API exposed by the component's module.
This component has been created to support the modal work on inline
images, which involves replacing the entire content of the modal
multiple times, either with a static screen, such as a loading screen,
or with dynamic content that forms part of the inline image workflow.
In order to avoid any flickering, the content of each section is wrapped
with a class to hide it by default, using styles to override this. Since
the point of this …

Add component to show one section at a time

---

app/views/components/_multi_section_viewer.html.erb

Previously we required an ID to be specified for this component.
This auto-generates the ID if it's not specified, to support support a
more consistent initialisation by data-module as part of the modal work
for inline images, where the scope of the module is already isolated.

Add auto-generated ID to multi-section-viewer

---

app/controllers/schedule_controller.rb
app/helpers/application_helper.rb
app/helpers/time_options_helper.rb
app/models/revision.rb
app/services/requirements/scheduled_datetime_checker.rb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_scheduling_form.html.erb
config/locales/en/requirements.yml
config/routes.rb
db/migrate/20190214120136_add_schedule_date_to_metadata_revision.rb
db/schema.rb
spec/features/workflow/schedule_requirements_spec.rb
spec/features/workflow/schedule_spec.rb
spec/services/requirements/scheduled_datetime_checker_spec.rb

For https://trello.com/c/4Ycdjj3C/640-allow-users-to-set-a-future-date-and-time-for-content-to-be-published
This PR enables users to set a scheduled date and time for content to be published.  A default time appears in the form and users can set and update their chosen scheduled date and time.  The input users choose is validated using the ScheduledDateTimeChecker service and errors are displayed in the event a user inputs invalid data.  
This PR does not handle the process of scheduling itself, which will be covered in a subsequent card.
The current usage of input fields for the date is a temporary measure.  There is a card in the backlog that will look at creating a date input component to replace these.  It is also expected that the time selection dropdown will eventually be replaced …

Set scheduling date and time

---

app/views/layouts/application.html.erb

Error/flash messages are meant to sit within the main container, for layout consistency and accessibility reasons. This PR is dependent on having a consistent spacing for all error/alert components: https://github.com/alphagov/govuk_publishing_components/pull/765

Move flash messages in main container

---

app/assets/javascripts/components/autocomplete.js
app/assets/javascripts/components/contextual-guidance.js
app/assets/javascripts/components/image-cropper.js
app/assets/javascripts/components/input-length-suggester.js
app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/components/modal-dialogue.js
app/assets/javascripts/components/multi-section-viewer.js
app/assets/javascripts/components/url-preview.js
app/views/components/_contextual_guidance.html.erb
app/views/contacts/search.html.erb
spec/javascripts/components/contextual-guidance-spec.js
spec/javascripts/components/input-length-suggester-spec.js
spec/javascripts/components/markdown-editor-spec.js
spec/javascripts/components/modal-dialogue-spec.js
spec/javascripts/components/multi-section-viewer-spec.js
spec/javascripts/components/url-preview-spec.js

https://trello.com/c/5qBQd1ko/654-allow-users-to-crop-inline-images-in-the-context-of-a-modal
Please see the commits for more detail about how some of the components have changed. In general, the current JS for our local components has been written to look like this:
```
function MyComponent($module) {
// init stuff
}
MyComponent.prototype.myfunction = function ...
var components = document.querySelectorAll('[data-module="my-component"]')
components.forEach(function (component) {
new MyComponent(component).init()
}
```
The above is neither consistent with govuk-frontend or govuk_publishing_components, and also means that this JS can only run when the page loads, which is incompatible with the dynamic content we load into a modal (e.g. the images index page). This rewrites our local …

Modular components

---

app/assets/javascripts/application.js
app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/components/multi-section-viewer.js
app/assets/javascripts/modules/inline-image-modal.js
app/assets/javascripts/vendor/@alphagov/markdown-toolbar-element/index.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_loading-spinner.scss
app/controllers/application_controller.rb
app/controllers/images_controller.rb
app/views/components/_loading_spinner.html.erb
app/views/components/_markdown_editor.html.erb
app/views/components/docs/loading_spinner.yml
app/views/images/_image.html.erb
app/views/images/_lead_image.html.erb
app/views/images/index.html.erb
app/views/layouts/_modal_error.html.erb
app/views/layouts/application.html.erb
app/views/layouts/modal.html.erb
config/locales/en/application.yml
spec/features/editing_content/insert_inline_image_spec.rb
spec/javascripts/components/multi-section-viewer-spec.js

This adds a 'glue' module to operate a modal for the purpose of inserting inline images. Please see the commits for further details.

Inline image modal

---

app/assets/javascripts/application.js
app/assets/javascripts/components/toolbar-dropdown.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_toolbar-dropdown.scss
app/views/components/_markdown_editor.html.erb
app/views/components/_toolbar_dropdown.html.erb
app/views/components/docs/toolbar_dropdown.yml
spec/features/editing_content/insert_contact_publishing_api_down_spec.rb
spec/features/editing_content/insert_contact_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/javascripts/components/dropdown-spec.js

This PR adds a [toolbar dropdown component](https://content-publisher-revie-pr-803.herokuapp.com/component-guide/toolbar_dropdown) ✨ to be used within the markdown toolbar to group "insert" action buttons (such as images and contacts).
This component does not require JavaScript to be toggled, so the actions will be accessible in a no-js experience.
This implementation is purely functional. Have had a chat with @soniaturcotte and we'll iterate the style of this component.
Another PR will follow this one to use the component in the markdown toolbar to launch a modal dialogue for each of these two "insert" actions.
[Trello card](https://trello.com/c/Wf0A8zsq)

Add toolbar dropdown component

---

app/assets/stylesheets/components/_loading-spinner.scss
app/views/components/_loading_spinner.html.erb
app/views/components/docs/loading_spinner.yml

This PR adds a [loading spinner component](https://content-publisher-revie-pr-807.herokuapp.com/component-guide/loading_spinner) ✨ which displays an animated graphic to indicate loading activity. In our application it will be used when transitioning from one section to another within the 'multi section viewer' component. It relies on SVG and CSS animation.
GPU Memory Usage - Google Chrome v 72
[Trello card](https://trello.com/c/qouF8txw)

Add loading spinner component

---

app/assets/javascripts/modules/inline-image-modal.js
app/controllers/images_controller.rb
app/views/images/index.html.erb
app/views/layouts/modal.html.erb
spec/features/editing_images/upload_image_modal_requirements_spec.rb
spec/features/editing_images/upload_image_modal_spec.rb
spec/features/editing_images/upload_image_spec.rb

https://trello.com/c/QDEuNPgp/653-allow-users-to-upload-an-inline-image-in-the-context-of-a-modal
This exposes the upload form in the modal context of the images index
page, and overrides the 'Upload' button to post the form data i.e. upload
the image. Depending on the form data, we may need to render the
response HTML to display requirements issues, or follow a redirect.
The API of the FormData class means we can support posting a form
generically, which is handled using a new 'postModalForm' function in
the existing 'glue' module called 'inline-image-modal'. We also follow
any redirects automatically, to avoid unnecessary boilerplate '.fetch's.
In future work we will implement the rest of the upload workflow, so
that the modal loads the crop page after the image is uploaded.

Support upload and display of new images

---

app/views/images/_image.html.erb
spec/features/editing_images/download_image_spec.rb

https://trello.com/c/w4aI961C/440-provide-a-960x640-download-link-for-images
Previously we showed the download link for all images, but we expect
this is only needed for the lead image. This removes the download link
for non-lead images, which has the added benefit of reduces the number
of actions from the still-crowded list.

Remove download link for non-lead images

---

app/assets/javascripts/modules/inline-image-modal.js
app/views/images/index.html.erb

https://trello.com/c/QDEuNPgp/653-allow-users-to-upload-an-inline-image-in-the-context-of-a-modal
Previously we moved some of the override behaviour of the inline image
modal to apply to the 'submit' form, instead of the 'click' event of
the submit button of the form.  However, the 'click' event was still
being handled on the form, which was interfering with its other inputs.
This separates the events we override for modal content: 'submit' for
forms and 'click' for links. It also removes the (now) redundant data
attribute to specify the ID of the form element, as this is now the same
as the action item (element) being performed.

Fix accidental submit when choosing images

---

app/assets/javascripts/modules/inline-image-modal.js
app/views/images/_image.html.erb
app/views/layouts/modal.html.erb
spec/features/editing_images/delete_image_spec.rb

https://trello.com/c/MkWywL4g/590-support-inline-images
There's no specific card for this, but it seems to be part of the design 
and it only took 20 minutes :-).
This adds a delete action for all non-lead images in the inline-images
modal. As we only show the lead image for context, this action is not
supported for it. One slight surprise was that we actually do a POST
request for deletions, using a hidden parameter to override the method.

Support deletion of images in a modal context

---

spec/services/requirements/scheduled_datetime_checker_spec.rb

We discovered some flakiness in the setup of Scheduled Datetime Checker tests
that were attempting to change a Time to be in the past by subtracting 2.
Unfortunately this actually subtracted 2 from the 'Day' value of Time, so in
instances where it was the 2nd of the month the day would be set to 0 which is
invalid. This introduces a more robust way of setting the Time to be in the
past.

Fix flaky Scheduled Datetime Checker tests

---

app/controllers/schedule_controller.rb
app/models/edition.rb
app/models/scheduling.rb
app/models/status.rb
app/models/timeline_entry.rb
app/services/schedule_service.rb
app/views/documents/show/_actions.html.erb
app/views/schedule/confirmation.html.erb
app/views/schedule/scheduled.html.erb
config/locales/en/documents/history.yml
config/locales/en/schedule/confirmation.yml
config/locales/en/schedule/scheduled.yml
config/locales/en/states.yml
config/routes.rb
db/migrate/20190225133030_create_scheduling.rb
db/schema.rb
spec/factories/edition_factory.rb
spec/factories/revision_factory.rb
spec/features/workflow/schedule_set_datetime_passes_spec.rb
spec/features/workflow/schedule_set_datetime_too_close_to_now_spec.rb
spec/features/workflow/schedule_spec.rb
spec/features/workflow/scheduled_publishing_datetime_requirements_spec.rb
spec/features/workflow/set_scheduled_publishing_datetime_spec.rb
spec/services/schedule_service_spec.rb

For https://trello.com/c/t0mha6An/649-schedule-content-for-publication
This PR allows users to set content to a `scheduled` state in the application.  Enabling scheduled publishing functionality via the Publishing API will be tackled in a separate PR.
Content must be in an editable state in order to be scheduled; it cannot be in a live state.  It must also have a `scheduled_publishing_datetime` set.  There is some existing validation for `scheduled_publishing_datetime`, and this PR introduces a check that this value is not in the past or too close to now when the user goes to schedule the content for publication.  There isn't a clear decision on how to handle this check failing, so for now failure will result in the "Schedule" button not displaying.  However in edge cases where users may …

Users can set content to scheduled

---

app/views/documents/show/_actions.html.erb

When a new edition is created then the schedule publishing form appears above
the "View published edition" link.
**Before**
**After**

Reorder schedule publishing form when new edition

---

app/views/images/crop.html.erb

This is no longer required by the inline-image module.

Remove redundant data attribute from crop page

---

app/assets/javascripts/components/markdown-editor.js
app/controllers/govspeak_preview_controller.rb
app/views/components/_markdown_editor.html.erb

Trello: https://trello.com/c/VDgVNurM/544-extract-govspeak-javascript-functionality-to-govukpublishingcomponents
This allows for the govspeak component to be initialised each time we
preview govspeak and therefore show videos and barcharts.
Previously this did not work as we were changing HTML inside the
component. This component then ignored any calls to initialise as it was
already initialised.
This won't work properly until https://github.com/alphagov/govuk_publishing_components/pull/775 is released and used by this app.

Return govspeak in component in GovspeakPreviewController

---

app/assets/stylesheets/components/_input-length-suggester.scss

Because we're injecting this element inside the textarea component, the margin-bottom is being applied after the message instead of before the 'input length suggester' component. This adds margin to the injected element.

Fix input length suggester spacing

---

app/assets/javascripts/components/autocomplete.js
app/views/components/_autocomplete.html.erb
app/views/contacts/search.html.erb
app/views/tags/edit.html.erb
app/views/tags/tags/_multi_tag_input.html.erb
app/views/tags/tags/_single_tag_input.html.erb

Previously we had a flag that would change the autocomplete to add hint
text to each entry. The hinted variant is only used for contacts, and
was broken due to a misplaced data attribute.
This merges the hinted variant with the normal non-hinted autocomplete,
which fixes the issue with contacts and removes some duplicated code,
noting that the hinted variant also supports not using a hint.
This also removes support for contextual guidance, since this is not
currently being used with the autocomplete, and in any case was only
implemented for the non-hinted variant.

Merge autocomplete and its hinted variant

---

app/assets/stylesheets/components/_loading-spinner.scss

This is just a quick fix so that the modal height doesn't collapse too
much in between rendering different sections.

Add a bit of vertical padding for the spinner

---

app/models/edition.rb
spec/models/edition_spec.rb

This ensures that an old `scheduled_publishing_datetime` belonging to an old
edition isn't carried over to a new edition.

Clear scheduled_publishing_datetime when new edition

---

app/assets/stylesheets/core/_link.scss

Add consistent padding for inline links and remove outline on focus to fit the height of the button.

Fix hover state for inline links

---

app/controllers/schedule_controller.rb
app/models/timeline_entry.rb
app/views/documents/show/_scheduling_form.html.erb
config/locales/en/documents/history.yml
config/routes.rb
spec/features/workflow/clear_scheduled_publishing_datetime_spec.rb
spec/features/workflow/set_scheduled_publishing_datetime_spec.rb

For https://trello.com/c/UJa3cgqL/678-users-can-clear-scheduled-publishing-datetime
This allows users to clear a set `scheduled_publishing_datetime`.  We also create a Timeline entry when `scheduled_publishing_datetime` is set or cleared.

Clear scheduled publishing datetime

---

app/views/components/_markdown_guidance.html.erb
app/views/documents/show/_scheduling_form.html.erb

This fixes instances of details component after #811 introduced the default spacing.
Tries to deal with excessive padding and markup on the scheduling details element.
@emmabeynon: will rebase after #826

Fix details components

---

app/assets/javascripts/modules/inline-image-modal.js

Previously we were trying to re-initialise all components in the app,
even though we only need to attempt this for the modal content.

Make re-initialisation for modal more efficient

---

app/views/images/edit.html.erb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_images/upload_image_spec.rb

https://trello.com/c/jsJLqcSa/667-allow-users-to-edit-image-metadata-in-the-context-of-a-modal
This adds the missing behaviour and test, which seems to have been
accidentally removed from the original branch for the metadata page.

Fix inserting inline image snippet after upload

---

app/assets/javascripts/components/autocomplete.js
app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/contacts/search.html.erb
app/views/tags/edit.html.erb

This reverts commit bb8ece15ec7aab1862de6e470cad71b9faf4b991.
I've learnt my lesson and will avoid making 'simple' changes to the 
autocomplete in future. We can still remove the redundant contextual 
guidance for the autocomplete, as well as making the type switch a 
first-class attribute of the component, as opposed to a data attribute.

Revert "Merge autocomplete and its hinted variant"

---

app/controllers/schedule_controller.rb
app/views/documents/show/_scheduling_form.html.erb
config/locales/en/requirements.yml

This moves the scheduled publishing datetime form errors to be displayed in the error summary on top of the document show page.  We also add a href so that errors link to the form, and ensure the form stays open in the event of invalid data being submitted.
**Before**
**After**

Display scheduled publishing date time errors in error summary

---

app/assets/javascripts/modal/modal-fetch.js
app/assets/javascripts/modules/inline-image-modal.js
app/views/layouts/application.html.erb

https://trello.com/c/jsJLqcSa/667-allow-users-to-edit-image-metadata-in-the-context-of-a-modal
It didn't take long to track down the pain-points when debugging with 
the modal, but I'm happy to break this out into another card if we feel 
it deserves some more thorough attention.
This adds a 'console.error' to ensure we don't swallow errors that we
don't hide errors caused by things like syntax issues with JavaScript.
I've also added a couple of 'console.debug' statements to help inspect
server errors when they occur - these won't be shown in production.

Improve quality of errors when debugging

---

config/locales/en/images/index.yml

https://trello.com/c/MkWywL4g/590-support-inline-images
This helps ensure the user doesn't break out of the inline image modal
accidentally, but this is equally applicable for the lead image page.

Open image guidance in a new tab

---

config/locales/en/images/crop.yml

This is incorrect now that this title is used in both lead and non-lead contexts.

Remove lead image reference

---

package.json
spec/javascripts/components/input-length-suggester-spec.js
spec/javascripts/components/markdown-editor-spec.js
spec/javascripts/components/modal-dialogue-spec.js
spec/javascripts/components/multi-section-viewer-spec.js
spec/javascripts/components/url-preview-spec.js
spec/javascripts/modules/gtm-copy-paste-listener-spec.js
spec/javascripts/modules/gtm-form-listener-spec.js

These weren't being linted previously. I reduced the linting scope to be .js files as it was catching yaml files for the test configuration.

Lint JavaScript test files

---

app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/vendor/@alphagov/markdown-toolbar-element/dist/index.umd.js

This uses the file from
https://github.com/alphagov/markdown-toolbar-element/blob/75b162c93120254fb7a081940ff4afa1e49342e8/dist/index.umd.js
I updated the path to match the vendor style used for
accessible-autocomplete since these were two distinct approaches and I
settled on one.

Update the vendored version of markdown-toolbar-element

---

app/assets/javascripts/components/markdown-editor.js
app/assets/javascripts/modules/inline-image-modal.js

This resurrects https://github.com/alphagov/content-publisher/pull/838
since we've now had this issue caught by other people and it's about to
become invalid markdown to have image within a paragraph from govspeak
5.9.1 (https://github.com/alphagov/govspeak/pull/142).
/cc @benthorner

Support a surroundWithNewLines option when inserting text

---

Gemfile
Gemfile.lock
app/assets/javascripts/modal/modal-fetch.js
app/assets/javascripts/modules/inline-image-modal.js
app/controllers/documents_controller.rb
app/controllers/images_controller.rb
app/controllers/withdraw_controller.rb
spec/spec_helper.rb

We have an issue in IE11 (and any other browsers that need a fetch polyfill) where uploading and inserting an image does not work because we rely on a property (response.redirected) which is not supported by the fetch polyfill.
We also have a minor issue where we return a status code to users of a 200 when they need to fix issues they posted on a form. It's more semantic to the HTTP spec to return a [status of 422](https://httpstatusdogs.com/422-unprocessable-entity).
I've combined these two things to work around the problem. I've removed the flag we have in our JS of `done` for when we've redirected, and instead added a flag of `unprocessableEntity` for when there are issues. This can then be switched around in the conditionals.
Annoyingly I hit a problem with …

Fix IE11 image insert issues / return 422 on forms with issues

---

app/views/images/crop.html.erb
app/views/images/edit.html.erb
app/views/images/index.html.erb
config/locales/en/images/crop.yml
config/locales/en/images/edit.yml
config/locales/en/images/index.yml

Trello: https://trello.com/c/MkWywL4g/590-support-inline-images
This is DNM as it is pending chats between @benhazell and @soniaturcotte.
This implements some of the changes @benhazell raised in the linked trello card for copy changes - the other changes suggested looked to require further discussion. Though to do these consistently I had to refer back to designs for some copy where there were gaps in Ben's suggestions.
Things that have changed:
Before:
After:
Before: 
After:
Before:
After:
Before:
After:

Image copy changes

---

app/workers/scheduled_publishing_worker.rb
spec/factories/edition_factory.rb
spec/factories/scheduling_factory.rb
spec/factories/status_factory.rb
spec/spec_helper.rb
spec/workers/scheduled_publishing_worker_spec.rb

For https://trello.com/c/rXTLvzSu/685-scheduling-is-sent-to-the-publishing-api
This PR creates a Scheduled Publishing worker using Sidekiq.

Add Scheduled Publishing worker

---

app/services/govspeak_document.rb
app/views/debug/index.html.erb

It turns out that govspeak doesn't do any sanitising of user input. This resolves this by using the `to_sanitize_html` method when rendering govspeak of user input. We can't actually use this same method for all of our govspeak rendering of markdown files, as these uses `<a target />` which isn't allowed by the Govspeak::HtmlSanitizer.
It turns out there is a [`valid?`](https://github.com/alphagov/govspeak/blob/34b2cd789b51ab9ce11cee5a0e8bfe3fac274da4/lib/govspeak.rb#L89) method in Govspeak which other publishing apps use ([1](https://github.com/alphagov/whitehall/blob/a94e27e0869ee086dae8278abaa0a5e96a7b306a/app/validators/safe_html_validator.rb), [2](https://github.com/alphagov/specialist-publisher/blob/e2782bcfb518ac497e978e48320e556675c4940a/app/validators/safe_html_validator.rb)) to …

Sanitise govspeak and debug output

---

app/controllers/unschedule_controller.rb
app/models/timeline_entry.rb
app/views/documents/show/_actions.html.erb
config/locales/en/documents/history.yml
config/routes.rb
spec/features/workflow/unschedule_spec.rb

Users can cancel their scheduled content so Content Publisher no longer sets its state to `scheduled`.  Content reverts back to its pre-scheduling status, factoring in whether it was flagged has having been reviewed or not when it was scheduled.
https://trello.com/c/iwxNCu9n/692-allow-users-to-revert-scheduled-status

Stop scheduling feature

---

app/workers/scheduled_publishing_worker.rb
config/initializers/sidekiq.rb
lib/sidekiq_abort_middleware.rb
spec/lib/sidekiq_abort_middleware_spec.rb
spec/workers/scheduled_publishing_worker_spec.rb

Trello: https://trello.com/c/rXTLvzSu/685-scheduling-is-sent-to-the-publishing-api
Paired with @emmabeynon on this
This sets up a middleware for sidekiq to provide the means to abort from
a worker and have this not cause any automatic retries.
The reasons for adding this are:
- To allow means to explicitly abort a worker from any point in a
worker, as opposed to only a return call in the perform method;
- To be able to provide direct feedback on worker aborting in test and
console scenarios.
Adding this is pretty simple but does mean some annoying decisions about
where to place code. The middleware itself seemed to belong in a lib
directory I went for /lib rather than creating /app/lib since that does
not exist in this app.
The exception also needs a place to live too, I decided against …

 Create abort middleware for Sidekiq

---

app/assets/javascripts/components/toolbar-dropdown.js
app/assets/javascripts/modal/modal-fetch.js
app/assets/stylesheets/components/_toolbar-dropdown.scss
app/views/components/_markdown_editor.html.erb
app/views/components/_toolbar_dropdown.html.erb
app/views/components/docs/toolbar_dropdown.yml

https://trello.com/c/RxrZShDD/694-open-a-new-tab-when-inserting-inline-images-without-javascript
This changes the toolbar-dropdown component to work with links by
default, so that we can use a target attribute to open a new tab for
inserting images for users without JS. Moving the button-specific
options into a namespace should make them easy to remove, as the need
for them is coupled to the current way we insert contacts.
Note that the toolbar-dropdown component doesn't work in Safari, in case you end up testing this in that browser :-).

No js insert image new tab

---

app/controllers/images_controller.rb
app/controllers/tags_controller.rb
app/services/versioning/base_updater.rb
app/services/versioning/image_revision_updater.rb
app/services/versioning/revision_updater.rb
app/services/versioning/revision_updater/image.rb
app/services/versioning/sub_revision_updater.rb
spec/services/versioning/image_revision_updater_spec.rb
spec/services/versioning/revision_updater/image_spec.rb
spec/services/versioning/revision_updater_spec.rb

https://trello.com/c/pAjSCymq/746-its-hard-to-follow-how-we-build-a-revision-and-to-see-whats-changed
To some extent I think I've tried to avoid making the ImagesController 
even longer, but this may have made it less readable and some more 
question methods somewhere might be beneficial. I've outlined an 
idea for doing this below, but I worry that it's just disguising a bunch of 
single-use code through a convenient interface...
Previously we used a tree of 'build_revision_update' methods on each
model, which has lead to some duplication between models and quite a lot
of extra code in the model classes. This makes a start at extracting
this logic into a set of 'updater' classes with some helper methods.
The updaters take a hash of 'fields', which can include columns,
collections and …

Begin replacing model build methods with updaters

---

config/application.rb
lib/notify_delivery_method.rb
lib/tasks/notify.rake
spec/lib/notify_delivery_method_spec.rb
spec/tasks/notify_rake_spec.rb

https://trello.com/c/NUdRomQV/714-set-up-content-publisher-to-use-notify
Following convention of accessing delivery method config via Action Mailer settings, we add Notify template id to Notify settings. This removes the need for us to include a template id in the Mail object and pass a template id env to the `notify:send_email` rake task.

Add template_id to Notify settings

---

app/controllers/schedule_controller.rb
app/services/publishing_api_payload.rb
app/services/schedule_service.rb
config/locales/en/documents/show.yml
spec/features/workflow/schedule_publishing_api_down_spec.rb
spec/features/workflow/schedule_spec.rb
spec/services/schedule_service_spec.rb
spec/spec_helper.rb

When a user schedules content to be published, we need to create a
publish intent in the Publishing API so that Content Store will run down
the TTL and the document's cache will expire as the new content is
published.
Trello:
https://trello.com/c/fXtvPpIO/696-create-publish-intent

Create publish intent request

---

app/assets/javascripts/components/toolbar-dropdown.js

This PR updates the toolbar dropdown component to make sure the target is correctly being picked up regardless of the browser so the actions within the component are available to all users.
Test URL: https://content-publisher-revie-pr-897.herokuapp.com/documents/80c5f480-c149-4408-97f2-07e624148741:en/edit
[Trello card](https://trello.com/c/7GyG0o6N)

Address target for each individual event model

---

app/models/edition.rb
app/services/delete_draft_service.rb
spec/features/workflow/delete_draft_asset_manager_down_spec.rb
spec/features/workflow/delete_draft_publishing_api_down_spec.rb
spec/features/workflow/delete_draft_spec.rb
spec/services/delete_draft_service_spec.rb

https://trello.com/c/6s9Bhzyj/632-delete-publishing-api-path-reservations-when-we-discard-drafts
Previously we only discarded the content when deleting a draft, which
leaves the original path reservations in the Publishing API. This
creates a problem if users begin creating their document in Content
Publisher, but need to start again in Whitehall.
This adds an association to the Edition model to retrieve all its
Revisions, which enables the DeleteDraftService to find and unreserve
all the associated base paths, so they can be used in other apps.
I've also refactored the DeleteDraftService to keep the top-level method
short and at a single level of abstraction.

Unreserve paths when discarding a first edition

---

config/initializers/mail_recipient_interceptor.rb
config/secrets.yml
lib/mail_recipient_interceptor.rb
lib/notify_delivery_method.rb
spec/lib/mail_recipient_interceptor_spec.rb
spec/lib/notify_delivery_method_spec.rb

For https://trello.com/c/eNpUY7Ek/744-add-email-intercept
We don't want users to receive notifications in integration and staging
environments as they could get confused with production notifications. While
Notify allows us to specify certain email addresses to only receive
notifications in integration and staging, if a notification is sent to a
non-allowed email address (for example in future when publishers receive
notifications that their content has been published) then Notify will return a
`BadRequestError` which is not ideal.
To avoid this, we create a Mail Recipient Interceptor to intercept emails that
are sent in integration and staging and route them to a team email address
instead of the original intended recipient.  We prefix the intended recipient to the
body of the email so …

Add Mail Recipient Interceptor

---

config/application.rb
config/initializers/mail_recipient_interceptor.rb
config/initializers/mailer.rb
config/secrets.yml

https://trello.com/c/CJSGxDmN/717-notify-editors-when-content-has-been-published
This fixes the NotifyDeliveryMethod to pass the settings to the
constructor, as well as adding a missing 'require' statement on the
MailRecipientInterceptor when it's added by the initializer.

Fix Notify delivery method and interceptor

---

app/controllers/images_controller.rb

https://trello.com/c/wrIdevce/738-audit-the-way-we-rescue-gdsapi-errors-and-identify-pain-points
This is no longer required because the PreviewService doesn't throw any
errors when using #try_create_preview.

Remove redundant rescue_from in ImagesController

---

app/assets/stylesheets/objects/_side.scss
app/views/documents/show/_scheduling_form.html.erb

- Replace the multiple inputs for inserting date with the date-input component
- Adjust whitespacing in the details element within the side area to fit the default date-input fields in one line
[Trello card](https://trello.com/c/0ZphzvRd)

Use date-input component for scheduling date

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/core/_typography.scss

Font loading is by default disabled since govuk-frontend v.2.9.0 https://github.com/alphagov/govuk-frontend/releases/tag/v2.9.0 for projects that are [set to be compatible with govuk-template](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/components/helpers/_govuk-frontend-settings.scss#L3) as it's the case with govuk_publishing_component. The reason behind this change is to [ensure the font file is not required twice](https://github.com/alphagov/govuk_publishing_components/issues/597) for projects that rely on govuk_template. So, the font comes disabled from govuk_publishing_component and needs to be enabled in repos that don't rely govuk_template.

Add nta font

---

app/controllers/publish_controller.rb
app/controllers/schedule_controller.rb
app/views/publish/confirmation.html.erb
config/locales/en/publish/confirmation.yml
config/locales/en/schedule/confirmation.yml
spec/features/workflow/publish_asset_manager_down_spec.rb
spec/features/workflow/publish_publishing_api_down_spec.rb
spec/features/workflow/publish_review_status_not_selected_spec.rb
spec/features/workflow/schedule_review_status_not_selected_spec.rb
spec/features/workflow/schedule_spec.rb

Currently when a user clicks 'Publish' on the confirmation screen without selecting whether the document has been approved or not we default the document to 'published without review', this is a bad user experience. 
We should ensure that a user confirms a review status when publishing / scheduling a document.

Fix and improve radio buttons on confirmation

---

app/controllers/unwithdraw_controller.rb
app/controllers/withdraw_controller.rb
app/services/remove_service.rb
app/services/unwithdraw_service.rb
app/services/withdraw_service.rb

In a few places within the app we seem to use nested transactions which aren't actually necessary as long as the rescue block is put in the correct place.
Previously there was a nested transaction where the parent transaction didn't perform any database operations and had a confusing rollback procedure.
If we just removed the nested transaction and did nothing else then
this would not work as expected. The reason for this is that when a
GdsApi exception is thrown the exception would be rescued before the
transaction had a chance to roll back, meaning records could be
updated / created even if a GdsApi error is thrown.
The rescue is outside the only transaction, this means when a GdsApi exception
is thrown the transaction handles all the roll backs it needs to do,
uninterrupted. Then when …

Refactor and fix transactions

---

.rubocop.yml
app/services/requirements/scheduled_datetime_checker.rb
spec/services/requirements/scheduled_datetime_checker_spec.rb

https://ci.integration.publishing.service.gov.uk/job/content-publisher/job/use-active-job/5/console
Previously we did two rounds of parsing of the date and time when
setting the schedule for publishing a document, as follows:
parsed_date = Date.parse('2019-04-01')
=> '2019-04-01'
parsed_time = Time.parse('09:00am')
=> '2019-03-29 09:00:00 +0000'
DateTime.parse("#{parsed_date} #{parsed_time}").in_time_zone
DateTime.parse('2019-04-01 2019-03-29 09:00:00 +0000').in_time_zone
=> '2019-04-01 10:00:00 +01:00'
Double-parsing the time separately from the date caused us to inject a
UTC override '+0000' into what would otherwise have been a BST date.
This fixes the requirements checker to avoid double-parsing of the time.
In order to help avoid future timezone issues, this also adds a cop to …

Avoid DateTime and multiple parsing of Date/Time

---

app/assets/javascripts/modal/modal-workflow.js

https://trello.com/c/S9BlkYgz/794-support-govuk-frontend-components-in-the-context-of-a-modal
Previously we had to manually interact with the error-summary component,
which is part of govuk-frontend, in order to ensure it was focussed when
the modal displays an error. This replaces the manual code with a call
to re-init all govuk-frontend components on the modal element and its
children - previously this was only possible for the entire page, which
had a real risk of initialising components twice on other elements.
We should still use components with caution in the context of the modal,
as some are still coupled to the outer window e.g. the tabs component
modifies the page URL, which doesn't make sense within a modal.

Improve re-init for frontend components in modal

---

app/views/documents/index/_filters.html.erb

The "Clear all filters" is not being styled properly, hence it's displayed in a different size.

Fix clear all filters link

---

app/controllers/withdraw_controller.rb
app/services/govspeak_document.rb
app/services/requirements/content_checker.rb
app/services/requirements/withdrawal_checker.rb
config/locales/en/requirements.yml
spec/services/requirements/content_checker_spec.rb
spec/services/requirements/withdrawal_checker_spec.rb

Trello: https://trello.com/c/SdMUjUmj/722-resolve-xss-issues-raised-by-pen-testers
Marked as DNM until final content decisions.
This adds validation for the places where we accept govspeak input. It is used as a means to tell them that the content they have entered can't be accepted. Writing the validation message is rather grim as there are quite a few reasons the `Govspeak#valid?` method can fail. I felt the simplest way
to resolve this was just to tell users to "Remove HTML" - this hasn't been content designed though and may need revising if there are situations where users are actively advised to enter HTML.

Check govspeak is valid

---

app/controllers/images_controller.rb
app/views/components/_image_cropper.html.erb

This fixes the warning about unpermitted params, and the longstanding fixme.
It also switches to round a crop number rather than floor it. See commits for further details.

Image crop params

---

app/controllers/new_document_controller.rb
app/controllers/publish_controller.rb
app/controllers/schedule_controller.rb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
app/views/publish/confirmation.html.erb
app/views/schedule/confirmation.html.erb
config/locales/en/new_document/choose_document_type.yml
config/locales/en/new_document/choose_supertype.yml
config/locales/en/publish/confirmation.yml
config/locales/en/requirements.yml
config/locales/en/schedule/confirmation.yml
spec/features/workflow/create_document_format_not_selected_spec.rb
spec/features/workflow/publish_review_status_not_selected_spec.rb
spec/features/workflow/schedule_review_status_not_selected_spec.rb

https://trello.com/c/LhoqJDhC/733-revisit-the-radio-buttons-for-the-publish-confirmation-screen
Previously we only displayed an error summary when a radio selection was
not made for publishing, scheduling, or choosing a format, which is
inconsistent with the design system pattern for forms. This modifies the
argument we pass to the radio component to include any error items, for
which it made sense to use the normal requirements data structures, but
without the boilerplate of having an actual checker class.

Show error state on radio buttons if not selected

---

app/controllers/publish_controller.rb
app/jobs/email_delivery_job.rb
app/jobs/scheduled_publishing_job.rb
app/mailers/application_mailer.rb
app/mailers/publish_mailer.rb
app/models/edition.rb
app/services/publish_service.rb
app/views/documents/show/_contents.html.erb
app/views/publish_mailer/publish_email.text.erb
config/locales/en/publish_mailer/publish_email.yml
config/sidekiq.yml
db/seeds.rb
spec/factories/user_factory.rb
spec/features/workflow/publish_spec.rb
spec/features/workflow/publish_without_review_spec.rb
spec/features/workflow/schedule_spec.rb
spec/jobs/scheduled_publishing_job_spec.rb
spec/services/publish_service_spec.rb
spec/spec_helper.rb

https://trello.com/c/CJSGxDmN/717-notify-editors-when-content-has-been-published
This adds the ability to notify the editors of an edition by email when their document is published, with or without review. Editors are defined to be any user who has modified or change the state of an edition. Please see the commit for further details :-).

Publish notification 2

---

app/views/publish_mailer/publish_email.text.erb
lib/mail_recipient_interceptor.rb

https://trello.com/c/CJSGxDmN/717-notify-editors-when-content-has-been-published
GOV.UK Notify was also styling one of the lines strangely, which seems
to be related to the indentation from ERB. This removes all node
indentationt to make the output more predictable.

This fixes a missing newline after the update type

---

app/controllers/documents_controller.rb
spec/features/editing_content/edit_edition_requirements_spec.rb

We can't refer to edition.revision at this point as it isn't yet
persisted to edition.
I've updated the test to catch this scenario if it re-occurs.

Fix previous input lost on document edit

---

app/controllers/withdraw_controller.rb
app/views/withdraw/new.html.erb

Trello: https://trello.com/c/SdMUjUmj/722-resolve-xss-issues-raised-by-pen-testers
This form previously only showed issues as a flash message, this now includes them with the fields.
Screenshot:

Include errors with relevant field on withdraw form

---

app/assets/javascripts/components/markdown-editor.js
app/views/components/_markdown_editor.html.erb
app/views/components/docs/markdown_editor.yml
app/views/documents/edit.html.erb
app/views/documents/fields/_govspeak_input.html.erb

Trello: https://trello.com/c/SdMUjUmj/722-resolve-xss-issues-raised-by-pen-testers
This PR does a few things:
- It fixes problems that was causing the markdown to not render in component guide, this whole component is a bit dubious though. See commit for more info.
- Adds error_items support to the markdown component
- Wires errors into markdown component on edit document page
Screenshot:

Show markdown component errors on edit document page

---

app/assets/javascripts/application.js
app/assets/javascripts/modal/modal-fetch.js
app/assets/javascripts/modules/video-embed-modal.js
app/controllers/video_embed_controller.rb
app/services/requirements/video_embed_checker.rb
app/views/components/_markdown_editor.html.erb
app/views/images/edit.html.erb
app/views/images/index.html.erb
app/views/video_embed/new.html.erb
config/locales/en/requirements.yml
config/locales/en/video_embed/new.yml
config/routes.rb
spec/features/editing_content/insert_video_embed_requirements_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb
spec/services/requirements/video_embed_checker_spec.rb

https://trello.com/c/4kQa7EZO/762-allow-users-embed-videos
This adds an embed video workflow, which is only accessible in the context of a modal. Please see the commits for further info. Future things to look into:
- Reduce duplication of the render logic between the two modal modules
- Make the modal appear at two thirds with for this workflow

Video embed

---

app/views/components/_markdown_editor.html.erb
app/views/video_embed/new.html.erb

https://trello.com/c/4kQa7EZO/762-allow-users-embed-videos
It looks like we prefer to begin our GTM tags with a verb, so I've stuck
with that convention.

Add GTM tags when embedding a video

---

docs/adr/000x-sending-email-notifications.md

https://trello.com/c/xraOMbHg/757-write-an-adr-documenting-tech-product-decisions-around-notifications
This adds an ADR for sending notifications, which is coupled to the way
we handle background jobs, so it seems sensible to discuss them both in
the same document.

Add ADR for background jobs and notifications

---

app/services/linkables_service.rb

This is very much an attempt to quick fix the common support requests
we're receiving about timeout problems with the application.
This will give us up to 3 seconds before giving up on loading linkables
rather than 1. The most common linkable we see having this problem is
organisations which on April 10th seems to have hit up to 14 seconds 😬.
So doing this will only limit occurrences of this rather than removing
them all.
I chose 3 seconds as I believe this gives us enough time that in most
cases even with a timeout here we'll still return a response before
nginx gives up and returns a 504.

Up the linkables timeout to 3 seconds.

---

app/assets/javascripts/components/markdown-editor.js
app/views/components/_markdown_editor.html.erb
app/views/components/docs/markdown_editor.yml
app/views/documents/fields/_govspeak_input.html.erb
package.json
yarn.lock

For https://trello.com/c/3JX1Pc9f/770-embed-paste-html-to-govspeak-functionality
This embeds the [paste-html-to-govspeak](https://www.npmjs.com/package/paste-html-to-govspeak) npm package in the body field on the edit document page.  We put this behind a pre-release feature flag for now; note that when we set this as a data attribute on the text area component the boolean value comes through as a string, which is why we check if this is equal to 'true' before adding a paste event listener.

Add paste html to govspeak functionality

---

app/services/content_data_url.rb
app/views/documents/show/_actions.html.erb
spec/factories/edition_factory.rb
spec/features/content_data/content_data_link_spec.rb
spec/features/workflow/publish_spec.rb
spec/services/content_data_url_spec.rb

For https://trello.com/c/y1CtmFT9/763-link-from-our-app-to-content-data-page
This adds a link to the data page in the Content Data app for a particular piece of content.  The conditions under which we display a link are:
- The user must be part of an organisation that is a Content Data beta partner (otherwise they won't be able to access the page), AND
- Content was published before yesterday, OR
- Content was published yesterday AND it is after 9am (the Content Data ETL runs at 7am and finishes around 7.30am.  I've agreed with Sean in Data Informed Content that 9am gives enough buffer time in case the ETL is delayed).
As part of this PR we have also changed the 'View published content on GOV.UK' link text to 'View on GOV.UK'.  The link to Content Data appears below this, and in order to …

Link Content Data page

---

package.json
yarn.lock

This has improved word paste support.

Bump paste-html-to-govspeak to 0.2.1

---

package.json
yarn.lock

Trello: https://trello.com/c/7pL98HiY/780-investigate-chrome-address-bar-copy-and-paste-issue
This resolves an issue pasting from chrome address bar.

Bump paste-html-to-govspeak to 0.2.2

---

app/views/components/_contextual_guidance.html.erb
app/views/components/_formatted_text.html.erb
app/views/components/_image_cropper.html.erb
app/views/components/_multi_section_viewer.html.erb
app/views/components/_side_navigation.html.erb
app/views/components/_summary.html.erb
app/views/components/_toolbar_dropdown.html.erb
app/views/components/_warning_summary.html.erb
app/views/components/docs/url_preview.yml
spec/javascripts/components/contextual-guidance-spec.js
spec/javascripts/components/toolbar-dropdown-spec.js

This PR does the following in an attempt to code consistency:
- Update templates to only generate unique `id`s when mandatory and make use of rails view helpers to simplify the logic and preserve markup formatting
- Rename `dropdown-spec` to `toolbar-dropdown-spec` as it was missed when renaming the component
- Declare `eslint-env` consistently in spec files
- Fixed a wrongly formatted YAML line which is currently breaking the component-guide

Frontend cleanup

---

app/assets/stylesheets/utilities/_overwrites.scss

Remove margin overwrite on success-alert as [the component was updated to have a margin: 0 by default](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss#L15)
Remove govuk-template overwrite as [the modal dialogue component was updated to deal with this](alphagov/govuk_publishing_components#805).

Remove (now) unnecessary overwrites

---

app/models/edition.rb
app/models/file_attachment/file_revision.rb
app/models/file_attachment/revision.rb
app/models/image/revision.rb
spec/factories/file_attachment_factory.rb
spec/factories/file_attachment_file_revision_factory.rb
spec/factories/file_attachment_metadata_revision_factory.rb
spec/factories/file_attachment_revision_factory.rb

Trello: https://trello.com/c/3c6nomPo/782-mvp-of-inline-attachment-flow-add-and-insert
This fixes a few things Emma and I caught today while working on the MVP and adds in some factories. 
A few of the things here are cherry picked from the [create-form-to-upload-attachments](https://github.com/alphagov/content-publisher/tree/create-form-to-upload-attachment) branch

More File Attachment modelling

---

app/models/file_attachment/file_revision.rb
spec/factories/file_attachment_file_revision_factory.rb
spec/models/file_attachment/file_revision_spec.rb

Trello: https://trello.com/c/3c6nomPo/782-mvp-of-inline-attachment-flow-add-and-insert
This changes the approach to managing the assets associated with with a
FileAttachment::FileRevision. The collection approach makes sense for
images where we have a group of different sizes but less so for files
where we will mostly have a single file and occasionally a thumbnail.
Thus rather than having a group this has specific associations.
I was initially tempted to swap the association to be held by the
file_revision model with a link to the Asset, however this wouldn't have
worked because the Asset needs access to the FileRevision and it can't
determine this if it can be associated on different join points.
It's a bit unclear what the future of the ensure_assets method is as I
don't know how that …

Change the many assets association on FileAttachment::FileRevision

---

app/services/content_data_url.rb
spec/features/content_data/content_data_link_spec.rb
spec/services/content_data_url_spec.rb

The domain for the Content Data App, described in some places as
content-data-admin has changed. It's now
`content-data.publishing.service.gov.uk` rather than
`content-data-admin.publishing.service.gov.uk`.
Requests using the old domain name will be redirected to the new
domain, but to avoid that redirect, this commit updates the domain
that Content Publisher links to.

Update the domain for the Content Data app

---

app/assets/javascripts/components/autocomplete.js
app/assets/stylesheets/components/_autocomplete.scss
app/helpers/time_options_helper.rb
app/views/components/docs/autocomplete.yml
app/views/documents/show/_scheduling_form.html.erb
spec/features/workflow/clear_scheduled_publishing_datetime_spec.rb
spec/features/workflow/set_scheduled_publishing_datetime_spec.rb

This PR updates the autocomplete to support a custom configuration ([without-narrowing-results](https://content-publisher-revie-pr-957.herokuapp.com/component-guide/autocomplete/autocomplete_without_narrowing_results/preview)) in which essentially acts as a dropdown list which also allows custom input from users.
This custom configuration is used in [time select in the scheduling form](https://content-publisher-revie-pr-957.herokuapp.com/documents/d7e73a7d-17b2-4488-b41c-c6b3b5758dd3:en) as shown below.
[Trello card](https://trello.com/c/QrEdhtTO)

Use autocomplete as dropdown for time input

---

app/controllers/file_attachments_controller.rb
app/controllers/images_controller.rb
app/services/versioning/revision_updater/file_attachment.rb
app/services/versioning/revision_updater/image.rb
spec/services/versioning/revision_updater/file_attachment_spec.rb
spec/services/versioning/revision_updater/image_spec.rb

https://trello.com/c/pd6fOgwf/800-follow-up-steps-on-minimal-workflow-for-inline-attachments
Previously we used a single 'update' method to handle the addition of
new images and attachments, as well as the substitution of an existing
image or attachment with a new revision. While adding a new image or
attachment happens to be a special case of 'updating', the call to the
'update' method in the context of addition is confusing. This splits the
'add' aspect out of the 'update' method and adds a few pre-checks.

Split adding/updating images/attachments

---

Gemfile
Gemfile.lock

This updates to the latest version of govuk_test in order to take
advantage of the new env var to disable the now-deprecated
chromedriver-helper.

Bump govuk_test to 0.4.2

---

app/controllers/file_attachments_controller.rb
app/models/file_attachment/blob_revision.rb
app/models/file_attachment/revision.rb
app/services/file_attachment_upload_service.rb
app/views/components/_attachment_meta.html.erb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/index.html.erb
app/views/file_attachments/show.html.erb
config/locales/en/file_attachments/show.yml
config/routes.rb
db/migrate/20190430091427_remove_redundant_file_attachment_size.rb
db/schema.rb
spec/factories/file_attachment_blob_revision_factory.rb

https://trello.com/c/gf8wSm9P/825-build-page-for-inserting-inline-attachments-to-match-design
Previously we showed the markdown snippet for an attachment as part of
the list of attachments for an edition. This moves the snippet to a
separate page and makes use of the attachment_meta component to work
towards matching the design for both of these pages.

Show attachment snippet on separate page

---

app/models/edition.rb
app/models/file_attachment/asset.rb
app/models/revision.rb
app/services/delete_draft_service.rb
app/services/draft_asset_cleanup_service.rb
app/services/publish_asset_service.rb
app/services/publish_service.rb
app/services/remove_service.rb
db/migrate/20190426090323_add_superseded_by_to_file_attachment_assets.rb
db/schema.rb
spec/services/delete_draft_service_spec.rb
spec/services/draft_asset_cleanup_service_spec.rb
spec/services/publish_asset_service_spec.rb
spec/services/publish_service_spec.rb
spec/services/remove_service_spec.rb

Changes made in this PR:
* FileAttachmentAssets are published to asset manager when a document is published
* Deleted FileAttachmentAssets are only removed from asset manager when a document is published
* FileAttachmentAssets are removed from asset manager when a document is removed
* FileAttachmentAssets are removed from asset manager when a draft document is discarded
* Draft FileAttachmentAssets are cleaned up when they are removed from a draft document
The work for removing FileAttachmentAssets follows the same pattern that removing images already uses.
I've also created a new service to handle the publishing of assets as it made sense to separate the logic around the publishing of assets from the general publishing service. 
Trello: …

Publish and delete assets

---

app/interactors/file_attachments/create_interactor.rb
app/models/timeline_entry.rb
config/locales/en/documents/history.yml
spec/features/editing_file_attachments/upload_file_attachment_spec.rb

This adds a TimelineEntry to the documents history everytime a file
attachment is uploaded.
Trello:
https://trello.com/c/604eHfVR/833-create-timelineentry-when-uploading-a-file-attachment

Create a TimelineEntry when uploading a file attachment

---

app/assets/stylesheets/components/_attachment-meta.scss
app/helpers/application_helper.rb
app/helpers/file_attachment_helper.rb
app/models/file_attachment/blob_revision.rb
app/models/file_attachment/revision.rb
app/services/govspeak_document/in_app_options.rb
app/services/govspeak_document/payload_options.rb
app/views/components/_attachment_meta.html.erb
app/views/components/_metadata.html.erb
app/views/components/docs/attachment_meta.yml
app/views/components/docs/metadata.yml
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/show.html.erb
config/locales/en/file_attachments/index.yml
config/locales/en/file_attachments/show.yml
spec/factories/file_attachment_revision_factory.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/services/govspeak_document/in_app_options_spec.rb
spec/services/govspeak_document/payload_options_spec.rb

Trello: https://trello.com/c/zMYmFTPx/801-show-metadata-for-attachments
This is a draft as it waits for https://github.com/alphagov/govuk_publishing_components/pull/842 to be released.
This provides the rendering for attachments within the application and for govspeak.
A tricky part is that we have the same hash of attachment data that is used to render a component and is sent to govspeak. I tried to find a single place that could store that serialising logic. After initially going with a method on the model I tried out a Helper after a chat with Ben. I'm not quite sure where'd be best, there are disadvantages to all options.
See commits for more details

Render attachment

---

app/controllers/file_attachments_controller.rb
app/helpers/file_attachment_helper.rb
app/interactors/file_attachments/preview_interactor.rb
app/services/asset_manager_service.rb
app/services/govspeak_document/in_app_options.rb
app/services/preview_asset_service.rb
app/services/preview_service.rb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/preview_pending.html.erb
app/views/file_attachments/show.html.erb
config/locales/en/file_attachments/preview_pending.yml
config/routes.rb
spec/features/editing_file_attachments/preview_file_attachment_asset_manager_down_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_unavailable_spec.rb
spec/interactors/file_attachments/preview_interactor_spec.rb
spec/services/govspeak_document/in_app_options_spec.rb
spec/services/preview_asset_service_spec.rb
spec/services/preview_service_spec.rb

https://trello.com/c/xpS0zlU4/803-download-an-attachment-file-through-content-publisher
This is the initial attempt at doing 'intelligent preview' for an asset, so that we redirect to Asset Manager only when we know a file is available, and potentially try to upload it if it's not in Asset Manager at all e.g. if it was uploaded as part of the edit form for a document. Further work:
- Use the auth bypass token in the asset URL
- Use the new preview path elsewhere in the app
- Consider if we want special behaviour for infected files
I've done a bit of refactoring on the PreviewService, which had similar code for managing assets, to keep the tests manageable. The commit explains a bit more about the pros/cons of doing that - it seems to be a compromise between duplication and stubbing our …

Download attachments

---

Gemfile
Gemfile.lock

https://trello.com/c/EL9jPXIl/802-validation-requirements-for-uploading-file-attachments
Previously we were unknowingly relying on this depedency to be provided
by a gem that was only installed in the dev/test environments. This adds
the gem explicitly to ensure it's available in the prod environment.

Add missing rubyzip gem in production

---

Gemfile

This is necessary because the name of the library differs from the
naming used in its code, so it isn't auto-required.

Require 'zip' instead of 'rubyzip'

---

app/assets/stylesheets/components/_autocomplete.scss

While typing in an autocomplete the suggestion text is misaligned with the typed text.
Before: 
After:

Fix misaligned text in autocomplete

---

app/views/documents/edit.html.erb

We initially set `autocomplete="false"` on the edit document form trying to disable suggestions on input elements (such as Title and Summary), but we've found that this behaviour is also disabling the browser from retaining edited inputs when offline resulting in potential loss of content. We're also no longer using input elements for these fields (Title and Summary) so the initial purpose is not being met anymore.
Edit the main textarea within the markdown editor > Disable WiFi > Submit your changes > The submit will fail > Press the back button to return to the edit page > The updated content is missing.
The scenario above could be achieved by any failed submissions of the edit document form.

Enable autocomplete on edit document form

---

app/assets/stylesheets/components/_attachment-meta.scss
app/views/file_attachments/index.html.erb
app/views/file_attachments/show.html.erb
app/views/images/index.html.erb

Fix visual styles on attachments. This includes:
- Update image upload page to have the guidance as hint
- Update attachment form markup
- Fix hr styling an fix `</p>` when showing attachments
- Fix style attachment meta for group listing
Trello:
https://trello.com/c/zMYmFTPx

Align image and file upload

---

app/views/documents/edit.html.erb

Looks like form_for is hairier than I gave it credit for :-|.

Fix missing class for edit page guidance

---

app/interactors/file_attachments/preview_interactor.rb
spec/features/editing_file_attachments/preview_file_attachment_unavailable_spec.rb
spec/interactors/file_attachments/preview_interactor_spec.rb

https://trello.com/c/xpS0zlU4/803-download-an-attachment-file-through-content-publisher
Previously we did a 'context.fail' when initially uploading an asset for
preview, which caused the wrapping transaction to rollback and the
created asset to be removed, even though it exists in Asset Manager.
This modifies the PreviewInteractor to combine and rename the associated
'check_' methods to better describe what they achieve, which also means
we can short-circuit return and avoid any erreneous rollback.

Fix rollback when creating assets for preview

---

app/services/content_data_url.rb
app/views/documents/show/_actions.html.erb
app/views/publisher_information/how_to_use_publisher.govspeak.md
app/views/publisher_information/publisher_updates.govspeak.md
spec/services/content_data_url_spec.rb

We should now display a link for every document which points to its content-data page regardless
of a users organisation now content-data is in public beta.
Depends on: (updating 'whats new' section)
https://github.com/alphagov/content-publisher/pull/1037
Trello:
https://trello.com/c/MdKhnoLP/847-link-from-our-app-to-content-data-all-organisations
https://trello.com/c/rX051n9o/837-update-guidance-for-users-expecting-whitehall-publisher
https://trello.com/c/6CurP3Iz/860-change-note-for-recent-fixes

Allow all orgs to access content-data link

---

spec/features/editing_images/edit_image_metadata_requirements_spec.rb

This adds a selector check to make Capybara wait before trying to edit
metadata for an inline image, where the page may not have finished
loading asynchronously.

Fix image spec not passing on CI

---

app/assets/javascripts/modal/modal-fetch.js

Trello: https://trello.com/c/gPfQ2lBT/819-interface-with-a-documents-attachments-via-a-modal
I had a quick go at seeing if there was a simple way I could stop the risk of timeouts when uploading files since we can't reasonably guess whether the time spent is waiting on the client side or server side.
This was the least invasive/complex way I could think of. May be too simple, comments/suggestions welcome.

Don't timeout for modal forms that upload files

---

config/locales/en/documents/history.yml
config/locales/en/images/index.yml
spec/spec_helper.rb
spec/support/i18n_cov.rb

https://trello.com/c/s122Fg91/959-we-dont-monitor-unused-and-untested-i18n-translations
This adds a GOVUKI18nCov class* that generates a coverage report of the
I18n keys used after a script (e.g. rspec) has finished running. I've
removed a couple of unused locales that the report has identified as
being unused - the remainder are used but not covered by the tests.
I'm not really sure where this code should live, but it does seem to be 
beneficial to monitor coverage of our locales :-).
*there are other tools out there, such as i18n-tasks, but I couldn't find one 
that produces a good quality results for our use case - we have a lot of 
dynamic uses of I18n in our code, as well as simple uses in the views.

Add coverage checker for I18n locales

---

app/helpers/file_attachment_helper.rb
app/models/edition.rb
app/models/revision.rb
app/models/tags_revision.rb
app/services/govspeak_document/in_app_options.rb
app/services/govspeak_document/payload_options.rb
app/services/organisation_service.rb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/show.html.erb
spec/services/govspeak_document/in_app_options_spec.rb
spec/services/govspeak_document/payload_options_spec.rb
spec/services/organisation_service_spec.rb

https://trello.com/c/OcuVomSb/820-show-the-alternative-format-email-address-for-an-attachment
This makes use of the [upcoming component change](https://github.com/alphagov/govuk_publishing_components/pull/858) to render alternative format contact emails for attachments. More detail in the commits...

Attachment alt email

---

app/views/components/docs/url_preview.yml

This criteria wasn't meant to be a shared one, so the component guide is currently failing to render the preview page as it's expecting for `shared_accessibility_criteria` to be iterable.

Fix yml for url_preview component

---

app/assets/stylesheets/utilities/_overwrites.scss
app/controllers/file_attachments_controller.rb
app/interactors/file_attachments/update_interactor.rb
app/services/file_attachment_blob_service.rb
app/services/file_attachment_upload_service.rb
app/services/requirements/file_attachment_checker.rb
app/views/file_attachments/edit.html.erb
config/locales/en/file_attachments/edit.yml
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/fixtures/files/replacement-text-file.txt
spec/services/file_attachment_blob_service_spec.rb
spec/services/versioning/file_attachment_revision_updater_spec.rb

For https://trello.com/c/WvCPILCl/817-provide-means-to-edit-replace-an-attachment
This allows users to replace an existing file attachment's file with a new one.  If a file attachment is live then the original file will be redirected to the new file.  When upload a replacement file it is validated against the existing requirements for a file upload.  A separate PR will look at making additional checks as per the comments in the Trello card.
**Current file attachment**
**Upload a new file**
**Replacement file**
**Update confirmation**

Replace File Attachment file

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/inline-attachment-modal.js
app/controllers/file_attachments_controller.rb
app/views/components/_markdown_editor.html.erb
app/views/file_attachments/_file_attachment.html.erb
app/views/file_attachments/edit.html.erb
app/views/file_attachments/index.html.erb
app/views/file_attachments/show.html.erb
spec/features/editing_file_attachments/delete_file_attachment_spec.rb
spec/features/editing_file_attachments/edit_file_attachment_requirements_spec.rb
spec/features/editing_file_attachments/edit_file_attachment_title_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_asset_manager_down_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_unavailable_spec.rb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_requirements_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb

Clicking 'Insert < Attachment' opens the attachment workflow in a modal. If JavaScript is not enabled, the current behaviour of opening the workflow in a new tab is preserved. Previewing an attachment is still opened in a new tab regardless of whether a user is using the modal or not.
Trello:
https://trello.com/c/gPfQ2lBT/819-interface-with-a-documents-attachments-via-a-modal

Use modal for attachments

---

app/services/organisation_service.rb
spec/services/organisation_service_spec.rb

https://trello.com/c/OcuVomSb/820-show-the-alternative-format-email-address-for-an-attachment
This changes the OrganisationService to handle the case where the
primary org for an edition is not found in the Publishing API, when
attempting to lookup its alternative format contact email.
Although this is unlikely to be an issue in production, in development
we create a seed user who's primary org may not be in sync with the
development data for the Publishing API.
We should avoid coupling to specific data in remote systems so that our
app continues to work well in a variety of environments, and to minimise
the prerequisites required to begin developing on it.

Stop relying on data import for alt email

---

app/assets/javascripts/application.js
app/assets/javascripts/modal/modal-editor.js
app/assets/javascripts/modal/modal-workflow.js
app/assets/javascripts/modules/inline-attachment-modal.js
app/assets/javascripts/modules/inline-image-modal.js
app/assets/javascripts/modules/video-embed-modal.js
app/views/file_attachments/show.html.erb
spec/features/editing_content/insert_inline_file_attachment_no_js_spec.rb
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb

For https://trello.com/c/gPfQ2lBT/819-interface-with-a-documents-attachments-via-a-modal
This enables users with Javascript enabled to auto-insert file attachment markdown via the modal.
I've tested inserting the markdown before text, after text and within text for both attachment types. All renders correctly bar the attachment link when inserted before text, however this is being dealt with here https://github.com/alphagov/govspeak/pull/154

Insert file attachments via modal

---

spec/features/editing_content/insert_inline_image_no_js_spec.rb

Since we now test for a no-JS experience when inserting inline attachments, we
should have a test for a no-JS experience when inserting inline images.

Add test for inserting inline image without JS

---

app/assets/javascripts/modal/modal-workflow.js
app/assets/javascripts/modules/inline-attachment-modal.js
app/assets/javascripts/modules/inline-image-modal.js
app/assets/javascripts/modules/video-embed-modal.js

https://trello.com/c/NwWjLtlX/724-user-can-embed-attachment-links-inline-attachment
Previously we duplicated some of the render and action code in each
modal module. It now appears three times, which is good evidence it
needs DRY-ing up. This refactors the render and action code into the
existing ModalWorkflow utility to avoid duplication.
Originally it was unclear how portable the code we wrote for inline
images would be, so leaving it in each modal module allowed it to be
easily customised in the future, which a refactoring like this could
make harder. But this flexibility has not been useful, so there's no
strong argument for continuing to duplicate the code between modules.

Refactor rendering/actions into modal workflow

---

app/views/documents/show/_actions.html.erb
app/views/file_attachments/edit.html.erb
app/views/publish/confirmation.html.erb
app/views/video_embed/new.html.erb

Previously we had a mixture of data-gtm attributes on a form element or
its submit button, where the latter don't seem to make it to GTM. This
moves all data-gtm attributes within a form to be on the form element.

Move form GTM attributes onto form element

---

app/assets/javascripts/modules/gtm-copy-paste-listener.js
app/views/components/_page_preview.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_submitted_for_review.html.erb
app/views/publish/published.html.erb
spec/javascripts/modules/gtm-copy-paste-listener-spec.js

Previously we enabled tracking for copy/paste events using a particular
'data-gtm-copy-paste-tracking' attribute. In some cases, we also set the
'data-gtm' attribute, which we conventionally use the identify the
element. This ensures 'data-gtm' is populated in all places where we
track copy/paste events, and replaces the (now) redundant value of the
'data-gtm-copy-paste-tracking' attribute with 'true' so it still works.

Standardise copy/paste GTM attributes

---

app/helpers/actions_helper.rb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_external_links.html.erb

This was a pain point when I attempted to add some data-gtm attrs...
Previously we had a long and complex 'if' statement to determine which
actions a user can perform on a document. Much of the length of the
statement was due to (duplicated) rendering of elements, passing various
options. This refactors all the rendering into a new 'ActionsHelper' and
an 'external_links' partial, leaving just a complex 'if' statement ;-).

Refactor actions into helper methods

---

app/services/requirements/video_embed_checker.rb
spec/services/requirements/video_embed_checker_spec.rb

https://trello.com/c/Rf4RSnKZ/147-user-can-embed-video-from-markdown-toolbar
Previously the video embed checker would raise an error if the user
pasted the hint text into the URL input. This fixes that.

Fix edge case for video embed checker

---

app/helpers/actions_helper.rb

Previously only a couple of actions had data-gtm attributes to support
automatic analytics on them, while others (2i and preview) were picked
up with unconventional CSS-style tags in GTM. This ensures each action
link or button/form has an appropriate 'data-gtm' attribute.

Ensure all actions have GTM attributes

---

app/helpers/file_attachment_helper.rb
app/interactors/file_attachments/preview_interactor.rb
app/models/file_attachment/asset.rb
app/models/file_attachment/blob_revision.rb
app/models/file_attachment/revision.rb
app/models/revision.rb
app/services/draft_asset_cleanup_service.rb
app/services/file_attachment_blob_service.rb
app/services/govspeak_document/payload_options.rb
app/services/preview_asset_service.rb
app/services/publish_asset_service.rb
db/migrate/20190530175303_remove_variant_from_file_attachment_assets.rb
db/schema.rb
spec/factories/file_attachment_blob_revision_factory.rb
spec/factories/file_attachment_revision_factory.rb
spec/features/editing_file_attachments/preview_file_attachment_spec.rb
spec/features/editing_file_attachments/preview_file_attachment_unavailable_spec.rb
spec/features/editing_file_attachments/replace_file_attachment_file_spec.rb
spec/interactors/file_attachments/preview_interactor_spec.rb
spec/models/file_attachment/blob_revision_spec.rb
spec/services/delete_draft_service_spec.rb
spec/services/draft_asset_cleanup_service_spec.rb
spec/services/publish_asset_service_spec.rb
spec/services/remove_service_spec.rb

Trello: https://trello.com/c/BQ5bBkMw/881-wrap-up-technical-loose-ends-on-attachments
This PR builds on work in https://github.com/alphagov/content-publisher/pull/1092 and is thus marked as a draft until that is merged.
Previously we expected file attachments to potentially multiple assets
associated with each one, as is the case with images. This was based on
the expectation that PDFs would have a file and a thumbnail asset.
However later it was decided that PDF preview images would not be a part
of Content Publisher.
This therefore simplifies the model code to only deal with a single
asset association for a FileAttachment::BlobRevision. This allows for
numerous methods to be simplified to avoid a loop.
The owner of the association remains to be the Asset model, this allows
us to switch …

Change FileAttachment assets from one-to-many to one-to-one

---

app/views/documents/edit.html.erb
app/views/documents/edit/_change_notes.html.erb
app/views/documents/fields/_govspeak_input.html.erb
app/views/documents/show/_requirements.html.erb
spec/features/editing_content/insert_inline_file_attachment_spec.rb
spec/features/editing_content/insert_inline_image_spec.rb
spec/features/editing_content/insert_video_embed_spec.rb
spec/features/editing_images/upload_image_spec.rb

Adjusted links found in the warning message box of a draft document such that they bring the user to the required location (e.g. the content edit field of the document) for further editing.
Changed the ID for the govuk content field to refer to revision_field.id instead of just field.id so we avoid conflicts in the use of anchors. Updated related tests that were affected by this.
Trello Card: https://trello.com/c/Ml6qt5on/845-make-publishing-requirement-prompt-target-accurate

Make publishing requirement prompt target accurate

---

app/assets/stylesheets/components/_autocomplete.scss
app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/documents/show/_scheduling_form.html.erb

Update autocomplete to support a narrow version witch matches the date input component width so it can be used for time select.
Use tag helpers to generate markup for the autocomplete component.
[Trello card](https://trello.com/c/rGjDviSL)

Update autocomplete to allow narrow width needed for time select

---

app/controllers/unschedule_controller.rb
app/interactors/unschedule/unschedule_interactor.rb
config/locales/en/documents/show.yml
spec/features/workflow/unschedule_publishing_api_down_spec.rb
spec/features/workflow/unschedule_spec.rb
spec/interactors/unschedule/unschedule_interactor_spec.rb

For https://trello.com/c/FndkZ8gG/843-allow-users-to-stop-a-scheduled-publishing
This extracts the existing unschedule controller action into an interactor and creates a dedicated Unschedule Service to take care of making the appropriate status changes to a scheduled edition and deleting the publish intent that had been created when the edition was scheduled.

Stop scheduled publishing

---

app/services/requirements/checker_issues.rb
app/services/requirements/image_revision_checker.rb
app/services/requirements/issue.rb
app/views/documents/show/_requirements.html.erb
app/views/images/edit.html.erb
spec/features/workflow/preview_requirements_spec.rb

Trello: https://trello.com/c/Ml6qt5on/845-make-publishing-requirement-prompt-target-accurate
As a companion to https://github.com/alphagov/content-publisher/pull/1078 this adds in the links for image requirement issues. These were somewhat tricky as the URLs require the id of the image which isn't readily available. To resolve this I have made use of the context hash on an Issue and allowed passing in a lambda to generate the link.
This also fixes a couple of issues I spotted along the way, such as missing credit link and errors. 
For further details see commit messages.

Links to image requirement issues

---

app/assets/stylesheets/components/_summary.scss
app/views/components/_summary.html.erb
app/views/components/docs/summary.yml
app/views/documents/show/_contents.html.erb
app/views/documents/show/_lead_image.html.erb
app/views/documents/show/_tags.html.erb
app/views/documents/show/_topics.html.erb
spec/features/editing_content/edit_edition_spec.rb
spec/features/editing_content/edit_edition_with_line_breaks_and_spaces_spec.rb
spec/features/editing_content/govspeak_preview_spec.rb
spec/features/editing_content/insert_contact_publishing_api_down_spec.rb
spec/features/editing_content/insert_contact_spec.rb
spec/features/editing_content/url_preview_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_requirements_spec.rb
spec/features/editing_file_attachments/upload_file_attachment_spec.rb
spec/features/editing_images/upload_image_requirements_spec.rb
spec/features/editing_tags/edit_tags_publishing_api_down_spec.rb
spec/features/editing_tags/edit_tags_spec.rb
spec/features/editing_topics/edit_topics_spec.rb
spec/features/workflow/edition_spec.rb
spec/features/workflow/submit_for_2i_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb

Trello: https://trello.com/c/R0SXPvK1/900-change-change-link-on-content-summary-to-edit
This replaces the wording of the links on the summary page to have "Edit" rather than "Change".
This also refactors the summary component to accept data attributes and updates the tag manager attributes for each of the edit links
Before: 
After:

Replace "change" links with "edit"

---

app/views/layouts/application.html.erb

Previously we defined data-gtm tags in order to support robust analytics
for user actions, as more volatile things like CSS and link text change
over time. When a user action can occur on multiple pages, such when in
the context of a modal, it can be difficult to filter by workflow. This
adds an automated 'page-name' attribute to make it easier to filter by
workflow when the same user actions can occur on multiple pages.

Report page name for all events

---

yarn.lock

> js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.
> js-yaml prior to 3.13.0 are vulnerable to Denial of Service. By parsing a carefully-crafted YAML file, the node process stalls and may exhaust system resources leading to a Denial of Service.

Update yarn.lock to fix vulnerabilities

---

app/assets/javascripts/components/autocomplete.js
app/controllers/schedule_controller.rb
app/helpers/scheduling_helper.rb
app/helpers/time_options_helper.rb
app/interactors/schedule/save_datetime_interactor.rb
app/services/requirements/scheduled_datetime_checker.rb
app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/documents/show/_scheduling_notice.html.erb
app/views/schedule/confirmation.html.erb
app/views/schedule/scheduled.html.erb
app/views/schedule/scheduled_publishing_datetime.html.erb
config/locales/en/requirements.yml
spec/features/workflow/change_scheduled_publishing_datetime_spec.rb
spec/features/workflow/clear_scheduled_publishing_datetime_spec.rb
spec/features/workflow/schedule_publishing_datetime_requirements_spec.rb
spec/features/workflow/schedule_set_datetime_passes_spec.rb
spec/features/workflow/schedule_set_datetime_too_close_to_now_spec.rb
spec/features/workflow/set_scheduled_datetime_action_missing_spec.rb
spec/features/workflow/set_scheduled_publishing_datetime_and_schedule_spec.rb
spec/features/workflow/set_scheduled_publishing_datetime_spec.rb
spec/services/requirements/scheduled_datetime_checker_spec.rb

Trello: https://trello.com/c/rGjDviSL/848-adapt-scheduling-implementation-for-iterated-workflow
This allows each of the requirements issues to link directly to a field. It does this by breaking up the datetime errors into ones that are date or time. To complete this the autocomplete component needed updating to accept errors.
There are few things that aren't quite ideal in this which I'll explain:
- The fields for scheduling are most prefixed with `schedule_` this is done to disambiguate them amongst the many fields in the requirements yaml file, it would have been nicer to have date, time and action as names but they looked rather generic in amongst that file;
- The time parsing is quite strict to limit checking that a time input is actually a time, the alternative is pretty wild west …

Show scheduling errors with their respective fields

---

spec/features/scheduling/schedule_spec.rb

As this test changed the Sidekiq Testing mode to fake! and future tests
that expected inline! would fail. By running the example within a block
no global state is changed.

Move and fix rogue schedule test

---

Gemfile.lock
app/views/components/_autocomplete.html.erb
app/views/components/_markdown_editor.html.erb
app/views/schedule/scheduled_publishing_datetime.html.erb

Trello: https://trello.com/c/rGjDviSL/848-adapt-scheduling-implementation-for-iterated-workflow
This updates to govuk_publishing_components 16.29.0 which allows us to pass in error_items to the error_message component and the date_input component.
This then updates our code to make use of this.

Pass error items into components rather than convert to strings

---

app/controllers/schedule_controller.rb
app/interactors/schedule/clear_datetime_interactor.rb
app/models/timeline_entry.rb
spec/features/scheduling/clear_scheduled_publishing_datetime_spec.rb

For https://trello.com/c/bFymOdvj/850-allow-updating-and-clearing-of-a-proposed-scheduling-date
This extracts the logic for clearing a scheduled publishing datetime into an
interactor.  We have made a content decision that we no longer need to create a
timeline entry when a scheduled publishing datetime is clearer as this is an
edit. This is consistent with not creating a timeline entry when a scheduled
publishing datetime is updated.  We have also decided not to check if a
scheduled publishing datetime is present before clearing it, as if it's not
present the updater won't assign a new revision as it won't have changed.

Create Clear Datetime interactor

---

app/controllers/schedule_proposal_controller.rb
app/helpers/actions_helper.rb
app/interactors/schedule_proposal/update_interactor.rb
app/services/requirements/schedule_datetime_checker.rb
app/views/schedule/new.html.erb
app/views/schedule_proposal/edit.html.erb
spec/services/requirements/schedule_datetime_checker_spec.rb

https://trello.com/c/rGjDviSL/848-adapt-scheduling-implementation-for-iterated-workflow
This covers a follow-up action on the above card, to fix the 'Back' button on the page to schedule a document. Previously we took the user back to the summary page, but sometimes this needs to be the page to edit the proposed date/time. See the commit for more info...

Schedule back link

---

app/jobs/scheduled_publishing_job.rb
app/mailers/scheduled_publish_mailer.rb
app/views/scheduled_publish_mailer/success_email.text.erb
config/locales/en/scheduled_publish_mailer/success_email.yml
spec/jobs/scheduled_publishing_job_spec.rb
spec/mailers/scheduled_publish_mailer_spec.rb

We need to send users who have edited an edition a notification that their scheduled content has been published.
Trello:
https://trello.com/c/utiuH5Q9/736-notify-users-that-scheduled-content-has-been-published

Notify users about scheduled publishing

---

app/views/components/_markdown_editor.html.erb

Previously we set the same data-gtm attribute for all MD toolbar
buttons, which was used to scope the associated GTM trigger. This
modifies the data-gtm attributes to consistently reflect the action
performed, making events for these elements equivalent to other
data-gtm actions, avoiding premature grouping. Using the common
'markdown-toolbar' prefix to scope the GTM trigger should suffice.

Standardise tracking for MD toolbar buttons

---

spec/features/scheduling/unschedule_publishing_api_down_spec.rb
spec/features/scheduling/unschedule_spec.rb

https://trello.com/c/0Bh5ORiV/705-schedule-an-edition-for-publishing
This also ensures we check the associated intent is actually destroyed.

Move unschedule specs under scheduling/

---

app/controllers/schedule_controller.rb
app/interactors/schedule/create_interactor.rb
app/models/edition.rb
app/views/documents/show/_actions.html.erb

https://trello.com/c/a4sDMtqD/844-ensure-publishers-meet-requirements-before-they-schedule
Previously we had a schedulable? method on each edition that was used
for sanity checking in a couple of controller actions, as well as to
modify the actions shown to the user. The latter behaviour conflicts
with the new design for schedule requirements, as the 'Schedule' action
would disappear if the proposed time drifted into the past.
This replaces the schedulable? check for user actions by simply checking
the scheduled_publishing_datetime, noting the edition is editable in
both scenarios. Since it is valid to enqueue a job in the past (?!),
this also inlines and simplifies the schedulable? check when scheduling
a document, and removes it when harmlessly rendering the form.

Replace Edition#schedulable? with inline checks

---

docs/adr/0011-moving-business-logic-out-of-controllers.md
docs/adr/00xx-moving-business-logic-out-of-controllers.md

This documents the decision made recently to move business logic outside
of controllers and to use the Interactor gem as a pattern to implement
our business logic concerns.
This builds on the discussion in https://github.com/alphagov/content-publisher/issues/740

ADR for interactors

---

lib/tasks/lint.rake

Previously this would break, depending on how you run 'rake'.

Fix lint task so it uses bundle exec

---

app/views/components/_markdown_editor.html.erb
app/views/components/_markdown_guidance.html.erb
app/views/documents/index/_filters.html.erb
app/views/new_document/choose_document_type.html.erb
app/views/new_document/choose_supertype.html.erb
app/views/publish/confirmation.html.erb

This makes a few iterations to further simplify our analytics:
- A more generic way to track unusual clicks (e.g. MD toolbar)
- A more generic / less verbose way to specify event actions
- A more generic way to track based on visibility (for guidance and filters)
Please see the commits for more details...

Gtm mega bundle

---

app/views/components/_markdown_guidance.html.erb
app/views/documents/edit.html.erb

It seems like we're carrying wrongly nested erb/html tags for a while now which was probably corrected by the browser up until some recent changes which reveal the problem.

Fix mark-up tags on edit document page

---

app/views/components/_markdown_guidance.html.erb

We recently [removed the email markdown link](https://github.com/alphagov/content-publisher/pull/1035/commits/44efa4fcbea2ac105e077683bb04963e7f73c16b) from the  sidebar and [updated the link button so it can be used for email](https://github.com/alphagov/markdown-toolbar-element/pull/8). During research, most users did not use the link button and tried to find the markdown instructions.
In this PR we want re-add this instruction while we explore other ways of helping users add email correctly.
[Trello card](https://trello.com/c/srCexKrZ)

Add back the guidance for email markdown

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_inset-prompt.scss
app/models/status.rb
app/views/components/_inset_prompt.html.erb
app/views/components/docs/inset_prompt.yml
app/views/documents/index/_filters.html.erb
app/views/documents/show/_actions.html.erb
app/views/documents/show/_failed_to_publish_notice.html.erb
app/views/documents/show/_requirements.html.erb
app/views/documents/show/_summary_tab.html.erb
config/locales/en/documents/show.yml
config/locales/en/states.yml
spec/factories/edition_factory.rb
spec/factories/scheduling_factory.rb
spec/factories/status_factory.rb
spec/features/scheduling/resolve_failed_to_publish_spec.rb
spec/features/scheduling/schedule_requirements_spec.rb
spec/features/workflow/preview_requirements_spec.rb
spec/features/workflow/publish_requirements_publishing_api_down_spec.rb
spec/features/workflow/publish_requirements_spec.rb
spec/spec_helper.rb

Trello: https://trello.com/c/rBYaERp4/708-handle-scheduled-publishing-errors
This builds off of https://github.com/alphagov/content-publisher/pull/1137 I've set that as the base branch for it to be clearer what this PR introduces.
This sets up the UI for handling failed_to_publish and makes it (and scheduled) selectable statuses on the index page.
Part of this involved setting up a component to show the "Failed to publish" error to the user. To do this I renamed the warning summary component to be inset prompt, then I gave it an error option. I'm not sure I've achieved setting the background colour of this in a standard way.

Failed to publish user interface

---

app/controllers/documents_controller.rb
app/controllers/tags_controller.rb
app/interactors/tags/update_interactor.rb
app/services/requirements/edition_checker.rb
app/services/requirements/tag_checker.rb
app/views/documents/show/_requirements.html.erb
app/views/tags/edit.html.erb
app/views/tags/tags/_single_tag_input.html.erb
config/locales/en/requirements.yml
spec/features/editing_tags/edit_tags_requirements_spec.rb
spec/formats/news_story_spec.rb
spec/formats/press_release_spec.rb

Trello card: https://trello.com/c/4Uc4JL4T/870-add-a-publishing-requirement-to-select-a-primary-organisation
The Primary Organisation field can now accept a blank string, however using
a new Tag Checker we insist that the user must submit a valid organisation
not only to publish the document, but also to save the Edit Tags page.
Browser no longer in a redirect loop if you have a nil organisation and visit the home page.
Now pass a revision to Edit Tags view instead of an edition to maintain the user's previous form submission.
Moved the point where we fail until after the issues are checked to make sure validation errors were found even with no changes made.

Add a publishing requirement to select a primary organisation

---

app/views/components/_inset_prompt.html.erb

Fix inset-prompt class name which results in unnecessary space after the list-item

Fix inset-prompt class name

---

app/views/components/_metadata.html.erb
app/views/components/docs/metadata.yml
app/views/documents/show/_document_metadata.html.erb
app/views/layouts/application.html.erb

https://trello.com/c/a4sDMtqD/844-ensure-publishers-meet-requirements-before-they-schedule
Previously we had two custom GTM attributes to communicate the visible
document status and type, although the latter was never actually used.
Both can now be inferred from other events, but we should ideally use
the app DB as the source of this kind of non-eventful information.
This removes both attributes and the associated field of the metadata
component, as it is now redundant.

Remove gtm-doc-status and gtm-doc-type attributes
